import type { ArticleMetadata } from "@/types/engineering/content";

export const aiCoolingMetadata: ArticleMetadata = {
  slug: "ai-cooling",
  title: "AI Cooling: Liquid Cooling, Immersion Cooling and AI Data Center Heat Management",
  seoTitle: "What Is AI Cooling? Liquid Cooling, Immersion Cooling, CDU, Rear-Door HX — Complete English Guide",
  seoDescription:
    "A complete engineering guide to AI Cooling — air cooling vs liquid cooling vs immersion cooling, CDU architecture, direct liquid cooling (cold plates), rear-door heat exchangers, PUE and WUE metrics, AI rack power density challenges, cooling capacity planning, failure scenarios, and troubleshooting. For AI infrastructure engineers, DC professionals, and students.",
  canonicalUrl: "https://behindthetech.in/learn/ai/data-centers/ai-cooling",
  keywords: [
    "what is ai cooling",
    "liquid cooling data center ai",
    "immersion cooling ai servers",
    "cdu cooling distribution unit",
    "direct liquid cooling cold plates gpu",
    "rear-door heat exchanger rdhx",
    "pue wue ai data center metrics",
    "ai rack power density kw",
    "air cooling vs liquid cooling ai",
    "single phase immersion cooling",
    "two phase immersion cooling",
    "ai data center thermal management",
    "cooling capacity planning ai",
    "gpu thermal throttling",
    "ai cooling failure scenarios",
    "nvidia h100 cooling requirements",
    "crac crah vs cdhu ai",
    "hot aisle cold aisle containment ai",
    "ai cooling troubleshooting",
    "cooling infrastructure ai data center",
  ],
  authorName: "Kumar Anil",
  datePublished: "2026-08-12",
  readingTimeMinutes: 75,
};
