import type { GlossarySection } from "../study/types";

// ─────────────────────────────────────────────────────────────────────────────
// content/reference/glossary.ts
// All glossary terms. Add new sections or terms here — page auto-renders.
// articles[] — only slugs in ARTICLE_ROUTE_MAP in GlossaryClient.tsx.
// ─────────────────────────────────────────────────────────────────────────────

export const GLOSSARY_SECTIONS: GlossarySection[] = [

  {
    heading: "Power Infrastructure",
    color: "#f97316",
    terms: [
      { term:"UPS", aliases:["Uninterruptible Power Supply","No-Break Power Supply"], full:"Uninterruptible Power Supply", meaning:"Power conditioning + backup device. Online Double Conversion type: AC→DC→AC, pure sine wave output regardless of input quality. Switches to battery in 0ms on grid failure. Battery runtime 10-15 min (DG bridge only).", whyMatters:"Single most critical power protection element. Millisecond grid interruption = server crash without UPS. Also conditions power quality — filters harmonics, voltage fluctuations.", whereSeen:"Every DC from edge to Tier IV. Schneider Galaxy, Vertiv Liebert, Eaton 9395, ABB DPA.", confusion:"UPS = backup generator. Wrong. UPS = minutes. Generator = hours. UPS bridges, DG sustains.", example:"Grid fails 2 AM. UPS switches to battery in 0ms. DG starts in 30s. Servers never notice the grid failure.", related:["DG Set","ATS","VRLA Battery","STS","PDU"], articles:["ups"] },

      { term:"DG Set", aliases:["Diesel Generator","Genset","DG"], full:"Diesel Generator Set", meaning:"Diesel engine + alternator generating AC power. Standard DC: 1500 RPM, 50Hz, 415V three-phase. Connected via ATS. Runtime = fuel availability. Critical DCs maintain 48-72 hours fuel on-site.", whyMatters:"Only sustained backup when grid fails. Monthly test under load mandatory — DG fails most when needed if not maintained.", whereSeen:"All DCs. 250kVA (edge) to multiple 2-4MW units (hyperscale). Sound-proof outdoor enclosures or indoor plant rooms.", confusion:"DG = UPS. Different roles — DG generates, UPS bridges. Both needed.", example:"Grid failure. UPS instant pickup. DG start signal. ATS transfers at 40 seconds. DC runs on DG for 6 hours until grid restored.", related:["ATS","UPS","Fuel System","Paralleling Panel"], articles:[] },

      { term:"ATS", aliases:["Automatic Transfer Switch","Auto Transfer Switch"], full:"Automatic Transfer Switch", meaning:"Power switching device that automatically transfers load from normal supply (grid) to alternate supply (DG) when primary fails. Monitors input voltage and frequency. Make-before-break or break-before-make arrangements.", whyMatters:"Automates grid-to-DG transfer. Transfer time must be shorter than UPS battery bridge capability.", whereSeen:"Between grid supply and DG output in every DC. Multiple ATSs in large DCs.", confusion:"ATS = STS. ATS: mechanical, seconds-range (for grid-DG). STS: static (thyristors), milliseconds (for UPS-UPS).", example:"Grid voltage drops below 380V. ATS starts DG. DG reaches 415V. ATS transfers load in 40ms.", related:["STS","DG Set","UPS","MCC"], articles:[] },

      { term:"STS", aliases:["Static Transfer Switch","2N Switch"], full:"Static Transfer Switch", meaning:"Fast switching device (<4ms, sub-cycle) between two independent UPS sources using thyristors/SCRs. No mechanical parts. Transfers between two live UPS systems without any interruption.", whyMatters:"Tier IV redundancy enabler. Allows two complete power systems both active with fast transfer.", whereSeen:"Between two UPS systems in Tier IV DCs. Critical single-corded equipment in 2N architecture.", confusion:"STS = ATS. ATS: slow mechanical, grid-DG. STS: fast static electronics, UPS-UPS.", example:"UPS-A fault detected. STS transfers to UPS-B in 3ms. Servers experience nothing — within PSU hold-up time.", related:["ATS","UPS","PDU","2N Redundancy"], articles:["sts"] },

      { term:"PDU", aliases:["Power Distribution Unit","Rack PDU","Floor PDU"], full:"Power Distribution Unit", meaning:"Panel distributing power from UPS to server racks. Floor PDU: UPS to row. Rack PDU: within rack to servers. Smart/Intelligent PDUs add per-outlet current monitoring and remote switching.", whyMatters:"Last mile of power distribution. Smart PDUs enable actual vs allocated capacity tracking — critical for stranded capacity management.", whereSeen:"Every DC rack. Vertiv, Raritan, APC, Schneider. Smart PDUs are now standard in enterprise DC.", confusion:"PDU = UPS. PDU only distributes — no conditioning, no backup. Smart PDU ≠ basic power strip.", example:"2N design: each rack has PDU-A (from UPS-A) and PDU-B (from UPS-B). Dual-corded servers connect one PSU to each.", related:["UPS","STS","Busbar","2N","Stranded Capacity"], articles:["pdu"] },

      { term:"PUE", aliases:["Power Usage Effectiveness","DCiE"], full:"Power Usage Effectiveness", meaning:"PUE = Total Facility Power ÷ IT Equipment Power. PUE 1.0 = theoretical perfect (100% to IT). PUE 2.0 = 50% wasted on cooling, UPS losses, lighting.", whyMatters:"Primary DC efficiency and sustainability metric. PUE improvement directly reduces OpEx and carbon footprint. Used in client SLAs, green certifications, government reporting.", whereSeen:"Every DC. DCIM systems. Annual reports. Green Star DC (India). Google/Microsoft publish PUE figures.", confusion:"Lower PUE always better. Climate determines baseline. PUE 1.3 in Mumbai = excellent. PUE 1.3 in Iceland = poor (should be 1.1 with free cooling).", example:"100kW IT load, 160kW total. PUE 1.6. 60kW overhead. At Rs. 8/kWh: Rs. 4,147/day overhead cost. PUE 1.4 target saves Rs. 1,382/day.", related:["DCiE","DCIM","Free Cooling","CRAC","CRAH"], articles:[] },

      { term:"N+1", aliases:["N Plus One","N+1 Redundancy"], full:"N Plus One Redundancy", meaning:"N = components required for load. N+1 = one extra standby. Any single component failure = still operational. Minimum Tier III standard.", whyMatters:"Most common DC redundancy level. Allows maintenance without shutdown. But: during maintenance you're at N — any additional failure = outage.", whereSeen:"CRACs, UPS modules, generators, network switches, storage controllers.", confusion:"N+1 = always 2 units. If N=5, N+1=6. Only equals 2 when N=1.", example:"500kW IT load. CRAC 150kW each. N = ceil(500/150) = 4. N+1 = 5 CRACs. One fails: 4 remaining = 600kW capacity. Safe.", related:["2N","2N+1","SPOF","Tier III"], articles:[] },

      { term:"2N", aliases:["Dual N","Two N","2N Redundancy","Dual Redundancy"], full:"Two N Redundancy — Complete Duplication", meaning:"Two complete independent systems each capable of 100% load. Not just extra components — separate power feeds, cooling loops, paths. Tier IV minimum requirement.", whyMatters:"Eliminates system-level SPOFs. Any fault — planned or unplanned — zero impact. Required for financial exchanges, critical national infrastructure.", whereSeen:"Tier IV DCs, financial trading floors, core national infrastructure.", confusion:"2N = 2× capacity without independence. Two UPS sharing one bypass bus = NOT true 2N. Independence means no shared components.", example:"True 2N UPS: UPS-A and UPS-B, each 100% capacity, completely independent. UPS-A explodes — UPS-B carries full DC load.", related:["N+1","Tier IV","SPOF","STS"], articles:[] },

      { term:"SPOF", aliases:["Single Point of Failure"], full:"Single Point of Failure", meaning:"Any component whose failure alone causes complete service disruption. Even redundant designs can have hidden SPOFs — a shared bypass bus, single network cable between redundant components.", whyMatters:"SPOF identification drives risk assessment. Finding them before failure = proactive reliability engineering. Tier certification explicitly maps and eliminates SPOFs.", whereSeen:"Risk assessments, design reviews, audit findings. Tier certification process.", confusion:"Redundant components = no SPOF. Two UPS can still share one maintenance bypass panel — that's a SPOF.", example:"Two UPS (2N design), but both fed from same LT panel main breaker. That breaker = SPOF. True 2N needs two independent LT feeds.", related:["N+1","2N","Redundancy","Tier IV"], articles:[] },

      { term:"Power Factor", aliases:["PF","kW/kVA ratio"], full:"Power Factor", meaning:"PF = Real Power (kW) / Apparent Power (kVA). PF 1.0: all apparent power is real. PF 0.8: 20% reactive power — wasted as heat. Modern UPS output PF = 1.0. Old UPS = 0.8.", whyMatters:"Affects UPS sizing, utility billing (some utilities charge on kVA), and cable sizing. Critical for accurate capacity calculations.", whereSeen:"UPS specifications, LT panel sizing, utility billing, APFC panels.", confusion:"100kVA UPS = 100kW capacity. Only with PF 1.0 output. Old 0.8 PF UPS: 100kVA = 80kW only.", example:"IT load 90kW at PF 0.9 = 100kVA apparent. Modern PF 1.0 UPS: 100kVA unit works. Old PF 0.8 UPS: overloaded.", related:["UPS","kVA","kW","APFC"], articles:[] },

      { term:"VRLA Battery", aliases:["Valve Regulated Lead-Acid","AGM Battery","Sealed Lead-Acid","SLA"], full:"Valve Regulated Lead-Acid Battery", meaning:"Sealed lead-acid UPS battery. No free liquid acid — electrolyte in gel or AGM. Sealed with pressure relief valve. Lifespan 3-5 years at 25°C. Each 10°C above 25°C halves battery life.", whyMatters:"UPS backup depends entirely on battery health. Regular testing and timely replacement prevents silent failure during actual outages.", whereSeen:"All UPS systems unless specified Li-Ion or Ni-Cd. Yuasa, GS Yuasa, Enersys, Exide brands.", confusion:"VRLA = maintenance-free = never needs attention. Needs: voltage checks, capacity testing, temperature monitoring, timely replacement.", example:"Battery string 40 × 12V VRLA = 480V. Float voltage monitored monthly. At year 4, discharge test: 70% capacity. Replace before year 5.", related:["UPS","Li-Ion Battery","Float Voltage","Battery Test"], articles:["battery-bank"] },

      { term:"Li-Ion Battery", aliases:["Lithium-Ion Battery","LFP Battery","Lithium Battery"], full:"Lithium-Ion UPS Battery", meaning:"Modern UPS battery using lithium-ion chemistry. Advantages: 10+ year lifespan, higher energy density (smaller footprint), faster recharge, lower temperature sensitivity, built-in BMS.", whyMatters:"10-year DC deployments: Li-Ion may be cheaper TCO despite higher upfront cost. Critical for high-ambient environments where VRLA degrades quickly.", whereSeen:"New DC builds, retrofit UPS upgrades, edge DCs. Schneider Galaxy VX, Vertiv Liebert, Eaton offer Li-Ion options.", confusion:"Li-Ion always better than VRLA. TCO analysis needed. 2-3× upfront cost. Over 10 years: potentially cost-neutral or better depending on ambient temperature.", example:"Mumbai DC with 35°C battery room: VRLA lasting 2-3 years. Li-Ion with BMS: 8-10 year life. TCO favors Li-Ion despite higher purchase price.", related:["VRLA Battery","UPS","TCO","Battery BMS"], articles:["battery-bank"] },

      { term:"Busbar", aliases:["Busbar Trunking","BTS","Busway","Busduct"], full:"Busway / Busbar Trunking System", meaning:"Pre-fabricated power distribution using rigid aluminum/copper conductors in protective enclosures. Plug-in tap-offs allow connections at any point along the run without shutdown.", whyMatters:"Modern DC power distribution. Flexible IT load addition without rewiring. Higher current density, better heat dissipation than bundled cables.", whereSeen:"Large DCs between UPS and row-level distribution. Overhead power distribution. Starline, Schneider Canalis, ABB Zucchini, Eaton.", confusion:"Busbar = extension cord. Industrial-grade current-rated conductors in protective enclosure. Completely different.", example:"Row of 20 racks. Busbar runs overhead. Each rack has plug-in tap-off — clean, expandable, no individual cables from remote electrical room.", related:["PDU","UPS","Power Distribution"], articles:[] },

      { term:"Transformer", aliases:["HT Transformer","Step-Down Transformer","Isolation Transformer"], full:"Power Transformer", meaning:"Electromagnetic device that steps voltage up or down. DC use: step-down from utility HT (11kV/33kV) to LT (415V). Types: oil-cooled (ONAN/ONAF) for large outdoor, dry-type for indoor/critical installations.", whyMatters:"First element in DC power chain after utility. Transformer failure = extended outage until replacement. Oil DGA testing critical for early fault detection.", whereSeen:"HT yard or indoor substation. Between utility HT panel and LT distribution board.", confusion:"Transformer failure is rare so maintenance not important. DGA testing reveals developing faults weeks before failure. Annual testing mandatory.", example:"11kV utility supply → step-down transformer → 415V LT panel → UPS. Dual transformers for Tier III/IV.", related:["HT Panel","LT Panel","DG Set","UPS"], articles:["transformer"] },

      { term:"APFC", aliases:["Automatic Power Factor Correction","Capacitor Bank"], full:"Automatic Power Factor Correction Panel", meaning:"Capacitor banks that automatically switch in/out to maintain target PF (typically 0.95-0.99). Capacitors produce leading reactive power — offsets inductive (lagging) loads. APFC controller monitors PF via CTs.", whyMatters:"Reduces utility kVA billing, reduces cable current, reduces losses. Many Indian utilities have PF penalty for PF <0.85.", whereSeen:"LT panels in DCs with old inductive loads (motors, old HVAC, old UPS). Modern DC with high-PF UPS: APFC largely unnecessary.", confusion:"APFC mandatory in all DCs. Modern UPS input PF >0.99 — APFC largely unnecessary in new builds.", example:"Old DC with legacy HVAC motors: PF 0.75. APFC panel installed. PF → 0.96. Utility bill reduced 20%. Penalty eliminated.", related:["Power Factor","LT Panel","UPS","kVA"], articles:[] },

      { term:"RMU", aliases:["Ring Main Unit","Ring Main Switchgear","Secondary Substation"], full:"Ring Main Unit", meaning:"Medium voltage switchgear unit for secondary distribution in ring-main networks. Allows ring feeder connection, transformer connection, and sectionalising in compact unit. Typically 11kV or 33kV.", whyMatters:"Enables dual utility feed connections for redundancy. Fault isolation in ring network without affecting other consumers.", whereSeen:"Utility distribution networks, large campus developments, large DC HT yards. ABB, Schneider, Siemens.", confusion:"RMU = transformer. RMU is switchgear only — no voltage transformation. Transformer is separate.", example:"DC with dual utility feeds: two RMUs (one per feeder) → HT switchgear → transformers → LT panels.", related:["HT Panel","Transformer","Grid Supply"], articles:["rmu"] },

      { term:"HT Panel", aliases:["HT Switchgear","High Tension Panel","High Voltage Panel","11kV Switchgear"], full:"High Tension Switchgear Panel", meaning:"Switchgear operating at high voltage (11kV, 33kV, 66kV). Contains HT circuit breakers, protection relays (OC, EF, differential), current transformers (CT), voltage transformers (VT), metering. Incoming from utility, outgoing to transformers.", whyMatters:"First protection layer in DC power chain. Fault isolation at HT level prevents transformer damage. Protection relay settings critical.", whereSeen:"DC HT yard or indoor substation. Between utility connection (RMU/feeder) and step-down transformers.", confusion:"HT panel = LT panel. HT operates at kilovolt level — specialist design, installation, and maintenance required.", example:"Utility 11kV → HT panel (incomer breaker, OC/EF relays) → step-down transformer 11kV/415V → LT panel.", related:["LT Panel","Transformer","Protection Relay","Grid Supply"], articles:["ht-yard"] },

      { term:"LT Panel", aliases:["MLDB","Main LT Distribution Board","Low Tension Panel","415V Panel"], full:"Low Tension Main Distribution Board", meaning:"Main 415V switchgear panel after transformer LV winding. Contains ACBs (Air Circuit Breakers) or MCCBs for distribution. Feeds UPS, HVAC, lighting, emergency circuits. Phase and neutral busbars, earth bar.", whyMatters:"415V distribution hub. Fault at LT panel level = multiple systems affected. Phase balancing, protection relay coordination critical.", whereSeen:"Electrical room of every DC, adjacent to transformers. ACB/MCCB breakers per circuit.", confusion:"LT panel = UPS output panel. LT panel is upstream of UPS — utility supply comes in at LT panel, then feeds UPS.", example:"Transformer LV terminals → LT panel main ACB → outgoing feeders: UPS-A, UPS-B, HVAC, lighting, emergency.", related:["HT Panel","Transformer","UPS","ACB","MCCB"], articles:[] },

      { term:"LOTO", aliases:["Lockout Tagout","Lockout/Tagout","Lock Out Tag Out"], full:"Lockout Tagout Safety Procedure", meaning:"Safety procedure ensuring dangerous equipment is de-energized and cannot be restarted during maintenance. Physical lock applied by working engineer — cannot be removed by anyone else. Tag indicates work in progress.", whyMatters:"Life safety — equipment accidentally energized during maintenance = electrocution. LOTO mandatory for all electrical maintenance work.", whereSeen:"UPS battery work, generator maintenance, LT panel work, chiller maintenance. OSHA requirement globally.", confusion:"Tag alone = LOTO. Wrong. Tag can be removed by others. Lock cannot. Full LOTO = physical lock + tag.", example:"Engineer servicing UPS battery: isolate → verify zero energy (multimeter) → apply own lock → tag → work. Only this engineer can remove their lock.", related:["Arc Flash","Isolation","Permit to Work","Safety"], articles:[] },
    ],
  },

  {
    heading: "Cooling Systems",
    color: "#0284c7",
    terms: [
      { term:"CRAC", aliases:["Computer Room Air Conditioner","Precision Air Conditioner","In-row Cooling"], full:"Computer Room Air Conditioner", meaning:"Self-contained DX (Direct Expansion) precision cooling unit. Internal compressor, refrigerant circuit, evaporator, condenser. Standalone — no external chiller needed. 24x7x365 design for DC environments. COP ~2-3.", whyMatters:"Standard cooling for small-medium DCs. N+1 configuration provides redundancy. Each unit independently operable.", whereSeen:"Small-medium DCs, edge DCs, server rooms. Schneider, Vertiv/Liebert, Stulz, Uniflair brands.", confusion:"CRAC = CRAH. CRAC has internal refrigerant + compressor (standalone). CRAH needs external chiller plant.", example:"250kW IT room: 3 CRACs (N+1 where N=2 at 125kW each). One CRAC fault at 2 AM — remaining two handle load.", related:["CRAH","PAC","DX","Airflow","Containment"], articles:["crac"] },

      { term:"CRAH", aliases:["Computer Room Air Handler","Air Handler Unit"], full:"Computer Room Air Handler", meaning:"Air handler using chilled water from central chiller plant to cool air. No internal refrigerant circuit — only fan and cooling coil. More efficient than CRAC at scale. Requires chiller plant infrastructure.", whyMatters:"Preferred for large DCs with chiller plants. Energy efficient at scale (chiller COP 4-6 vs CRAC COP 2-3). Supports free cooling integration.", whereSeen:"Large enterprise DCs >1MW with chiller plants. Stulz, Vertiv, Schneider. In-row variants available.", confusion:"CRAH works standalone. CRAH needs chiller plant — if chiller fails, CRAH stops cooling.", example:"2MW data hall: central chiller plant (N+1 chillers) + cooling towers + CRAHs. Winter: free cooling mode — chillers off, PUE drops from 1.55 to 1.18.", related:["CRAC","Chiller","Cooling Tower","Free Cooling","PAC"], articles:[] },

      { term:"PAC", aliases:["Precision Air Conditioner","Close Control Unit","CCU"], full:"Precision Air Conditioner", meaning:"High-precision cooling unit for IT environments. Temperature control ±0.5°C, humidity control, 24x7x365 operation. Unlike comfort ACs (designed 8-12 hours/day for humans). DX-based like CRAC.", whyMatters:"IT equipment requires consistent temperature (18-27°C) and humidity (40-60% RH). PACs maintain this precision. Normal split ACs cannot.", whereSeen:"Server rooms, network rooms, edge DCs, telecom BTS rooms. Schneider, Vertiv, Stulz, Emerson.", confusion:"Normal split AC can replace PAC. Wrong. Split ACs cycle, swing temperature, have no humidity control. Server PCB corrosion from humidity swings.", example:"Branch office server room: split AC installed. Summer humidity 80% RH. Server PCB corrosion in 6 months. PAC with humidity control fixed permanently.", related:["CRAC","CRAH","AHU","Humidity Control","ASHRAE"], articles:["pac"] },

      { term:"Chiller", aliases:["Water Chiller","Chiller Plant","Refrigeration Machine"], full:"Chiller / Chilled Water Plant", meaning:"Central cooling plant producing chilled water for CRAHs. Uses refrigerant cycle to cool water (typically 7°C supply, 12°C return). Air-cooled chiller (condenser to outdoor air) or water-cooled (condenser to cooling tower).", whyMatters:"Heart of large DC cooling infrastructure. Failure impacts entire DC cooling. Central chillers more efficient at scale (COP 4-6 vs CRAC 2-3).", whereSeen:"Large DCs with CRAH systems. Carrier, Trane, York, Daikin, Stulz. Sizes 200TR to 2000TR+.", confusion:"One chiller = OK. N+1 chillers needed where N = minimum for full load. If N=2, install 3 chillers.", example:"500TR DC: N=2 (two 250TR chillers). Install 3 (N+1). One fails summer peak — two remaining handle full load.", related:["CRAH","Cooling Tower","Chilled Water","Free Cooling","PUE"], articles:["chiller"] },

      { term:"Cooling Tower", aliases:["CT","Evaporative Cooling Tower","Wet Cooling Tower"], full:"Evaporative Cooling Tower", meaning:"Heat rejection device for water-cooled chiller systems. Hot condenser water sprayed over fill media with air flowing through — evaporation cools the water by 5-8°C. Returns cool condenser water to chiller.", whyMatters:"Water-cooled chillers need cooling towers for heat rejection. Tower performance directly impacts chiller efficiency and PUE. Also enables free cooling economizer mode.", whereSeen:"DC rooftops, outdoor mechanical areas. Cross-flow or counter-flow types. Baltimore Air Coil, Evapco, Marley/SPX brands.", confusion:"Cooling tower = direct DC cooling. No — it rejects heat from chiller condenser water. IT → CRAH → chilled water → chiller → condenser water → cooling tower.", example:"Delhi summer OAT 43°C: condenser water 40°C. High head pressure. Night OAT 28°C: condenser water 30°C. Chiller more efficient. PUE improves 0.1.", related:["Chiller","CRAH","Free Cooling","Water Treatment"], articles:["cooling-tower"] },

      { term:"Free Cooling", aliases:["Economizer Mode","Waterside Economizer","Airside Economizer"], full:"Free Cooling / Economizer Mode", meaning:"Using outdoor ambient temperature to assist or replace mechanical (compressor-based) cooling. 'Free' means no compressor energy. Types: Waterside economizer (cooling tower water → bypass chiller → CRAH), Airside (outdoor air directly into DC).", whyMatters:"Biggest single PUE improvement lever. Chillers consume 40-50% of non-IT power. Reducing their runtime dramatically reduces PUE.", whereSeen:"DCs in moderate-to-cold climates. Hyperscale DCs in Nordic Europe: near-100% free cooling, PUE 1.1-1.15. Delhi: 1000-1500 hours/year. Mumbai: <100 hours.", confusion:"Free cooling = zero cost. Cooling tower fans/pumps still run. 'Free' means no compressor operation.", example:"Waterside economizer: outdoor wet-bulb 12°C (Delhi winter). Cooling tower water 15°C. CRAHs served without chiller. Chillers off. PUE 1.6 → 1.15 for 6 hours.", related:["Chiller","CRAH","Cooling Tower","PUE","BMS"], articles:[] },

      { term:"Containment", aliases:["Hot Aisle Containment","Cold Aisle Containment","HAC","CAC"], full:"Hot Aisle / Cold Aisle Containment", meaning:"Physical barriers separating cold supply air from hot exhaust air in DC aisles. Prevents mixing which reduces cooling efficiency. CRAC inlet temperature rises → higher delta-T → less airflow → fan energy saved.", whyMatters:"Prevents hot-cold air mixing. PUE improvement 0.1-0.3 possible. Reduces CRAC inlet temperature = higher efficiency.", whereSeen:"Modern DC aisles. Plastic/aluminum curtains, hard walls, aisle end doors. Retractable doors for access.", confusion:"Containment = blanking panels. Blanking panels = individual rack-level. Containment = aisle-level. Different scale, different impact.", example:"Mumbai DC: CRAC inlet 28°C without containment. With HAC: inlet 38°C → higher delta-T → same cooling, less airflow. Fan energy reduced 30%.", related:["Blanking Panels","CRAC","CRAH","PUE","Hot Aisle"], articles:["containment"] },

      { term:"ASHRAE", aliases:["ASHRAE A1","ASHRAE A2","Thermal Guidelines"], full:"American Society of Heating, Refrigerating and Air-Conditioning Engineers", meaning:"Standards body publishing thermal guidelines for DC environments. ASHRAE A1 (most common): 15-32°C inlet, 20-80% RH. A2 class allows wider range (10-35°C). Higher allowance = warmer supply air = less cooling energy.", whyMatters:"Defines acceptable server inlet temperatures. Expanding temperature range enables warmer supply air → reduced cooling energy → better PUE.", whereSeen:"DC design specs, cooling system design, server hardware environmental specs, audit checklists.", confusion:"ASHRAE A1 range 15-32°C means operating at 30°C inlet is safe. Technically A1 compliant but with very low margin. Most DCs target 18-24°C.", example:"Traditional setpoint: 16°C supply → 22°C server inlet. ASHRAE A2 allowance permits 35°C inlet. Raising supply to 20°C → 26°C inlet: chiller COP improves 15-20%.", related:["CRAC","CRAH","Containment","PUE","Inlet Temperature"], articles:[] },

      { term:"RCI", aliases:["Rack Cooling Index","Cooling Index"], full:"Rack Cooling Index", meaning:"Metric measuring how effectively the cooling delivery meets the IT equipment's cooling needs. RCI = percentage of racks with inlet temperatures within recommended range. RCI >96% = good. RCI <91% = poor.", whyMatters:"Quantifies cooling distribution quality at rack level. Different from PUE (facility level). RCI shows where cooling is inadequate.", whereSeen:"DCIM thermal analysis, cooling audit reports, DC design verification.", confusion:"Good PUE = good RCI. PUE measures overall efficiency. RCI measures distribution quality. A DC can have good PUE but poor RCI (hot spots).", example:"DCIM RCI report: 98% racks within ASHRAE A1 range. Two racks in Row 12 at 32°C inlet = pulling down RCI. Blanking panel issue found and fixed.", related:["PUE","DCIM","Containment","ASHRAE","Thermal Map"], articles:["rci"] },

      { term:"Airflow Management", aliases:["Airflow Optimization","Thermal Management"], full:"Data Center Airflow Management", meaning:"Systematic control of air movement in DC to maximize cooling efficiency. Includes: containment, blanking panels, perforated tile positioning, cable management, raised floor plenum management, in-row cooling.", whyMatters:"80% of DC hot spots resolved by airflow management, not adding more cooling equipment. Blanking panels alone can fix most thermal issues.", whereSeen:"Every DC. Perforated tiles, blanking panels, containment curtains, cable management systems.", confusion:"More CRAC = better cooling. Adding CRACs without fixing airflow = expensive and ineffective. Fix airflow first.", example:"Hot spot in Row 5: added another CRAC — no improvement. Then found: missing blanking panels in 6 racks. Fixed: hot spot resolved immediately. CRAC addition unnecessary.", related:["Containment","Blanking Panels","CRAC","CRAH","RCI"], articles:["airflow-management"] },
    ],
  },

  {
    heading: "Fire and Safety",
    color: "#dc2626",
    terms: [
      { term:"VESDA", aliases:["Very Early Smoke Detection","Aspirating Smoke Detector","ASD"], full:"Very Early Smoke Detection Apparatus", meaning:"Active air sampling smoke detection. Continuously draws air through pipes using fan. Analyzes for smoke particles. Detects fire at incipient stage — before visible smoke, before traditional detectors. Alarm levels: Alert → Action → Fire.", whyMatters:"DC needs earliest warning to allow equipment shutdown before suppression discharge. VESDA detects 30 min to hours before traditional detectors. Reduces false suppression events.", whereSeen:"Under-floor plenum, above ceiling void, within high-value racks. Xtralis VESDA, Napco brands.", confusion:"VESDA = regular smoke detector. Traditional detectors reactive (visible smoke). VESDA proactive — sub-visible particle detection.", example:"3 AM: VESDA Alert alarm. Engineer investigates: overheating PSU in row 12. Server gracefully shut down. Without VESDA: suppression would have activated at smoke stage.", related:["FM200","Novec","Fire Panel","Smoke Detector"], articles:["vesda"] },

      { term:"FM200", aliases:["HFC-227ea","Clean Agent","Heptafluoropropane"], full:"FM200 — Heptafluoropropane (HFC-227ea)", meaning:"Clean agent fire suppression gas. Extinguishes by heat absorption and oxygen displacement. Stored as liquid, discharged as gas flooding protected zone. No residue — safe for electronics. Discharge in 10 seconds.", whyMatters:"Standard DC fire suppression for 20+ years. No water damage to equipment. Return to service after discharge with minimal cleanup.", whereSeen:"Server rooms, UPS rooms, telecom equipment rooms. Cylinder banks in adjacent space. Kidde, Hochiki, Wagner brands.", confusion:"FM200 = Halon. Halon banned (ozone depleting). FM200 = HFC (not ozone depleting but GWP = 3500). Novec 1230 is newer lower-GWP alternative.", example:"Electrical fault generates smoke. Fire panel activates. Warning horn → 30-second delay for evacuation. FM200 discharges. Room flooded in 10 seconds. Equipment saved.", related:["Novec","VESDA","Fire Panel","Pre-Action","Clean Agent"], articles:["fm200"] },

      { term:"Novec 1230", aliases:["Novec","FK-5-1-12","3M Novec","Low GWP Agent"], full:"3M Novec 1230 Fire Protection Fluid (FK-5-1-12)", meaning:"Next-generation clean agent suppression. GWP = 1 (vs FM200 GWP = 3500). Fluoroketone chemistry. Extinguishes by heat absorption. Same performance as FM200, significantly better environmental profile.", whyMatters:"Regulatory future-proofing. High-GWP refrigerants and suppression agents being phased out. ESG reporting value. Green building certifications.", whereSeen:"New DC builds, green-certified DCs, European DCs (stricter environmental regulations). Retrofits replacing FM200.", confusion:"Novec = more effective than FM200. Performance similar. Novec advantage is environmental, not suppression effectiveness.", example:"New Mumbai DC: Novec vs FM200 decision. Cost +5%. ESG report benefits + regulatory future-proofing → chose Novec.", related:["FM200","VESDA","GWP","Fire Panel"], articles:["novec","novec-1250"] },

      { term:"LOTO", aliases:["Lockout Tagout","Lock Out Tag Out"], full:"Lockout Tagout Safety Procedure", meaning:"Safety procedure ensuring dangerous equipment is de-energized and cannot be restarted during maintenance. Physical lock applied by working engineer — cannot be removed by anyone else. Tag indicates work in progress.", whyMatters:"Life safety — equipment accidentally energized during maintenance = electrocution. Mandatory for all electrical/mechanical maintenance in DC.", whereSeen:"UPS battery work, generator maintenance, LT panel work, chiller maintenance. Required per OSHA globally.", confusion:"Tag alone = LOTO. Tag can be removed by others. Lock cannot. Always lock AND tag.", example:"Engineer servicing UPS battery: isolate → verify zero energy (multimeter) → own lock applied → tag → work. Only this engineer can remove their lock.", related:["Arc Flash","Isolation","Safety","Permit to Work"], articles:[] },

      { term:"Arc Flash", aliases:["Electrical Explosion","Arc Blast","Arc Fault"], full:"Arc Flash Electrical Hazard", meaning:"Electrical explosion from arc discharge. Releases enormous energy: 35,000°C heat (4× sun surface), light, pressure wave, molten metal. Measured in cal/cm² incident energy. PPE category based on hazard level.", whyMatters:"Engineers are killed by arc flash in DC environments. Working near energized HV equipment without proper arc-rated PPE = fatal risk.", whereSeen:"HT switchgear maintenance, LT panel work, UPS busbar work. NFPA 70E standard for PPE requirements.", confusion:"Safety glasses sufficient near electrical panels. Arc flash burns at distance from thermal energy — not electrical contact. Standard glasses inadequate.", example:"Arc flash study on HT switchgear: incident energy 8 cal/cm² at 600mm. Category 2 PPE required: arc-rated FR clothing, face shield, arc-rated gloves.", related:["LOTO","HT Panel","LT Panel","PPE"], articles:[] },

      { term:"Pre-Action System", aliases:["Pre-Action Sprinkler","Double Interlock","Pre-action"], full:"Pre-Action Sprinkler Fire Suppression System", meaning:"Sprinkler system requiring two independent events before water discharges: (1) fire detection activation AND (2) individual sprinkler head glass bulb fusing from heat. Prevents accidental water discharge from single fault.", whyMatters:"For DC areas where clean agent impractical. Reduces false discharge risk vs standard wet-pipe systems. Water still damages equipment if discharged.", whereSeen:"Large DC mechanical rooms, loading bays, storage areas, large open halls where clean agent flooding impractical.", confusion:"Pre-action = safe for servers. Water discharge still damages electronics. Clean agent preferred in server rooms. Pre-action for areas where clean agent impractical.", example:"Large DC: server halls use FM200/Novec. Mechanical plant room uses double-interlock pre-action. Both appropriate for their environments.", related:["FM200","VESDA","Sprinkler","Fire Panel"], articles:["sprinkler"] },

      { term:"Earthing", aliases:["Grounding","Earth System","Protective Earth","PE"], full:"Electrical Earthing / Grounding System", meaning:"Connection of equipment and system neutrals to earth potential. Dual role: 1. Safety — fault current path to earth, no voltage buildup on metal surfaces. 2. Signal quality — reference potential stabilized, EMI reduced, ground loops prevented.", whyMatters:"Improper earthing = safety hazard AND IT equipment failures. TN-S earthing system mandatory for DC (separate PE and N).", whereSeen:"All electrical installations. IS:3043 Indian standard. Earth resistance <1 ohm for DC environments.", confusion:"Any earthing system works for DC. TN-C (combined N/PE) creates noise on earth conductor — affects IT equipment. TN-S mandatory.", example:"DC with TN-C earthing: servers experiencing random errors and EMI issues. Converted to TN-S (separate PE). Problems resolved.", related:["HT Panel","LT Panel","Transformer","IS:3043","TN-S"], articles:["earthing"] },
    ],
  },

  {
    heading: "IT Networking",
    color: "#7c3aed",
    terms: [
      { term:"VLAN", aliases:["Virtual LAN","802.1Q","Virtual Local Area Network"], full:"Virtual Local Area Network", meaning:"Logical network segmentation on physical switches using IEEE 802.1Q tagging. Multiple isolated L2 networks on one physical switch. Traffic between VLANs requires L3 routing. VLAN IDs: 1-4094.", whyMatters:"Security isolation, traffic control, compliance (PCI-DSS CDE), multi-tenant DC isolation. Misconfiguration is one of most common DC network issues.", whereSeen:"Every production network. DC access layer: multiple VLANs per trunk port. L3 switch or router for inter-VLAN routing.", confusion:"VLAN = separate physical network. Wrong. VLANs share physical cable — logically separated by 802.1Q tags.", example:"VLAN 10 Management (IPMI/iDRAC), VLAN 20 Production, VLAN 30 Storage (iSCSI), VLAN 40 DMZ. Server compromise on VLAN 20 cannot reach iDRAC on VLAN 10.", related:["Trunk Port","BGP","OSPF","STP","VRF"], articles:["switch"] },

      { term:"Switch", aliases:["Network Switch","L2 Switch","L3 Switch","Managed Switch"], full:"Network Switch", meaning:"Layer 2 (or L3) network device that forwards frames based on MAC address table. L2 switch: VLAN, STP, port security. L3 switch: routing between VLANs, OSPF/BGP support. Leaf switches in Spine-Leaf, access switches in 3-tier.", whyMatters:"Core network infrastructure. Switch failure = all connected devices lose connectivity. Spine-Leaf architecture eliminates single switch as SPOF.", whereSeen:"Every DC. Cisco Nexus, Arista EOS, Juniper EX/QFX, HPE Aruba. ToR (Top-of-Rack) switches in each rack.", confusion:"Switch = hub. Hub broadcasts to all ports. Switch forwards only to destination MAC. Switches are intelligent, hubs are not.", example:"Spine-Leaf: 4 spine switches + 40 leaf switches. Each server connects to one leaf. Each leaf connects to all 4 spines. 2-hop max between any servers.", related:["VLAN","Spine-Leaf","STP","ECMP","Router"], articles:["switch"] },

      { term:"Router", aliases:["L3 Router","Border Router","Core Router"], full:"Network Router", meaning:"Layer 3 device forwarding packets based on IP routing table. Connects different networks/subnets. Routing protocols: OSPF (internal), BGP (external/ISP). DC border router: connects DC to ISP and cloud providers.", whyMatters:"Gateway for inter-network traffic. Border router connects DC to internet and cloud. Internal router (or L3 switch) routes between VLANs.", whereSeen:"DC network edge. Cisco ASR, Juniper MX, Arista 7280. Also embedded in modern L3 switches.", confusion:"Router = firewall. Router routes packets. Firewall filters packets based on security policy. Different functions, often different hardware.", example:"DC border router: BGP peering with ISP-A (primary) and ISP-B (backup). DC advertises 103.x.x.x/24 to both. ISP-A fails → BGP withdraws → traffic shifts to ISP-B.", related:["BGP","OSPF","Firewall","Switch","VPN"], articles:["router"] },

      { term:"Firewall", aliases:["NGFW","Next-Gen Firewall","Stateful Firewall","Packet Filter"], full:"Network Firewall", meaning:"Security device controlling network traffic based on rules. Stateless: per-packet rules. Stateful: connection tracking. NGFW (Next-Gen): application awareness, DPI, IPS/IDS. DC perimeter firewalls + internal microsegmentation.", whyMatters:"Primary network security control. Perimeter firewall + internal segmentation = defense in depth. NGFW identifies and blocks application-level threats.", whereSeen:"DC perimeter (internet-facing), DMZ, internal segmentation. Palo Alto Networks, Fortinet FortiGate, Check Point, Cisco Firepower.", confusion:"Firewall = router. Router routes packets. Firewall allows or blocks based on security policy. Stateful firewall tracks connection state for better security.", example:"DC perimeter NGFW: allows inbound port 443 to web tier. Blocks all inbound to DB tier except from app tier on port 3306.", related:["VLAN","Router","DMZ","IPS/IDS","Zero Trust"], articles:["firewall"] },

      { term:"Load Balancer", aliases:["LB","Application Load Balancer","Network Load Balancer","ALB","NLB"], full:"Network/Application Load Balancer", meaning:"Distributes incoming traffic across multiple servers. Prevents overload, provides HA. L4: TCP/UDP level, fast, by IP:port. L7: HTTP/HTTPS, URL routing, SSL termination, cookie persistence. Health checks remove unhealthy servers automatically.", whyMatters:"Critical for production DC HA. Sub-second failover vs DNS Round Robin (TTL-based = minutes). SSL offload reduces server CPU load.", whereSeen:"F5 BIG-IP, Citrix ADC, HAProxy, Nginx, AWS ALB/NLB, Azure Load Balancer, GCP Cloud LB.", confusion:"DNS Round Robin = load balancer. No health checking, no session persistence, slow failover. Real LB provides sub-second detection and failover.", example:"3-server web farm behind F5. Server 2 fails. F5 health check detects in 2 seconds. Traffic redistributed to servers 1 and 3. Users see nothing.", related:["VLAN","Switch","Firewall","SSL Offload"], articles:["load-balancer"] },

      { term:"BGP", aliases:["Border Gateway Protocol","eBGP","iBGP"], full:"Border Gateway Protocol", meaning:"Internet's routing protocol — path-vector, between Autonomous Systems (AS). Policy-based routing decisions. DC uses: ISP connectivity (multi-homing), AWS Direct Connect, Azure ExpressRoute, GCP Cloud Interconnect.", whyMatters:"Internet connectivity backbone. BGP misconfiguration causes major outages (Facebook 2021 — BGP route withdrawal = 6+ hours offline). Multi-ISP DC design requires BGP.", whereSeen:"DC border routers to ISP. Cloud connectivity (Direct Connect, ExpressRoute = BGP). Large DC internal Spine-Leaf fabric.", confusion:"BGP = OSPF. OSPF: internal, same AS, fast convergence. BGP: external, between ASes, deliberately slow for stability.", example:"DC: ISP-A (primary) and ISP-B (backup) both BGP peers. ISP-A fails → BGP withdraws routes → traffic via ISP-B in seconds.", related:["OSPF","AS","Multi-homing","SD-WAN","VRF"], articles:["sd-wan","router"] },

      { term:"OSPF", aliases:["Open Shortest Path First","Link State Protocol","Interior Gateway Protocol"], full:"Open Shortest Path First", meaning:"Link-State routing protocol within single AS. Routers exchange LSAs to build complete topology map. Dijkstra shortest path algorithm. Fast convergence (seconds after link change).", whyMatters:"Standard interior gateway protocol for DC networks. Spine-Leaf fabrics use OSPF or BGP internally for fast reconvergence.", whereSeen:"DC internal network between core/distribution/access. ISP backbone. Enterprise campus networks.", confusion:"OSPF = BGP. OSPF internal, fast. BGP external, deliberately slow. Different purposes, different use cases.", example:"Spine-Leaf DC: OSPF between all switches. Leaf loses uplink to Spine 1. OSPF reconverges in 1-2 seconds. Traffic rerouted via Spine 2.", related:["BGP","STP","Spine-Leaf","VLAN","Routing"], articles:["router"] },

      { term:"STP", aliases:["Spanning Tree Protocol","802.1D","RSTP","MSTP","Rapid Spanning Tree"], full:"Spanning Tree Protocol (IEEE 802.1D)", meaning:"L2 loop prevention. Root Bridge elected, ports assigned roles (Root, Designated, Blocked). Blocked ports prevent loops. RSTP (802.1w): faster convergence 1-2 seconds. MSTP: per-VLAN trees.", whyMatters:"L2 loops = broadcast storms = network unusable. STP prevents loops. But convergence (30-50 sec classic, 1-2 sec RSTP) is too slow for DC.", whereSeen:"All L2 switched networks. Legacy 3-tier DC architectures. Less relevant in modern Spine-Leaf (pure L3).", confusion:"STP = always safe. STP convergence unacceptable in DC. Modern: eliminate L2 loops by design (Spine-Leaf), not fix them with STP.", example:"Miscabling: both ends of patch cable in same VLAN. No BPDU Guard → broadcast storm → 200 servers impacted. Fix: BPDU Guard on all access ports.", related:["RSTP","BPDU Guard","Port Channel","Spine-Leaf","Loop"], articles:["switch"] },

      { term:"Spine-Leaf", aliases:["Clos Network","Spine-Leaf Architecture","Leaf-Spine","Fat-Tree"], full:"Spine-Leaf (Clos) Network Architecture", meaning:"Modern DC topology: every Leaf connects to every Spine. Any server-to-server = always 2 hops. No STP (pure L3). ECMP active-active on all uplinks. Linear scale: add Leaf = new rack, add Spine = more bandwidth.", whyMatters:"Optimized for east-west (server-to-server) traffic. Predictable latency, linear scalability, no STP issues. Replaced 3-tier in modern DCs.", whereSeen:"All modern DC builds. Hyperscale (Google, Meta, Amazon). 25GbE/100GbE leaf ports, 100GbE/400GbE spine uplinks.", confusion:"Spine-Leaf = always 2 physical switches. Wrong — number of each scales independently.", example:"40-rack DC: 4 spine switches, 40 leaf switches. Server in rack 1 to server in rack 40: Leaf-1 → Spine (any) → Leaf-40 = 2 hops always.", related:["BGP","ECMP","STP","Overlay","VXLAN"], articles:["switch","router"] },

      { term:"SD-WAN", aliases:["Software-Defined Wide Area Network","SD-WAN Gateway"], full:"Software-Defined Wide Area Network", meaning:"Overlay network managing WAN connections (MPLS, Internet, LTE) with centralized software control. Intelligent path selection based on application requirements and link quality. Zero-touch provisioning for remote sites.", whyMatters:"Replaces expensive dedicated MPLS with intelligent use of multiple cheaper links. Application-aware routing. Cloud on-ramp for hybrid DC.", whereSeen:"Enterprise branch-to-DC connectivity. DC-to-cloud connectivity. Cisco Viptela, VMware VeloCloud, Palo Alto Prisma SD-WAN.", confusion:"SD-WAN = VPN. VPN encrypts one path. SD-WAN manages multiple paths, selects best dynamically, encrypts all.", example:"Retail: 100 branches, SD-WAN device. MPLS primary + 4G backup. SD-WAN routes POS/ERP over MPLS, browsing over internet. MPLS fails → seamless failover to 4G in <1 second.", related:["VPN","MPLS","BGP","Zero-Trust","WAN"], articles:["sd-wan"] },

      { term:"ECMP", aliases:["Equal Cost Multi-Path","Equal-Cost Multipath","ECMP Routing"], full:"Equal-Cost Multi-Path Routing", meaning:"Routing technique using multiple equal-cost paths simultaneously. Traffic distributed across all paths — active-active load sharing. Used in Spine-Leaf architectures. Per-flow hashing preferred over per-packet (avoids out-of-order).", whyMatters:"Spine-Leaf DC networks rely on ECMP for bandwidth utilization. Without ECMP, redundant paths wasted.", whereSeen:"Spine-Leaf DC fabrics. Border routers with multiple ISP links. BGP and OSPF both support ECMP.", confusion:"ECMP distributes traffic evenly per packet. Per-packet ECMP = out-of-order packets. Per-flow ECMP = same flow always same path. Per-flow preferred.", example:"Leaf switch: 4 uplinks to 4 spines. ECMP distributes across all 4 active. One spine fails: 3 uplinks still active, traffic redistributes. 75% bandwidth maintained.", related:["Spine-Leaf","BGP","OSPF","Load Balancing"], articles:["switch","router"] },

      { term:"VRF", aliases:["Virtual Routing and Forwarding","VRF-Lite","Virtual Router"], full:"Virtual Routing and Forwarding", meaning:"Multiple independent routing tables on single physical router or L3 switch. Each VRF has own routing table, interfaces, forwarding decisions. Traffic between VRFs requires explicit policy. L3 equivalent of VLANs.", whyMatters:"Multi-tenant DC: same physical router serves multiple customers each in separate VRF. Complete routing isolation at L3.", whereSeen:"Service provider MPLS VPN. Multi-tenant colo DCs. DC border routers with separate customer routing.", confusion:"VRF = VLAN. VLAN = L2 segmentation. VRF = L3 routing segmentation. VRF can contain multiple VLANs.", example:"Colo DC: Customer A (10.0.0.0/8) and Customer B (also 10.0.0.0/8) on same router in separate VRFs. Identical IP ranges isolated.", related:["VLAN","BGP","MPLS","Multi-tenant"], articles:[] },
    ],
  },

  {
    heading: "Storage Technologies",
    color: "#16a34a",
    terms: [
      { term:"SAN", aliases:["Storage Area Network","FC SAN","iSCSI SAN"], full:"Storage Area Network", meaning:"Dedicated high-speed network for storage traffic. Block storage access — server sees storage as local disk. Protocols: FC, FCoE, iSCSI. Separate fabric from LAN.", whyMatters:"Enterprise storage standard for databases and mission-critical workloads. Dedicated fabric means storage traffic doesn't compete with network traffic.", whereSeen:"Enterprise DCs, banking, healthcare. VMware shared storage, Oracle RAC. NetApp, Pure Storage, Dell EMC PowerStore.", confusion:"SAN = NAS. SAN = block storage (server sees disk). NAS = file storage (server sees folder/share). Different use cases.", example:"Oracle RAC cluster: 4 servers sharing same SAN LUNs via FC fabric. Each server reads/writes same storage simultaneously.", related:["NAS","DAS","iSCSI","Fibre Channel","HBA"], articles:["san"] },

      { term:"NAS", aliases:["Network Attached Storage","File Server","NFS Server","SMB Storage"], full:"Network Attached Storage", meaning:"File-level storage accessed over standard IP network. Protocols: NFS (Linux), SMB/CIFS (Windows). Server accesses storage as network share/folder, not raw disk. Simpler management than SAN.", whyMatters:"Cost-effective file sharing, user home directories, media storage, backup target. No special hardware — uses existing Ethernet.", whereSeen:"File servers, backup targets, shared user storage. NetApp, Dell EMC Isilon, Synology, QNAP brands.", confusion:"NAS always slower than SAN. Modern NAS with NVMe and high-speed networking approaches SAN for many workloads.", example:"1000-user company: NAS serves home directories via NFS on Linux, mapped drives via SMB on Windows. Single 50TB NAS serves all users.", related:["SAN","DAS","SMB","NFS","iSCSI"], articles:["nas"] },

      { term:"DAS", aliases:["Direct Attached Storage","Local Storage","Internal Storage"], full:"Direct Attached Storage", meaning:"Storage directly connected to single server — no network. HDDs/SSDs in server itself or external enclosure via SAS/SATA. Not shareable between servers. Simplest storage architecture.", whyMatters:"Highest performance (no network overhead), lowest latency, simplest architecture. HCI platforms use DAS with software pooling.", whereSeen:"Individual servers, hyperconverged infrastructure (vSAN, Nutanix), edge servers, NVMe drives.", confusion:"DAS = simple = not enterprise. HCI uses DAS with software layer — very enterprise, very scalable.", example:"Web server: 2× NVMe SSD (DAS in RAID 1 for OS), 4× SSD (DAS for application data). No SAN needed.", related:["SAN","NAS","NVMe","RAID","HCI"], articles:["das"] },

      { term:"RAID", aliases:["Redundant Array of Independent Disks","RAID 0","RAID 1","RAID 5","RAID 6","RAID 10"], full:"Redundant Array of Independent Disks", meaning:"Multiple disks combined as logical volume for performance or redundancy. RAID 0: striping only. RAID 1: mirror. RAID 5: stripe+parity (1 fail). RAID 6: double parity (2 fails). RAID 10: mirror+stripe.", whyMatters:"Protects against disk failures without data loss. RAID is NOT a backup substitute — ransomware encrypts all RAID disks.", whereSeen:"All enterprise servers, storage arrays, NAS devices. Hardware RAID controller or software RAID (ZFS, mdadm).", confusion:"RAID = backup. RAID protects against disk failure only. Ransomware, accidental deletion, controller failure not protected. Both RAID AND backup needed.", example:"RAID 6: 8-disk array, any 2 disks can fail simultaneously without data loss. Disk 1 fails → rebuild starts → Disk 3 also fails → RAID 6 still operational.", related:["SAN","DAS","NAS","Hot Spare","Backup"], articles:[] },

      { term:"iSCSI", aliases:["Internet SCSI","iSCSI SAN"], full:"Internet Small Computer System Interface", meaning:"Block storage protocol encapsulating SCSI commands in TCP/IP packets. Storage traffic over standard Ethernet. No dedicated FC hardware needed. Uses dedicated storage VLAN. Jumbo frames (MTU 9000) recommended.", whyMatters:"Cost-effective SAN alternative. Uses existing Ethernet infrastructure. Modern 25GbE iSCSI approaches FC performance.", whereSeen:"Mid-market DCs, SMB server rooms, VMware vSphere datastore. Dedicated storage VLAN.", confusion:"iSCSI = slow. Modern 25GbE iSCSI with RDMA (iSER) matches FC latency for most workloads.", example:"50-server DC: FC SAN = Rs. 40L (FC switches + HBAs). iSCSI with dedicated 25GbE VLAN = Rs. 5L incremental. Same workloads fine at 0.3ms latency.", related:["SAN","Fibre Channel","NFS","NVMe-oF","Block Storage"], articles:["san"] },

      { term:"Fibre Channel", aliases:["FC","FC SAN","SAN Fabric","Fibre Channel SAN"], full:"Fibre Channel Storage Network", meaning:"Dedicated high-speed network protocol for storage. FC switches (SAN fabric), HBAs (Host Bus Adapters) in servers, FC cables. Lowest latency, highest reliability. Port speeds: 8/16/32/64 Gbps.", whyMatters:"Enterprise standard for mission-critical, high-IOPS storage. Dedicated fabric = zero interference with network traffic. Wire-level hardware ACK.", whereSeen:"Banking, financial services, healthcare, telco. Large Oracle/SAP environments. Brocade/Broadcom SAN switches, Cisco MDS.", confusion:"FC = always better than iSCSI. For typical enterprise workloads at 25GbE: iSCSI within 5-10% at fraction of cost.", example:"NYSE trading system: FC SAN, 32Gbps, sub-100µs storage latency. Trade execution requires microsecond performance. FC justified.", related:["iSCSI","SAN","HBA","NVMe-oF"], articles:["san"] },

      { term:"Backup", aliases:["Data Backup","Point-in-Time Copy","Recovery Backup"], full:"Data Backup and Recovery", meaning:"Point-in-time copy of data stored separately. Scheduled (hourly, daily, weekly). Protects against: accidental deletion, ransomware, hardware failure, corruption. Recovery: restore from backup = some time + some data loss (RPO = backup interval).", whyMatters:"Only protection against ransomware (pre-infection point-in-time). Replication copies encrypted data — doesn't protect. 3-2-1-1 rule.", whereSeen:"All production environments. Veeam, Commvault, Veritas NetBackup, AWS Backup, Azure Backup.", confusion:"RAID = backup. Wrong. Replication = backup. Wrong. Both protect against different failures but neither protects against ransomware without point-in-time copies.", example:"Ransomware encrypts production at 3 PM. Replication copies encryption to DR site. Only yesterday's 2 AM backup (point-in-time) can restore clean data.", related:["Disaster Recovery","Replication","RAID","RPO","RTO"], articles:["backup"] },

      { term:"Disaster Recovery", aliases:["DR","Business Continuity","DR Site","BCP"], full:"Disaster Recovery / Business Continuity", meaning:"Processes and infrastructure enabling recovery from major failure event. DR site: secondary DC with replicated systems. RTO: recovery time objective. RPO: recovery point objective. Active-Active, Warm Standby, Cold DR variants.", whyMatters:"Business survival after major incidents. DR design drives infrastructure investment. RTO/RPO requirements determine architecture.", whereSeen:"Enterprise DCs with DR contracts. AWS DR (Pilot Light, Warm Standby, Multi-Region). Azure Site Recovery. Veeam DR.", confusion:"DR = backup. DR includes backup but also infrastructure, networking, procedures, and testing. Backup alone is not DR.", example:"Bank: RPO 1 hour (1 hour max data loss), RTO 4 hours (operational within 4 hours). Warm standby DR site with hourly replication.", related:["Backup","RPO","RTO","Replication","SLA"], articles:["disaster-recovery"] },
    ],
  },

  {
    heading: "Availability and Reliability",
    color: "#0369a1",
    terms: [
      { term:"SLA", aliases:["Service Level Agreement","Uptime SLA","Availability SLA"], full:"Service Level Agreement", meaning:"Contractual commitment defining service quality, availability, response times, and penalties for breach. DC SLA: uptime % (99.9%, 99.99%), power availability, temperature range, incident response and resolution times.", whyMatters:"Financial and reputational obligation. SLA breach = financial penalty + client relationship damage. DC design must guarantee SLA commitments.", whereSeen:"Colocation contracts, cloud service agreements, managed service agreements.", confusion:"SLA = uptime only. SLA covers power quality, cooling (temperature/humidity), connectivity, MTTR for incidents, security requirements.", example:"Colo SLA: 99.99% power. Annual: 0.876 hours maximum unplanned downtime. DC had 1.5 hours downtime: SLA breached. Penalty: 10× monthly fee credit.", related:["RPO","RTO","Uptime","MTTR","SLA Credits"], articles:[] },

      { term:"RPO", aliases:["Recovery Point Objective","Maximum Data Loss"], full:"Recovery Point Objective", meaning:"Maximum acceptable data loss measured in time. If disaster happens, how much data can business tolerate losing? RPO 1 hour: system can lose up to 1 hour of data. Drives backup frequency and replication technology.", whyMatters:"Foundation of DR planning. RPO 5 minutes = near-real-time replication (expensive). RPO 24 hours = daily backup (cheap). Business defines it, IT implements it.", whereSeen:"DR plans, BCP documents, cloud backup configurations, database replication setups.", confusion:"RPO = RTO. RPO = data loss (time). RTO = recovery time (how fast). Both are separate requirements.", example:"E-commerce: RPO 4 hours. Server crashes 6 PM: last backup was 2 AM = 16 hours of orders lost. If business can't tolerate: needs hourly backup or continuous replication.", related:["RTO","DR","Backup","Replication","BCP"], articles:["disaster-recovery"] },

      { term:"RTO", aliases:["Recovery Time Objective","Maximum Downtime"], full:"Recovery Time Objective", meaning:"Maximum acceptable downtime — how quickly systems must be restored after disaster. Drives infrastructure design. RTO 4 hours = restore from backup. RTO 15 minutes = warm standby. RTO 0 = active-active.", whyMatters:"Determines DR infrastructure investment. Shorter RTO = more expensive solution. Financial trading RTO 0. Internal HR system RTO 24 hours.", whereSeen:"DR runbooks, BCP documents, cloud DR configurations, SLA documents.", confusion:"RTO = time to backup data. Wrong. RTO = time from disaster event to system fully operational again.", example:"Hospital patient management: RTO 30 minutes. Requires warm standby on secondary DC — hot replica ready, DNS change ready, runbook rehearsed.", related:["RPO","DR","Warm Standby","Failover","BCP"], articles:["disaster-recovery"] },

      { term:"MTTR", aliases:["Mean Time To Repair","Mean Time To Restore","Incident Resolution Time"], full:"Mean Time To Repair / Restore", meaning:"Average time to restore failed equipment or service to operational state. Measures maintenance efficiency and support responsiveness. Low MTTR = fast recovery.", whyMatters:"DC SLAs often include MTTR commitments (P1 resolved within 4 hours). Trend analysis identifies systemic maintenance issues.", whereSeen:"SLA documents (P1/P2/P3 incident resolution times), maintenance management systems, operations dashboards.", confusion:"MTTR = time to respond. MTTR includes full repair and restoration, not just first response.", example:"UPS MTTR target: 4 hours for P1. UPS fails 2 PM. Detected 2:01 PM. OEM arrives 4 PM. Module replaced 5 PM. Tested 5:30 PM. MTTR = 3.5 hours. Within SLA.", related:["MTBF","SLA","Availability","RCA"], articles:[] },

      { term:"MTBF", aliases:["Mean Time Between Failures","Mean Time Before Failure"], full:"Mean Time Between Failures", meaning:"Average time between failures for a component or system. Higher MTBF = more reliable. Used in equipment selection and maintenance scheduling.", whyMatters:"Equipment selection criteria. High MTBF components justify higher cost for critical applications. Component MTBF used in reliability calculations.", whereSeen:"Equipment specifications, reliability engineering calculations, OEM datasheets.", confusion:"MTBF = guaranteed lifetime. MTBF is statistical average — individual components can fail much sooner.", example:"Disk drive MTBF 1.5 million hours. With 1000 drives: statistically expect ~1 failure every 1500 hours (63 days). RAID and hot spares essential.", related:["MTTR","SLA","Availability","Reliability"], articles:[] },

      { term:"DCIM", aliases:["Data Center Infrastructure Management","DC Management Software"], full:"Data Center Infrastructure Management", meaning:"Software platform integrating real-time monitoring, capacity planning, change management, and analytics across all DC infrastructure — power, cooling, IT, space. Single pane of glass. Collects from BMS, SNMP, smart PDUs, sensors.", whyMatters:"DC complexity at scale cannot be managed manually. DCIM: real-time PUE, thermal maps, capacity forecasting, stranded capacity identification, automated alerts.", whereSeen:"Mid-large enterprise DCs and colocation. Vertiv Trellis, Schneider EcoStruxure IT, Nlyte, Device42, Sunbird.", confusion:"DCIM = BMS. BMS manages building infrastructure. DCIM manages IT + infrastructure together. DCIM consumes BMS data.", example:"DCIM alert: 'Rack R12C4 inlet temp 28.5°C (alert threshold). Trend: rising 0.5°C/hour.' Engineer investigates: CRAC filter clogged. Fixed before server throttling.", related:["BMS","PUE","Smart PDU","Capacity Planning","SNMP"], articles:["dcim"] },

      { term:"BMS", aliases:["Building Management System","Building Automation System","BAS"], full:"Building Management System", meaning:"Automated control system managing building's mechanical and electrical equipment — HVAC, cooling, ventilation, electrical monitoring, fire detection interfaces. Protocols: BACnet, Modbus. Collects sensors, runs control logic, raises alarms.", whyMatters:"Automation of facility operations — thousands of sensors and control points managed by software. Without BMS: impossible to operate at scale.", whereSeen:"Every commercial building and DC. Honeywell EBI, Siemens Desigo CC, Schneider EcoStruxure Building, Johnson Controls Metasys.", confusion:"BMS = DCIM. BMS manages building systems. DCIM manages IT + building integrated. BMS doesn't understand server density. DCIM does.", example:"BMS logic: CRAC outlet temp rising → increase CRAC airflow → still rising 5 min → SMS to on-call engineer → critical threshold → auto-escalate to site manager.", related:["DCIM","SCADA","BACnet","Modbus","Alarm Management"], articles:["bms"] },
    ],
  },

  {
    heading: "Cloud and Virtualization",
    color: "#2563EB",
    terms: [
      { term:"Hypervisor", aliases:["VMM","Virtual Machine Monitor","Type-1 Hypervisor","Type-2 Hypervisor"], full:"Hypervisor — Virtual Machine Monitor", meaning:"Software layer allowing multiple OSes simultaneously on single physical hardware. Type 1 (bare-metal): directly on hardware (VMware ESXi, Hyper-V, KVM). Type 2 (hosted): runs on OS (VirtualBox). Manages CPU, memory, disk, network virtualization per VM.", whyMatters:"Foundation of server virtualization. 30-50 VMs per physical server. Utilization from 15% (physical) to 70%+ (virtual). vMotion enables live migration.", whereSeen:"Every enterprise DC server cluster. VMware vSphere/ESXi most common. KVM for OpenStack/Linux. Public cloud hypervisors (AWS Nitro, Azure, GCP).", confusion:"Hypervisor = container runtime. Hypervisors run full VMs (complete OS). Containers share host OS kernel. Different isolation levels.", example:"Physical server: 2× Xeon 32-core, 512GB RAM, 4×25GbE. ESXi installed. 40 VMs deployed. CPU 70%, RAM 75% utilized. Without virtualization: 40 physical servers.", related:["VM","Container","VMware vSphere","vMotion","KVM"], articles:["virtualization"] },

      { term:"VM", aliases:["Virtual Machine","VMs","Guest VM","Virtual Server"], full:"Virtual Machine", meaning:"Complete software emulation of a physical computer. Includes virtual CPU, memory, storage, network adapters. Runs own complete OS. Managed by hypervisor. Isolated from other VMs on same physical hardware.", whyMatters:"Building block of virtualized DC infrastructure. Snapshots, cloning, vMotion (live migration), backup — all benefit from VM abstraction.", whereSeen:"Every virtualized DC. VMware vSphere VMs, Azure VMs, AWS EC2 instances.", confusion:"VM = physical server level isolation. VM isolation very good but not perfect. VM escape vulnerabilities exist (rare). Physical isolation still preferred for highest security.", example:"Legacy Oracle database on physical server → virtualized to VM on vSphere cluster: same specs, same performance, but live-migratable and snapshottable.", related:["Hypervisor","Container","vMotion","Snapshot","VMware"], articles:["virtualization"] },

      { term:"Container", aliases:["Docker Container","Linux Container","OCI Container"], full:"Application Container", meaning:"Lightweight process isolation unit. App + dependencies packaged in image. Shares host OS kernel. Boot milliseconds. Size MBs. Docker most common runtime. Kubernetes orchestrates at scale.", whyMatters:"Modern application deployment standard. Millisecond startup, consistent environments, microservices architecture enabler.", whereSeen:"Enterprise application platforms, CI/CD pipelines, public cloud (EKS, AKS, GKE). Docker Engine, containerd, Podman runtimes.", confusion:"Container = VM. VM has full OS isolation. Container shares kernel. Container isolation weaker — escape vulnerabilities. For sensitive workloads: VMs preferred.", example:"E-commerce: 200 microservices deployed as containers. K8s auto-restarts failed pods, scales on traffic, distributes load.", related:["VM","Kubernetes","Docker","Pod","Namespace"], articles:[] },

      { term:"AWS", aliases:["Amazon Web Services","Amazon Cloud","EC2","S3"], full:"Amazon Web Services", meaning:"World's largest public cloud platform. 200+ services: EC2 (compute), S3 (storage), RDS (database), VPC (networking), Lambda (serverless), IAM (identity). Global: 30+ regions, 90+ AZs.", whyMatters:"Largest market share cloud (~32% global). DC engineers increasingly manage hybrid AWS environments. Direct Connect, VPC, IAM, CloudWatch are daily tools.", whereSeen:"Global enterprises, startups, government. India regions: Mumbai (ap-south-1), Hyderabad (ap-south-2).", confusion:"AWS = cloud = simple. AWS has thousands of services with complex pricing, security configurations, and networking. AWS expertise is a career in itself.", example:"Bank: core banking on-prem. Digital banking app on AWS ap-south-1. Direct Connect 1Gbps from DC to AWS. Hybrid architecture.", related:["VPC","EC2","S3","IAM","Direct Connect"], articles:["aws"] },

      { term:"Azure", aliases:["Microsoft Azure","Azure Cloud","Azure AD","Entra ID"], full:"Microsoft Azure Cloud Platform", meaning:"Microsoft's public cloud. 200+ services. Strong in: Windows workloads, Active Directory (Entra ID), Office 365 integration, hybrid cloud (Azure Arc, Azure Stack). 60+ regions globally.", whyMatters:"Enterprise Microsoft shops extend naturally to Azure. Entra ID is enterprise identity standard. Azure ExpressRoute for private connectivity.", whereSeen:"Enterprise Microsoft environments, Windows Server/SQL workloads. India: Central India (Pune), South India (Chennai), West India (Mumbai).", confusion:"Azure = only for Microsoft workloads. Azure runs Linux excellently. Azure best advantage: Microsoft ecosystem integration.", example:"Enterprise: On-prem AD + Azure Entra ID via AD Connect. ExpressRoute 1Gbps. Azure VMs with Azure Hybrid Benefit licensing.", related:["Entra ID","ExpressRoute","Azure Arc","Azure Stack","IAM"], articles:["azure"] },

      { term:"GCP", aliases:["Google Cloud Platform","Google Cloud","GKE","BigQuery"], full:"Google Cloud Platform", meaning:"Google's public cloud. Differentiators: Google's global private fiber backbone, BigQuery (serverless analytics), GKE (most mature Kubernetes), TPUs for ML, Global VPC (unique — single VPC spans all regions).", whyMatters:"Best for: analytics (BigQuery), ML/AI (Vertex AI, TPUs), Kubernetes (GKE Autopilot), global networking. DC engineers manage GKE clusters, Cloud Interconnect.", whereSeen:"Data-intensive companies, ML/AI workloads. India: Mumbai (asia-south1), Delhi (asia-south2).", confusion:"GCP = only for Google-scale companies. GCP accessible to any size. BigQuery serverless analytics compelling for mid-size data teams.", example:"Media company: 5PB data analysis. BigQuery: query 5PB in 30 seconds. Same with on-prem Hadoop: 200+ nodes, 2-hour queries.", related:["BigQuery","GKE","Vertex AI","Cloud Interconnect","TPU"], articles:["gcp"] },

      { term:"Hybrid Cloud", aliases:["Hybrid IT","Hybrid Infrastructure","Cloud Hybrid"], full:"Hybrid Cloud Architecture", meaning:"Architecture integrating on-premises infrastructure with public cloud as unified system. Shared identity (AD + cloud IAM), unified monitoring, private connectivity (VPN/ExpressRoute/Direct Connect), workload portability.", whyMatters:"Most enterprise DCs are hybrid cloud today. DC engineers must understand cloud connectivity, identity federation, and hybrid workload management.", whereSeen:"Enterprise DCs globally. Azure Hybrid Benefit, AWS Outposts, Azure Arc — tools bridging on-prem and cloud.", confusion:"Hybrid cloud = having cloud and on-prem data. Wrong. Hybrid requires integration — shared identity, unified network path, consistent security policies.", example:"Indian bank: Core banking on-prem (RBI compliance). Customer app on Azure (elastic scaling). ExpressRoute connects DC to Azure. Shared AD identity.", related:["Multi-Cloud","ExpressRoute","Direct Connect","Azure Arc","VPN"], articles:["hybrid-cloud"] },

      { term:"Multi-Cloud", aliases:["Multi-Cloud Strategy","Multiple Cloud Providers","Cloud Diversity"], full:"Multi-Cloud Strategy", meaning:"Using multiple public cloud providers simultaneously (AWS + Azure + GCP). Avoids vendor lock-in, enables best-of-breed services. More complex than single cloud.", whyMatters:"Prevents single-vendor dependency. Best services per workload. Geographic coverage. Regulatory requirements per jurisdiction.", whereSeen:"Large enterprises, multi-national companies, organizations with strict vendor diversification policies.", confusion:"Multi-cloud = hybrid cloud. Hybrid: on-prem + cloud integration. Multi-cloud: multiple public clouds. A company can be both.", example:"Indian financial group: AWS Mumbai (primary workloads, RBI compliant), Azure West Europe (EU GDPR for European subsidiary), GCP (BigQuery analytics).", related:["Hybrid Cloud","AWS","Azure","GCP","FinOps"], articles:["multi-cloud"] },

      { term:"Kubernetes", aliases:["K8s","Container Orchestration","K8s Cluster"], full:"Kubernetes Container Orchestration Platform", meaning:"Open-source container orchestration managing deployment, scaling, and operation of containerized applications. Manages pods, services, deployments across cluster of nodes. De facto standard for container orchestration.", whyMatters:"Modern application deployment standard. DC engineers must understand K8s networking (CNI), storage (PV/PVC), and compute (node pools).", whereSeen:"Enterprise application platforms. Public cloud: EKS (AWS), AKS (Azure), GKE (GCP). On-prem: OpenShift, Rancher.", confusion:"Kubernetes = Docker. Docker is container runtime. Kubernetes is orchestration (managing many containers). K8s can use Docker, containerd, or CRI-O.", example:"E-commerce: 200 microservices as K8s pods across 20 nodes. K8s auto-restarts failed pods, scales services on traffic, distributes load.", related:["Container","Docker","Pod","CNI","Helm"], articles:[] },
    ],
  },

  {
    heading: "Monitoring and Security",
    color: "#475569",
    terms: [
      { term:"SNMP", aliases:["Simple Network Management Protocol","SNMP Trap","SNMP Poll","OID","MIB"], full:"Simple Network Management Protocol", meaning:"Standard protocol for network device monitoring and management. Manager polls devices (GET) or receives alerts from devices (TRAP). MIB defines available data points (OIDs). SNMPv3 adds auth and encryption.", whyMatters:"Monitoring backbone for DC infrastructure. UPS, CRAC, switches, servers — all via SNMP to central NMS.", whereSeen:"Every monitored device. Monitoring: Nagios, Zabbix, Prometheus SNMP exporter, SolarWinds.", confusion:"SNMP Trap = proactive monitoring. SNMP Trap: device alerts manager (async). SNMP Poll: manager asks device at intervals. Both needed.", example:"UPS SNMP: poll every 60s for battery %, load %, runtime. TRAP configured: immediate alert on bypass event, battery low, critical fault.", related:["MIB","NMS","OID","Zabbix","DCIM"], articles:[] },

      { term:"SIEM", aliases:["Security Information and Event Management","Log Management","SOC Platform"], full:"Security Information and Event Management", meaning:"Security platform collecting and correlating log data from all sources (servers, network devices, applications, cloud) for threat detection, investigation, and compliance. Real-time analysis, alert generation, long-term retention.", whyMatters:"Centralized security visibility across entire DC. Correlates events from multiple sources — finds threats invisible to individual systems.", whereSeen:"Enterprise SOC. Splunk, Microsoft Sentinel, IBM QRadar, Elastic SIEM. Cloud: Microsoft Sentinel, Sumo Logic.", confusion:"SIEM = log management. Log management = store logs. SIEM = correlate logs + detect threats + alert in real time.", example:"SIEM rule: 'Failed login on UPS web interface + successful login from internal IP within 5 minutes = alert.' Combined pattern = possible credential stuffing.", related:["SOC","SNMP","IAM","Log Management","Threat Detection"], articles:[] },

      { term:"Zero Trust", aliases:["Zero Trust Security","ZTNA","ZTA","Never Trust Always Verify"], full:"Zero Trust Security Architecture", meaning:"Security model: 'Never trust, always verify.' No implicit trust based on network location. Every access request verified: identity, device health, context. Microsegmentation. Least-privilege access.", whyMatters:"Traditional perimeter: internal network trusted. Zero trust: attacker inside still can't move laterally. Critical for modern distributed DC environments.", whereSeen:"Modern enterprise security. Zscaler, Palo Alto Prisma, Cloudflare Access. Cloud providers implementing for hybrid cloud.", confusion:"Zero Trust = VPN replacement. Zero Trust is architectural principle. ZTNA replaces VPN as one component. Full ZT includes IAM, device management, microsegmentation.", example:"Traditional: corporate network = trusted. Zero Trust: valid credentials + compliant device + business context required for each resource access.", related:["ZTNA","IAM","RBAC","MFA","Microsegmentation"], articles:["hybrid-cloud","multi-cloud"] },

      { term:"IAM", aliases:["Identity and Access Management","Identity Management","Access Control"], full:"Identity and Access Management", meaning:"Framework ensuring right users have right access to right resources at right times. Authentication (who are you), Authorization (what can you do), Accounting (what did you do). Cloud IAM: AWS IAM, Azure RBAC, GCP Cloud IAM.", whyMatters:"Security foundation — access control across all DC and cloud resources. IAM misconfiguration = unauthorized access. CIS Controls: IAM is #5 critical control.", whereSeen:"Every cloud environment, on-prem AD/LDAP, application-level access control.", confusion:"IAM = just passwords. IAM encompasses: MFA, RBAC, ABAC, PAM, just-in-time access, access certification.", example:"AWS IAM: EC2 instance needs to write to S3. Create IAM Role with S3 write permission, attach to EC2 instance profile. No credentials stored.", related:["RBAC","MFA","PAM","SAML","LDAP"], articles:["aws","azure","gcp"] },

      { term:"MFA", aliases:["Multi-Factor Authentication","Two-Factor Authentication","2FA","OTP","TOTP"], full:"Multi-Factor Authentication", meaning:"Authentication requiring two or more verification factors from different categories: something you know (password), something you have (hardware token, phone), something you are (biometric). TOTP, FIDO2/WebAuthn common methods.", whyMatters:"Passwords alone insufficient — credential theft, phishing all bypass password-only auth. MFA dramatically reduces account compromise risk.", whereSeen:"All admin access: iDRAC, switch management, cloud consoles, VPN, DCIM/BMS. Compliance requirements mandate MFA for privileged access.", confusion:"SMS OTP = strong MFA. SMS OTP weakest MFA — SIM swapping attacks defeat it. TOTP (authenticator app) better. FIDO2 hardware key strongest.", example:"DC rule: All iDRAC access = LDAP auth + TOTP (Google Authenticator). No exception. Contractor access: time-limited account + MFA mandatory.", related:["IAM","RBAC","Zero Trust","PAM","SAML"], articles:[] },

      { term:"PAM", aliases:["Privileged Access Management","Privileged Account Management","Password Vault"], full:"Privileged Access Management", meaning:"Security solution managing, monitoring, and auditing privileged accounts (admin, root, service accounts). Features: password vaulting (rotate after each use), session recording, just-in-time access, least-privilege enforcement.", whyMatters:"Privileged accounts are highest-value target. Compromised admin account = full DC access. PAM limits blast radius, provides complete audit trail.", whereSeen:"Enterprise DCs with compliance requirements. CyberArk, BeyondTrust, Delinea. Cloud-native: AWS IAM + SSM Session Manager, Azure PIM.", confusion:"PAM = password manager. Password managers for regular users. PAM for privileged accounts with additional controls: session recording, approval workflows.", example:"DC admin needs root to Linux server: Request in PAM → Manager approves → SSH access for 4 hours → Session recorded → Access auto-revoked → Password rotated.", related:["IAM","MFA","RBAC","Zero Trust","Audit"], articles:[] },

      { term:"CCTV", aliases:["Closed Circuit Television","IP Camera","Video Surveillance","NVR"], full:"Closed Circuit Television / Video Surveillance", meaning:"Video surveillance system for physical security monitoring. IP cameras (PoE or powered) connected to NVR/NAS for recording. Analytics: motion detection, person detection, face recognition. Retention typically 30-90 days.", whyMatters:"Physical security verification. CCTV + access log correlation enables incident investigation. Deterrent effect reduces violations.", whereSeen:"All DC facility areas: perimeter, building entry, corridors, server halls, critical rooms. Hikvision, Axis, Bosch, Dahua cameras.", confusion:"CCTV = security. CCTV records but doesn't prevent unless combined with access control and human response. Deterrent + investigation tool.", example:"Tailgating incident: Access log shows door opened with one badge. CCTV confirms two people entered. CCTV provides evidence for investigation.", related:["Access Control","Biometrics","Mantrap","Physical Security"], articles:["cctv"] },

      { term:"Access Control", aliases:["ACS","Physical Access Control","Card Access","PACS"], full:"Physical Access Control System", meaning:"Electronic system controlling physical access to DC areas. Components: card readers/biometrics, access control panels, electric strikes/maglocks, door status sensors. Logs all access events with timestamp and identity.", whyMatters:"Restricts physical access to authorized personnel. Log provides audit trail. Integration with HR systems for automatic access provisioning/deprovisioning.", whereSeen:"All DC zones. HID, Lenel, Software House, Genetec, Honeywell ProWatch systems.", confusion:"Access card = secure. Card can be tailgated or stolen. Card + PIN or biometric = more secure. Access logs must be reviewed regularly.", example:"DC access policy: Server hall = biometric + PIN. Building entry = card only. All events logged. Monthly review of dormant cards (not used 90 days).", related:["CCTV","Biometrics","Mantrap","Visitor Management"], articles:["access-control"] },

      { term:"Mantrap", aliases:["Airlock","Security Airlock","Anti-tailgating Airlock","Man Trap"], full:"Security Mantrap / Airlock", meaning:"Two-door security airlock — person enters first door (badge in), first door must close and lock before second door opens. Prevents tailgating physically. Only one person can be in the vestibule at a time (weight sensors or cameras verify).", whyMatters:"Technical control that physically prevents tailgating. Policy alone doesn't work — people hold doors. Mantrap makes tailgating mechanically impossible.", whereSeen:"High-security DC entrances, financial trading floors, government facilities. Often at server room entry from public area.", confusion:"Mantrap = revolving door. Mantrap is security airlock with interlocked doors. Revolving door doesn't prevent tailgating.", example:"DC with mantrap: badge reader on outer door → inner door opens only after outer closes → cameras verify single occupant → inner door releases.", related:["Access Control","CCTV","Biometrics","Tailgating"], articles:["mantrap"] },
    ],
  },
];

export const ALL_GLOSSARY_TERMS = GLOSSARY_SECTIONS.flatMap((s) =>
  s.terms.map((t) => ({ ...t, category: s.heading, color: s.color }))
);
