import type { TroubleshootingGuide } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// content/study/troubleshooting.ts
// All troubleshooting guide data. Add new guides here — page auto-renders.
// ─────────────────────────────────────────────────────────────────────────────

export const TROUBLESHOOTING_GUIDES: TroubleshootingGuide[] = [
  // ── POWER ──────────────────────────────────────────────────────────────────
  {
    id: "ups-bypass",
    category: "Power",
    categoryColor: "#f97316",
    title: "UPS Automatic Bypass — Load Unprotected",
    symptoms: [
      "UPS front panel pe 'BYPASS' LED blinking ya solid",
      "DCIM/BMS alarm: 'UPS in bypass mode'",
      "UPS input/output voltages same (no conversion happening)",
      "Battery not charging despite grid available",
    ],
    causes: [
      "UPS overloaded — load exceeds inverter capacity",
      "Inverter fault — IGBT failure, driver board fault",
      "Internal temperature high — cooling fan failure",
      "UPS firmware error — rare but post-firmware update possible",
      "Manual bypass switched accidentally during maintenance",
    ],
    verify: [
      "UPS event log download (LCD menu ya SNMP trap history) — review last 50 events",
      "Front panel alarm codes note karo — each code is a specific fault",
      "Load meter check: actual kW vs UPS rated kW capacity",
      "Ambient temperature around UPS — inlet vents blocked?",
      "Bypass switch position — manual bypass accidentally engaged?",
    ],
    steps: [
      "Safety first: Inform ops team and customer/stakeholder that load is unprotected",
      "Grid power quality check: Multimeter on UPS input — voltage stable? Frequency 50Hz?",
      "UPS event log download — first 10 events reveal root cause 90% of time",
      "Load check: Per-phase kW reading vs UPS rating — overload?",
      "Temperature check: UPS internal temperature (LCD or SNMP) — high temp auto-bypass triggers",
      "Contact OEM support 24x7 hotline with event log data already downloaded",
      "DO NOT force return to inverter without understanding root cause",
      "If overload: Load shed identify karo — which non-critical loads can be moved",
      "OEM diagnostic session: Remote access to UPS for deeper fault analysis",
      "Document everything — timestamp, actions, communications",
    ],
    rootCause: "Most common: Overloading (after server additions without capacity check) aur inverter IGBT failure (capacitor aging in older units, typically after 5-7 years). Fan failure se temperature-induced bypass bhi frequent.",
    resolution: "Overload: Immediate load shed + capacity planning review. Inverter fault: OEM field engineer, module replacement if modular UPS. Temperature: Clean cooling path, replace fans. Return to inverter only after root cause resolved.",
    prevention: [
      "UPS load monitoring weekly — alert configured at 75% loading",
      "Annual battery test + preventive maintenance (capacitor check at 5-7 years)",
      "Cooling path quarterly inspection — filter cleaning, fan check",
      "Load change control process — server additions need capacity approval",
      "SNMP traps to DCIM/BMS so bypass alarm gives instant notification",
    ],
    escalation: "OEM L2 support immediately. If site safety concern or outage risk — escalate to site manager + customer within 15 minutes of discovery.",
    siteExample: "Mumbai DC mein ek UPS ne bypass liya after midnight. Log check: load was 98% on one phase (unbalanced). Three servers added that afternoon without capacity check. Balanced load across phases, UPS returned to inverter without fault. Added capacity check to server deployment process.",
    mistakes: [
      "Ignore karna ya 'keep monitoring' bolna — bypass state = imminent outage risk",
      "Force transfer back to inverter without root cause = possible power blip",
      "Event log download bhool jaana — OEMs always ask for this first",
    ],
  },
  {
    id: "ups-battery-alarm",
    category: "Power",
    categoryColor: "#f97316",
    title: "UPS Battery Fault / Low Battery Warning",
    symptoms: [
      "UPS alarm: 'Battery fault', 'Battery disconnect', ya 'Replace battery'",
      "UPS runtime significantly reduced (from 15 minutes to 2-3 minutes)",
      "Battery temperature elevated on battery string sensors",
      "Battery voltage reading outside normal float range",
      "Battery string open circuit alarm",
    ],
    causes: [
      "Battery aging — VRLA lifespan typically 3-5 years",
      "Battery in elevated temperature environment (>25°C shortens life significantly)",
      "Cell reversal in battery string — one cell discharging others",
      "Loose or corroded battery terminal connections",
      "Battery charger fault — not maintaining proper float voltage",
      "External short circuit — accidental tool contact during maintenance",
    ],
    verify: [
      "Battery string voltage: Check overall string voltage and per-battery voltage",
      "Battery temperature sensors (if available): Temperature above 25°C significantly?",
      "Battery age: When were batteries last replaced? Date in maintenance log?",
      "Float voltage: Correct float voltage maintained by charger? (12V VRLA: ~13.6V)",
      "Physical inspection: Bulging, leakage, corrosion, burned terminals?",
      "Terminal torque: Verify proper torque on battery connections",
    ],
    steps: [
      "Safety first: Battery maintenance requires PPE (insulated gloves, safety glasses, arc flash gear)",
      "Load assessment: Current runtime test — how long will UPS hold load now?",
      "Identify which battery string has fault (multi-string UPS — isolate affected string)",
      "Per-battery voltage test under float: Any single battery significantly low?",
      "Temperature check: IR thermometer or thermal camera on battery terminals",
      "Terminal inspection: Torque check, corrosion cleaning if present",
      "Charger voltage verification: Is charger maintaining correct float voltage?",
      "Contact UPS OEM + battery vendor for capacity test and replacement recommendation",
      "If runtime critically low (<5 min): Alert management, consider load reduction, generator readiness check",
      "Schedule battery replacement during maintenance window with proper capacity available",
    ],
    rootCause: "Battery aging is #1 cause — VRLA batteries in DC environments have 3-5 year design life. Elevated ambient temperature halves battery life for every 10°C above 25°C. High ambient + aging = catastrophic failure risk.",
    resolution: "Battery replacement required. Cannot 'fix' aging batteries. Complete string replacement recommended (not individual batteries) — mixing old and new batteries degrades entire string. Replacement during scheduled maintenance window.",
    prevention: [
      "Battery replacement schedule: VRLA every 4 years regardless of apparent condition",
      "Annual battery capacity test (discharge test) — reveals actual remaining capacity",
      "Battery room temperature maintained 20-25°C year-round",
      "Monthly battery voltage measurement — per string",
      "SNMP battery alarms configured with 90/60/30 day advance warning",
    ],
    escalation: "If UPS runtime below 5 minutes with critical load: escalate immediately to site manager, consider graceful application shutdown, activate emergency power plan.",
    siteExample: "Pune DC: UPS battery alarm on string 3. Runtime test: 4 minutes remaining (was 15 minutes 18 months ago). Battery date check: 6 years old — significantly past replacement. Emergency replacement ordered. During investigation: battery room had no cooling — ambient 35°C consistently. Root cause: inadequate battery room cooling. Battery life: 2.5 years vs expected 5 due to temperature. Cooling added, replacement cycle shortened to 3 years.",
    mistakes: [
      "Replacing only failed batteries in a string, not the entire string",
      "Testing battery health only when alarm appears — annual capacity test proactive approach needed",
      "Battery room temperature ignorana — biggest life reduction factor",
    ],
  },
  {
    id: "dg-fail-start",
    category: "Power",
    categoryColor: "#f97316",
    title: "DG Set Fail to Start — Generator Won't Crank",
    symptoms: [
      "DG start signal sent from ATS but engine doesn't crank",
      "Control panel: 'Fail to start' alarm after multiple crank attempts",
      "ATS stays on position A (grid) even after grid failure",
      "No exhaust visible, no engine sound during start attempt",
    ],
    causes: [
      "Battery for DG starter motor discharged (trickle charger failure)",
      "Fuel starvation — level low, pump failure, filters choked",
      "Engine lube oil pressure alarm — safety protection preventing start",
      "Air filter blocked — especially in dusty environments",
      "Coolant temperature fault — coolant heater failure in cold weather",
      "Control board fault — start relay failure",
      "Water in fuel — especially if stored diesel over 6 months",
    ],
    verify: [
      "DG battery voltage: Starter battery (typically 24V system) — below 22V = depleted",
      "Fuel level gauge AND physical dipstick check — gauges can be stuck",
      "Oil pressure indicator at DG control panel",
      "Coolant temperature reading",
      "Control panel status LEDs — exact fault code",
      "Last successful test run log — when was it? Under load?",
    ],
    steps: [
      "Safety: Inform site team of DG failure. Note UPS battery time remaining — critical.",
      "Parallel track: Troubleshoot DG AND assess load shedding options simultaneously",
      "DG control panel: Any fault LED active? Note exact alarm code — call OEM with code ready",
      "Starter battery check: Voltmeter on battery terminals",
      "Fuel: Gauge reading + physical dip check. Fuel inlet valve open?",
      "Oil level dipstick: Low oil = engine protection prevents start",
      "Coolant level check",
      "Attempt manual crank (local control panel) — does engine attempt to crank?",
      "If cranks but doesn't fire: Fuel delivery issue (pump, filter, injectors, water in fuel)",
      "If no crank: Starter motor or battery issue",
      "Contact DG OEM/service contractor immediately with fault code and findings",
      "Assess: Rental DG possible if repair takes >30 minutes?",
    ],
    rootCause: "Most common: DG start battery discharged due to trickle charger failure. Second: Fuel filter clogged (especially low-quality diesel or old stored fuel). Third: Monthly test skipped — batteries self-discharge.",
    resolution: "Battery: Jump-start with portable battery pack immediately + replace starter battery. Fuel filter: Replace. Low fuel: Refuel immediately. Engine protection trips: Resolve root cause (oil, coolant), reset protection, retry.",
    prevention: [
      "Monthly DG test run under load — not just idle spin",
      "Weekly DG start battery voltage check",
      "Fuel quality check — water contamination test bi-annually",
      "Fuel filter replacement per OEM schedule (typically 250-500 operating hours)",
      "Trickle charger status monthly verification",
      "OEM annual maintenance contract — mandatory",
    ],
    escalation: "If DG fail during real grid failure with UPS battery <5 minutes: IMMEDIATE escalation to site manager + customer + DG OEM emergency service + rental DG inquiry.",
    siteExample: "Hyderabad DC quarterly test: DG fail to start — 3 crank attempts, no ignition. Investigation: Trickle charger had failed 3 weeks earlier. Starter battery completely discharged. Portable jump pack used for immediate start, proper battery replacement followed. Battery charger added to monthly maintenance checklist.",
    mistakes: [
      "Assuming DG fine because it started last month — batteries discharge between tests",
      "Only checking fuel level on gauge, not physically — gauges can be stuck/broken",
      "No OEM emergency contact on speed dial before real outage happens",
    ],
  },
  {
    id: "ats-no-transfer",
    category: "Power",
    categoryColor: "#f97316",
    title: "ATS Not Transferring — Grid to Generator Switch Fails",
    symptoms: [
      "Grid has failed (confirmed), DG running and stable",
      "ATS still showing position 'GRID' (not transferred to DG)",
      "UPS battery draining — DG not picked up as expected",
      "ATS alarm: 'Transfer failure' or stuck in transition",
    ],
    causes: [
      "DG output not within ATS acceptance window (voltage/frequency out of spec)",
      "ATS mechanical failure — contactor stuck, actuator fault",
      "ATS control logic fault — transfer logic not executing",
      "Interlocks not satisfied — DG safety alarms preventing transfer command",
      "DG ready signal not received by ATS (wiring or signal fault)",
      "Emergency stop engaged on ATS or DG — prevents transfer",
    ],
    verify: [
      "DG output voltage: Multimeter at DG output terminals — 415V ±10%?",
      "DG output frequency: DG panel display — 50Hz ±2Hz?",
      "ATS acceptance window settings: What voltage and frequency range programmed?",
      "ATS control panel: Any fault indication? Transfer attempted?",
      "DG 'ready' output signal: Is DG sending 'OK to transfer' signal to ATS?",
      "E-Stop buttons: Any emergency stop pressed on DG or ATS panel?",
    ],
    steps: [
      "Check DG output parameters: Voltage aur frequency within spec?",
      "ATS acceptance window: Some ATSs have tight frequency windows (49.5-50.5Hz). If DG governer slightly off — frequency out of window",
      "Manual transfer test (if ATS has manual mode): Attempt manual transfer from ATS panel",
      "Inspect ATS mechanism: Contacts visually OK? No burnt contacts?",
      "DG 'ready' relay output: Test with multimeter at ATS input terminal",
      "All interlocks check: E-stop, OLTP, protection relay input to ATS",
      "ATS control voltage check: ATS control supply (typically 24VDC or 220VAC) present?",
      "Contact ATS OEM with findings",
      "If transfer not happening and UPS battery critical: Load shed begin",
    ],
    rootCause: "DG frequency/voltage outside ATS acceptance window is most common (especially on older DG sets where governor needs maintenance). ATS mechanical failure less common but catastrophic — no transfer capability.",
    resolution: "DG governor calibration if frequency off. ATS replacement if mechanical failure. ATS acceptance window reconfiguration if too tight. Ensure DG stabilizes fully before ATS attempts transfer.",
    prevention: [
      "Quarterly ATS transfer test with actual DG — test full sequence",
      "DG governor calibration annual — verify frequency stability under load",
      "ATS acceptance window documented and appropriate for DG specification",
      "ATS contacts inspection annual — check for arc damage, burning",
    ],
    escalation: "If ATS failure with real grid outage and UPS battery critical: Emergency call to ATS OEM, manual transfer attempt (trained engineers only), customer notification.",
    siteExample: "Chennai DC: ATS not transferring to DG during grid failure simulation. DG running fine. Investigation: ATS frequency acceptance window was set to ±0.5Hz. DG frequency was 50.8Hz during warm-up — just outside window. Window widened to ±2Hz (standard). Transfer succeeded on retest. Lesson: ATS settings must match DG characteristics.",
    mistakes: [
      "Assuming ATS mechanical failure without checking DG output quality first",
      "Testing ATS transfer only without DG in circuit — incomplete test",
      "ATS acceptance window set to datasheet spec not actual DG behavior",
    ],
  },
  {
    id: "pdcb-trip",
    category: "Power",
    categoryColor: "#f97316",
    title: "PDU Circuit Breaker Trip — Rack Power Loss",
    symptoms: [
      "Servers in specific rack all powered off simultaneously",
      "PDU circuit indicator showing 'tripped' (usually red or no LED)",
      "DCIM power monitoring shows zero draw on specific PDU circuit",
      "Physical circuit breaker on PDU in tripped position (middle position on MCCB)",
    ],
    causes: [
      "Overcurrent — load exceeds circuit breaker rating",
      "Short circuit — internal server PSU failure",
      "Ground fault — insulation failure in cable or equipment",
      "Mechanical fault in circuit breaker — worn contacts trip at lower current",
      "Nuisance trip — inrush current spike during server startup sequence",
    ],
    verify: [
      "Visual inspection: Is circuit breaker in tripped position?",
      "Current draw just before trip: DCIM historical data — was load near breaker rating?",
      "Server PSU check: Any servers with fault LEDs after power loss?",
      "Cable inspection: Any visible damage, discoloration, burning smell?",
      "Verify circuit breaker rating matches documented capacity for that rack",
    ],
    steps: [
      "Check: Is any server smoking or showing signs of failure? If yes — do not restore power, investigate server first",
      "Identify circuit: Which PDU, which circuit, which servers affected",
      "Total load calculation: What was total kW draw before trip?",
      "If overload suspected: Power off some servers before attempting reset",
      "Circuit breaker reset attempt: Push fully to OFF then to ON",
      "If trips again immediately: Short circuit — do not reset again",
      "If resets successfully: Monitor current for next 10 minutes — stable?",
      "If intermittent trips: Check individual server PSU health, replace suspect PSU",
      "If circuit breaker will not reset or trips immediately: Remove all load, call electrician for breaker inspection",
      "Document: Time of trip, load at time, resolution, root cause",
    ],
    rootCause: "Most common: Overloading due to additional servers added without capacity check. Second: Individual server PSU internal failure creating instantaneous overcurrent. Third: Circuit breaker aging — trips at lower current than rated.",
    resolution: "Overload: Reduce load below 80% of breaker rating. PSU failure: Replace server PSU. Breaker mechanical issue: Replace breaker. All work involving circuit breakers requires qualified electrician.",
    prevention: [
      "PDU circuit loading: Maximum 80% of breaker rating (20% headroom)",
      "Per-circuit current monitoring via smart PDU",
      "Server addition approval including circuit capacity check",
      "Circuit breaker inspection as part of annual PDU maintenance",
    ],
    escalation: "Any signs of burning, melting, or persistent tripping: Immediately isolate power, do not attempt to reset, call electrician and fire safety officer.",
    siteExample: "Bangalore DC: 6 servers down, PDU circuit B2 tripped. Investigation: Circuit was rated 16A, load had grown to 18A after adding 2 servers over 3 months. No capacity check for last 2 additions. Moved 2 servers to adjacent circuit. Added per-circuit load monitoring with 80% alert threshold.",
    mistakes: [
      "Resetting circuit breaker without reducing load — will trip again immediately",
      "Resetting immediately if burning smell or smoke — fire hazard",
      "Non-electrician attempting breaker replacement — safety hazard",
    ],
  },

  // ── COOLING ─────────────────────────────────────────────────────────────────
  {
    id: "cooling-hotspot",
    category: "Cooling",
    categoryColor: "#0284c7",
    title: "Rack Hot Spot — High Inlet Temperature",
    symptoms: [
      "Rack inlet temperature >27°C (yellow alert), >32°C (red alert)",
      "Server fans at high speed — audibly louder than adjacent racks",
      "Server IPMI/iDRAC thermal warnings in event log",
      "Application performance degradation (thermal throttling)",
      "DCIM thermal map showing isolated hot zone",
    ],
    causes: [
      "Missing blanking panels — hot exhaust recirculates through empty rack slots",
      "Cable management blocking front airflow to servers",
      "High-density rack exceeding tile/CRAC design capacity for zone",
      "CRAC unit underperforming (filter clogged, low refrigerant, fan issue)",
      "Hot aisle containment breach — physical gap allowing hot-cold air mixing",
      "Perforated floor tile mis-positioned or insufficient tile count",
    ],
    verify: [
      "Thermal camera scan — front of rack, cold aisle, underfloor visible through tiles",
      "CRAC nearest unit: Operating normally? Temperature setpoint? Filter status light?",
      "Physical walk-through: Check all blanking panel positions top to bottom",
      "DCIM trend: Is this new or gradual? Any recent changes to rack (new servers)?",
      "Underfloor plenum check: Tile positions correct, no obstructions under hot rack",
    ],
    steps: [
      "Identify exact rack(s) affected — DCIM sensors or spot thermometer",
      "Visual inspection: Count missing blanking panels in affected rack",
      "Cable management audit: Front-to-back airflow path clear?",
      "Check rack kW draw vs design capacity for that floor zone",
      "CRAC/CRAH status: Filter check, outlet temperature, airflow rate",
      "Containment inspection: Physical barriers intact? Any gaps in containment?",
      "Perforated tile placement: Tiles in cold aisle, directly in front of high-draw servers",
      "Implement immediate fixes: Blanking panels, cable management",
      "Monitor temperature trend over 30 minutes after fixes",
      "If not resolved: Increase CRAC cooling output, engage cooling contractor",
    ],
    rootCause: "Missing blanking panels cause 80% of rack hot spots. Air takes path of least resistance — empty slots allow hot exhaust to recirculate. One missing 1U blanking panel can raise inlet temperature 5-8°C.",
    resolution: "Immediate: Install blanking panels in all empty rack slots. Medium-term: Review rack power density vs cooling zone capacity. Long-term: DCIM-based thermal monitoring with automated alerts at 27°C.",
    prevention: [
      "Blanking panels policy: All empty rack slots filled at all times — checked during weekly walk",
      "DCIM thermal alert at 27°C inlet — early warning before reaching critical",
      "Power density planning — don't exceed zone design capacity",
      "Quarterly thermal imaging survey",
      "Cable management standard enforced during rack build commissioning",
    ],
    escalation: "If inlet >35°C and no immediate root cause found: Contact cooling OEM. If server hardware at risk from sustained high temperature: notify application owners for graceful shutdown consideration.",
    siteExample: "Delhi DC audit — one row of racks consistently 4-6°C hotter than adjacent rows. Thermal camera: overhead containment had 2-meter gap. Hot exhaust directly entering cold aisle. Foam sealing resolved — inlet temperature normalized in 45 minutes. Cost: Rs. 500. Alternative (larger CRAC): Rs. 4 lakh.",
    mistakes: [
      "Increasing CRAC capacity without finding root cause — wasted energy and money",
      "Server thermal warnings ignoring — hardware failure accelerates at high temperature",
      "Blanking panels as cosmetic item — they are thermal management critical elements",
    ],
  },
  {
    id: "crac-fault",
    category: "Cooling",
    categoryColor: "#0284c7",
    title: "CRAC Unit Fault — Cooling Unit Offline",
    symptoms: [
      "CRAC unit fault alarm on BMS/DCIM",
      "CRAC unit fault LED active on front panel",
      "CRAC supply air temperature rising (less cold than normal)",
      "Adjacent rack temperatures gradually increasing",
      "CRAC compressor not running (no sound, low power draw)",
    ],
    causes: [
      "High pressure trip — refrigerant circuit fault, condenser fouling",
      "Low pressure trip — low refrigerant charge, evaporator freeze",
      "High supply air temperature trip — coil icing, airflow restriction",
      "Compressor fault — electrical failure, mechanical seizure",
      "Fan failure — evaporator fan or condenser fan failure",
      "Power supply fault — CRAC internal power issue",
    ],
    verify: [
      "CRAC front panel fault code — note exact code before calling OEM",
      "CRAC event log (if available) — last 20 events",
      "High/low pressure: Pressure gauges on CRAC if accessible",
      "Supply air temperature: Below setpoint = working but less efficient, above = fault",
      "Condenser unit (if split): Is condenser fan running? Any visible damage?",
      "Power supply check: CRAC main power ON? Circuit breaker intact?",
    ],
    steps: [
      "Check N+1 status: Other CRACs in zone — can they carry increased load?",
      "Notify: Cooling capacity reduced — rack temperatures may rise. Monitor closely.",
      "CRAC front panel: Fault code? Attempt reset (press fault reset button)?",
      "If resets: Monitor for 30 minutes — does fault recur?",
      "If doesn't reset or recurs: Note fault code, call cooling OEM/contractor",
      "Condenser check (split system): Is condenser fan running? Fins clean?",
      "Refrigerant leak check: Any ice on suction pipe, frost? Oil staining around connections?",
      "Temperature trend: If zone temperatures rising rapidly — load shedding may be needed",
      "If >75% load on remaining CRACs: Alert to potential thermal risk, engage contractor urgently",
    ],
    rootCause: "High pressure trips most common in hot climates — condenser fouling (dust on fins reduces heat rejection), refrigerant overcharge, or condenser location with recirculating hot air. Low pressure = refrigerant leak.",
    resolution: "High pressure/condenser fouling: Clean condenser coils (specialist work). Low pressure/refrigerant leak: Leak detection, repair, recharge (licensed refrigerant technician). Fan failure: Replacement. Allow OEM/certified contractor to perform all refrigerant work.",
    prevention: [
      "Quarterly condenser coil cleaning — especially dusty environments",
      "Annual preventive maintenance by OEM/certified contractor",
      "Refrigerant pressure logging monthly — trending helps predict failure",
      "Filter replacement per OEM schedule (typically 3-6 months)",
      "CRAC runtime hours log — maintenance triggered by hours, not calendar",
    ],
    escalation: "If multiple CRACs down simultaneously or zone temperatures rising >32°C: Immediate cooling contractor emergency call. Consider application load shedding if thermal risk high.",
    siteExample: "Noida DC: CRAC unit 3 fault alarm 3 PM. High pressure trip. Investigation: Outdoor condenser unit fins completely blocked with dust and debris (industrial area). Condenser coil cleaning — CRAC operational in 2 hours. Had been running degraded for weeks (high head pressure, poor efficiency). Quarterly cleaning schedule established.",
    mistakes: [
      "Attempting refrigerant work without certification — illegal and dangerous",
      "Ignoring one CRAC fault when zone has N+1 — degraded state needs urgent repair",
      "Not checking condenser unit when indoor CRAC has high pressure fault",
    ],
  },
  {
    id: "chiller-fault",
    category: "Cooling",
    categoryColor: "#0284c7",
    title: "Chiller Plant — Chilled Water Temperature Rising",
    symptoms: [
      "Chilled water supply temperature rising above setpoint",
      "BMS alarm: Chiller leaving water temperature high",
      "CRAHs drawing more chilled water (valves opening further)",
      "Server inlet temperatures gradually rising across DC",
      "Chiller plant kW consumption changing unexpectedly",
    ],
    causes: [
      "Chiller compressor fault — VFD failure, compressor protection trip",
      "Condenser fouling — cooling tower scaling, poor water treatment",
      "Chilled water pump failure — reduced flow",
      "Chilled water bypass valve stuck open — short-circuiting the circuit",
      "BMS setpoint changed — chiller not hitting lower temperature",
      "IT load increase — chiller at capacity, can't meet setpoint",
    ],
    verify: [
      "Chiller status: Compressor running? What alarms active?",
      "Chilled water supply/return temperatures: What is current supply temp?",
      "Condenser water supply temp (from cooling tower): What is it?",
      "Chilled water flow rate: Flow meter reading — normal?",
      "BMS setpoint: What temperature setpoint is active?",
      "IT load: Any recent significant load increase?",
    ],
    steps: [
      "BMS: Identify which chiller(s) active, any fault alarms",
      "Chiller local panel: Fault code if compressor tripped",
      "Check available standby chillers: N+1 available? Start standby chiller if needed",
      "Chilled water temperature trend: Rising rapidly or slowly? Rate of rise determines urgency",
      "Condenser water temperature check: High condenser water = poor cooling tower performance",
      "Cooling tower check: Fan running? Water level? Drift eliminators intact?",
      "Bypass valve position check: Any valve in open position that should be closed?",
      "Start standby chiller if available and primary is faulted",
      "Contact chiller OEM/HVAC contractor with fault code",
      "If temperatures approaching critical (server inlet >27°C): Notify operations team",
    ],
    rootCause: "Chiller compressor protection trips most common (high head pressure, refrigerant issues). Cooling tower fouling/scaling reduces condenser water temperature performance. Chilled water pump failure reduces flow causing temperature rise.",
    resolution: "Chiller fault: OEM engineer required. Cooling tower fouling: Water treatment specialist + cleaning. Pump failure: Pump maintenance or replacement. Start standby chiller immediately during troubleshooting if available.",
    prevention: [
      "Chilled water quality testing monthly (pH, conductivity, inhibitor levels)",
      "Cooling tower inspection and cleaning quarterly",
      "Chilled water pump vibration monitoring — bearing failure early detection",
      "Chiller annual OEM preventive maintenance",
      "BMS trending of approach temperature — early condenser fouling detection",
    ],
    escalation: "Multiple chiller fault or inadequate cooling capacity: HVAC contractor emergency call. Cascade cooling failures require incident manager and customer notification.",
    siteExample: "Gurgaon financial DC: Chilled water supply temperature rising from 7°C to 14°C over 4 hours on summer afternoon. Investigation: Cooling tower scaling had reduced heat rejection capacity. Condenser water temperature was 38°C vs design 32°C. Emergency chemical treatment + standby chiller brought on line. Full cooling tower descaling scheduled next week. Temperature monitoring daily until fixed.",
    mistakes: [
      "Adjusting chiller setpoint upward to 'stop the alarm' — masking the problem",
      "Not checking cooling tower when chiller shows high head pressure",
      "Ignoring chilled water quality — monthly testing frequently skipped",
    ],
  },

  // ── NETWORKING ───────────────────────────────────────────────────────────────
  {
    id: "network-vlan",
    category: "Networking",
    categoryColor: "#7c3aed",
    title: "VLAN Connectivity Failure — Servers Not Reaching Gateway",
    symptoms: [
      "Servers in specific VLAN can't ping gateway",
      "ARP requests going unanswered (packet capture shows no ARP reply)",
      "Inter-VLAN traffic failing but intra-VLAN works",
      "Switch port shows up/up but no traffic passing",
      "DHCP failures in specific VLAN",
    ],
    causes: [
      "VLAN not configured on trunk port between switches",
      "STP blocking port in specific VLAN",
      "Layer 3 switch: interface VLAN not created or not 'no shutdown'",
      "Access port in wrong VLAN (mis-configuration during rack move)",
      "Native VLAN mismatch between trunk endpoints",
      "ACL blocking traffic between VLANs",
    ],
    verify: [
      "Show VLAN database: Is VLAN ID created? Is port in correct VLAN?",
      "Show trunk: Is VLAN in allowed list on trunk ports?",
      "Show spanning-tree vlan X: Any ports in blocking state?",
      "Layer 3: Show interface vlan X — UP/UP? IP address correct?",
      "Packet capture on server NIC: ARP being sent? Any reply?",
    ],
    steps: [
      "Confirm VLAN ID on server NIC config matches switch configuration",
      "Check switch port: access mode? Correct VLAN? 'show int GiX/X switchport'",
      "Trace trunk path: All trunk ports in path have VLAN allowed? 'show int trunk all'",
      "STP check: 'show spanning-tree vlan X' — port states. Any blocking?",
      "Layer 3 SVI: 'show interface vlan X' — is it up? Correct IP?",
      "Default gateway on server correct? Same subnet as VLAN SVI?",
      "Packet capture at server level: ARP for gateway MAC — reply received?",
      "Check ACLs: any ACL on VLAN interface blocking traffic?",
      "If DHCP issue: 'show ip dhcp binding' — IP assigned? Helper address on SVI?",
      "Compare working VLAN config with broken VLAN — find the diff",
    ],
    rootCause: "Most common: VLAN added to server but not propagated to all trunk ports in path. Or STP topology change after maintenance that left port in blocking.",
    resolution: "Add VLAN to trunk ports (both ends), verify SVI is up, check STP states. If STP blocking incorrectly: investigate root bridge placement, PortFast on access ports.",
    prevention: [
      "Change management: VLAN addition requires documentation of all trunk ports it must traverse",
      "Network diagram with VLAN-to-port mapping — updated after every change",
      "STP monitoring — topology change alert",
      "Post-change connectivity test standard procedure",
    ],
    escalation: "Network team L2 after initial assessment. If production impact: notify application team ETA, NOC involvement for monitoring.",
    siteExample: "Post server rack migration, 3 servers couldn't reach gateway. 45-minute debug: trunk port on new ToR switch missing VLAN 40 in allowed list. One command fixed it. Root cause: migration checklist didn't include 'verify VLAN trunk config on destination switch'. Added to checklist.",
    mistakes: [
      "Rebooting server without checking network first — server reboot won't fix switch config",
      "Checking only access port without verifying trunk ports upstream",
      "Missing native VLAN mismatch — subtle issue causing intermittent behavior",
    ],
  },
  {
    id: "network-link-flap",
    category: "Networking",
    categoryColor: "#7c3aed",
    title: "Network Link Flapping — Intermittent Connectivity",
    symptoms: [
      "Interface going up-down repeatedly (flapping) in syslog",
      "Intermittent connectivity — ping timeouts every few seconds",
      "STP topology changes triggered by flapping port",
      "Application sessions dropping periodically",
      "Switch syslog: 'LINEPROTO-5-UPDOWN: GiX/X changed state to down/up'",
    ],
    causes: [
      "Faulty SFP transceiver — intermittent optical signal",
      "Dirty fiber connectors — cleaning required",
      "Damaged fiber cable — bend radius exceeded, physical damage",
      "Cable negotiation mismatch — duplex/speed auto-negotiation issue",
      "Faulty NIC in server — intermittent signal transmission",
      "Power issue on switch port — marginal power to SFP",
    ],
    verify: [
      "Interface error counters: CRC errors, input errors, runts, giants? Increasing counts?",
      "Optical power levels (SFP): 'show interface transceiver' — Tx/Rx power within spec?",
      "Cable type: Fiber or copper? Which media type?",
      "SFP type: Compatible with port? Supported by switch?",
      "Duplex/speed: 'show interface GiX/X' — any duplex mismatch?",
      "Flap frequency: How often? Correlated with temperature changes?",
    ],
    steps: [
      "Interface log: Note exact flap times — any pattern (time of day, temperature)?",
      "SFP diagnostic: 'show interface transceiver detail' — Rx power within range?",
      "Fiber end-face inspection: Clean connectors with fiber optic cleaning kit (IEC 61300-3-35)",
      "Swap SFP: Replace with known-good SFP from spare parts",
      "Test with patch cable: Replace patch cable if copper, try shorter fiber if fiber",
      "Move cable to different port: Does issue follow port or cable?",
      "Speed/duplex: Force to specific setting (avoid auto-negotiation if causing issues)",
      "If issue follows SFP: Replace SFP. If follows cable: Replace cable.",
      "If issue follows port: Escalate to switch maintenance/replacement",
    ],
    rootCause: "Dirty fiber connectors cause 60-70% of fiber link flaps. Fiber contamination (fingerprints, dust) causes optical signal degradation. Second: faulty SFP transceivers, especially third-party or aging units.",
    resolution: "Fiber cleaning with proper tools (one-click cleaner or wet-dry cleaning). SFP replacement. Cable replacement. Never touch fiber end-face with fingers.",
    prevention: [
      "Fiber cleaning before every connection — one-click cleaners are inexpensive",
      "Store fiber connectors with dust caps when not in use",
      "SFP inventory — always have hot spares",
      "Fiber patch panel inspection quarterly — end-face inspection microscope",
    ],
    escalation: "If link flapping causing significant production impact and root cause not immediately clear: raise to network team L2 with full diagnostic data.",
    siteExample: "Critical link between core switch and distribution switch flapping 30+ times per hour. Caused STP topology changes affecting entire building network. Root cause: LC connector on fiber patch cable had microscopic crack on end-face from previous mishandling. Replaced Rs. 500 patch cable — link stable. Fiber inspection kit deployed at all patch panels.",
    mistakes: [
      "Cleaning fiber with cloth/tissue — damages end-face with scratches",
      "Touching fiber end-face with fingers — oil contamination causes attenuation",
      "Replacing switch hardware before checking cables and SFPs",
    ],
  },
  {
    id: "network-spanning-tree",
    category: "Networking",
    categoryColor: "#7c3aed",
    title: "Spanning Tree Loop — Network Broadcast Storm",
    symptoms: [
      "Network essentially unusable — very high CPU on all switches",
      "All interfaces showing very high traffic utilization simultaneously",
      "Ping timeouts to all devices (not specific)",
      "Switch syslog: Many STP topology change notifications rapidly",
      "Some interfaces showing millions of broadcasts per second",
    ],
    causes: [
      "Loop created — cable plugged into two ports creating physical loop",
      "PortFast on trunk port — BPDU ignored, loop not detected",
      "BPDU Guard disabled — BPDU not sent/received to detect loop",
      "Incorrect STP root bridge — suboptimal topology or root election issue",
      "Unmanaged switch added to network without STP support",
    ],
    verify: [
      "Show interface counters: Which port has highest broadcast count?",
      "Show spanning-tree: Any topology changes? Root bridge correct?",
      "Physical inspection: Any cables connected to two ports? Any unmanaged switch?",
      "Packet capture: Broadcast storms visible? Same MAC from multiple ports?",
    ],
    steps: [
      "IMMEDIATELY: Identify and physically disconnect the loop-causing cable",
      "If source unclear: Start systematically disconnecting suspect ports until storm stops",
      "Show span-tree: Is root bridge as designed?",
      "Check for unmanaged switches: Any consumer/small business switch added without STP?",
      "After loop resolved: Verify STP reconvergence (may take 30-50 seconds on classic STP)",
      "Check all PortFast + BPDU Guard configurations",
      "Verify all trunk ports do NOT have PortFast configured",
    ],
    rootCause: "Physical loop introduced by accidental double-cabling or adding a device with two network ports connected to the same network. Unmanaged switches without STP cause loops that aren't self-healing.",
    resolution: "Disconnect the offending cable. Implement BPDU Guard on all access ports to prevent future loops. Consider replacing any unmanaged switches with managed switches.",
    prevention: [
      "BPDU Guard enabled on all access ports (PortFast ports)",
      "Root Guard enabled on access ports facing distribution",
      "Loop Guard enabled on non-designated STP ports",
      "Unmanaged switches prohibited policy enforcement",
      "Change management for any cable/switch additions",
    ],
    escalation: "Broadcast storm can take down entire network segment — immediate escalation to network team and site management. Application teams: connectivity may be impacted during storm and STP reconvergence.",
    siteExample: "Data center network storm traced to engineer testing a new patch cable — plugged both ends into the same patch panel accidentally (different ports on same VLAN). BPDU Guard not enabled on those ports. Storm lasted 8 minutes, multiple server connections dropped. Post-incident: BPDU Guard enabled on all access ports within 24 hours.",
    mistakes: [
      "Adding configuration changes during active storm — isolate issue first",
      "Not checking for physical loops before complex configuration debugging",
      "Restarting switches during storm — problem returns when switch comes back up",
    ],
  },

  // ── STORAGE ──────────────────────────────────────────────────────────────────
  {
    id: "storage-iops",
    category: "Storage",
    categoryColor: "#16a34a",
    title: "Storage Performance Degradation — High Latency",
    symptoms: [
      "Application response time increased significantly",
      "Storage array dashboard: high queue depth (>8 for SSD, >2 for HDD)",
      "Server logs: disk I/O wait time high",
      "Storage latency >5ms for SSD (should be <1ms)",
      "IOPS counter at or near array maximum rated IOPS",
    ],
    causes: [
      "Disk array controller CPU overloaded",
      "RAID rebuild consuming disk I/O resources",
      "Cache hit ratio low (cold cache after restart, or working set larger than cache)",
      "Noisy neighbor — one VM consuming disproportionate IOPS",
      "HBA queue depth misconfigured",
      "SAN fabric saturation or ISL congestion",
      "Disk failure reducing RAID stripe performance",
    ],
    verify: [
      "Array management console: latency histogram, controller utilization, cache stats",
      "RAID status: Any rebuild in progress? Degraded RAID set?",
      "Per-LUN IOPS: Which LUNs are busiest? Any single LUN consuming >50% IOPS?",
      "SAN fabric: ISL utilization percentage? Congestion notifications?",
      "Host HBA stats: Queue depth, TX/RX rates, error counts",
    ],
    steps: [
      "Array console: Current latency graph — when did spike start? Correlate with changes",
      "RAID health check: Any disk failed? Rebuild in progress?",
      "Cache statistics: Hit ratio — below 80% is concerning for hot data",
      "Per-LUN performance: Identify top IOPS LUN — is it expected?",
      "Check controller balance: In dual-controller arrays, is load balanced?",
      "SAN fabric utilization: FC switch stats, ISL usage",
      "HBA queue depth: SSD recommended = 256, HDD = 32 (varies by OEM)",
      "If RAID rebuild: Current rebuild rate, ETA. Consider I/O throttling.",
      "If noisy neighbor: Identify VM, apply storage QoS policy",
      "Document findings for capacity planning",
    ],
    rootCause: "RAID rebuild is #1 cause of unexpected storage degradation. Second: Cache miss after maintenance restart. Third: Gradual workload growth exceeding array capacity.",
    resolution: "RAID rebuild: Wait and monitor, optionally throttle rebuild rate. Cache miss: Wait for warm-up (hours). Noisy neighbor: QoS policy. Capacity issue: Add SSD cache tier or expand array.",
    prevention: [
      "Storage performance baseline — weekly latency/IOPS/throughput report",
      "RAID spare disks always present and ready",
      "Capacity alert at 70% IOPS utilization",
      "Firmware and driver updates per OEM recommended schedule",
    ],
    escalation: "Storage OEM L2 if: controller failure suspected, RAID rebuild fails, data integrity warnings. Escalate to application owner if degradation impacts SLA.",
    siteExample: "Financial services client: Storage latency suddenly from 0.8ms to 12ms. Root cause: RAID-6 rebuild started after disk failed overnight. Rebuild consumed 40% array I/O. Built-in rebuild throttle enabled (30% max I/O for rebuild). Latency normalized in 20 minutes. Disk failure alert had been missed — monitoring gap fixed.",
    mistakes: [
      "Array reboot without root cause — cache loss makes it worse",
      "RAID rebuild ignore — degraded RAID + another failure = data loss",
      "Only application performance monitoring without storage-level visibility",
    ],
  },
  {
    id: "storage-disk-failure",
    category: "Storage",
    categoryColor: "#16a34a",
    title: "Storage Disk Failure — RAID Degraded State",
    symptoms: [
      "Storage array alarm: 'Drive failure' or 'Drive removed'",
      "RAID group showing 'Degraded' status",
      "Array performance may degrade (RAID 5/6 without spare)",
      "Predictive failure alert (SMART errors) before actual failure",
      "Array status indicator showing amber/red",
    ],
    causes: [
      "Disk mechanical failure — bearing, read head",
      "Disk firmware bug — sudden death syndrome",
      "Drive removed accidentally during maintenance",
      "Environmental factors — vibration, temperature excursion",
      "Disk age — past typical 5-7 year lifespan",
    ],
    verify: [
      "Array management: Which specific disk (bay, slot) failed?",
      "Disk SMART data if accessible: How many reallocated sectors, errors?",
      "RAID group status: Degraded? How many disks failed?",
      "Hot spare: Is hot spare disk assigned? Auto-rebuild starting?",
      "Other disks in same RAID group: Any SMART warnings on siblings?",
    ],
    steps: [
      "Identify failed disk exactly: Bay number, drive identifier",
      "RAID group status: Single failure (degraded) or two failures (failed)?",
      "Hot spare check: Is auto-rebuild starting on hot spare?",
      "If no hot spare: Urgency high — order replacement immediately. Until replaced, one more failure = data loss.",
      "Other disks in group: Pull SMART data from all disks in same RAID group — any others approaching failure?",
      "Replacement disk: Same vendor, same model, equal or larger size, same interface",
      "After disk replacement: Verify rebuild starts. Monitor rebuild completion.",
      "Rebuild time estimate: Depends on disk size and array load — large HDD arrays may take 24-48 hours",
      "After rebuild complete: Verify RAID group back to optimal status",
      "Increase monitoring frequency until rebuild complete",
    ],
    rootCause: "Disk mechanical failure — most common. 'Baby shoes syndrome': new disks and old disks fail more than mid-life disks. RAID groups with disks of same age all approach end of life simultaneously — dangerous.",
    resolution: "Replace failed disk with identical or compatible drive. Monitor auto-rebuild. After rebuild: RAID back to full redundancy. Order spare disks proactively for matching arrays.",
    prevention: [
      "Hot spare disks configured for all critical RAID groups",
      "SMART monitoring — predictive failure detection",
      "Disk age tracking — proactive replacement before end of lifespan",
      "Mixed-age disks in RAID groups where possible (not all same batch)",
      "Spare disk inventory on-site — minimize time-to-replace",
    ],
    escalation: "Two disk failures in same RAID group (RAID 5) = data loss risk — OEM emergency support immediately. Any RAID group failure = storage administrator + application owner notification.",
    siteExample: "VMware storage array: Disk failure on Saturday night. No hot spare configured. IT team on call didn't notice alarm until Monday morning — 36 hours in degraded state. Second disk showed SMART errors same batch. Critical risk situation. Emergency hot spares procured. Policy change: all RAID groups must have hot spare. SMART monitoring to ticketing system automated.",
    mistakes: [
      "Rebuilding RAID with wrong disk type (wrong interface, smaller size)",
      "Not monitoring SMART data on surviving disks during rebuild",
      "No on-site spare disks — procurement takes days, disk is unprotected during that time",
    ],
  },

  // ── BMS/DCIM ─────────────────────────────────────────────────────────────────
  {
    id: "bms-false-alarm",
    category: "BMS",
    categoryColor: "#0369a1",
    title: "BMS False Alarm — Nuisance Alarms Flooding System",
    symptoms: [
      "Hundreds of alarms in BMS in short period — clearly not real events",
      "Same alarm repeatedly firing and clearing",
      "BMS alarm system overwhelmed — real alarms may be missed",
      "Operations team ignoring alarms because too many false ones",
      "BMS polling showing 'communication failure' to field devices",
    ],
    causes: [
      "BMS sensor failed — sending erratic values (alarm/clear cycling)",
      "BMS communication issue — controller losing contact with sensor",
      "Sensor threshold set too tight — real process variation triggering alarm",
      "BMS software bug — alarm logic error after update",
      "Network issue between BMS server and field controllers",
      "Power fluctuation affecting BMS field devices",
    ],
    verify: [
      "Which specific point is generating alarms? Same sensor or multiple?",
      "BMS trend data for that point: What is actual value doing?",
      "Communication status: BMS controller showing 'OK' or 'Fail' for field device?",
      "Alarm threshold setting: Is current deadband appropriate for process?",
      "Recent changes: Any BMS software update? Any sensor recently replaced?",
      "Physical sensor check: Is it accessible? Any visible damage?",
    ],
    steps: [
      "Identify flood source: Sort alarms by source — which sensor/controller causing most?",
      "BMS trend for that point: Is value actually oscillating? Or stuck at error value?",
      "Communication status: If controller shows communication fail — network/power to field device",
      "If sensor value stuck at error (0, negative, 9999): Sensor fault",
      "Suppress alarm temporarily in BMS to stop flood — but document reason",
      "Physical inspection of sensor: Connected? Visible damage?",
      "Replace sensor if faulty (temperature sensor, pressure sensor, etc.)",
      "If threshold issue: Widen deadband to reduce false alarm rate",
      "After fix: Re-enable suppressed alarm, verify behavior",
      "Never leave alarm permanently suppressed without root cause fix",
    ],
    rootCause: "Single faulty sensor generating hundreds of alarms most common. Communication loss between BMS controller and field device also creates flood of 'status unknown' alarms.",
    resolution: "Faulty sensor replacement. Communication restoration (check network cable, BACnet/Modbus connection). Threshold adjustment with documented rationale.",
    prevention: [
      "BMS alarm quality metrics: Track nuisance alarm rate per month — target <5% false alarm",
      "Alarm threshold review annually — are setpoints still appropriate?",
      "Sensor preventive maintenance and calibration per OEM schedule",
      "BMS software updates in non-production environment first",
    ],
    escalation: "If alarm flood masks real critical alarms: temporarily put BMS in acknowledged mode while source identified. Real events cannot be missed.",
    siteExample: "Large DC BMS: 400+ alarms in 2 hours, all from 'CRAC-7 supply air temperature'. Investigation: Temperature sensor had failed open — sending -40°C reading (error value). BMS alarming on low temperature. Sensor replaced (Rs. 3,000 part), 400 false alarms stopped. Operations team were planning to reduce alarm sensitivity — correct fix was sensor replacement.",
    mistakes: [
      "Increasing alarm thresholds to reduce false alarms without finding root cause",
      "Permanently suppressing alarms instead of fixing sensor",
      "Ignoring all alarms because 'there are always false alarms' — real events get missed",
    ],
  },

  // ── CLOUD ────────────────────────────────────────────────────────────────────
  {
    id: "cloud-connectivity",
    category: "Cloud",
    categoryColor: "#2563EB",
    title: "Cloud VPN Connectivity Failure — On-Prem Cannot Reach Cloud",
    symptoms: [
      "Applications on-prem timeout when calling cloud APIs",
      "VPN tunnel shows 'down' or flapping in SD-WAN/VPN console",
      "Cloud-hosted databases unreachable from on-prem servers",
      "BGP session to cloud router not established",
      "Traceroute to cloud private IP fails at routing boundary",
    ],
    causes: [
      "VPN tunnel down — IKE/IPsec re-keying failure",
      "BGP session dropped — hold timer expired, route withdrawn",
      "Firewall rule blocking VPN traffic (UDP 500/4500)",
      "MTU mismatch — large packets fragmented or dropped in tunnel",
      "Cloud-side changes — security group, route table, gateway changes",
      "ISP-side routing change impacting path to cloud",
    ],
    verify: [
      "VPN gateway status: Both tunnels up? (AWS: Site-to-Site VPN console shows 2 tunnels)",
      "BGP session: BGP neighbor state — Established? Session uptime?",
      "Small packet test: Ping to cloud private IP with small size (-s 100) — success?",
      "Large packet test: Ping -M do -s 1400 — success? (MTU test)",
      "On-prem firewall: UDP 500, 4500 outbound allowed?",
      "Cloud security group: Allows inbound from on-prem CIDR?",
    ],
    steps: [
      "Identify: VPN tunnel issue or application-level issue? Ping cloud private IP.",
      "VPN console check: Tunnel status — Up/Down? Last state change time?",
      "BGP check: Neighbor status, prefixes received/sent",
      "Small packet test first — ping 100 byte. Passes = connectivity exists.",
      "Large packet test — if small passes but large fails = MTU issue. Check MSS clamping.",
      "Firewall audit: On-prem firewall outbound ports for VPN open?",
      "Cloud side: Security groups, route tables, VPN gateway status",
      "Provider status pages: Any cloud outage?",
      "If BGP: Reset BGP session (soft reset first)",
      "If tunnel down: Re-initiate IKE from on-prem side",
    ],
    rootCause: "VPN tunnel IKE rekeying failure (often after 24-hour rekey timer) most common. MTU issues common after VPN infrastructure changes. Cloud-side security group or route table changed by another team.",
    resolution: "IKE failure: Re-initiate VPN tunnel from on-prem. MTU: Set MSS clamping (TCP MSS = MTU - 40 bytes, typically 1350-1380 for VPN). BGP: Re-establish session.",
    prevention: [
      "VPN tunnel health check — automated ping every 5 minutes, alert on failure",
      "BGP session monitoring — alert on state change",
      "Change management for cloud infrastructure changes",
      "VPN certificate expiry monitoring",
      "MTU testing during VPN initial setup — document working MTU value",
    ],
    escalation: "If production application impacted: notify application owner immediately with ETA. ISP-side issue: ISP NOC contact. Cloud provider: Open support case.",
    siteExample: "Mumbai DC to Azure connectivity dropped every Sunday at 2 AM. Root cause: IKE SA lifetime 86400 seconds — Azure initiates rekey at midnight UTC (5:30 AM IST). On-prem firewall had UDP 4500 intermittently blocked due to high connection table. Fixed: reduced IKE lifetime to 28800 seconds + firewall UDP session table increase.",
    mistakes: [
      "Only checking on-prem side — cloud side changes are very common cause",
      "Skipping large packet test — MTU issues invisible with small pings",
      "No VPN monitoring — learning about failures from application users",
    ],
  },

  // ── SERVERS ───────────────────────────────────────────────────────────────────
  {
    id: "server-post-failure",
    category: "Servers",
    categoryColor: "#475569",
    title: "Server POST Failure — Server Won't Boot",
    symptoms: [
      "Server powered on but no OS boot — stuck at POST screen",
      "iDRAC/iLO showing POST error codes",
      "Physical error LEDs on server front panel",
      "Repeated reboot cycles without completing POST",
      "Memory failure codes displayed on server LCD",
    ],
    causes: [
      "Memory module failure — single DIMM failure or memory compatibility issue",
      "DIMM not seated properly after maintenance",
      "CPU failure or CPU not seated correctly",
      "PCIe device causing POST hang (network card, storage controller)",
      "BIOS/UEFI corruption",
      "Battery failure on server board (CMOS battery)",
    ],
    verify: [
      "Server LCD/front panel error code — note exact code before anything",
      "iDRAC/iLO system event log — what error was logged at last power-on?",
      "Physical: DIMMs all seated? CPU socket cover installed?",
      "Any recent maintenance on server? What was done?",
      "POST beep codes: How many beeps, what pattern?",
    ],
    steps: [
      "Note exact error code from front panel/LCD — don't reset it before noting",
      "iDRAC/iLO system log: Check last power-on events",
      "Power off, reseat all DIMMs — remove and firmly reinstall each",
      "Power on with minimal hardware: Remove all PCIe cards except essential",
      "Memory test: Boot with one DIMM at a time to isolate failed module",
      "BIOS reset to defaults: BIOS/UEFI → Load Optimal Defaults",
      "CMOS battery check: If server date resets to 2000 → CMOS battery flat (CR2032)",
      "If CPU fault suspected: Requires OEM engineer — CPU socket is very delicate",
      "Update server firmware (BIOS/iDRAC) if other steps fail",
      "Contact OEM with exact error code if unresolved",
    ],
    rootCause: "Memory module failure or poor seating after maintenance most common. PCIe card conflict (new card causing POST hang) second most common. BIOS corruption less common but requires firmware reflash.",
    resolution: "Memory: Replace failed DIMM. PCIe conflict: Remove cards one by one to identify offender. BIOS corruption: BIOS recovery procedure (varies by OEM — typically USB recovery or jumper reset).",
    prevention: [
      "Proper ESD procedures during memory/hardware work",
      "Verify memory compatibility before installation (OEM compatibility list)",
      "Record server configuration before maintenance for easy restoration",
      "BIOS backup before any firmware update",
    ],
    escalation: "CPU fault or motherboard fault: OEM engineer required — cannot be field-repaired without proper tools and training.",
    siteExample: "Dell R750 server POST failing after RAM upgrade. Code: 'DIMM slot B1 failure'. Reseating DIMM — still failing. Moved DIMM to different slot — worked. Original B1 slot had damaged socket pin. Server RMA'd for slot repair. Verification procedure added: test each new DIMM in its designated slot before closing server.",
    mistakes: [
      "Adding multiple changes at once — can't isolate which caused POST failure",
      "Not noting error code before attempting fixes — loses diagnostic information",
      "Attempting CPU reseating without proper training — CPU socket pins extremely delicate",
    ],
  },

  // ── FIRE ─────────────────────────────────────────────────────────────────────
  {
    id: "fire-vesda-alarm",
    category: "Fire",
    categoryColor: "#dc2626",
    title: "VESDA Alarm — Early Smoke Detection Response",
    symptoms: [
      "VESDA panel showing Alert or Action level alarm",
      "VESDA aspirating pipe shows increased particle count",
      "BMS alarm from fire detection system",
      "VESDA Pre-alarm level activated (below full alarm threshold)",
    ],
    causes: [
      "Actual overheating equipment — incipient fire stage",
      "Dust contamination in aspirating pipe (especially during construction/work nearby)",
      "Chemical contamination — solvent, cleaning products used near pipe inlets",
      "Pest activity in underfloor — rodent droppings near inlet",
      "VESDA sensor aging — sensitivity drift",
    ],
    verify: [
      "Which VESDA zone? What sampling pipe inlet point? Narrow location.",
      "VESDA alarm level: Alert vs Action vs Fire alarm — determines urgency",
      "Visual inspection: Walk the zone immediately — any visible smoke? Burning smell?",
      "Server equipment: Any fault LEDs, amber indicators in the zone?",
      "Temperature sensors in zone: Any elevated readings?",
    ],
    steps: [
      "Immediately: Two-person response to VESDA zone. Both must assess before any action.",
      "Visually inspect zone: Any visible smoke? Burning smell? Any equipment with fault indicators?",
      "Server equipment inspection: Power supply LEDs, any overheating components",
      "Cable check: Any cables with discoloration, burning odor?",
      "If ANY signs of actual smoke: Follow emergency procedure — evacuation, fire panel notification",
      "If no visible smoke: VESDA may be reacting to construction dust, cleaning chemicals",
      "Notify fire safety officer per site procedure",
      "VESDA engineer called to inspect system and identify alarm source",
      "Do NOT acknowledge and ignore VESDA alarm without physical investigation",
      "Document: Time, zone, observations, actions taken",
    ],
    rootCause: "In DC environments: overheating power supply (most common actual risk) or dust/chemical contamination (most common false alarm). VESDA sensitivity means it alarms well before visible smoke — this is its value.",
    resolution: "Actual smoke source: Power off equipment, follow fire emergency procedure, notify fire department if actual fire. Dust/chemical: Clean aspirating pipes, identify contamination source. VESDA false alarm still requires root cause identification.",
    prevention: [
      "Negative pressure work areas during construction to prevent dust entering DC",
      "Chemical use prohibition in DC without fire safety officer approval",
      "VESDA cleaning and calibration per OEM schedule",
      "Server equipment health monitoring — power supply health before VESDA alarm stage",
    ],
    escalation: "Any sign of actual smoke or burning: Immediate fire emergency response — evacuation, fire department notification, fire panel activation. VESDA Action level without visible cause: Senior management + fire safety officer notification.",
    siteExample: "VESDA Alert alarm at 11 PM in pod 3. Two engineers investigate immediately. Find: Server in row 12 with amber PSU fault LED and slight burning smell from rear. Server gracefully shut down. PSU had failing capacitor — pre-failure stage. VESDA caught it before actual fire. Server PSU replaced. VESDA prevented what would have been a serious fire 2-3 hours later.",
    mistakes: [
      "Acknowledging VESDA alarm without physical investigation — most dangerous mistake",
      "One person investigating alone — safety requires at least two",
      "Disabling VESDA zone because of 'too many false alarms' without fixing root cause",
    ],
  },

  // ── SECURITY ─────────────────────────────────────────────────────────────────
  {
    id: "security-tailgating",
    category: "Security",
    categoryColor: "#64748b",
    title: "Physical Security Incident — Tailgating Detection",
    symptoms: [
      "Access control system shows door held open beyond normal time",
      "CCTV shows two persons entering on one badge swipe",
      "Access log shows badge scan but person count doesn't match",
      "Visitor log person not escorted but moved to restricted area",
    ],
    causes: [
      "Authorized person held door for unauthorized person (politeness)",
      "Visitor left unescorted contrary to procedure",
      "Contracted maintenance person not badged in properly",
      "Security guard not present at reception",
      "Anti-tailgating system (if installed) not configured or faulty",
    ],
    verify: [
      "CCTV footage: Review exact door event — who entered on that badge?",
      "Access log: What badge/person is associated with that access event?",
      "Visitor log: Any unaccounted visitors at that time?",
      "Identify the second person: Employee? Vendor? Unknown?",
    ],
    steps: [
      "Review CCTV from suspected tailgating event",
      "Identify both individuals if possible",
      "Check visitor log against CCTV — any unregistered visitor in building?",
      "Security guard (if present): Interview about observed event",
      "Alert all security staff — unauthorized person may be in building",
      "Systematic area sweep if unidentified person suspected to be inside",
      "If person identified and harmless (employee from different department): Document and debrief",
      "Security incident report filed regardless of apparent severity",
      "Building sweep completion: Verify all areas checked, person accounted for",
      "Review and close",
    ],
    rootCause: "Human behavior — politeness overriding security protocol ('I didn't want to be rude by not holding the door'). Cultural change needed alongside technology controls.",
    resolution: "Security awareness training. Policy reinforcement: 'You are responsible for persons who follow you through your access point.' Potential disciplinary action for repeated violations. Consider man-trap installation.",
    prevention: [
      "Regular security awareness training — 'no tailgating' specific training",
      "Man-trap (airlock) at building/DC hall entry — physically prevents tailgating",
      "CCTV + access log correlation alerts for door-held-open events",
      "Security culture: Reporting encouraged, not penalized",
    ],
    escalation: "If unidentified person found in restricted area: Security incident, police notification if warranted, immediate management escalation.",
    siteExample: "Annual security audit: CCTV review revealed 6 tailgating incidents in one month, all by different employees. Security awareness training conducted — 'each person is responsible for who follows them'. Month after training: Zero tailgating incidents captured on CCTV. Culture change more effective than additional physical controls in this case.",
    mistakes: [
      "Not treating tailgating as serious — 'it was just an employee' attitude",
      "No CCTV + access log correlation — incidents go undetected",
      "Security audits too infrequent to detect patterns",
    ],
  },
];

/** Category list derived from data — page can use for filter UI */
export const TROUBLESHOOTING_CATEGORIES = [
  ...new Set(TROUBLESHOOTING_GUIDES.map((g) => g.category)),
].sort();

// ── ADDITIONAL GUIDES WITH FULL A→I→D→R→P→RCA WORKFLOW ─────────────────────

const ADDITIONAL_GUIDES: TroubleshootingGuide[] = [
  {
    id: "ups-bypass-workflow",
    category: "Power",
    categoryColor: "#f97316",
    title: "UPS Automatic Bypass — Workflow Guide",
    alarm: "BMS/DCIM: 'UPS in Bypass mode'. Front panel BYPASS LED active. Immediate risk: load on grid with NO battery protection. Any grid fault = instant server outage.",
    isolation: "Confirm which UPS, which bus. Automatic bypass (UPS fault) or manual (maintenance)? Note exact bypass time — correlate with workload changes same day.",
    diagnosis: "Download UPS event log immediately. Note exact fault code. Check per-phase kW vs rated capacity. Check internal temperature via LCD/SNMP. Inspect cooling path — inlet vents blocked? Capacitor age?",
    resolution: "Overload: shed non-critical loads below 80% capacity. Return to inverter only after root cause confirmed. Inverter fault: OEM field engineer required. Temperature: clean cooling path, verify all fans. Never force-transfer back without confirmed root cause.",
    prevention: ["UPS load alert at 75%", "Annual battery + capacitor PM", "Cooling path quarterly inspection", "Load change approval process"],
    rca: "Why was load allowed to reach overload? Capacity check bypassed during server additions? Battery temperature monitored? OEM PM schedule followed? Action: capacity approval process + 75% load alert + annual PM contract.",
    symptoms: ["UPS BYPASS LED active", "DCIM alarm: UPS in bypass", "Input/output voltages identical (no conversion)", "Battery not charging"],
    causes: ["Load exceeds inverter capacity", "Inverter IGBT failure", "Internal overtemperature", "Manual bypass accidentally engaged"],
    verify: ["Event log download via LCD or SNMP", "Per-phase load reading vs rated kW", "Internal temperature reading", "Bypass switch position"],
    steps: ["Inform ops team and customer — load unprotected", "Grid quality check (multimeter)", "Event log review — first 10 events", "Load check per phase", "Temperature check", "OEM 24x7 hotline with log data", "Do NOT force return to inverter without root cause"],
    rootCause: "Overloading after server additions without capacity check (most common). Inverter IGBT failure due to aging capacitors (5-7 years). Fan failure causing temperature-induced bypass.",
    escalation: "OEM L2 immediately. Site manager + customer within 15 minutes if outage risk.",
    siteExample: "Mumbai DC: UPS bypass at midnight. Log showed phase A at 98% (unbalanced). Three servers added that afternoon without capacity check. Load balanced across phases, UPS returned to inverter.",
    mistakes: ["Ignore and 'keep monitoring'", "Force transfer back without root cause", "Forget to download event log before calling OEM"],
  },
  {
    id: "cooling-chiller-high-temp",
    category: "Cooling",
    categoryColor: "#0284c7",
    title: "Chiller Plant — Chilled Water Temperature Rising",
    alarm: "BMS: 'Chiller leaving water temperature above setpoint'. CRAH chilled water valves opening further. Server inlet temperatures rising gradually across DC hall.",
    isolation: "Which chiller(s) active? Is standby chiller available? Is this a chiller fault or a cooling tower/condenser water issue?",
    diagnosis: "Check chiller status panel: compressor running? Any fault alarms? Chilled water supply/return temps. Condenser water supply temp from cooling tower. Chilled water flow rate (flow meter). BMS setpoint — has it changed? Recent IT load increase?",
    resolution: "Start standby chiller if available and primary is faulted. Condenser water high: check cooling tower fan, fill, water level. Chilled water flow low: check pump status, bypass valve position. Call HVAC contractor with fault code.",
    prevention: ["Chilled water quality testing monthly", "Cooling tower quarterly inspection + cleaning", "Pump vibration monitoring for bearing failure", "Annual chiller OEM PM"],
    rca: "Why was cooling tower not maintained (scaling)? Why was pump vibration not monitored (bearing failure early detection)? Why no standby chiller auto-start? Action: monthly water quality checks, pump monitoring, auto-start configuration.",
    symptoms: ["BMS alarm: chiller leaving water temp high", "CRAHs drawing more chilled water (valves open)", "Server inlet temperatures rising across DC", "Chiller kW consumption abnormal"],
    causes: ["Chiller compressor fault (VFD failure, protection trip)", "Condenser fouling (cooling tower scaling)", "Chilled water pump failure", "Bypass valve stuck open", "IT load increase beyond chiller capacity"],
    verify: ["Chiller status: compressor running? Active alarms?", "CHW supply/return temperatures", "Condenser water temperature from cooling tower", "Chilled water flow meter reading", "BMS setpoint currently active"],
    steps: ["BMS: identify active chillers, any fault alarms", "Chiller local panel fault code", "Check available standby chillers — start if needed", "Rate of temperature rise determines urgency", "Condenser water temp check: cooling tower performance?", "Cooling tower: fan running? Water level? Drift eliminators?", "Bypass valve position check", "Contact HVAC contractor with fault code"],
    rootCause: "Chiller compressor protection trip (high head pressure from condenser fouling) most common. Cooling tower scaling reduces heat rejection. Chilled water pump bearing failure reduces flow.",
    escalation: "Multiple chillers down or temperatures approaching 30°C: HVAC contractor emergency call. Application teams notified.",
    siteExample: "Gurgaon DC summer: CHW rising from 7°C to 14°C over 4 hours. Condenser water 38°C vs design 32°C — cooling tower scaling. Emergency chemical treatment + standby chiller. Full descaling next week.",
    mistakes: ["Raise chiller setpoint to 'stop the alarm' — masking the problem", "Not checking cooling tower when chiller shows high head pressure", "Skipping monthly water quality tests"],
  },
  {
    id: "dc-environmental-alarm",
    category: "BMS",
    categoryColor: "#0369a1",
    title: "Environmental Alarm — Temperature or Humidity Out of Range",
    alarm: "BMS/DCIM alert: temperature >28°C or humidity <40% or >70% RH in server room. ASHRAE A1 class violation. Equipment damage risk at sustained levels.",
    isolation: "Which zone/room? Single sensor or multiple sensors? Is CRAC/CRAH in that zone running? Is alarm real or sensor fault?",
    diagnosis: "Physical spot thermometer/hygrometer at alarm location — compare to BMS reading. If physical reading matches = real alarm. If mismatch = sensor fault. Check CRAC status: running? Fault LED? Setpoint correct? Check for recent changes (new equipment, containment gap).",
    resolution: "Real temperature high: treat as hot spot (see cooling-hotspot guide). Real humidity low: check CRAC humidifier (if fitted). Real humidity high: check for water ingress, cooling tower drift, outside air infiltration. Sensor fault: replace sensor, suppress alarm with documented reason.",
    prevention: ["Calibrate sensors annually against calibrated reference", "Redundant sensors in critical zones", "BMS alarm threshold review quarterly", "Physical walk with spot thermometer monthly"],
    rca: "Was this a sensor fault causing false alarm (nuisance) or real environmental excursion? If real: what changed? New equipment? Containment breach? CRAC failure? Action: root cause fix + sensor calibration schedule.",
    symptoms: ["BMS alarm: temperature/humidity out of range", "Multiple server inlet alerts in same zone", "CRAC not maintaining setpoint", "Visible moisture or condensation"],
    causes: ["CRAC/CRAH failure in zone", "Missing containment panels (hot spot)", "Sensor calibration drift", "Water ingress (leaks)", "Outside air infiltration affecting humidity"],
    verify: ["Physical spot measurement at alarm location", "CRAC status in zone", "Sensor calibration date", "Any recent changes in zone (new equipment, construction)"],
    steps: ["Physical spot measurement to confirm alarm real vs sensor fault", "If sensor fault: replace/recalibrate, suppress alarm with documentation", "If real: identify CRAC status in zone", "Hot spot: walk for missing blanking panels, cable blockage", "Humidity high: check for water sources", "Humidity low: CRAC humidifier status", "Notify application teams if approaching critical levels"],
    rootCause: "Sensor calibration drift (most common false positive). Real temperature event: CRAC failure or blanking panel issue. Real humidity event: water ingress or humidifier failure.",
    escalation: "Sustained >30°C inlet or <30% or >75% RH: application team notification and cooling contractor.",
    siteExample: "Pune DC: BMS showed 32°C in Row 5 for 2 hours. Physical check with thermometer: 23°C actual. BMS temperature sensor failure — sending stuck high value. Sensor replaced. BMS nuisance alarm avoided for 3 other zones by auditing all sensor calibration dates.",
    mistakes: ["Acting on BMS alarm without physical verification — sensor faults waste hours", "Adjusting CRAC setpoint to chase a faulty sensor reading", "Not documenting alarm suppression reason"],
  },
  {
    id: "server-idrac-unreachable",
    category: "Servers",
    categoryColor: "#475569",
    title: "iDRAC/iLO Unreachable — Out-of-Band Management Lost",
    alarm: "Monitoring alert: iDRAC/iLO not responding to ICMP/SNMP. Cannot access management console for server. Physical access to server required if not resolved.",
    isolation: "Is the production NIC also unreachable? Is it this specific server or all servers in the rack (network issue)? Is it the iDRAC network path or the iDRAC itself?",
    diagnosis: "Ping iDRAC IP from monitoring system. Ping other devices on same management VLAN — are they responding? Check management switch port: up? Correct VLAN? Check iDRAC power: dedicated iDRAC port connected? Management VLAN SVI up? iDRAC may have crashed (firmware bug, hung).",
    resolution: "Network path issue: management switch port config, VLAN, SVI. iDRAC itself hung: power cycle the iDRAC without rebooting server — iDRAC reset button on server (usually small pinhole) or racadm command. Full server power cycle only as last resort.",
    prevention: ["iDRAC firmware updates per OEM schedule", "Management VLAN monitoring — dedicated SNMP polling", "iDRAC watchdog enabled (auto-resets iDRAC if hung)", "Separate management network (not shared with production)"],
    rca: "Was iDRAC firmware outdated (known crash bug)? Was management VLAN misconfigured after network change? Was iDRAC watchdog enabled? Action: firmware update schedule, management VLAN change management, watchdog enable.",
    symptoms: ["iDRAC/iLO not responding to ping", "Cannot access web console", "SNMP alerts stopped from this server", "Production NIC may still be working"],
    causes: ["iDRAC firmware crash (known bugs in some versions)", "Management VLAN misconfiguration", "Management network switch issue", "iDRAC IP conflict", "iDRAC power loss (iDRAC port disconnected)"],
    verify: ["Ping iDRAC IP from monitoring server", "Ping other devices on same management VLAN", "Management switch port status and VLAN config", "Is production NIC also unreachable?"],
    steps: ["Ping iDRAC IP — times out?", "Ping other devices on management VLAN — management network accessible?", "Check management switch port for this server", "If management network OK: iDRAC itself is issue", "Try iDRAC reset via racadm: racadm racreset", "If racadm unreachable: physical iDRAC reset button (no server reboot)", "Check iDRAC firmware version — known crash bug?", "Last resort: full server power cycle"],
    rootCause: "iDRAC firmware crash most common (firmware bug causing hang). Management VLAN misconfiguration after network change second most common.",
    escalation: "If server is production critical and iDRAC needed urgently for hardware diagnosis: physical access to server room may be required.",
    siteExample: "40 iDRAC units unreachable after network maintenance. Root cause: trunk port on management switch had VLAN 10 (management) removed. One command restored management access to all 40 servers. iDRAC itself was fine — network path was broken.",
    mistakes: ["Full server reboot when only iDRAC is unreachable — unnecessary downtime", "Not checking management VLAN switch port before assuming iDRAC failure", "No iDRAC watchdog configured — hung iDRAC stays hung indefinitely"],
  },
  {
    id: "dc-water-leak",
    category: "Facility",
    categoryColor: "#6b21a8",
    title: "Water Leak Detection Alarm — Under Floor or Overhead",
    alarm: "BMS/leak detection: 'Water detected at [location]'. Water and electricity in DC = immediate danger. Life safety and equipment damage risk.",
    isolation: "Where exactly? Under floor (CRAC drain, chilled water pipe) or overhead (roof, cooling pipe above racks)? Any visible water? Any electrical equipment affected?",
    diagnosis: "Visual inspection at alarm location with caution. Trace water source: CRAC drain blocked/overflowing? Chilled water pipe joint leaking? Cooling tower pipe? Roof penetration? Condensation on cold pipe? Amount of water: standing water vs drip?",
    resolution: "Immediate: isolate water source if safe to do so (shut CRAC drain valve, close isolation valve on leaking pipe section). Protect IT equipment: raise equipment off floor if water pooling, move to dry area if safe. Call facilities/plumber immediately. Document water quantity and spread. If water approaching electrical equipment: power off affected zone by exception, notify operations.",
    prevention: ["CRAC drain inspection monthly", "Chilled water pipe joint inspection annually (thermal imaging)", "Roof inspection after monsoon", "Under-floor sensor coverage mapping — ensure full coverage", "Condensate pan alarm configured in BMS"],
    rca: "Was drain blocked? Was pipe joint at end of maintenance life? Was there proper roof drainage? Was the leak sensor positioned correctly to detect early? Action: drain maintenance schedule, pipe inspection program, leak sensor coverage audit.",
    symptoms: ["BMS: water leak alarm at specific location", "Leak detection rope/sensor triggered", "Visible water on floor or dripping from ceiling", "CRAC showing drain fault"],
    causes: ["CRAC condensate drain blocked (most common)", "Chilled water pipe joint failure", "Cooling tower overflow or pipe burst", "Roof leak (monsoon season)", "Condensation on cold uninsulated pipes"],
    verify: ["Location of alarm — specific sensor ID", "Visual inspection at location", "CRAC drain status in nearest unit", "Chilled water pressure normal?", "Amount of water — drip or flow?"],
    steps: ["Safety: Do not enter if water near electrical panels", "Identify exact source from BMS sensor location", "Visual inspection — trace water upstream", "CRAC drain: blocked? Flush drain line", "Chilled water pipe: isolation valve to leak section", "Protect IT equipment from water", "Facilities/plumber immediate call", "Water extraction and drying if pooled", "Monitor for recurrence after fix"],
    rootCause: "CRAC condensate drain blockage most common (biological growth, debris). Chilled water pipe joint corrosion second most common in older DCs.",
    escalation: "Water approaching active electrical equipment: power isolation and emergency escalation to site manager. Any pooled water near server rows: application team notification immediately.",
    siteExample: "Hyderabad DC monsoon: roof leak above cold aisle. 2 liters of water before detected. Overhead cable tray diverted water away from servers — damage avoided. Roof penetration sealed. DC redesigned cable tray to act as water barrier for all monsoon-risk overhead areas.",
    mistakes: ["Walk through standing water near electrical equipment", "Not locating source before just mopping up (will recur)", "Under-floor leak sensors not tested annually"],
  },
];

// Merge additional guides into main export
TROUBLESHOOTING_GUIDES.push(...ADDITIONAL_GUIDES);
