import type { ArticleMetadata } from "@/types/engineering/content";

export const dlMetadata: ArticleMetadata = {
  slug: "deep-learning",
  title: "Deep Learning — The Complete Engineering Guide",
  seoTitle: "What Is Deep Learning? Neural Networks, CNN, Transformer, GPU Training",
  seoDescription:
    "A complete engineering guide to Deep Learning — neural networks, CNN, RNN, LSTM, Transformers, attention mechanism, GPU acceleration, distributed training, the CUDA stack, inference infrastructure, enterprise deployment, and production operations. For DC engineers, IT engineers, and AI engineers.",
  canonicalUrl: "https://behindthetech.in/learn/ai/fundamentals/deep-learning",
  keywords: [
    "what is deep learning english",
    "deep learning explained hindi",
    "neural networks beginners",
    "transformer architecture explained",
    "cnn rnn lstm",
    "gpu deep learning training",
    "cuda software stack",
    "distributed training gpu cluster",
    "deep learning infrastructure",
    "nvlink infiniband deep learning",
    "backpropagation explained",
    "attention mechanism transformer",
    "deep learning vs machine learning",
    "foundation models fine tuning",
    "deep learning enterprise deployment",
    "mlperf benchmarks",
    "deep learning inference optimization",
    "pytorch tensorflow jax",
    "gpu memory hierarchy",
    "deep learning data center",
  ],
  authorName: "Kumar Anil",
  datePublished: "2025-08-03",
  readingTimeMinutes: 70,
};
