import type { ArticleMetadata } from "@/types/engineering/content";

export const tpuMetadata: ArticleMetadata = {
  slug: "tpu",
  title: "TPU (Tensor Processing Unit) — The Complete Engineering Guide",
  seoTitle: "What Is a TPU? Architecture, Systolic Array, TPU Pod, Cloud TPU",
  seoDescription:
    "A complete engineering guide to the TPU — CPU vs GPU vs TPU, Systolic Array architecture, MXU, HBM, TPU Pod, TPU Interconnect, Cloud TPU, TensorFlow, PyTorch/XLA, training vs inference, cost analysis, Google AI infrastructure, data center deployment, and the future roadmap. For AI engineers, DC engineers, and architects.",
  canonicalUrl: "https://behindthetech.in/learn/ai/hardware/tpu",
  keywords: [
    "what is a tpu",
    "tensor processing unit explained hindi",
    "google tpu architecture",
    "systolic array explained",
    "mxu matrix multiply unit",
    "tpu vs gpu comparison",
    "tpu pod architecture",
    "cloud tpu google",
    "tpu v4 v5e training",
    "tpu inference serving",
    "tensorflow tpu optimization",
    "pytorch xla tpu",
    "google ai infrastructure",
    "tpu data center",
    "tpu cooling power",
    "tpu interconnect",
    "ai accelerator comparison",
    "google gemini tpu",
    "tpu bfloat16",
    "custom ai chip explained",
  ],
  authorName: "Kumar Anil",
  datePublished: "2025-08-06",
  readingTimeMinutes: 100,
};
