import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Virtualisation — Hypervisors, VMs, HA, Live Migration & Containers | Behind The Tech",
  description: "Virtualisation kya hai, Type 1/2 hypervisors, VM architecture, overcommit, live migration, HA clusters, snapshots vs backups, RPO/RTO, VM vs containers — Zero-to-Hero Hinglish guide.",
  keywords: ["virtualisation","hypervisor","VMware ESXi","Hyper-V","KVM","VM","vCPU vRAM","live migration","vMotion","HA cluster","snapshots backups","VM vs container"],
  openGraph: { title: "Virtualisation — Hypervisors, VMs, HA & Live Migration", description: "Type 1/2 hypervisors, VM architecture, overcommit, HA, live migration, containers.", url: "https://behindthetech.in/learn/it/servers/virtualization", siteName: "Behind The Tech", type: "article", authors: ["Kumar Anil"] },
  twitter: { card: "summary_large_image", title: "Virtualisation — Behind The Tech", description: "Hypervisors, VMs, HA aur live migration complete guide." },
  alternates: { canonical: "https://behindthetech.in/learn/it/servers/virtualization" },
};
export const faqs = [
  { q: "Type 1 aur Type 2 hypervisor mein kya difference hai?", a: "Type 1 (bare metal) directly physical hardware pe install hota hai — no host OS. Lower overhead, better performance. Data center standard: VMware ESXi, Microsoft Hyper-V, KVM (Linux kernel module — Type 1 semantics), Xen. Type 2 (hosted) existing OS ke upar run karta hai — VirtualBox, VMware Workstation. Host OS crash → all VMs affected. Development/testing ke liye, production data centers mein typically nahi." },
  { q: "CPU overcommit kya hai aur kab problematic hota hai?", a: "Physical CPU threads se zyada vCPUs VMs ko assign karna. Work karta hai kyunki sab VMs simultaneously peak pe nahi hote. Problematic hota hai jab sab VMs simultaneously heavy load pe hon — CPU ready queue mein VMs wait karte hain → performance degradation. CPU ready time metrics monitor karo, workload-specific baselines establish karo, overcommit ratio carefully manage karo." },
  { q: "Snapshot aur backup mein kya difference hai?", a: "Snapshot VM ka point-in-time state hai same storage pe — rapid rollback ke liye (risky change se pehle). Backup data separate location pe copy hai — actual disaster recovery ke liye. Snapshot backup replace nahi karta: same storage fail → snapshot bhi gone. Long-running snapshots VM performance degrade karte hain (delta disk growth). Production environments mein proper backup solution zaroori hai." },
  { q: "Live migration ke liye kya requirements hain?", a: "Traditional shared-storage live migration (VMware vMotion, Hyper-V Live Migration) ke liye: shared storage (both hosts same datastore access karein), compatible CPUs (ya EVC/CPU compatibility mode), network connectivity between hosts, adequate resources on destination. Shared storage universally mandatory nahi hai — KVM storage migration allow karta hai without pre-shared storage, aur modern hypervisors storage migration bhi simultaneously support karte hain. Specific requirements hypervisor documentation se verify karo." },
  { q: "VM aur container mein kya difference hai?", a: "VM full virtual hardware aur complete OS run karta hai — strong isolation, different kernels possible, heavier resource use. Container host OS kernel share karta hai — application aur dependencies isolate hote hain. Containers lighter, faster start, less overhead. VMs stronger isolation dete hain. Production mein often dono sath use hote hain — VMs infrastructure provide karte hain, containers VMs pe run hote hain." },
];
export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };
