import type { FaqItem } from "@/lib/schemas";

export const openaiFaq: FaqItem[] = [
  {
    question: "OpenAI kya hai aur yeh sirf ChatGPT company se zyada kyun hai?",
    answer:
      "OpenAI ek AI research aur deployment company hai jo 2015 mein San Francisco mein founded thi. Public perception mein yeh mainly ChatGPT ke liye jaani jaati hai, lekin infrastructure perspective se OpenAI bahut zyada hai: ek frontier AI research lab jo large language models train karta hai, ek commercial API platform jo developers ko programmatic access deta hai, ek enterprise solution provider, aur ek organization jo AI safety research actively karta hai. ChatGPT sirf OpenAI ka ek consumer product hai — actual platform mein frontier/general-purpose models, reasoning models, embeddings, image/audio models, APIs, fine-tuning capabilities, aur developer tools ka complete ecosystem hai. Current model portfolio official documentation pe verify karo: platform.openai.com/docs/models. Data center professionals ke liye OpenAI important hai kyunki yeh demonstrate karta hai ki modern AI workloads traditional compute infrastructure se kitna dramatically alag hain.",
  },
  {
    question: "ChatGPT aur OpenAI API mein kya fundamental difference hai?",
    answer:
      "ChatGPT ek consumer-facing web application aur mobile app hai — OpenAI ne build kiya, end users directly use karte hain, conversational interface hai, aur OpenAI ke servers pe hosted hai. OpenAI API ek programmatic interface hai jo developers aur businesses use karte hain apne applications mein OpenAI models integrate karne ke liye. API mein: aap specific models choose karte hain, requests programmatically send karte hain, responses process karte hain, aur pay per token karte hain. Important distinctions: ChatGPT conversations by default OpenAI ke training mein use ho sakti hain (opt-out available hai), jabki API usage default mein training ke liye use nahi hoti — yeh enterprise data sensitivity ke liye important distinction hai. Context management bhi alag hai: ChatGPT session mein conversation maintain karta hai; standard Chat Completions API stateless hai aur developer messages array manage karta hai. OpenAI ke newer Responses API aur conversation state features bhi available hain — current capabilities official documentation se verify karo: platform.openai.com/docs. ChatGPT aur API pe available model versions, configurations aur features exact same nahi hote — OpenAI different surfaces pe different defaults aur lineups maintain karta hai.",
  },
  {
    question: "OpenAI Microsoft Azure ke saath kaise connected hai?",
    answer:
      "OpenAI aur Microsoft ke beech ek significant strategic partnership hai. Microsoft OpenAI ka ek major cloud infrastructure partner hai — substantial training aur inference capacity Azure-based infrastructure pe hai. Azure OpenAI Service ek separate Microsoft product hai jo enterprises ko OpenAI models Azure ke through access karne deta hai — data Azure regions mein rehta hai, Azure compliance certifications apply hote hain, aur enterprise Azure contracts ke through billing hoti hai. Important clarification: OpenAI ki infrastructure sirf Azure tak limited nahi hai. OpenAI ne Stargate project announce kiya hai — ek significant infrastructure initiative jisme OpenAI, SoftBank aur other partners dedicated AI infrastructure build kar rahe hain. Exact details — locations, capacity, technical architecture — publicly confirmed nahi hain beyond high-level announcements. Yeh pattern demonstrate karta hai ki AI labs frontier infrastructure ke liye major cloud providers pe depend karte hain lekin simultaneously independent capacity bhi build kar rahe hain.",
  },
  {
    question: "AI request OpenAI API pe exactly kaise flow karta hai infrastructure se?",
    answer:
      "Note: Yeh ek generalized AI-serving architecture description hai — OpenAI ka internal production architecture publicly confirmed nahi hai. Jab aap OpenAI API call karte hain: (1) HTTPS request API gateway pe pahonchti hai — authentication (API key verify), rate limiting, aur routing yahan hoti hai. (2) Request inference infrastructure pe route hoti hai — yeh GPU servers hain jahan model weights already loaded hain memory mein. (3) Model inference run hoti hai — input tokens process hote hain, output tokens autoregressively generate hote hain (ek ek token). (4) Streaming response possible hai — har token generate hone ke saath server-sent events ke through client tak pahonchta hai, ya complete response buffer hoke ek saath return hoti hai. (5) Token usage track hoti hai billing ke liye. Total latency depend karta hai: model (larger/reasoning models = slower), input length, output length, current server load, aur geographic distance. Enterprise tier typically more consistent latency provide karta hai.",
  },
  {
    question: "Training aur inference infrastructure mein kya main differences hain OpenAI jaise scale pe?",
    answer:
      "Training infrastructure: Massive scale — frontier model training enormous compute require karta hai, weeks to months tak. Exact hardware specifications publicly disclosed nahi hote. High-speed interconnects GPU-to-GPU gradient exchange ke liye essential. Checkpoint storage significant hoti hai — frontier-scale models ke checkpoints very large hote hain. One-time ya periodic compute job. Inference infrastructure: Fundamentally alag pattern. Many serving clusters — exact architecture publicly undisclosed. Low latency priority. High concurrency — millions of simultaneous users. Model weights memory mein preloaded. Autoscaling demand ke saath. Quantization often used. Cost economics alag hain: training ek large upfront cost, inference continuous per-request cost jo revenue se match karna hota hai. OpenAI ke internal infrastructure details officially disclosed nahi hain beyond general statements — specific GPU counts ya exact locations publicly confirmed nahi.",
  },
  {
    question: "OpenAI ke reasoning models standard models se infrastructure pe kaise alag hain?",
    answer:
      "OpenAI ke o-series reasoning models (current lineup verify karo: platform.openai.com/docs/models) ek different inference pattern use karte hain — extended thinking/chain-of-thought reasoning jo models ko complex problems pe zyada compute spend karne deta hai before final answer. Infrastructure implications: Longer generation time per request. Higher compute per request. More expensive per request — accordingly higher API pricing. Different timeout requirements — applications ko longer response times handle karne ke liye design karna padta hai. Streaming especially important for UX. Yeh demonstrate karta hai ki 'inference' ek monolithic concept nahi hai — alag model architectures dramatically alag resource profiles create karte hain.",
  },
  {
    question: "Enterprise ke liye OpenAI API aur Azure OpenAI Service mein kya choose karna chahiye?",
    answer:
      "OpenAI API directly: Simpler setup, latest models typically pehle available, direct billing with OpenAI, OpenAI ke terms apply. Azure OpenAI Service: Azure subscription ke through billing, Azure compliance portfolio (SOC 2, ISO 27001, HIPAA eligibility, etc.), data Azure region mein, Azure networking integration (VNet, private endpoints), existing Azure enterprise agreement leverage. Recommendation framework: Already Azure enterprise customer ho aur compliance/data residency critical ho → Azure OpenAI Service. Startup ya developer simplicity chahiye → Direct OpenAI API. Regulated industry (healthcare, finance, government) → Azure OpenAI Service typically better aligned. Note: Both products OpenAI models serve karte hain lekin exact model availability, versions aur features alag ho sakte hain — Azure deployment lag hoti hai aur feature parity exact nahi hoti. Current Azure OpenAI model availability: learn.microsoft.com/azure/ai-services/openai/",
  },
  {
    question: "OpenAI models ke liye data privacy kaise kaam karta hai?",
    answer:
      "Official OpenAI policy ke mutabik: API ke through send kiya gaya data OpenAI ke models train karne ke liye use nahi hota by default. Data kuch period ke liye abuse monitoring ke liye retain kiya ja sakta hai — exact retention details current privacy policy mein. Zero data retention (ZDR) option kuch configurations mein available hai. ChatGPT consumer product mein: conversations training data mein contribute kar sakti hain — settings mein opt-out kiya ja sakta hai. Enterprise tier additional protections provide karta hai. Practical guidance: Sensitive data carefully handle karo. Data residency requirements ke liye Azure OpenAI Service consider karo. Always current official policy verify karo — policies update ho sakti hain: openai.com/policies/privacy-policy",
  },
  {
    question: "Rate limits aur quotas AI infrastructure design pe kaise impact karte hain?",
    answer:
      "OpenAI API rate limits multiple dimensions mein exist karte hain: RPM (Requests Per Minute), TPM (Tokens Per Minute), RPD (Requests Per Day), aur model-specific limits. Yeh limits tier-based hain — free tier bahut limited, paid tiers zyada capacity, enterprise agreements custom limits. Infrastructure design pe impact: Applications ko rate limit handling implement karni chahiye — exponential backoff with jitter, retry logic. High-volume applications ko batching consider karna chahiye. Rate limits architecture decisions drive karte hain. Caching important ho jaata hai — same queries repeatedly OpenAI pe bhejne ki jagah responses cache karo. Cost optimization: Token usage optimize karo — system prompts concise rakho, output length control karo. Current tier limits frequently update hote hain — official docs check karo: platform.openai.com/docs/guides/rate-limits",
  },
  {
    question: "OpenAI models embed karne ke liye (embeddings) infrastructure mein kya considerations hain?",
    answer:
      "OpenAI Embeddings API text ko dense vector representations mein convert karta hai jo semantic similarity search ke liye useful hain. Current embedding models (text-embedding-3-large, text-embedding-3-small — verify at platform.openai.com/docs/guides/embeddings). Infrastructure implications: Vector storage: Embeddings ko vector databases mein store karna hota hai — Pinecone, Weaviate, pgvector, Qdrant, etc. Scale: Storage requirements corpus size, dimensions aur document count pe depend karte hain — project-specific planning zaruri hai. Index updates: Naye documents add hone pe embeddings generate aur index update karna hota hai. Retrieval latency: Vector similarity search latency vector DB implementation, index size, aur hardware pe depend karta hai — well-configured systems pe low latency possible hai. RAG (Retrieval Augmented Generation) architecture: Embeddings → vector search → retrieve relevant context → pass to LLM for generation. Cost: Embeddings models relatively cheap hain per token but large-scale indexing projects mein cumulative cost significant ho sakti hai.",
  },
];
