import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",           text: "Quick Summary",                               level: 1 },
  { id: "who-should-read",         text: "Who Should Read This",                        level: 1 },
  { id: "what-you-will-learn",     text: "What You Will Learn",                         level: 1 },
  { id: "learning-path",           text: "Learning Path",                               level: 1 },
  { id: "introduction",            text: "Introduction",                                level: 1 },
  { id: "nlp-evolution",           text: "NLP Evolution — Before LLMs",                level: 1 },
  { id: "what-is-llm",             text: "What is an LLM?",                             level: 1 },
  { id: "parameters",              text: "Parameters Explained",                        level: 1 },
  { id: "tokens",                  text: "Tokens aur Tokenization",                     level: 1 },
  { id: "embeddings",              text: "Embeddings",                                  level: 1 },
  { id: "positional-encoding",     text: "Positional Encoding",                         level: 1 },
  { id: "transformer-arch",        text: "Transformer Architecture",                    level: 1 },
  { id: "self-attention",          text: "Self-Attention",                               level: 1 },
  { id: "multi-head-attention",    text: "Multi-Head Attention",                        level: 1 },
  { id: "ffn",                     text: "Feed-Forward Networks",                       level: 1 },
  { id: "residual-connections",    text: "Residual Connections",                        level: 1 },
  { id: "layer-normalization",     text: "Layer Normalization",                         level: 1 },
  { id: "decoder-only",            text: "Decoder-Only Models",                         level: 1 },
  { id: "encoder-only",            text: "Encoder-Only Models",                         level: 1 },
  { id: "encoder-decoder",         text: "Encoder-Decoder Models",                      level: 1 },
  { id: "context-window",          text: "Context Window — Engineering Deep Dive",      level: 1 },
  { id: "kv-cache",                text: "KV Cache",                                    level: 1 },
  { id: "scaling-laws",            text: "Scaling Laws",                                level: 1 },
  { id: "training-pipeline",       text: "Training Pipeline",                           level: 1 },
  { id: "pretraining",             text: "Pretraining",                                 level: 2 },
  { id: "distributed-training",    text: "Distributed Training Strategies",             level: 2 },
  { id: "fine-tuning",             text: "Fine-Tuning",                                 level: 2 },
  { id: "instruction-tuning",      text: "Instruction Tuning",                          level: 2 },
  { id: "rlhf",                    text: "RLHF aur Alignment",                          level: 2 },
  { id: "dpo",                     text: "DPO",                                         level: 2 },
  { id: "lora",                    text: "LoRA",                                        level: 1 },
  { id: "qlora",                   text: "QLoRA",                                       level: 1 },
  { id: "moe",                     text: "Mixture of Experts",                          level: 1 },
  { id: "quantization",            text: "Quantization",                                level: 1 },
  { id: "distillation",            text: "Knowledge Distillation",                      level: 1 },
  { id: "speculative-decoding",    text: "Speculative Decoding",                        level: 1 },
  { id: "context-engineering",     text: "Context Engineering",                         level: 1 },
  { id: "prompt-processing",       text: "Prompt Processing Pipeline",                  level: 1 },
  { id: "function-calling",        text: "Function Calling aur MCP",                    level: 1 },
  { id: "rag-integration",         text: "RAG Integration",                             level: 1 },
  { id: "ai-agents",               text: "AI Agents with LLMs",                         level: 1 },
  { id: "gpu-requirements",        text: "GPU Requirements",                            level: 1 },
  { id: "memory-requirements",     text: "Memory Requirements",                         level: 1 },
  { id: "storage",                 text: "Storage Requirements",                        level: 1 },
  { id: "networking",              text: "Networking",                                  level: 1 },
  { id: "gpu-communication",       text: "GPU Communication",                           level: 1 },
  { id: "ai-serving",              text: "AI Serving Infrastructure",                   level: 1 },
  { id: "vllm",                    text: "vLLM",                                        level: 2 },
  { id: "tensorrt-llm",            text: "TensorRT-LLM",                                level: 2 },
  { id: "triton",                  text: "Triton Inference Server",                     level: 2 },
  { id: "sglang",                  text: "SGLang",                                      level: 2 },
  { id: "kubernetes",              text: "Kubernetes for LLM Serving",                  level: 1 },
  { id: "enterprise-stack",        text: "Enterprise LLM Stack",                        level: 1 },
  { id: "ai-gateway",              text: "Enterprise AI Gateway",                       level: 1 },
  { id: "inference-scheduling",    text: "Inference Scheduling",                        level: 1 },
  { id: "enterprise-serving-metrics", text: "Enterprise Serving Metrics",               level: 1 },
  { id: "model-lifecycle",         text: "Model Lifecycle",                             level: 1 },
  { id: "monitoring",              text: "Monitoring",                                  level: 1 },
  { id: "security",                text: "Security",                                    level: 1 },
  { id: "hallucinations",          text: "Hallucinations",                              level: 1 },
  { id: "alignment-safety",        text: "Alignment aur Safety",                        level: 1 },
  { id: "cost-optimization",       text: "Cost Optimization",                           level: 1 },
  { id: "open-source-llms",        text: "Open Source LLMs",                            level: 1 },
  { id: "closed-source-llms",      text: "Closed Source LLMs",                         level: 1 },
  { id: "hopper-blackwell",        text: "Hopper aur Blackwell Infrastructure",         level: 1 },
  { id: "enterprise-case-studies", text: "Enterprise Case Studies",                     level: 1 },
  { id: "troubleshooting",         text: "Troubleshooting",                             level: 1 },
  { id: "interview-questions",     text: "Interview Questions",                         level: 1 },
  { id: "glossary",                text: "Glossary",                                    level: 1 },
  { id: "key-takeaways",           text: "Key Takeaways",                               level: 1 },
];
