import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "what-is-pdu",               text: "What is a PDU?",                           level: 1 },
  { id: "why-pdu-required",          text: "Why PDU is Required",                      level: 1 },
  { id: "power-flow-architecture",   text: "Complete Data Center Power Flow",           level: 1 },
  { id: "pdu-types-overview",        text: "Types of PDU",                              level: 1 },
  { id: "basic-pdu",                 text: "Basic PDU",                                 level: 2 },
  { id: "metered-pdu",               text: "Metered PDU",                               level: 2 },
  { id: "monitored-pdu",             text: "Monitored PDU",                             level: 2 },
  { id: "switched-pdu",              text: "Switched PDU",                              level: 2 },
  { id: "intelligent-pdu",           text: "Intelligent PDU (iPDU)",                    level: 2 },
  { id: "internal-construction",     text: "Internal Construction",                     level: 1 },
  { id: "connectors-standards",      text: "Input & Output Connectors — IEC Standards", level: 1 },
  { id: "single-phase-three-phase",  text: "Single Phase vs Three Phase",               level: 1 },
  { id: "rack-pdu-vs-floor-pdu",     text: "Rack PDU vs Floor PDU",                     level: 1 },
  { id: "horizontal-vs-vertical",    text: "Horizontal vs Vertical Rack PDU",           level: 1 },
  { id: "power-capacity",            text: "Power Capacity & Load Planning",            level: 1 },
  { id: "circuit-breakers",          text: "Circuit Breakers in PDU",                   level: 1 },
  { id: "metering",                  text: "Metering — What Gets Measured",             level: 1 },
  { id: "sensors",                   text: "Sensors",                                   level: 1 },
  { id: "environmental-monitoring",  text: "Environmental Monitoring",                  level: 1 },
  { id: "remote-monitoring",         text: "Remote Monitoring",                         level: 1 },
  { id: "bms-integration",           text: "BMS Integration",                           level: 1 },
  { id: "dcim-integration",          text: "DCIM Integration",                          level: 1 },
  { id: "snmp-modbus-mqtt",          text: "SNMP, Modbus & MQTT",                       level: 1 },
  { id: "asset-identification",      text: "RFID & Asset Identification",               level: 1 },
  { id: "oem-comparison",            text: "OEM Comparison",                            level: 1 },
  { id: "failure-modes",             text: "Failure Modes",                             level: 1 },
  { id: "preventive-maintenance",    text: "Preventive Maintenance",                    level: 1 },
  { id: "pdu-vs-ipdu",              text: "PDU vs iPDU",                               level: 1 },
  { id: "pdu-vs-rpp",               text: "PDU vs RPP",                                level: 1 },
  { id: "key-takeaways",            text: "Key Takeaways",                              level: 1 },
];
