import type { FaqItem } from "@/lib/schemas";

export const googleGeminiFaq: FaqItem[] = [
  {
    question: "Google Gemini kya hai aur yeh OpenAI/Anthropic se infrastructure perspective se kaise different hai?",
    answer:
      "Google Gemini Google DeepMind ka flagship AI model family hai — Google ke in-house TPU (Tensor Processing Unit) infrastructure pe trained aur served. Key infrastructure difference: OpenAI primarily Microsoft Azure pe depend karta hai, Anthropic primarily AWS pe — lekin Google apna khud ka AI hardware (TPUs) design karta hai aur apni global data center infrastructure pe run karta hai. Yeh Google ko fundamentally different position deta hai: hardware, software, training framework (JAX/XLA), aur deployment infrastructure sab in-house. Gemini models Google Search, Gmail, Docs, aur other products mein deeply integrated hain — consumer scale inference sirf API ke liye nahi hai. Data center perspective se: Google ke data centers purpose-built hain AI workloads ke liye, TPU pods specifically large-scale distributed training ke liye design kiye gaye hain.",
  },
  {
    question: "Google TPU kya hai aur NVIDIA GPU se fundamentally kaise alag hai?",
    answer:
      "TPU (Tensor Processing Unit) Google ka purpose-built AI accelerator hai — general-purpose GPU nahi. Key architectural differences: TPUs primarily matrix multiplication (neural network ka core operation) ke liye optimized hain using systolic array architecture — yeh operations hardware level pe highly efficient execute karte hain. NVIDIA GPUs general-purpose parallel compute hain jo AI ke liye bhi use hote hain. TPUs Google's JAX/XLA compiler ecosystem ke saath tightly integrated hain. TPU generations (v1, v2, v3, v4, v5, v5p, v6 Trillium etc.) publicly documented hain — har generation mein improvements aate hain compute density, interconnect bandwidth, aur memory (HBM) mein. Important caveat: Exactly kaunsa Gemini model kaunse TPU generation pe run karta hai yeh Google publicly fully disclose nahi karta. TPUs primarily Google Cloud ke through access hote hain — general public ke paas TPU hardware ownership nahi hota.",
  },
  {
    question: "Gemini API aur Google AI Studio mein kya difference hai?",
    answer:
      "Google AI Studio ek web-based IDE/playground hai — developers browser mein directly Gemini models ke saath experiment kar sakte hain bina code likhe. Prototyping, prompt engineering, aur quick testing ke liye ideal. Free tier generous hai. Gemini API wo programmatic interface hai jo production applications mein integrate hota hai — REST API ya Google Cloud client libraries se. AI Studio se directly API key generate karke Gemini API call kar sakte hain. Production applications ke liye: Gemini API directly (Google AI Developer platform) ya Vertex AI ke through. Vertex AI enterprise-grade deployment deta hai: Google Cloud compliance, VPC networking, IAM, aur advanced MLOps capabilities. Small projects/prototyping → AI Studio. Production consumer apps → Gemini API direct. Enterprise regulated → Vertex AI. Current documentation: ai.google.dev (AI Studio + Gemini API) aur cloud.google.com/vertex-ai (Vertex AI).",
  },
  {
    question: "HBM (High Bandwidth Memory) kya hai aur AI accelerators mein kyun critical hai?",
    answer:
      "HBM (High Bandwidth Memory) ek specialized DRAM technology hai jo AI accelerators (TPUs, GPUs) mein use hoti hai. Standard DDR/LPDDR memory se kaise alag: Physical stacking — multiple memory dies vertically stack ki jaati hain, wide data bus se connected. Result: dramatically higher memory bandwidth at lower power. AI training aur inference mein bandwidth critical hai: transformer models mein attention computation mein weights aur activations constantly memory se fetch hote hain. Agar memory bandwidth insufficient ho, accelerator compute units hungry wait karte hain — expensive hardware underutilized. HBM generations (HBM2, HBM2e, HBM3, HBM3e) increasing bandwidth aur capacity provide karte hain. Google TPUs mein HBM use hoti hai — specific HBM versions per TPU generation Google ke public datasheets mein documented hain. Data center perspective: HBM high heat density create karti hai accelerator pe — thermal management critical hai.",
  },
  {
    question: "Vertex AI aur direct Gemini API mein enterprise ke liye kya choose karna chahiye?",
    answer:
      "Direct Gemini API (ai.google.dev): Simpler setup, latest models typically pehle available, Google AI developer platform billing. Enterprise/regulated use ke liye limitations ho sakte hain compliance scope mein. Vertex AI (Google Cloud): Enterprise-grade — Google Cloud compliance certifications applicable per current GCP documentation (verify scope at cloud.google.com). VPC Service Controls for network isolation, Cloud IAM for access control, audit logging, data residency options, managed endpoints with SLAs, model versioning, aur full MLOps pipeline. Claude/OpenAI ke barabar: Vertex AI wahi role play karta hai jo Azure OpenAI Service ya Amazon Bedrock play karte hain — enterprise controls ke saath AI models. Decision framework: Startup/developer → Direct Gemini API or AI Studio. Production app with scale → Gemini API. Regulated enterprise (healthcare, finance, government) → Vertex AI. All compliance features current GCP documentation se verify karo — features change hote rehte hain.",
  },
  {
    question: "Google training infrastructure itni large scale pe kaise kaam karti hai?",
    answer:
      "Google ka large-scale AI training infrastructure publicly described hai research papers aur blog posts mein. Key elements: TPU Pods — hundreds ya thousands of TPUs ek high-speed custom interconnect ke through connected hote hain. Google ICI (Inter-Chip Interconnect) TPU-to-TPU communication enable karta hai ek pod ke andar — yeh publicly documented hai. JAX/XLA framework — Google ka primary ML framework jo TPUs ke saath tightly integrated hai. Distributed training strategies: data parallelism, model parallelism, pipeline parallelism — sab coordinate karni parti hain efficiently. Pathways system — Google ne Pathways architecture describe kiya hai jo multiple accelerator types across multiple datacenters ko ek single model training mein use kar sakta hai. Checkpoint storage — large model training mein regular checkpoints essential hain — Google ka Colossus distributed file system yeh handle karta hai per public documentation. Exact cluster sizes, specific Gemini training configurations, aur precise hardware counts publicly disclosed nahi hain.",
  },
  {
    question: "Gemini inference infrastructure training se kaise alag hai?",
    answer:
      "Training: One-time ya periodic massive compute job — thousands of TPUs weeks to months tak synchronously run karte hain. Throughput optimize karo. Failure pe checkpoint se restart. Inference: Continuous serving — massive scale across Google products (Search, Gmail, etc.) aur API customers simultaneously. Latency critical hai. Model weights memory mein preloaded. Geographically distributed serving — Google ke global data centers. Different hardware possible — smaller/more efficient models inference ke liye. Quantization used — model weights lower precision mein store karke faster inference aur more models per TPU. Prefill vs decode: LLM inference mein pehle input tokens process hote hain (prefill — compute-intensive), phir output tokens one by one generate hote hain (decode — memory-bandwidth intensive). Different hardware configurations dono phases optimize kar sakte hain. Google Search aur product integration se yeh inference operation massive scale pe operate karta hai globally — exact query volumes publicly disclosed nahi hain.",
  },
  {
    question: "Google ke data centers AI workloads ke liye kaise design hain?",
    answer:
      "Google apne data centers in-house design karta hai — publicly documented hai. AI infrastructure perspective se key elements: Power density: TPU pods extremely high power density create karte hain — specific figures publicly disclosed nahi hain per facility, lekin high-density AI racks 40–100+ kW per rack achieve kar sakte hain. Cooling: Google ke data centers evaporative cooling aur chilled water extensively use karte hain. Google liquid cooling bhi research aur deploy karta hai high-density workloads ke liye — specific configurations per facility publicly detailed nahi hain. PUE: Google historically very good PUE report karta hai (1.1 ke aas paas) — efficient cooling design aur warm aisle/cold aisle containment se. Water usage: Google significant water usage acknowledge karta hai cooling ke liye — WUE metric track karta hai aur public reporting karta hai. Renewable energy: Google apni global energy use 100% renewable energy se match karne ka commitment rakhta hai — Power Purchase Agreements (PPAs) se. Specific data center locations jahan Gemini run hota hai — publicly disclosed nahi.",
  },
  {
    question: "Gemini ke liye data privacy aur security kaisi hai?",
    answer:
      "Data handling Gemini access path se vary karta hai: Google AI Studio (free tier): Data Google ke AI improvement ke liye use ho sakta hai — current privacy settings aur policy verify karo at ai.google.dev/gemini-api/terms. Gemini API (paid): Training data policies current API terms se verify karo. Vertex AI: Enterprise-grade data controls — data customer's GCP project mein rehta hai, Google ke models train karne ke liye use nahi hota per current Vertex AI terms (verify at cloud.google.com). Google Workspace Gemini: Workspace admin policies aur enterprise terms apply. Important caveat: Policies product, plan aur configuration ke basis pe vary karti hain. Absolute claims — 'Google never trains on your data' — context-specific hain. Always current official Google privacy documentation verify karo specific product ke liye. Regulated industries ke liye: Vertex AI through deployment recommended — Google Cloud compliance certifications aur BAA eligibility (verify current scope).",
  },
  {
    question: "TPU Pod kya hai aur yeh AI training ke liye kyun important hai?",
    answer:
      "TPU Pod multiple TPU chips ko ek high-speed interconnect network ke through connect karke ek logical unit banata hai — ek massive distributed accelerator effectively. Why pods matter for AI training: Single TPU chip pe large frontier models fit nahi hote — model weights billions of parameters hote hain. Pod mein chips distributed memory share karte hain aur synchronized computation karte hain. Google ICI (Inter-Chip Interconnect) pod ke andar chips ko connect karta hai — yeh purpose-built high-bandwidth interconnect hai, standard Ethernet/InfiniBand se different. Pod slices: Large pods mein specific 'slices' allocate ki ja sakti hain different jobs ke liye — Google Cloud pe TPU v4 aur newer pods mein yeh concept publicly documented hai. Scale: TPU pods publicly hundreds to thousands of chips tak scale karte hain — exact configurations Google Cloud documentation mein available hain. Data center implication: Ek TPU pod ka power consumption aur cooling requirement enormous hota hai — dedicated infrastructure required.",
  },
];
