import type { FaqItem } from "@/lib/schemas";

export const nvidiaArchFaq: FaqItem[] = [
  {
    question: "What's the practical difference between a CUDA Core and a Tensor Core — what's the impact on AI training?",
    answer:
      "A CUDA Core is a general-purpose FP32 arithmetic unit — one floating point operation (add or multiply) per clock cycle. A Tensor Core is a specialized matrix multiply-accumulate unit — it completes a 4×4 matrix operation in one clock cycle, meaning 128 multiply-add operations simultaneously. In AI training, 90%+ of the computation is matrix multiplications (neural network layers = matrix operations). Tensor Cores do this work 64-128× faster per clock vs CUDA Cores. Practical impact: after Volta (the first Tensor Cores), AI training speed improved dramatically. On H100, FP8 Tensor Cores are 2-3× faster than A100's BF16 Tensor Cores for transformer models. CUDA Cores are used for element-wise operations (activation functions, normalization) — Tensor Cores for matrix math. To optimize an AI system: keep Tensor Core utilization high = efficient training.",
  },
  {
    question: "What is warp divergence and what's its actual impact on GPU code performance?",
    answer:
      "A warp is a group of 32 threads that execute in lockstep on a GPU — one instruction at a time, all 32 threads simultaneously. Warp divergence happens when threads take different branches: if (thread_id % 2 == 0) { path_A; } else { path_B; }. The GPU handles this by serializing both paths — Phase 1: even threads execute path_A, odd threads idle; Phase 2: odd threads execute path_B, even threads idle. Performance impact: worst case 2× slower (two branches). N distinct branches = N× potential slowdown. Real-world examples: irregular data patterns (graphs, sparse tensors), conditional processing (attention masking with different sequence lengths). Mitigation: design the data layout so threads in the same warp mostly take the same branch; use branchless code (predicated instructions); use sorted input data that guarantees branch uniformity. For AI: implement transformer attention mask operations carefully to avoid divergence in attention computation.",
  },
  {
    question: "What's the fundamental difference between NVLink and PCIe — what's the impact on multi-GPU training?",
    answer:
      "PCIe (Peripheral Component Interconnect Express) is the standard interface between the CPU and GPU. PCIe 5.0: 128 GB/s bidirectional. A universal standard — any PCIe device uses it. NVLink is NVIDIA's proprietary direct GPU-to-GPU interconnect. NVLink 4.0 (H100): 900 GB/s bidirectional per GPU. Specifically designed for GPU-to-GPU. Bandwidth difference: NVLink has ~7× more bandwidth than PCIe 5.0. Multi-GPU training impact: in distributed training, gradient synchronization (AllReduce) is the main bottleneck. An 8-GPU DGX H100 (NVSwitch + NVLink): 7.2 TB/s aggregate GPU-to-GPU bandwidth → AllReduce is fast, GPUs rarely wait. An 8-GPU server with PCIe only (no NVLink): 128 GB/s bottleneck → AllReduce is slow → GPUs sit idle waiting → training efficiency drops. Practical numbers: a 70B model's gradient sync at BF16 = 280 GB per AllReduce. NVLink: ~0.3 seconds. PCIe: ~2+ seconds. Training step time is significantly affected. For multi-GPU deployments: always prefer the SXM form factor (NVLink) over the PCIe form factor for training.",
  },
  {
    question: "What is MIG and when should it be used in the enterprise?",
    answer:
      "MIG (Multi-Instance GPU) is a feature introduced with A100 that lets you partition one physical H100 GPU into up to 7 hardware-isolated independent instances. 'Hardware-isolated' is the key — not software emulation, actual silicon partitioning. Each instance gets dedicated SMs, a portion of L2 cache, a slice of HBM memory, and a slice of the memory controller. No instance can access another instance's hardware. Enterprise use cases: (1) cloud inference multi-tenancy — serve 7 customers independently and isolated on one H100; (2) research team sharing — 7 researchers run experiments independently on one GPU; (3) mixed workloads — production inference + development + testing simultaneously on one physical GPU. When to use it: GPU utilization consistently under 60% for a single workload → extract more value from it with MIG. When to avoid it: training jobs that need the whole GPU (use the full 7g.80gb GPU), latency-sensitive single workloads (a full GPU is better). MIG limitations: live migration isn't supported (vGPU supports it), a GPU restart is needed for creation, MIG and time-slicing can't run simultaneously.",
  },
  {
    question: "What is Hopper's Transformer Engine and why is it important for LLMs?",
    answer:
      "The Transformer Engine is a dedicated hardware feature of H100 (Hopper architecture) specifically optimized for transformer-based models (BERT, GPT, LLaMA, T5). Technical detail: hardware support for FP8 precision plus intelligent precision management. The Transformer Engine dynamically decides whether it's safe to use FP8 for a given layer or necessary to use FP16 — with per-tensor scaling. This decision happens per-layer, per-tensor, automatically — the engineer doesn't have to manage it manually. Why it matters for LLMs: FP8 = 8-bit floating point. 2× less memory than FP16, 2× faster Tensor Core operations. Without the Transformer Engine: you'd have to manually decide which layers support FP8 — error-prone, tedious. With the Transformer Engine: write standard PyTorch/JAX code, H100 automatically uses FP8 wherever it's safe. Result: 3× speedup vs A100 for transformer training without any code changes. This is why every LLM training team upgraded from A100 to H100 — the speedup is that significant. A100 vs H100 for 70B LLM training: H100 trains in roughly 1/3 the time.",
  },
  {
    question: "What does TensorRT do and how much faster is inference than PyTorch?",
    answer:
      "TensorRT is NVIDIA's inference optimization engine that optimizes a trained model for production deployment. Four key optimizations: (1) graph optimization — remove unnecessary operations, eliminate redundant computations; (2) layer fusion — Conv + BatchNorm + ReLU becomes a single fused kernel → fewer memory trips; (3) precision calibration — convert an FP32 model to INT8/FP8, determine scale factors from a calibration dataset → minimal accuracy loss with maximum speed; (4) kernel auto-tuning — benchmark and select the best kernel implementation for your specific GPU and input shape. Speedup numbers (approximate, workload dependent): PyTorch eager FP32 → TensorRT FP32: 1.5-2× faster; TensorRT FP32 → TensorRT INT8: an additional 2-3×; total vs PyTorch eager: typically 3-8× faster. Memory also reduces proportionally with precision. When to use it: production inference (always), latency-critical serving (required), cost optimization at scale (critical). When not to use it: research/development (the overhead of a TRT build isn't worth it), rapidly changing models (a rebuild is needed per change). Workflow: PyTorch model → ONNX export → TensorRT engine build (one-time, 10-30 minutes) → fast deployment.",
  },
  {
    question: "What is NVIDIA DCGM and how do you set up GPU cluster monitoring?",
    answer:
      "DCGM (Data Center GPU Manager) is NVIDIA's enterprise GPU monitoring and management tool. Designed to track GPU health at data center scale. Key capabilities: per-GPU health monitoring (ECC errors, thermal state, power draw, utilization), active diagnostics (test GPU functionality without a server restart), job statistics (track GPU utilization per training job), policy management (automatically take actions on fault detection), Prometheus/Grafana integration (plugs into an existing monitoring stack). Critical metrics to monitor: GPU utilization (target >80% for training), GPU memory utilization, GPU temperature (alert above 80°C, the H100 throttle point), power draw vs TDP, ECC single-bit errors (correctable, log and monitor), ECC double-bit errors (uncorrectable, immediate attention needed), NVLink error counters. Setup: a DCGM agent runs on every GPU node, a central collector aggregates the metrics, and exposes them as Prometheus metrics. Alert thresholds: sustained temperature >80°C = investigate a cooling issue; GPU utilization consistently <60% during training = investigate a data bottleneck; ECC double-bit errors = schedule a GPU replacement; NVLink errors = check the cable/connection.",
  },
  {
    question: "What advantage does Grace CPU and Grace-Blackwell (GB200) have over a traditional CPU+GPU setup?",
    answer:
      "Traditional setup: Intel/AMD CPU on the motherboard ←PCIe→ NVIDIA GPU on a card. CPU memory and GPU memory are completely separate address spaces. Data transfer: data in CPU memory → explicit cudaMemcpy (over PCIe) → GPU memory. PCIe 5.0 bandwidth: 128 GB/s. Grace-Blackwell GB200: NVIDIA's ARM-based Grace CPU + Blackwell GPU in the same package. Connection: NVLink-C2C (Chip-to-Chip) — 900 GB/s bandwidth (7× PCIe 5.0). Unified memory: CPU memory (512 GB LPDDR5X) and GPU memory (192 GB HBM3e) in one coherent address space. No explicit copies needed — the GPU can directly access data stored in CPU memory via NVLink-C2C. Practical AI benefit: large model inference where the model doesn't fit in GPU memory (e.g., a 405B parameter model needs ~810 GB at BF16 — a single H100's 80 GB is far too little). On GB200: 704 GB of unified addressable memory (512 GB Grace + 192 GB Blackwell). The model can spread across the whole memory pool, and NVLink-C2C ensures fast access. Second benefit: NUMA-like locality — compute where the data is, no PCIe trips. For systems design: a GB200 NVL72 rack has 36 Grace CPUs + 72 Blackwell GPUs = 1.4 EFLOPS FP4. Liquid cooling is mandatory, 120+ kW per rack.",
  },
  {
    question: "What are the common bottlenecks in GPU training and how do you identify them?",
    answer:
      "There are three main bottlenecks — identifying which one matters because the solution differs for each. (1) GPU compute-bound: Tensor Cores running near 100%, data supply adequate. Identify it: GPU utilization >90%, memory bandwidth underutilized, NVLink bandwidth underutilized. Solution: larger batch size, mixed precision for faster computation. (2) Memory bandwidth-bound: HBM bandwidth saturated, Tensor Cores wait for data. Identify it: GPU utilization 60-80%, HBM bandwidth near maximum, compute units often idle. Solution: better memory access patterns (coalesced access), larger tiles, Flash Attention (reduces memory bandwidth for attention). (3) IO/data-loading bound: GPUs wait for training data. Identify it: GPU utilization <60%, periodic drops to 0%, CPU DataLoader high utilization. Solution: more DataLoader workers, pin_memory=True, GPUDirect Storage, faster storage. (4) Communication bound (distributed): AllReduce time > compute time. Identify it: NVLink bandwidth saturated, GPU idle during the backward pass. Solution: gradient compression, ZeRO optimizer (reduce data to sync), overlap compute+communication (FSDP). Tools: the Nsight Systems timeline (visual — see GPU idle time and why), nvidia-smi dmon (quick utilization check), DCGM (cluster-level).",
  },
  {
    question: "What is ECC on an NVIDIA GPU and why should it be kept enabled in a data center?",
    answer:
      "ECC (Error Correcting Code) memory is a reliability feature. Data is stored in memory — sometimes cosmic rays, electrical noise, and hardware aging can flip a bit (0 → 1 or 1 → 0). Without ECC: a flipped bit = wrong data = a wrong training result or a crash. With ECC: extra check bits are stored per memory word. Hardware automatically detects single-bit errors and corrects them in place. Double-bit errors are detected (but can't be corrected). On A100/H100: ECC is ON by default. Types of ECC errors: single-bit (SBE, correctable) — automatically fixed, logged. Occasional occurrence is normal. Frequent SBEs = hardware degrading, plan a replacement. Double-bit (DBE, uncorrectable) — the training job will crash at that point. A DBE means immediate investigation, likely hardware replacement. Data center recommendation: always keep ECC ON for training and inference servers. Turn ECC OFF only for: gaming setups (a crash is acceptable), extreme performance testing (a 5% bandwidth improvement). Tradeoff: ~5% less HBM bandwidth, ~2-3% less usable memory. Worth it for: multi-week training runs (one wrong result = restart = expensive), medical/financial AI (correctness is critical), any production serving.",
  },
  {
    question: "Why do GPU clusters use InfiniBand instead of standard Ethernet?",
    answer:
      "Key differences between standard Ethernet and InfiniBand: Latency: Ethernet ~5-10 microseconds end-to-end; InfiniBand ~1-2 microseconds (5× lower). Bandwidth: 100 GbE = 100 Gb/s; InfiniBand HDR = 200 Gb/s per port; InfiniBand NDR = 400 Gb/s per port. Protocol overhead: Ethernet = TCP/IP stack (has to be processed by the CPU); InfiniBand = RDMA (Remote Direct Memory Access) — CPU bypass, the GPU sends/receives data on the network directly. Impact on AI training: AllReduce in a 1000-GPU cluster sends/receives data every step. Latency matters per step — millions of steps times 5 microseconds adds up. Bandwidth matters — more bandwidth = less time waiting for gradient sync. RDMA matters — no CPU needed for coordination = lower overhead = the GPU doesn't stall. RDMA over Converged Ethernet (RoCE 2.0): adds RDMA capabilities on top of Ethernet infrastructure. Slightly more latency than InfiniBand but can use standard switches (cheaper infrastructure). Practical choice: small clusters (<32 GPUs): RoCE 2.0 on 400 GbE is often sufficient. Large clusters (100+ GPUs): InfiniBand NDR is typically preferred for maximum performance. Google/AWS internal AI clusters: custom optical fabrics at hyperscale.",
  },
  {
    question: "What is a CUDA Stream and why is it used in AI inference?",
    answer:
      "A CUDA Stream is an in-order execution queue on the GPU. In a single stream: operations execute sequentially — the next operation starts only after the previous one completes. In multiple streams: separate streams can be scheduled independently — overlap is possible. Example without streams: data transfer A → GPU (PCIe, slow) → wait for completion → kernel execute → wait for completion → data transfer B → wait... the GPU is idle during data transfer. Example with streams: Stream 1: transfer data batch 1 → kernel on batch 1. Stream 2: transfer data batch 2. The GPU executes the Stream 1 kernel while Stream 2's transfer is running — overlap. Key operations to overlap: data transfer (H2D: host to device) and GPU compute. Multiple inference requests (preprocessing for one request and inference for another). Checkpoint writing and the next training step's computation. Code pattern: cudaStreamCreate(&stream1); cudaStreamCreate(&stream2); // Launch operations on different streams cudaMemcpyAsync(..., stream1); // async transfer kernel<<<..., ..., stream1>>>(...); // compute on stream1. CUDA Events: create synchronization points — wait for a specific stream event to complete. Inference optimization: multiple user requests on different streams → better GPU utilization → higher throughput.",
  },
  {
    question: "Why does FP4 support in NVIDIA's Blackwell architecture matter practically?",
    answer:
      "FP4 (4-bit floating point) was introduced in the Blackwell architecture — the first time in a data center GPU for the industry. Context: FP32 (32 bits) → FP16 (16 bits) → FP8 (8 bits) → FP4 (4 bits). Each halving: 2× less memory, potentially 2× faster compute. FP4's practical impact: Memory: a 70B parameter model at FP4 = 35 GB (vs 140 GB at FP16, vs 70 GB at FP8). An FP16 70B model doesn't fit on a single H100 (80 GB). It fits on a Blackwell GPU at FP4 with room to spare. Throughput: FP4 Tensor Cores are theoretically 2× faster than FP8. Real-world inference: dramatically more requests per second per GPU. Cost per inference: lower. Quality tradeoff: FP4 quantization is aggressive. Not all models handle FP4 well without significant accuracy loss. Careful calibration and post-training quantization are necessary. Current state (2024): FP4 inference is early stage. Models specifically quantized for FP4 show good results. Research is ongoing for FP4-aware training (train at FP4 instead of post-training quantize). Use case: very large model inference where memory is the binding constraint and throughput is critical. Not for training (too aggressive). A Blackwell GB200 NVL72 rack with FP4: ~1.4 EFLOPS total — enables real-time inference for models that previously required multiple GPU nodes.",
  },
];
