import type { FaqItem } from "@/lib/schemas";

export const nvidiaArchFaq: FaqItem[] = [
  {
    question: "CUDA Core aur Tensor Core mein kya practical difference hai — AI training pe impact kya hota hai?",
    answer:
      "CUDA Core ek general-purpose FP32 arithmetic unit hai — ek clock cycle mein ek floating point operation (add ya multiply). Tensor Core ek specialized matrix multiply-accumulate unit hai — ek clock cycle mein 4×4 matrix operation complete karta hai, yaani 128 multiply-add operations simultaneously. AI training mein 90%+ computation matrix multiplications hain (neural network layers = matrix operations). Tensor Cores yeh kaam 64-128× faster karte hain per clock vs CUDA Cores. Practical impact: Volta (pehle Tensor Cores) ke baad AI training speed dramatically improve hui. H100 pe FP8 Tensor Cores — A100 ke BF16 Tensor Cores se 2-3× faster for transformer models. CUDA Cores element-wise operations ke liye use hote hain (activation functions, normalization) — Tensor Cores matrix math ke liye. AI system optimize karna hai toh: Tensor Core utilization high rakhna = efficient training.",
  },
  {
    question: "Warp divergence kya hai aur GPU code performance pe iska actual impact kya hota hai?",
    answer:
      "Warp 32 threads ka group hai jo GPU mein lockstep execute hota hai — ek time pe ek instruction, sab 32 threads simultaneously. Warp divergence tab hota hai jab threads alag branches lete hain: if (thread_id % 2 == 0) { path_A; } else { path_B; }. GPU yeh handle karta hai by serializing both paths — Phase 1: even threads path_A execute karte hain, odd threads idle; Phase 2: odd threads path_B execute karte hain, even threads idle. Performance impact: worst case 2× slower (two branches). N distinct branches = N× potential slowdown. Real-world examples: irregular data patterns (graphs, sparse tensors), conditional processing (attention masking with different sequence lengths). Mitigation: data layout design karo taaki same warp ke threads mostly same branch lein; branchless code (predicated instructions) use karo; sorted input data jo branch uniformity guarantee kare. For AI: transformer attention mask operations carefully implement karo to avoid divergence in attention computation.",
  },
  {
    question: "NVLink aur PCIe mein kya fundamental difference hai — multi-GPU training pe kya impact hota hai?",
    answer:
      "PCIe (Peripheral Component Interconnect Express) CPU aur GPU ke beech standard interface hai. PCIe 5.0: 128 GB/s bidirectional. Universal standard — koi bhi PCIe device use karta hai. NVLink NVIDIA ka proprietary GPU-to-GPU direct interconnect hai. NVLink 4.0 (H100): 900 GB/s bidirectional per GPU. GPU-to-GPU specifically designed. Bandwidth difference: NVLink ~7× more bandwidth than PCIe 5.0. Multi-GPU training impact: Distributed training mein gradient synchronization (AllReduce) main bottleneck hai. 8-GPU DGX H100 (NVSwitch + NVLink): 7.2 TB/s aggregate GPU-to-GPU bandwidth → AllReduce fast hai, GPUs rarely wait. 8-GPU server PCIe only (no NVLink): 128 GB/s bottleneck → AllReduce slow → GPUs idle wait karte hain → training efficiency drops. Practical numbers: 70B model gradient sync at BF16 = 280 GB per AllReduce. NVLink: ~0.3 seconds. PCIe: ~2+ seconds. Training step time significantly affected. For multi-GPU deployments: always prefer SXM form factor (NVLink) over PCIe form factor for training.",
  },
  {
    question: "MIG kya hai aur enterprise mein kab use karna chahiye?",
    answer:
      "MIG (Multi-Instance GPU) A100 se introduced ek feature hai jisme ek physical H100 GPU ko 7 tak hardware-isolated independent instances mein partition kiya ja sakta hai. 'Hardware-isolated' key hai — software emulation nahi, actual silicon partitioning. Har instance ko dedicated SMs, L2 cache portion, HBM memory slice, aur memory controller slice milta hai. Koi bhi instance doosre instance ka hardware access nahi kar sakta. Enterprise use cases: (1) Cloud inference multi-tenancy — ek H100 ke 7 customers independently isolated serve karo; (2) Research team sharing — 7 researchers independently experiments run karein on one GPU; (3) Mixed workloads — production inference + development + testing simultaneously on one physical GPU. Kab use karein: GPU utilization consistently <60% for single workload → MIG se zyada value extract karo. Kab avoid karein: Training jobs jo poora GPU chahiye (use 7g.80gb full GPU), latency-sensitive single workloads (full GPU better). MIG limitations: Live migration unsupported (vGPU supports it), creation ke liye GPU restart needed, MIG aur time-slicing simultaneously nahi chalta.",
  },
  {
    question: "Hopper ka Transformer Engine kya hai aur kyun important hai LLMs ke liye?",
    answer:
      "Transformer Engine H100 (Hopper architecture) ka ek dedicated hardware feature hai jo specifically transformer-based models (BERT, GPT, LLaMA, T5) ke liye optimize kiya gaya hai. Technical detail: FP8 precision support hardware mein + intelligent precision management. Transformer Engine dynamically decide karta hai ki har layer ke liye FP8 use karna safe hai ya FP16 use karna zaroori hai — per-tensor scaling ke saath. Yeh decision per-layer, per-tensor, automatically hoti hai — engineer ko manually manage nahi karna padta. Why important for LLMs: FP8 = 8-bit floating point. FP16 se 2× less memory, 2× faster Tensor Core operations. Without Transformer Engine: manually decide karna padta hai kaunse layers FP8 support karte hain — error-prone, tedious. With Transformer Engine: write standard PyTorch/JAX code, H100 automatically FP8 use karta hai jahan safe hai. Result: 3× speedup vs A100 for transformer training without any code changes. This is why every LLM training team upgraded from A100 to H100 — the speedup is that significant. A100 vs H100 for 70B LLM training: H100 trains in roughly 1/3 the time.",
  },
  {
    question: "TensorRT kya karta hai aur PyTorch se kitna faster inference hoti hai?",
    answer:
      "TensorRT NVIDIA ka inference optimization engine hai jo trained model ko production deployment ke liye optimize karta hai. Four key optimizations: (1) Graph optimization — unnecessary operations remove, redundant computations eliminate; (2) Layer fusion — Conv + BatchNorm + ReLU ek single fused kernel banta hai → memory trips reduce hoti hain; (3) Precision calibration — FP32 model ko INT8/FP8 mein convert karo, calibration dataset se scale factors determine karo → minimal accuracy loss with maximum speed; (4) Kernel auto-tuning — aapke specific GPU aur input shape ke liye best kernel implementation benchmark karo aur select karo. Speedup numbers (approximate, workload dependent): PyTorch eager FP32 → TensorRT FP32: 1.5-2× faster; TensorRT FP32 → TensorRT INT8: additional 2-3×; Total vs PyTorch eager: 3-8× faster typically. Memory also reduces proportionally with precision. When to use: production inference (always), latency-critical serving (required), cost optimization at scale (critical). When not to use: research/development (overhead of TRT build not worth it), rapidly changing models (rebuild needed per change). Workflow: PyTorch Model → ONNX export → TensorRT engine build (one-time, 10-30 minutes) → fast deployment.",
  },
  {
    question: "NVIDIA DCGM kya hai aur GPU cluster monitoring kaise setup karein?",
    answer:
      "DCGM (Data Center GPU Manager) NVIDIA ka enterprise GPU monitoring aur management tool hai. Data center scale pe GPU health track karne ke liye designed. Key capabilities: per-GPU health monitoring (ECC errors, thermal state, power draw, utilization), active diagnostics (GPU functionality test karo bina server restart), job statistics (GPU utilization track karo per training job), policy management (automatically actions lene pe fault detection), Prometheus/Grafana integration (existing monitoring stack mein plugin). Critical metrics to monitor: GPU utilization (target >80% for training), GPU memory utilization, GPU temperature (alert >80°C H100 throttle point), power draw vs TDP, ECC single-bit errors (correctable, log aur monitor), ECC double-bit errors (uncorrectable, immediate attention needed), NVLink error counters. Setup: DCGM agent har GPU node pe run karta hai, central collector metrics aggregate karta hai, Prometheus metrics expose karta hai. Alert thresholds: Temperature sustained >80°C = cooling issue investigate; GPU utilization consistently <60% on training = data bottleneck investigate; ECC double-bit errors = schedule GPU replacement; NVLink errors = cable/connection check.",
  },
  {
    question: "Grace CPU aur Grace-Blackwell (GB200) ka traditional CPU+GPU se kya advantage hai?",
    answer:
      "Traditional setup: Intel/AMD CPU on motherboard ←PCIe→ NVIDIA GPU on card. CPU memory aur GPU memory completely separate address spaces. Data transfer: CPU memory mein data → explicit cudaMemcpy (PCIe pe) → GPU memory. PCIe 5.0 bandwidth: 128 GB/s. Grace-Blackwell GB200: NVIDIA ARM-based Grace CPU + Blackwell GPU same package mein. Connection: NVLink-C2C (Chip-to-Chip) — 900 GB/s bandwidth (7× PCIe 5.0). Unified memory: CPU memory (512 GB LPDDR5X) aur GPU memory (192 GB HBM3e) ek coherent address space mein. No explicit copies needed — GPU directly CPU memory mein stored data access kar sakta hai via NVLink-C2C. Practical AI benefit: Large model inference jahan model GPU memory mein fit nahi hoti (e.g., 405B parameter model needs ~810 GB at BF16 — H100 ka 80 GB bahut kam hai). GB200 mein: 704 GB unified addressable memory (512 GB Grace + 192 GB Blackwell). Model puri memory pe spread ho sakti hai, NVLink-C2C fast access ensure karta hai. Second benefit: NUMA-like locality — data operations jahan data hai wahan compute karo, no PCIe trips. For systems design: GB200 NVL72 ek rack mein 36 Grace CPUs + 72 Blackwell GPUs = 1.4 EFLOPS FP4. Liquid cooling mandatory, 120+ kW per rack.",
  },
  {
    question: "GPU training mein common bottlenecks kaunse hain aur kaise identify karein?",
    answer:
      "Tin main bottlenecks hain — identify karna important hai kyunki solution alag hoti hai. (1) GPU compute-bound: Tensor Cores running at near 100%, data supply adequate. Identify karo: GPU utilization >90%, memory bandwidth underutilized, NVLink bandwidth underutilized. Solution: larger batch size, mixed precision se aur fast computation. (2) Memory bandwidth-bound: HBM bandwidth saturated, Tensor Cores wait karte hain data ke liye. Identify karo: GPU utilization 60-80%, HBM bandwidth near maximum, compute units often idle. Solution: better memory access patterns (coalesced access), larger tiles, Flash Attention (reduces memory bandwidth for attention). (3) IO/Data loading bound: GPUs wait karte hain training data ke liye. Identify karo: GPU utilization <60%, periodic drops to 0%, CPU DataLoader high utilization. Solution: more DataLoader workers, pin_memory=True, GPUDirect Storage, faster storage. (4) Communication bound (distributed): AllReduce time > compute time. Identify karo: NVLink bandwidth saturated, GPU idle during backward pass. Solution: gradient compression, ZeRO optimizer (reduce data to sync), overlap compute+communication (FSDP). Tools: Nsight Systems timeline (visual — see GPU idle time and why), nvidia-smi dmon (quick utilization check), DCGM (cluster-level).",
  },
  {
    question: "NVIDIA GPU mein ECC kya hai aur data center mein kyun enable rakhna chahiye?",
    answer:
      "ECC (Error Correcting Code) memory ek reliability feature hai. Memory mein data store hota hai — sometimes cosmic rays, electrical noise, aur hardware aging se ek bit flip ho sakti hai (0 → 1 ya 1 → 0). Bina ECC: flipped bit = wrong data = wrong training result ya crash. ECC ke saath: extra check bits store hote hain per memory word. Hardware automatically detect karta hai single-bit errors aur correct karta hai in-place. Double-bit errors detect hote hain (but can't be corrected). A100/H100 pe: ECC by default ON. Types of ECC errors: Single-bit (SBE, correctable) — automatically fixed, logged. Periodic occurrence normal. Frequent SBEs = hardware degrading, plan replacement. Double-bit (DBE, uncorrectable) — training job crash hoga at that point. DBE = immediate investigation, likely hardware replacement. Data center recommendation: Always ECC ON for training aur inference servers. ECC OFF sirf agar: gaming setup (crash acceptable), extreme performance testing (5% bandwidth improvement). Tradeoff: ~5% less HBM bandwidth, ~2-3% less usable memory. Worth it for: multi-week training runs (one wrong result = restart = expensive), medical/financial AI (correctness critical), any production serving.",
  },
  {
    question: "GPU cluster mein InfiniBand kyun use karte hain standard Ethernet ki jagah?",
    answer:
      "Standard Ethernet aur InfiniBand ke beech key differences: Latency: Ethernet ~5-10 microseconds end-to-end; InfiniBand ~1-2 microseconds (5× lower). Bandwidth: 100 GbE = 100 Gb/s; InfiniBand HDR = 200 Gb/s per port; InfiniBand NDR = 400 Gb/s per port. Protocol overhead: Ethernet = TCP/IP stack (CPU se process karna padta hai); InfiniBand = RDMA (Remote Direct Memory Access) — CPU bypass, GPU directly network pe data bhejta/receive karta hai. For AI training impact: AllReduce in 1000-GPU cluster sends/receives data each step. Latency matters per step — millions of steps times 5 microseconds adds up. Bandwidth matters — more bandwidth = less time waiting for gradient sync. RDMA matters — CPU nahi lagana coordination ke liye = lower overhead = GPU nahi rukta. RDMA over Converged Ethernet (RoCE 2.0): Ethernet infrastructure pe RDMA capabilities add karta hai. InfiniBand se slightly more latency lekin standard switches use kar sakte hain (cheaper infrastructure). Practical choice: Small clusters (<32 GPUs): RoCE 2.0 on 400 GbE often sufficient. Large clusters (100+ GPUs): InfiniBand NDR typically preferred for maximum performance. Google/AWS internal AI clusters: custom optical fabrics at hyperscale.",
  },
  {
    question: "CUDA Stream kya hai aur AI inference mein kyun use karte hain?",
    answer:
      "CUDA Stream ek in-order execution queue hai GPU pe. Single stream mein: operations sequentially execute hoti hain — previous operation complete hone ke baad next start hoti hai. Multiple streams mein: alag streams independently schedule ho sakte hain — overlap possible. Example without streams: Data transfer A → GPU (PCIe, slow) → Wait complete → Kernel execute → Wait complete → Data transfer B → Wait... GPU idle hai data transfer ke during. Example with streams: Stream 1: Data batch 1 transfer → Kernel batch 1. Stream 2: Data batch 2 transfer. GPU execute karta hai Stream 1 kernel jab Stream 2 ka transfer chal raha hai — overlap. Key operations to overlap: Data transfer (H2D: host to device) aur GPU compute. Multiple inference requests (ek request ka preprocessing aur doosre ka inference). Checkpoint writing aur next training step computation. Code pattern: cudaStreamCreate(&stream1); cudaStreamCreate(&stream2); // Launch operations on different streams cudaMemcpyAsync(..., stream1); // async transfer kernel<<<..., ..., stream1>>>(...); // compute on stream1. CUDA Events: Synchronization points create karo — wait karo specific stream event complete hone ke liye. Inference optimization: multiple user requests different streams pe → GPU better utilized → higher throughput.",
  },
  {
    question: "NVIDIA blackwell architecture ka FP4 support practically kyun matter karta hai?",
    answer:
      "FP4 (4-bit floating point) Blackwell architecture mein introduced hua — industry mein pehli baar in a data center GPU. Context: FP32 (32 bits) → FP16 (16 bits) → FP8 (8 bits) → FP4 (4 bits). Har halving: 2× less memory, potential 2× faster compute. FP4 practical impact: Memory: 70B parameter model at FP4 = 35 GB (vs 140 GB at FP16, vs 70 GB at FP8). Single H100 (80 GB) pe FP16 70B model fit nahi hota. Blackwell GPU pe FP4 mein fit hoti hai with room to spare. Throughput: FP4 Tensor Cores FP8 se 2× faster theoretically. Real-world inference: dramatically more requests per second per GPU. Cost per inference: lower. Quality tradeoff: FP4 quantization aggressive hai. Not all models handle FP4 well without significant accuracy loss. Careful calibration aur post-training quantization zaroori hai. Current state (2024): FP4 inference early stage hai. Models specifically quantized for FP4 good results dikhate hain. Research ongoing for FP4-aware training (train at FP4 instead of post-training quantize). Use case: Very large model inference where memory is binding constraint and throughput critical. Not for training (too aggressive). Blackwell GB200 NVL72 rack with FP4: ~1.4 EFLOPS total — enables real-time inference for models that previously required multiple GPU nodes.",
  },
];
