import type { ArticleMetadata } from "@/types/engineering/content";

export const nvidiaArchMetadata: ArticleMetadata = {
  slug: "nvidia-architecture",
  title: "NVIDIA Architecture — Tesla to Blackwell Complete Engineering Guide",
  seoTitle: "What Is NVIDIA GPU Architecture? Tesla to Blackwell, SM, Tensor Core, NVLink, MIG, DGX — Complete English Guide",
  seoDescription:
    "A complete engineering guide to NVIDIA GPU architecture — evolution from Tesla to Blackwell, GPC/TPC/SM internals, CUDA Cores, Tensor Cores, the Warp and Thread model, memory hierarchy, NVLink/NVSwitch, MIG virtualization, DGX/HGX platforms, the CUDA ecosystem, TensorRT, NCCL, data center power/cooling, and enterprise deployment. For AI engineers, DC engineers, and architects.",
  canonicalUrl: "https://behindthetech.in/learn/ai/hardware/nvidia-architecture",
  keywords: [
    "nvidia gpu architecture explained hindi",
    "tesla fermi kepler maxwell pascal volta turing ampere hopper blackwell",
    "streaming multiprocessor sm explained",
    "cuda core vs tensor core",
    "warp warp scheduler explained",
    "nvlink nvswitch explained",
    "mig multi instance gpu",
    "dgx hgx nvidia server",
    "cuda ecosystem",
    "tensorrt explained",
    "nccl collective communication",
    "nvidia blackwell architecture",
    "hopper transformer engine",
    "gpu memory hierarchy",
    "hbm gpu memory",
    "nvidia data center deployment",
    "gpu power cooling",
    "grace blackwell gb200",
    "gpu virtualization vgpu",
    "nvidia ai infrastructure",
  ],
  authorName: "Kumar Anil",
  datePublished: "2025-08-06",
  readingTimeMinutes: 110,
};
