import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary", text: "Quick Summary", level: 1 },
  { id: "what-is-sdwan", text: "What Is SD-WAN?", level: 1 },
  { id: "traditional-wan-limits", text: "Traditional WAN Limitations", level: 2 },
  { id: "what-sdwan-provides", text: "What SD-WAN Provides", level: 2 },
  { id: "underlay-vs-overlay", text: "Underlay vs Overlay", level: 1 },
  { id: "underlay", text: "The Underlay", level: 2 },
  { id: "overlay", text: "The Overlay", level: 2 },
  { id: "sdwan-architecture", text: "SD-WAN Architecture", level: 1 },
  { id: "three-planes", text: "Three Planes", level: 2 },
  { id: "key-components", text: "Key Components", level: 2 },
  { id: "sdwan-edge", text: "SD-WAN Edge", level: 1 },
  { id: "branch-edge", text: "Branch Edge", level: 2 },
  { id: "dc-edge", text: "Data Center Edge", level: 2 },
  { id: "tunnels-routing", text: "Tunnels and Routing", level: 1 },
  { id: "overlay-paths", text: "Overlay Paths", level: 2 },
  { id: "routing-in-sdwan", text: "Routing in SD-WAN", level: 2 },
  { id: "app-aware-steering", text: "Application-Aware Traffic Steering", level: 1 },
  { id: "application-classification", text: "Application Classification", level: 2 },
  { id: "steering-policy-example", text: "Steering Policy Example", level: 2 },
  { id: "sla-path-quality", text: "SLA and Path Quality", level: 1 },
  { id: "what-is-measured", text: "What SD-WAN Measures", level: 2 },
  { id: "link-up-vs-usable", text: "Link UP vs Application-Usable", level: 2 },
  { id: "dynamic-path-selection", text: "Dynamic Path Selection", level: 2 },
  { id: "failover", text: "Failover", level: 1 },
  { id: "blackout-brownout", text: "Blackout vs Brownout", level: 2 },
  { id: "active-active", text: "Active-Active Links", level: 2 },
  { id: "hybrid-wan", text: "Hybrid WAN — MPLS, Internet, LTE/5G", level: 1 },
  { id: "branch-to-dc", text: "Branch to Data Center Architecture", level: 1 },
  { id: "direct-internet-access", text: "Direct Internet Access", level: 2 },
  { id: "cloud-saas", text: "Cloud and SaaS Connectivity", level: 1 },
  { id: "sdwan-security", text: "SD-WAN Security", level: 1 },
  { id: "segmentation", text: "Segmentation", level: 2 },
  { id: "sdwan-firewall", text: "SD-WAN and Firewall", level: 2 },
  { id: "high-availability", text: "High Availability", level: 1 },
  { id: "controller-failure", text: "Controller Failure Behavior", level: 2 },
  { id: "nat-qos", text: "NAT and QoS", level: 1 },
  { id: "performance-monitoring", text: "Performance and Monitoring", level: 1 },
  { id: "troubleshooting", text: "Troubleshooting", level: 1 },
  { id: "ts-layers", text: "Troubleshooting Layers", level: 2 },
  { id: "ts-sequence", text: "Systematic Sequence", level: 2 },
  { id: "failure-scenarios", text: "Practical Failure Scenarios", level: 1 },
  { id: "operations", text: "Operations and Maintenance", level: 1 },
  { id: "misconceptions", text: "Common Misconceptions", level: 1 },
  { id: "final-architecture", text: "Final Integrated Architecture", level: 1 },
  { id: "key-takeaways", text: "Key Takeaways", level: 1 },
];
