import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",           text: "Quick Summary",                              level: 1 },
  { id: "who-should-read",         text: "Who Should Read This",                       level: 1 },
  { id: "what-you-will-learn",     text: "What You Will Learn",                        level: 1 },
  { id: "learning-path",           text: "Learning Path",                              level: 1 },
  { id: "introduction",            text: "Introduction",                               level: 1 },
  { id: "what-is-genai",           text: "What is Generative AI?",                     level: 1 },
  { id: "why-genai-exists",        text: "Why Generative AI Exists",                   level: 1 },
  { id: "history",                 text: "History and Evolution",                      level: 1 },
  { id: "how-genai-works",         text: "How Generative AI Works",                    level: 1 },
  { id: "tokens",                  text: "Tokens — The Atomic Unit",                   level: 1 },
  { id: "embeddings",              text: "Embeddings",                                 level: 1 },
  { id: "latent-space",            text: "Latent Space",                               level: 1 },
  { id: "prompt-engineering",      text: "Prompt Engineering",                         level: 1 },
  { id: "context-window",          text: "Context Window",                             level: 1 },
  { id: "attention-genai",         text: "Attention in Generative AI",                 level: 1 },
  { id: "decoder-only",            text: "Decoder-Only Models",                        level: 1 },
  { id: "encoder-decoder",         text: "Encoder-Decoder Models",                     level: 1 },
  { id: "diffusion-models",        text: "Diffusion Models",                           level: 1 },
  { id: "gans",                    text: "GANs",                                       level: 1 },
  { id: "vaes",                    text: "VAEs",                                       level: 1 },
  { id: "foundation-models",       text: "Foundation Models",                          level: 1 },
  { id: "fine-tuning",             text: "Fine-Tuning, LoRA, and QLoRA",               level: 1 },
  { id: "function-calling",        text: "Function Calling and Structured Outputs",    level: 1 },
  { id: "mcp",                     text: "Model Context Protocol (MCP)",               level: 1 },
  { id: "rag",                     text: "RAG — Retrieval Augmented Generation",       level: 1 },
  { id: "ai-agents",               text: "AI Agents",                                  level: 1 },
  { id: "agent-architecture",      text: "AI Agent Architecture",                      level: 2 },
  { id: "multimodal-ai",           text: "Multimodal AI",                              level: 1 },
  { id: "model-training",          text: "Model Training at GenAI Scale",              level: 1 },
  { id: "inference-pipeline",      text: "Inference Pipeline",                         level: 1 },
  { id: "gpu-acceleration",        text: "GPU Acceleration",                           level: 1 },
  { id: "ai-memory",               text: "AI Memory Requirements",                     level: 1 },
  { id: "storage-requirements",    text: "Storage Requirements",                       level: 1 },
  { id: "networking",              text: "Networking Requirements",                    level: 1 },
  { id: "ai-serving",              text: "AI Serving Infrastructure",                  level: 1 },
  { id: "ai-gateway",              text: "Enterprise AI Gateway",                      level: 1 },
  { id: "vector-databases",        text: "Vector Databases",                           level: 1 },
  { id: "enterprise-genai-stack",  text: "Enterprise GenAI Stack",                     level: 1 },
  { id: "ai-api-ecosystem",        text: "AI API Ecosystem",                           level: 1 },
  { id: "mlops-integration",       text: "MLOps Integration",                          level: 1 },
  { id: "ai-evaluation",           text: "AI Evaluation Frameworks",                   level: 1 },
  { id: "ai-observability",        text: "AI Observability",                           level: 1 },
  { id: "ai-model-registry",       text: "AI Model Registry",                          level: 1 },
  { id: "deployment-patterns",     text: "AI Deployment Patterns",                     level: 1 },
  { id: "hardware-mapping",        text: "AI Hardware Mapping",                        level: 1 },
  { id: "security",                text: "Security",                                   level: 1 },
  { id: "prompt-injection",        text: "Prompt Injection — Deep Dive",               level: 2 },
  { id: "ai-guardrails",           text: "AI Guardrails",                              level: 2 },
  { id: "enterprise-ai-security",  text: "Enterprise AI Security",                     level: 2 },
  { id: "responsible-ai",          text: "Responsible AI",                             level: 1 },
  { id: "cost-optimization",       text: "Cost Optimization",                          level: 1 },
  { id: "advantages",              text: "Advantages",                                 level: 1 },
  { id: "limitations",             text: "Limitations",                                level: 1 },
  { id: "best-practices",          text: "Best Practices",                             level: 1 },
  { id: "common-mistakes",         text: "Common Mistakes",                            level: 1 },
  { id: "production-case-studies", text: "Production Case Studies",                   level: 1 },
  { id: "hyperscale-case-studies", text: "Hyperscale AI Case Studies",                level: 2 },
  { id: "future-of-genai",         text: "Future of Generative AI",                    level: 1 },
  { id: "troubleshooting",         text: "Troubleshooting",                            level: 1 },
  { id: "interview-questions",     text: "Interview Questions",                        level: 1 },
  { id: "glossary",                text: "Glossary",                                   level: 1 },
  { id: "btt-learning-path",       text: "BTT AI Learning Path",                       level: 1 },
  { id: "key-takeaways",           text: "Key Takeaways",                              level: 1 },
];
