import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",          text: "Quick Summary",                                  level: 1 },
  { id: "who-should-read",        text: "Who Should Read This",                           level: 1 },
  { id: "what-you-will-learn",    text: "What You Will Learn",                            level: 1 },
  { id: "learning-path",          text: "Learning Path",                                  level: 1 },
  { id: "introduction",           text: "Introduction",                                   level: 1 },
  { id: "why-architecture",       text: "Why Architecture Understanding Matters",         level: 1 },
  { id: "evolution",              text: "Evolution — Tesla to Blackwell",                 level: 1 },
  { id: "die-hierarchy",          text: "GPU Die Hierarchy — GPC, TPC, SM",              level: 1 },
  { id: "gpc",                    text: "GPC — Graphics Processing Cluster",             level: 1 },
  { id: "tpc",                    text: "TPC — Texture Processing Cluster",              level: 1 },
  { id: "sm",                     text: "SM — Streaming Multiprocessor",                 level: 1 },
  { id: "cuda-cores",             text: "CUDA Cores — The General Workers",              level: 1 },
  { id: "tensor-cores",           text: "Tensor Cores — The AI Specialists",             level: 1 },
  { id: "rt-cores",               text: "RT Cores — Ray Tracing Hardware",               level: 1 },
  { id: "warp-scheduler",         text: "Warp and Warp Scheduler",                       level: 1 },
  { id: "thread-block-grid",      text: "Thread, Block, and Grid",                       level: 1 },
  { id: "registers",              text: "Registers — The Fastest Memory",                level: 1 },
  { id: "shared-memory",          text: "Shared Memory — The Team Whiteboard",           level: 1 },
  { id: "l1-l2-cache",            text: "L1 and L2 Cache",                               level: 1 },
  { id: "hbm",                    text: "HBM — The Main Memory",                         level: 1 },
  { id: "memory-controllers",     text: "Memory Controllers and ECC",                    level: 1 },
  { id: "nvlink",                 text: "NVLink — GPU-to-GPU Highway",                   level: 1 },
  { id: "nvswitch",               text: "NVSwitch — The GPU Fabric",                     level: 1 },
  { id: "pcie",                   text: "PCIe — The Standard Interface",                 level: 1 },
  { id: "mig",                    text: "MIG — Multi-Instance GPU",                      level: 1 },
  { id: "gpu-virtualization",     text: "GPU Virtualization — vGPU",                     level: 1 },
  { id: "grace-blackwell",        text: "Grace CPU + Blackwell — Unified Architecture",  level: 1 },
  { id: "dgx-hgx",               text: "DGX and HGX Platforms",                         level: 1 },
  { id: "data-flow",              text: "Data Flow Inside an NVIDIA GPU",                level: 1 },
  { id: "training-flow",          text: "AI Training Flow",                              level: 1 },
  { id: "inference-flow",         text: "AI Inference Flow",                             level: 1 },
  { id: "why-nvidia-dominates",   text: "Why NVIDIA Dominates AI",                       level: 1 },
  { id: "cuda-ecosystem",         text: "CUDA Ecosystem",                                level: 1 },
  { id: "tensorrt",               text: "TensorRT — Inference Optimization",             level: 1 },
  { id: "nccl",                   text: "NCCL — Collective Communications",              level: 1 },
  { id: "cuda-libraries",         text: "CUDA Libraries",                                level: 1 },
  { id: "driver-toolkit",         text: "Driver vs CUDA Toolkit",                        level: 1 },
  { id: "enterprise-deployment",  text: "Enterprise Deployment",                         level: 1 },
  { id: "power-cooling",          text: "Power and Cooling",                             level: 1 },
  { id: "rack-design",            text: "Rack Design for GPU Clusters",                  level: 1 },
  { id: "best-practices",         text: "Best Practices",                                level: 1 },
  { id: "common-mistakes",        text: "Common Mistakes",                               level: 1 },
  { id: "troubleshooting",        text: "Troubleshooting",                               level: 1 },
  { id: "interview-questions",    text: "Interview Questions",                           level: 1 },
  { id: "glossary",               text: "Glossary",                                      level: 1 },
  { id: "key-takeaways",          text: "Key Takeaways",                                 level: 1 },
];
