import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",          text: "Quick Summary",                                        level: 1 },
  { id: "who-should-read",        text: "Who Should Read This",                                 level: 1 },
  { id: "what-you-will-learn",    text: "What You Will Learn",                                  level: 1 },
  { id: "learning-path",          text: "Learning Path",                                        level: 1 },
  { id: "introduction",           text: "Introduction",                                         level: 1 },
  { id: "what-is-ai-dc",          text: "What is an AI Data Center?",                           level: 1 },
  { id: "why-different",          text: "Why AI Data Centers Are Different",                    level: 1 },
  { id: "evolution",              text: "Evolution of AI Data Centers",                         level: 1 },
  { id: "learning-hierarchy",     text: "The Learning Hierarchy — GPU to AI Factory",           level: 1 },
  { id: "training-vs-inference",  text: "AI Training vs AI Inference Infrastructure",           level: 1 },
  { id: "checkpointing-intro",    text: "Why Checkpointing Saves Training Jobs",                level: 1 },
  { id: "core-building-blocks",   text: "Core Building Blocks",                                 level: 1 },
  { id: "gpu-compute-nodes",      text: "AI Compute Nodes — GPU Servers",                       level: 1 },
  { id: "gpu-clusters-overview",  text: "GPU Clusters — Overview",                              level: 1 },
  { id: "east-west-traffic",      text: "East-West Traffic — AI Networking Pattern",            level: 1 },
  { id: "ai-networking-overview", text: "AI Networking — Overview",                             level: 1 },
  { id: "ai-storage-overview",    text: "AI Storage — Overview",                                level: 1 },
  { id: "data-locality",          text: "Data Locality",                                        level: 1 },
  { id: "ai-cooling-overview",    text: "AI Cooling — Overview",                                level: 1 },
  { id: "ai-power",               text: "AI Power Infrastructure",                              level: 1 },
  { id: "rack-design",            text: "Rack Design in AI Data Centers",                       level: 1 },
  { id: "ai-pod",                 text: "AI Pod Concept",                                       level: 1 },
  { id: "ai-factory",             text: "AI Factory Concept",                                   level: 1 },
  { id: "data-flow",              text: "AI Data Flow — Dataset to Results",                    level: 1 },
  { id: "gpu-scheduler",          text: "GPU Scheduling and Job Queues",                        level: 1 },
  { id: "gpu-utilization",        text: "GPU Utilization",                                      level: 1 },
  { id: "multi-tenancy",          text: "Multi-Tenancy",                                        level: 1 },
  { id: "software-stack",         text: "AI Software Stack Overview",                           level: 1 },
  { id: "enterprise-ai-dc",       text: "Enterprise AI Data Centers",                           level: 1 },
  { id: "hyperscale-ai-dc",       text: "Hyperscale AI Data Centers",                          level: 1 },
  { id: "capacity-planning",      text: "Capacity Planning",                                    level: 1 },
  { id: "scalability",            text: "Scalability",                                          level: 1 },
  { id: "reliability",            text: "Reliability",                                          level: 1 },
  { id: "redundancy",             text: "Redundancy",                                           level: 1 },
  { id: "high-availability",      text: "High Availability",                                    level: 1 },
  { id: "security",               text: "Security",                                             level: 1 },
  { id: "monitoring",             text: "Monitoring",                                           level: 1 },
  { id: "common-mistakes",        text: "Common Design Mistakes",                               level: 1 },
  { id: "best-practices",         text: "Best Practices",                                       level: 1 },
  { id: "troubleshooting",        text: "Troubleshooting",                                      level: 1 },
  { id: "future",                 text: "Future of AI Data Centers",                            level: 1 },
  { id: "interview-questions",    text: "Interview Questions",                                  level: 1 },
  { id: "glossary",               text: "Glossary",                                             level: 1 },
  { id: "key-takeaways",          text: "Key Takeaways",                                        level: 1 },
];
