import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary", text: "Quick Summary", level: 1 },
  { id: "what-is-hybrid-cloud", text: "What Is Hybrid Cloud?", level: 1 },
  { id: "hybrid-vs-multicloud", text: "Hybrid vs Multi-Cloud vs Private Cloud", level: 2 },
  { id: "why-hybrid-cloud", text: "Why Hybrid Cloud — Real Engineering Reasons", level: 2 },
  { id: "data-gravity", text: "Data Gravity — The Hidden Force", level: 2 },
  { id: "cloud-bursting", text: "Cloud Bursting", level: 2 },
  { id: "workload-placement", text: "Workload Placement Strategy", level: 2 },
  { id: "network-design", text: "Hybrid Network Design", level: 1 },
  { id: "connectivity-options", text: "Connectivity Options: VPN vs Interconnect", level: 2 },
  { id: "vpn", text: "IPsec VPN — Site to Cloud", level: 2 },
  { id: "dedicated-interconnect", text: "Direct Connect / ExpressRoute / Cloud Interconnect", level: 2 },
  { id: "sd-wan-hybrid", text: "SD-WAN in Hybrid Architectures", level: 2 },
  { id: "hybrid-dns", text: "Hybrid DNS Design", level: 2 },
  { id: "cidr-planning", text: "CIDR Planning — Non-Overlapping Networks", level: 2 },
  { id: "identity", text: "Hybrid Identity — SSO Across On-Prem and Cloud", level: 1 },
  { id: "active-directory", text: "Active Directory and Microsoft Entra ID", level: 2 },
  { id: "identity-sync-options", text: "PHS, PTA, and ADFS Federation", level: 2 },
  { id: "iam-integration", text: "AWS IAM Identity Center and GCP Cloud Identity", level: 2 },
  { id: "workload-identity", text: "Workload Identity — Applications Without Passwords", level: 2 },
  { id: "storage-sync", text: "Storage Sync and Data Replication", level: 1 },
  { id: "storage-patterns", text: "Hybrid Storage Patterns", level: 2 },
  { id: "database-replication", text: "Database Replication Strategies", level: 2 },
  { id: "backup-cloud", text: "Cloud Backup — 3-2-1-1 Rule", level: 2 },
  { id: "disaster-recovery", text: "Disaster Recovery Patterns", level: 1 },
  { id: "rpo-rto", text: "RPO and RTO — Engineering Definitions", level: 2 },
  { id: "cold-dr", text: "Cold DR — Backup and Restore", level: 2 },
  { id: "pilot-light", text: "Pilot Light", level: 2 },
  { id: "warm-standby", text: "Warm Standby", level: 2 },
  { id: "active-active", text: "Active-Active Architecture", level: 2 },
  { id: "dr-decision", text: "DR Pattern Decision Guide", level: 2 },
  { id: "hybrid-platforms", text: "Hybrid Cloud Platforms and Tools", level: 1 },
  { id: "vmware-hybrid", text: "VMware Hybrid Cloud (vSphere + HCX)", level: 2 },
  { id: "azure-arc", text: "Azure Arc", level: 2 },
  { id: "aws-outposts", text: "AWS Outposts", level: 2 },
  { id: "azure-stack-hci", text: "Azure Stack HCI", level: 2 },
  { id: "google-distributed-cloud", text: "Google Distributed Cloud", level: 2 },
  { id: "kubernetes-hybrid", text: "Kubernetes in Hybrid Cloud", level: 2 },
  { id: "openshift-anthos", text: "Red Hat OpenShift and Anthos", level: 2 },
  { id: "security", text: "Hybrid Cloud Security", level: 1 },
  { id: "zero-trust", text: "Zero Trust Architecture", level: 2 },
  { id: "network-security", text: "Network Security — Firewalls and Microsegmentation", level: 2 },
  { id: "encryption", text: "Encryption — Transit and Rest", level: 2 },
  { id: "key-management", text: "Key Management and HSMs", level: 2 },
  { id: "pam-bastion", text: "PAM, Bastion Hosts and JIT Access", level: 2 },
  { id: "certificate-lifecycle", text: "Certificate Lifecycle and Secrets Management", level: 2 },
  { id: "operations", text: "Operations — Monitoring, Logging and Governance", level: 1 },
  { id: "unified-monitoring", text: "Unified Monitoring Strategy", level: 2 },
  { id: "cmdb-itsm", text: "CMDB, ITSM and Incident Response", level: 2 },
  { id: "logging-strategy", text: "Centralized Logging", level: 2 },
  { id: "cost-management", text: "Cost Management and FinOps", level: 2 },
  { id: "compliance-governance", text: "Compliance and Governance", level: 2 },
  { id: "migration", text: "Migration Strategies — The 7 Rs", level: 1 },
  { id: "migration-7rs", text: "Retire, Retain, Rehost, Relocate", level: 2 },
  { id: "replatform-refactor", text: "Replatform, Repurchase, Refactor", level: 2 },
  { id: "migration-plan", text: "Migration Planning and Execution", level: 2 },
  { id: "architecture-examples", text: "Architecture Examples", level: 1 },
  { id: "enterprise-hybrid", text: "Enterprise Hybrid Reference Architecture", level: 2 },
  { id: "hospital-hybrid", text: "Healthcare Hybrid — Compliance-First", level: 2 },
  { id: "best-practices", text: "Best Practices", level: 1 },
  { id: "common-mistakes", text: "Common Engineering Mistakes", level: 1 },
  { id: "troubleshooting", text: "Troubleshooting Hybrid Cloud Issues", level: 1 },
  { id: "failure-scenarios", text: "Practical Failure Scenarios", level: 1 },
  { id: "cloud-adoption-framework", text: "Cloud Adoption Framework", level: 1 },
  { id: "caf-phases", text: "CAF Phases — Hybrid Cloud Context", level: 2 },
  { id: "landing-zone", text: "Landing Zone — Foundation Before Migration", level: 1 },
  { id: "landing-zone-components", text: "Landing Zone Components", level: 2 },
  { id: "hybrid-multicloud-deep", text: "Hybrid Cloud vs Multi-Cloud — Deep Comparison", level: 1 },
  { id: "decision-matrix", text: "Engineering Decision Matrix", level: 1 },
  { id: "certifications", text: "Certifications and Career", level: 1 },
  { id: "key-takeaways", text: "Key Takeaways", level: 1 },
];
