import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",            text: "Quick Summary",                                         level: 1 },
  { id: "who-should-read",          text: "Who Should Read This",                                  level: 1 },
  { id: "what-you-will-learn",      text: "What You Will Learn",                                   level: 1 },
  { id: "learning-path",            text: "Learning Path",                                         level: 1 },
  { id: "introduction",             text: "Introduction",                                          level: 1 },
  { id: "what-is-gpu-cluster",      text: "What Is a GPU Cluster?",                               level: 1 },
  { id: "why-clusters",             text: "Why Do We Need GPU Clusters?",                         level: 1 },
  { id: "gpu-vs-cpu",               text: "GPU vs CPU for AI Workloads",                          level: 1 },
  { id: "single-to-cluster",        text: "Single GPU → Multi-GPU Server → GPU Cluster",          level: 1 },
  { id: "gpu-compute-node",         text: "GPU Compute Node",                                     level: 1 },
  { id: "inside-gpu-server",        text: "What Is Inside a GPU Server?",                         level: 1 },
  { id: "gpu-hbm-ram",              text: "GPU Memory vs System Memory",                          level: 1 },
  { id: "terminology",              text: "GPU Server Terminology",                               level: 1 },
  { id: "cluster-architecture",     text: "GPU Cluster Architecture",                             level: 1 },
  { id: "building-blocks",          text: "GPU Cluster Building Blocks",                          level: 1 },
  { id: "rack-architecture",        text: "GPU Rack Architecture",                                level: 1 },
  { id: "network-architecture",     text: "GPU Cluster Network Architecture",                     level: 1 },
  { id: "mgmt-vs-compute-net",      text: "Management Network vs Compute Network",                level: 1 },
  { id: "nvlink-nvswitch",          text: "NVLink and NVSwitch",                                  level: 1 },
  { id: "infiniband-roce",          text: "InfiniBand and RoCE",                                  level: 1 },
  { id: "pcie-role",                text: "PCIe and Its Role",                                    level: 1 },
  { id: "gpu-to-gpu-comm",          text: "GPU-to-GPU Communication",                             level: 1 },
  { id: "east-west-traffic",        text: "East-West Traffic",                                    level: 1 },
  { id: "storage-architecture",     text: "Storage Architecture",                                 level: 1 },
  { id: "data-locality",            text: "Data Locality",                                        level: 1 },
  { id: "checkpoint-storage",       text: "Checkpoint Storage",                                   level: 1 },
  { id: "parallel-file-systems",    text: "Parallel File Systems",                                level: 1 },
  { id: "scheduler",                text: "GPU Cluster Scheduler",                                level: 1 },
  { id: "slurm",                    text: "Slurm",                                                level: 1 },
  { id: "kubernetes-gpu",           text: "Kubernetes and GPU Workloads",                         level: 1 },
  { id: "job-queue",                text: "GPU Job Queue and Resource Allocation",                 level: 1 },
  { id: "multi-tenancy",            text: "Multi-Tenancy",                                        level: 1 },
  { id: "gpu-utilization",          text: "GPU Utilization",                                      level: 1 },
  { id: "training-workloads",       text: "Training Workloads",                                   level: 1 },
  { id: "inference-workloads",      text: "Inference Workloads",                                  level: 1 },
  { id: "data-parallelism",         text: "Data Parallelism",                                     level: 1 },
  { id: "model-parallelism",        text: "Model Parallelism",                                    level: 1 },
  { id: "tensor-parallelism",       text: "Tensor Parallelism",                                   level: 1 },
  { id: "pipeline-parallelism",     text: "Pipeline Parallelism",                                 level: 1 },
  { id: "cluster-scaling",          text: "GPU Cluster Scaling",                                  level: 1 },
  { id: "power-requirements",       text: "Power Requirements",                                   level: 1 },
  { id: "cooling-requirements",     text: "Cooling Requirements",                                 level: 1 },
  { id: "reliability",              text: "Reliability and Failure Handling",                     level: 1 },
  { id: "redundancy",               text: "Redundancy and High Availability",                     level: 1 },
  { id: "monitoring",               text: "Monitoring and Observability",                         level: 1 },
  { id: "common-problems",          text: "Common GPU Cluster Problems",                          level: 1 },
  { id: "common-mistakes",          text: "Common Design Mistakes",                               level: 1 },
  { id: "best-practices",           text: "Best Practices",                                       level: 1 },
  { id: "interview-questions",      text: "Interview Questions",                                  level: 1 },
  { id: "glossary",                 text: "Glossary",                                             level: 1 },
  { id: "key-takeaways",            text: "Key Takeaways",                                        level: 1 },
];
