import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Energy Management System (EMS) — Complete Guide for Data Center Engineers | Behind The Tech",
  description: "EMS kya hai, energy meters integration, kW/kWh/PUE tracking, Modbus/BACnet data acquisition, dashboards, troubleshooting — complete Hinglish guide for data center engineers.",
  keywords: ["energy management system","EMS data center","energy meter Modbus","PUE calculation","power factor","kWh monitoring","data center energy"],
  openGraph: { title: "Energy Management System (EMS) — Complete Data Center Guide", description: "EMS architecture, meter integration, PUE analysis, troubleshooting.", url: "https://behindthetech.in/learn/non-it/bms-dcim/ems", siteName: "Behind The Tech", type: "article", authors: ["Kumar Anil"] },
  twitter: { card: "summary_large_image", title: "EMS Complete Guide — Behind The Tech", description: "Energy Management System for data centers." },
  alternates: { canonical: "https://behindthetech.in/learn/non-it/bms-dcim/ems" },
};
export const faqs = [
  { q: "EMS aur BMS mein kya fundamental difference hai?", a: "BMS building M&E systems monitor karta hai — HVAC, electrical, environment, aur where designed control bhi. EMS specifically energy consumption pe focus karta hai — utility meter readings, sub-metering, energy KPIs (kW, kWh, demand, power factor), reporting aur optimization. Kuch platforms dono combine karte hain, lekin EMS typically energy accounting aur cost analysis pe deeper hota hai jabki BMS operational monitoring aur alarm management pe." },
  { q: "PUE sirf EMS se calculate hoti hai kya?", a: "PUE (Power Usage Effectiveness) = Total Facility Power / IT Equipment Power. Data total facility input aur IT load measurement se aata hai — ye BMS, EMS, DCIM ya standalone metering systems se aa sakta hai. PUE accurately calculate karne ke liye metering points carefully define karne chahiye — kaunsa load IT mein count hoga, kaunsa facility mein. Measurement methodology aur metering accuracy pe PUE value depend karta hai — Uptime Institute aur Green Grid ke PUE guidelines reference karo." },
  { q: "Modbus energy meter ka zero ya wrong value aa raha hai — kya check karein?", a: "First: meter power ON hai aur display pe local readings correct hain? Second: Modbus wiring — RS-485 A/B polarity, baud rate, parity, slave ID match karte hain? Third: register address correct hai — OEM manual se verify karo, 0-based vs 1-based offset check karo. Fourth: data type aur scaling correct hai — energy meters often 32-bit registers use karte hain (2 consecutive Holding Registers), byte/word order verify karo. Fifth: BMS driver device status online hai?" },
  { q: "Peak demand kya hai aur EMS mein kyun important hai?", a: "Peak demand highest power draw hai ek specified interval mein — typically 15 or 30 minute average, utility billing period ke hisaab se. Utility companies often peak demand charges lagati hain jo total bill ka significant part ho sakta hai. EMS peak demand track karta hai, alerts generate karta hai jab demand threshold approach ho, aur demand response strategies support karta hai. Actual billing structure aur demand charge calculation apni utility tariff se verify karo." },
  { q: "Energy data retention kab tak rakhni chahiye?", a: "Retention period regulatory requirements, utility billing dispute resolution, sustainability reporting, ISO 50001 compliance aur operational analysis needs pe depend karta hai. Koi universal mandatory period nahi hai. Common practice mein granular (15-min/hourly) data 1-2 years, daily summaries longer period tak. Client contract, applicable standards aur local regulations check karo." },
  { q: "Sub-metering kya hai aur data center mein kyun useful hai?", a: "Sub-metering individual loads ko separately meter karna hai — UPS output, CRAC units, lighting, specific server hall circuits. Main utility meter total consumption batata hai lekin kaunsa load kitna consume karta hai visible nahi hota. Sub-metering granular visibility deta hai — IT load vs cooling load vs lighting — jo PUE calculation, cost allocation, efficiency analysis aur capacity planning ke liye essential hai. Instrumentation level project design pe depend karta hai." },
];
export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };
