import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "san-kya-hai",            text: "SAN Kya Hai — Definition aur Full Form",          level: 1 },
  { id: "san-vs-lan",             text: "SAN vs Normal Network",                           level: 1 },
  { id: "file-vs-block",          text: "File-Level vs Block-Level Storage",               level: 1 },
  { id: "das-nas-san-compare",    text: "DAS vs NAS vs SAN — Deep Comparison",             level: 1 },
  { id: "san-data-path",          text: "Complete SAN Data Path",                          level: 1 },
  { id: "san-terminology",        text: "Core SAN Terminology",                            level: 1 },
  { id: "lun-deep",               text: "LUN — Deep Explanation",                          level: 1 },
  { id: "san-architecture",       text: "SAN Architecture — Dual Fabric",                  level: 1 },
  { id: "fibre-channel",          text: "Fibre Channel SAN — Deep Explanation",            level: 1 },
  { id: "fc-login",               text: "Fibre Channel Login Process",                     level: 1 },
  { id: "san-zoning",             text: "SAN Zoning — Deep Explanation",                   level: 1 },
  { id: "lun-masking",            text: "LUN Masking / Host Mapping",                      level: 1 },
  { id: "zoning-vs-masking",      text: "Zoning vs LUN Masking — Comparison",              level: 1 },
  { id: "multipathing",           text: "Multipathing — Deep Practical Explanation",       level: 1 },
  { id: "windows-san",            text: "Windows SAN Practical",                           level: 1 },
  { id: "linux-san",              text: "Linux SAN Practical",                             level: 1 },
  { id: "vmware-san",             text: "VMware SAN",                                      level: 1 },
  { id: "iscsi-san",              text: "iSCSI SAN — Deep Practical Explanation",          level: 1 },
  { id: "iqn-naming",             text: "IQN Naming Convention",                           level: 1 },
  { id: "fc-vs-iscsi",            text: "FC SAN vs iSCSI SAN — Comparison",               level: 1 },
  { id: "fcoe",                   text: "FCoE — Fibre Channel over Ethernet",              level: 1 },
  { id: "nvme-of",                text: "NVMe over Fabrics (NVMe-oF)",                    level: 1 },
  { id: "san-switch-arch",        text: "SAN Switch Architecture",                         level: 1 },
  { id: "storage-array-arch",     text: "Storage Array Architecture",                      level: 1 },
  { id: "san-vendors",            text: "Enterprise SAN Vendors / Platforms",              level: 1 },
  { id: "san-provisioning",       text: "SAN Provisioning Workflow",                       level: 1 },
  { id: "san-capacity",           text: "SAN Capacity Management",                         level: 1 },
  { id: "thin-provisioning",      text: "Thin Provisioning",                               level: 1 },
  { id: "san-performance",        text: "SAN Performance",                                 level: 1 },
  { id: "san-monitoring",         text: "SAN Monitoring",                                  level: 1 },
  { id: "san-security",           text: "SAN Security",                                    level: 1 },
  { id: "san-ha",                 text: "SAN High Availability",                           level: 1 },
  { id: "san-failures",           text: "SAN Failure Scenarios — Field Guide",             level: 1 },
  { id: "san-troubleshoot-layers", text: "SAN Troubleshooting — Layer-by-Layer",            level: 1 },
  { id: "lun-not-visible",        text: "LUN Not Visible — Troubleshooting Flow",          level: 1 },
  { id: "production-incidents",   text: "Real Production Incidents",                       level: 1 },
  { id: "dangerous-mistakes",     text: "Dangerous SAN Mistakes",                          level: 1 },
  { id: "change-management",      text: "SAN Change Management",                           level: 1 },
  { id: "firmware-compat",        text: "Firmware and Compatibility",                      level: 1 },
  { id: "oem-escalation",         text: "OEM Escalation — What to Collect",               level: 1 },
  { id: "san-om-checklist",       text: "SAN O&M Checklist",                              level: 1 },
  { id: "preventive-maintenance", text: "Preventive Maintenance",                          level: 1 },
  { id: "san-documentation",      text: "SAN Documentation",                               level: 1 },
  { id: "san-migration",          text: "SAN Migration",                                   level: 1 },
  { id: "interview-questions",    text: "Interview / Job Knowledge",                       level: 1 },
  { id: "key-takeaways",          text: "Key Takeaways",                                   level: 1 },
];
