import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",            text: "Quick Summary",                                      level: 1 },
  { id: "who-should-read",          text: "Who Should Read This",                               level: 1 },
  { id: "what-you-will-learn",      text: "What You Will Learn",                                level: 1 },
  { id: "learning-path",            text: "Learning Path",                                      level: 1 },
  { id: "introduction",             text: "Introduction",                                       level: 1 },
  { id: "why-amd-matters",          text: "Why AMD AI Architecture Matters",                    level: 1 },
  { id: "evolution",                text: "Evolution — GCN to CDNA 4",                          level: 1 },
  { id: "compute-unit",             text: "Compute Unit (CU) — AMD's Building Block",           level: 1 },
  { id: "stream-processors",        text: "Stream Processors — The Compute Workers",            level: 1 },
  { id: "wavefront",                text: "Wavefront — AMD's Warp Equivalent",                  level: 1 },
  { id: "matrix-cores",             text: "Matrix Cores — The AI Math Engine",                  level: 1 },
  { id: "infinity-cache",           text: "Infinity Cache — AMD's Cache Innovation",            level: 1 },
  { id: "hbm-amd",                  text: "HBM Memory in AMD Context",                         level: 1 },
  { id: "infinity-fabric",          text: "Infinity Fabric — AMD's Interconnect",               level: 1 },
  { id: "memory-controllers",       text: "Memory Controllers",                                 level: 1 },
  { id: "chiplet-architecture",     text: "Chiplet Architecture",                               level: 1 },
  { id: "mi-series",                text: "MI Series — Product Line Overview",                  level: 1 },
  { id: "instinct-accelerators",    text: "Instinct Accelerators — Complete Family",            level: 1 },
  { id: "rocm-ecosystem",           text: "ROCm Ecosystem — AMD's CUDA Alternative",            level: 1 },
  { id: "hip-programming",          text: "HIP Programming Model",                              level: 1 },
  { id: "rccl",                     text: "RCCL — AMD's Collective Communications",             level: 1 },
  { id: "amd-software-stack",       text: "AMD AI Software Stack",                              level: 1 },
  { id: "training-workflow",        text: "Training Workflow on AMD",                           level: 1 },
  { id: "inference-workflow",       text: "Inference Workflow on AMD",                          level: 1 },
  { id: "amd-vs-nvidia",            text: "AMD vs NVIDIA — Technical Comparison",               level: 1 },
  { id: "enterprise-deployment",    text: "Enterprise Deployment",                              level: 1 },
  { id: "rack-design",              text: "Rack Design for AMD Instinct Clusters",              level: 1 },
  { id: "power-cooling",            text: "Power and Cooling",                                  level: 1 },
  { id: "dc-considerations",        text: "Data Center Considerations",                         level: 1 },
  { id: "best-practices",           text: "Best Practices",                                     level: 1 },
  { id: "common-mistakes",          text: "Common Mistakes",                                    level: 1 },
  { id: "troubleshooting",          text: "Troubleshooting",                                    level: 1 },
  { id: "interview-questions",      text: "Interview Questions",                                level: 1 },
  { id: "glossary",                 text: "Glossary",                                           level: 1 },
  { id: "key-takeaways",            text: "Key Takeaways",                                      level: 1 },
];
