import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",         text: "Quick Summary",                                         level: 1 },
  { id: "who-should-read",       text: "Who Should Read This",                                  level: 1 },
  { id: "what-is-meta-ai",       text: "What Is Meta AI?",                                      level: 1 },
  { id: "llama-ecosystem",       text: "Llama Ecosystem — Open-Weight AI",                      level: 1 },
  { id: "model-family",          text: "Llama Model Family",                                     level: 1 },
  { id: "meta-ai-products",      text: "Meta AI Products and Deployment Paths",                 level: 1 },
  { id: "compute-strategy",      text: "Meta Compute Strategy — Heterogeneous Infrastructure",  level: 1 },
  { id: "mtia",                  text: "MTIA — Meta's Custom Silicon",                          level: 1 },
  { id: "mtia-generations",      text: "MTIA Generations and Roadmap",                          level: 1 },
  { id: "nvidia-amd",            text: "NVIDIA and AMD GPU Infrastructure",                     level: 1 },
  { id: "ai-clusters",           text: "Meta AI Clusters",                                      level: 1 },
  { id: "grand-teton",           text: "Grand Teton and OpenRack",                              level: 1 },
  { id: "networking",            text: "AI Cluster Networking",                                  level: 1 },
  { id: "storage",               text: "Storage and Checkpoints",                               level: 1 },
  { id: "memory-hbm",            text: "Memory and HBM",                                        level: 1 },
  { id: "training-infra",        text: "Training Infrastructure",                               level: 1 },
  { id: "inference-infra",       text: "Inference Infrastructure",                              level: 1 },
  { id: "training-vs-inference", text: "Training vs Inference Comparison",                      level: 1 },
  { id: "power-density",         text: "Power and High-Density Racks",                          level: 1 },
  { id: "cooling",               text: "Cooling and Thermal Management",                        level: 1 },
  { id: "liquid-cooling-chain",  text: "Liquid Cooling Chain",                                  level: 1 },
  { id: "monitoring",            text: "Monitoring",                                            level: 1 },
  { id: "reliability",           text: "Reliability and RAS",                                   level: 1 },
  { id: "failure-troubleshoot",  text: "Failure Scenarios and Troubleshooting",                 level: 1 },
  { id: "enterprise",            text: "Enterprise and Deployment Considerations",               level: 1 },
  { id: "privacy-security",      text: "Privacy and Security",                                  level: 1 },
  { id: "dc-perspective",        text: "Practical Data Center and O&M Perspective",             level: 1 },
  { id: "references",            text: "Technical References",                                  level: 1 },
  { id: "key-takeaways",         text: "Key Takeaways",                                         level: 1 },
];
