import type { FaqItem } from "@/lib/schemas";

export const metaAiFaq: FaqItem[] = [
  {
    question: "What is the fundamental infrastructure difference between Meta AI and OpenAI/Anthropic/Google?",
    answer:
      "The biggest difference is the open-weight strategy and vertical integration. OpenAI, Anthropic, and Google primarily serve proprietary models through an API. Meta primarily releases Llama models as open-weight — model weights are publicly downloadable (open-weight, not fully open-source; training data/code isn't publicly released). The Meta AI consumer assistant (meta.ai) is currently powered by Muse Spark models per Meta announcements — a different family from Llama. Infrastructure implications: Meta has to run its own massive training/inference infrastructure simultaneously (at Facebook/Instagram/WhatsApp scale), while also making Llama models available to the community. Meta's compute mix is heterogeneous — it simultaneously uses NVIDIA GPUs, AMD GPUs, and its own custom MTIA silicon. MTIA's scope is expanding from R&R inference/training to GenAI inference. Llama's open-weight nature enables on-premise deployment for enterprises — the exact data control depends on architecture.",
  },
  {
    question: "What is the difference between Meta AI (Muse Spark) and Llama?",
    answer:
      "These are two distinct things. The Meta AI consumer product (meta.ai, Facebook/Instagram/WhatsApp integration) is Meta's internally served AI assistant — currently powered by Muse Spark 1.1 (text/conversation) and Muse Image (image generation) per Meta announcements. The exact model architecture and serving details are not fully publicly disclosed. Llama (Large Language Model Meta AI) is Meta's open-weight model family — the Llama 1/2/3/4 series. Model weights are publicly downloadable for researchers and developers. Llama doesn't necessarily power the Meta AI consumer product. For infrastructure: Meta AI = served internally in Meta's data centers. Llama = download it and deploy it on your own infrastructure. Do not conflate the two — they are separate product lines with different licensing, access models and infrastructure implications.",
  },
  {
    question: "What is MTIA and what is its current status?",
    answer:
      "MTIA (Meta Training and Inference Accelerator) is Meta's custom AI chip — designed in-house. Current status per Meta announcements: MTIA v1/100 and MTIA 200 are in production. MTIA 300 is in production for R&R (recommendation/ranking) training. MTIA 400 has completed testing and is on the deployment path — covering GenAI and R&R workloads with a 72-accelerator scale-up domain and AALC (Advanced Air/Liquid Cooling) support. MTIA 450 mass deployment is targeted for early 2027; MTIA 500 mass deployment for 2027. Hundreds of thousands of MTIA chips are deployed per Meta public statements. Why custom silicon: vendor diversification, workload-specific optimization (embedding lookups, ranking), reduced single-vendor dependence, power efficiency. MTIA hasn't completely replaced NVIDIA/AMD — large Llama training continues primarily on NVIDIA GPU clusters.",
  },
  {
    question: "Meta has documented TWO 24,576-GPU clusters — what's the difference?",
    answer:
      "Meta has publicly documented TWO 24,576 H100 GPU clusters for Llama 3 training — both with 400Gbps endpoints, but different network fabrics: Cluster 1 (RoCEv2): a RoCEv2 (RDMA over Converged Ethernet) 400Gbps fabric. RoCEv2 isn't ordinary Ethernet — RDMA requires a lossless fabric with PFC (Priority Flow Control) and ECN (Explicit Congestion Notification) congestion management. The largest Llama model was trained on this cluster per Meta's published paper. Cluster 2 (InfiniBand): an NVIDIA Quantum-2 InfiniBand 400Gbps fabric — a purpose-built HPC/AI interconnect with native RDMA. Significance: both fabrics are viable at 24K GPU scale with proper engineering. Meta's dual-fabric approach demonstrates that a single fabric choice isn't mandatory. Cluster evolution: ~4K → 24K documented; ~129K GPU scale is mentioned in future plans. Prometheus (~1 GW capacity, underway) and Hyperion (up to ~5 GW, ~2028 timeframe) are publicly announced large-scale next steps — exact GPU counts not disclosed.",
  },
  {
    question: "What are the infrastructure requirements for self-hosted Llama model deployment?",
    answer:
      "Download Llama models from llama.meta.com — subject to applicable license terms (restrictions vary by model/version — verify the current license). Deployment options: (1) On-premise GPU servers — on NVIDIA/AMD GPU hardware. For Llama 3 70B: BF16 model weights are approximately ~140 GB; but actual deployment memory includes weights + KV cache + runtime workspace, and depends on context length/batch size/serving architecture. Multiple high-end GPUs are typically required. (2) Cloud deployment — AWS EC2 P5, Google A3, Azure NDv5 offer Llama hosting. (3) Quantization — run on a smaller GPU using GGUF format (llama.cpp/Ollama) — with a quality tradeoff. (4) Fine-tuning — efficient via LoRA/QLoRA. Infrastructure considerations: inference data can stay within a controlled environment depending on architecture/integrations. Compliance (HIPAA, GDPR, etc.) isn't automatically achieved — additional technical and organisational controls are required. Inference speed/quality depends on model size, quantization, hardware, and serving architecture.",
  },
  {
    question: "How does the infrastructure for the Meta AI consumer product work?",
    answer:
      "Meta AI (meta.ai, Facebook/Instagram/WhatsApp integration) is Meta's internally served AI assistant — currently powered by Muse Spark 1.1 (conversation) and Muse Image (image generation) per Meta announcements. From an infrastructure perspective: serving happens primarily from Meta's own globally distributed data centers. Meta AI inference and recommendation/ranking/ad-serving inference are separate domains — different hardware configurations may be used. The exact serving architecture, model versions, and cluster assignments are not publicly disclosed. Meta uses heterogeneous infrastructure — NVIDIA GPUs for LLM/GenAI inference, MTIA for recommendation/ranking. Privacy: Meta AI conversations are governed by Meta's privacy policy — verify current terms at meta.ai/privacy. Training/retention policies can vary by product, region, and configuration.",
  },
  {
    question: "What are Grand Teton and OpenRack?",
    answer:
      "Grand Teton is Meta's purpose-built GPU server design — optimized for NVIDIA H100 SXM GPUs. Meta has publicly shared the Grand Teton design through the Open Compute Project (OCP). Key publicly documented specs: 8 GPUs per server, NVLink/NVSwitch integration (~900 GB/s bidirectional NVLink bandwidth per GPU per NVIDIA H100 specs), high-density power delivery, thermal management for sustained high-power GPU operation. H100 SXM GPU TDP is ~700W per GPU, so 8 GPUs = ~5.6 kW GPU TDP per server — full server power (CPU/memory/networking/VRM losses) is substantially more. OpenRack is an OCP community-developed rack standard — different from proprietary vendor racks. Meta, Microsoft, and others contribute to OCP. Data center implication: Grand Teton/OpenRack class servers draw significant sustained power — plan cooling infrastructure design carefully. Verify current specs on the OCP website.",
  },
  {
    question: "What is Meta's AI data center cooling strategy?",
    answer:
      "Meta publicly reports on data center thermal management. High-density GPU racks present significant cooling challenges. Meta's documented cooling approach includes: advanced cooling solutions deployed — warm-water cooling, rear-door heat exchangers, Direct Liquid Cooling (DLC), AALC (Advanced Air/Liquid Cooling). MTIA 400 specifically has AALC support per Meta announcements — relevant for high-density MTIA deployments. Meta contributes cooling innovations through OCP. Specific per-facility cooling configurations are not publicly detailed. Liquid cooling chain example (CDU-based, actual implementation facility-dependent): facility cooling plant → CDU (heat exchanger, isolates both loops) → secondary coolant loop → rack manifold → server cold plates → GPU chips → return. The CDU keeps the facility water and IT coolant loop physically separate — for chemistry, pressure, and contamination control. Actual cooling technology depends on server OEM design, rack density, and facility capability. Meta's annual sustainability report publicly reports PUE and water usage.",
  },
  {
    question: "Why does Meta use both NVIDIA and AMD GPUs?",
    answer:
      "Meta's heterogeneous GPU strategy is driven by multiple factors: (1) Vendor diversification — avoiding complete dependence on a single supplier; maintaining multiple hardware options. (2) Supply flexibility — having different vendors available reduces the impact of supply disruptions. (3) Workload fit — different GPU architectures may be better suited to different workloads. (4) Reduced single-vendor dependence — a long-term strategic goal. Practical implications: Meta's software stack has to support multiple GPU architectures — PyTorch (Meta-developed) naturally provides cross-platform support. AMD GPUs are publicly documented primarily in training workloads. NVIDIA GPUs in training and GenAI inference. MTIA in recommendation/ranking and expanding GenAI workloads. For O&M: heterogeneous GPU environments require complex driver management, monitoring, and maintenance — the operational complexity is real but balanced against the benefits of vendor flexibility.",
  },
  {
    question: "What are the data privacy and security considerations for Llama deployment?",
    answer:
      "With Llama open-weight models you can keep inference data within your own controlled environment — but this depends on architecture and integrations. Enterprise considerations: (1) On-premise deployment: inference requests stay within a controlled facility depending on setup — logging, monitoring, and third-party integrations can introduce data flows. An architecture review is required. (2) Compliance: HIPAA, GDPR, financial regulations — on-premise deployment controls data flows but compliance isn't automatically achieved. Additional technical/organisational controls, policies, and documentation are required. (3) Fine-tuning: you can fine-tune on organization-specific data on your own infrastructure — proprietary training data isn't exposed to an external API. (4) Private cloud: data typically stays in the customer VPC — but this depends on cloud provider infrastructure and configuration. Llama license: distributed under Meta's applicable license terms — restrictions vary by model/version; verify the current license at llama.meta.com before deployment. Security: apply access control to model weights, authenticate inference endpoints, consider prompt injection risks, secure fine-tuned models. Clearly distinguish this from the consumer Meta AI (meta.ai), where Meta's privacy policy applies.",
  },
];
