import type { FaqItem } from "@/lib/schemas";

export const metaAiFaq: FaqItem[] = [
  {
    question: "Meta AI aur OpenAI/Anthropic/Google mein fundamental infrastructure difference kya hai?",
    answer:
      "Sabse bada difference open-weight strategy aur vertical integration hai. OpenAI, Anthropic aur Google primarily proprietary models API ke through serve karte hain. Meta primarily Llama models open-weight release karta hai — model weights publicly downloadable hain (open-weight, not fully open-source; training data/code publicly released nahi). Meta AI consumer assistant (meta.ai) currently Muse Spark models se powered hai per Meta announcements — Llama se alag family. Infrastructure implications: Meta ko ek saath khud ka massive training/inference infrastructure chalana hai (Facebook/Instagram/WhatsApp scale pe), aur community ke liye Llama models available karne hain. Meta ka compute mix heterogeneous hai — NVIDIA GPUs, AMD GPUs, aur apna custom MTIA silicon simultaneously use karta hai. MTIA scope R&R inference/training se GenAI inference tak expand ho raha hai. Llama ki open-weight nature enterprises ko on-premise deployment enable karti hai — exact data control architecture pe depend karta hai.",
  },
  {
    question: "Meta AI (Muse Spark) aur Llama mein kya difference hai?",
    answer:
      "Yeh do distinct cheezein hain. Meta AI consumer product (meta.ai, Facebook/Instagram/WhatsApp integration) Meta ka internally served AI assistant hai — currently Muse Spark 1.1 (text/conversation) aur Muse Image (image generation) se powered per Meta announcements. Exact model architecture aur serving details publicly fully disclosed nahi hain. Llama (Large Language Model Meta AI) Meta ka open-weight model family hai — Llama 1/2/3/4 series. Model weights publicly downloadable hain researchers aur developers ke liye. Llama Meta AI consumer product ko necessarily power nahi karta. Infrastructure ke liye: Meta AI = Meta ke data centers mein internally served. Llama = download karke apne infrastructure pe deploy karo. Do not conflate — they are separate product lines with different licensing, access models and infrastructure implications.",
  },
  {
    question: "MTIA kya hai aur ab iski current status kya hai?",
    answer:
      "MTIA (Meta Training and Inference Accelerator) Meta ka custom AI chip hai — in-house designed. Current status per Meta announcements: MTIA v1/100 aur MTIA 200 production mein hain. MTIA 300 R&R (recommendation/ranking) training mein production mein hai. MTIA 400 testing completed hai aur deployment path pe hai — 72-accelerator scale-up domain aur AALC (Advanced Air/Liquid Cooling) support ke saath GenAI aur R&R workloads cover karta hai. MTIA 450 mass deployment early 2027 targeted; MTIA 500 mass deployment 2027. Hundreds of thousands of MTIA chips deployed hain per Meta public statements. Kyun custom silicon: vendor diversification, workload-specific optimization (embedding lookups, ranking), reduced single-vendor dependence, power efficiency. MTIA ne NVIDIA/AMD completely replace nahi kiya — large Llama training primarily NVIDIA GPU clusters pe continue karta hai.",
  },
  {
    question: "Meta ne TWO 24,576-GPU clusters document kiye hain — kya difference hai?",
    answer:
      "Meta ne Llama 3 training ke liye publicly TWO 24,576 H100 GPU clusters document kiye hain — dono 400Gbps endpoints ke saath, lekin different network fabrics: Cluster 1 (RoCEv2): RoCEv2 (RDMA over Converged Ethernet) 400Gbps fabric. RoCEv2 ordinary Ethernet nahi hai — RDMA ke liye lossless fabric required hai with PFC (Priority Flow Control) aur ECN (Explicit Congestion Notification) congestion management. Largest Llama model is cluster pe trained tha per Meta's published paper. Cluster 2 (InfiniBand): NVIDIA Quantum-2 InfiniBand 400Gbps fabric — purpose-built HPC/AI interconnect with native RDMA. Significance: Both fabrics 24K GPU scale pe viable hain with proper engineering. Meta ka dual-fabric approach demonstrate karta hai ki ek single fabric choice mandatory nahi hai. Cluster evolution: ~4K → 24K documented; ~129K GPU scale future plans mein mentioned. Prometheus (~1 GW capacity, underway) aur Hyperion (up to ~5 GW, ~2028 timeframe) publicly announced large-scale next steps hain — exact GPU counts not disclosed.",
  },
  {
    question: "Llama models self-hosted deployment ke liye infrastructure requirements kya hain?",
    answer:
      "Llama models llama.meta.com se download karo — applicable license terms ke saath (restrictions model/version ke anusaar vary karti hain — current license verify karo). Deployment options: (1) On-premise GPU servers — NVIDIA/AMD GPU hardware pe. Llama 3 70B ke liye: BF16 model weights ~140 GB approximate; lekin actual deployment memory mein weights + KV cache + runtime workspace include hota hai, aur context length/batch size/serving architecture pe depend karta hai. Multiple high-end GPUs typically required. (2) Cloud deployment — AWS EC2 P5, Google A3, Azure NDv5 — Llama hosting offer karte hain. (3) Quantization — GGUF format (llama.cpp/Ollama) se smaller GPU pe run karo — quality tradeoff ke saath. (4) Fine-tuning — LoRA/QLoRA se efficient. Infrastructure considerations: Inference data controlled environment mein reh sakta hai depending on architecture/integrations. Compliance (HIPAA, GDPR etc.) automatically achieved nahi hoti — additional technical aur organisational controls required hain. Inference speed/quality model size, quantization, hardware aur serving architecture pe depend karti hai.",
  },
  {
    question: "Meta AI consumer product ka infrastructure kaise kaam karta hai?",
    answer:
      "Meta AI (meta.ai, Facebook/Instagram/WhatsApp integration) Meta ka internally served AI assistant hai — currently Muse Spark 1.1 (conversation) aur Muse Image (image generation) se powered per Meta announcements. Infrastructure perspective se: Serving primarily Meta ke apne globally distributed data centers se hoti hai. Meta AI inference aur recommendation/ranking/ad-serving inference separate domains hain — different hardware configurations use ho sakti hain. Exact serving architecture, model versions aur cluster assignments publicly disclosed nahi hain. Meta heterogeneous infrastructure use karta hai — NVIDIA GPUs LLM/GenAI inference ke liye, MTIA recommendation/ranking ke liye. Privacy: Meta AI conversations Meta ki privacy policy ke under hain — verify current terms at meta.ai/privacy. Training/retention policies product, region aur configuration ke anusaar vary kar sakti hain.",
  },
  {
    question: "Grand Teton aur OpenRack kya hain?",
    answer:
      "Grand Teton Meta ka purpose-built GPU server design hai — NVIDIA H100 SXM GPUs ke liye optimized. Meta ne Grand Teton design Open Compute Project (OCP) ke through publicly shared kiya hai. Key specs publicly documented: 8 GPUs per server, NVLink/NVSwitch integration (~900 GB/s bidirectional NVLink bandwidth per GPU per NVIDIA H100 specs), high-density power delivery, thermal management for sustained high-power GPU operation. H100 SXM GPU TDP ~700W per GPU, 8 GPUs = ~5.6 kW GPU TDP per server — full server power (CPU/memory/networking/VRM losses) substantially more. OpenRack OCP community-developed rack standard hai — proprietary vendor racks se different. Meta, Microsoft aur others OCP mein contribute karte hain. Data center implication: Grand Teton/OpenRack class servers significant sustained power draw karte hain — cooling infrastructure design carefully plan karo. OCP website pe current specs verify karo.",
  },
  {
    question: "Meta ki AI data center cooling strategy kya hai?",
    answer:
      "Meta publicly data center thermal management report karta hai. High-density GPU racks significant cooling challenges present karte hain. Meta ke documented cooling approach mein: Advanced cooling solutions deployed hain — warm-water cooling, rear-door heat exchangers, Direct Liquid Cooling (DLC), AALC (Advanced Air/Liquid Cooling). MTIA 400 specifically AALC support rakhta hai per Meta announcements — high-density MTIA deployments ke liye relevant. Meta OCP ke through cooling innovations contribute karta hai. Specific per-facility cooling configurations publicly detailed nahi hain. Liquid cooling chain example (CDU-based, actual implementation facility pe dependent): Facility cooling plant → CDU (heat exchanger, dono loops isolate) → secondary coolant loop → rack manifold → server cold plates → GPU chips → return. CDU facility water aur IT coolant loop ko physically separate rakhta hai — chemistry, pressure, contamination control ke liye. Actual cooling technology server OEM design, rack density aur facility capability pe depend karti hai. Meta annual sustainability report PUE aur water usage publicly report karta hai.",
  },
  {
    question: "Meta NVIDIA aur AMD GPUs dono use kyun karta hai?",
    answer:
      "Meta ka heterogeneous GPU strategy multiple factors se driven hai: (1) Vendor diversification — single supplier pe complete dependence avoid karna; multiple hardware options maintain karna. (2) Supply flexibility — different vendors available hone se supply disruptions ka impact reduce hota hai. (3) Workload fit — different GPU architectures different workloads ke liye potentially better suited ho sakte hain. (4) Reduced single-vendor dependence — long-term strategic goal. Practical implications: Meta ke software stack ko multiple GPU architectures support karne padte hain — PyTorch (Meta-developed) cross-platform support naturally provide karta hai. AMD GPUs primarily training workloads mein publicly documented hain. NVIDIA GPUs training aur GenAI inference mein. MTIA recommendation/ranking aur expanding GenAI workloads mein. O&M ke liye: Heterogeneous GPU environments complex driver management, monitoring, aur maintenance require karte hain — operational complexity real hai lekin vendor flexibility ke benefits ke saath balanced hai.",
  },
  {
    question: "Llama deployment ke liye data privacy aur security considerations kya hain?",
    answer:
      "Llama open-weight models ke saath inference data apne controlled environment mein rakh sakte ho — lekin yeh architecture aur integrations pe depend karta hai. Enterprise considerations: (1) On-premise deployment: Inference requests controlled facility mein rehte hain depending on setup — logging, monitoring, aur third-party integrations data flows introduce kar sakte hain. Architecture review required. (2) Compliance: HIPAA, GDPR, financial regulations — on-premise deployment data flows control karta hai lekin compliance automatically achieved nahi hoti. Additional technical/organisational controls, policies aur documentation required hain. (3) Fine-tuning: Organization-specific data apne infrastructure pe fine-tune kar sakte ho — proprietary training data external API pe expose nahi hoti. (4) Private cloud: Data stays in customer VPC typically — but cloud provider infrastructure aur configuration pe depend karta hai. Llama license: Meta ke applicable license terms ke under distributed — restrictions model/version ke anusaar vary karti hain; current license llama.meta.com pe verify karo before deployment. Security: Model weights access-control karo, inference endpoints authenticate karo, prompt injection risks consider karo, fine-tuned models secure karo. Consumer Meta AI (meta.ai) se clearly distinguish karo — wahan Meta ki privacy policy apply hoti hai.",
  },
];
