import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  // Phase 1 — Core Fundamentals
  { id: "quick-summary",          text: "Quick Summary",                                          level: 1 },
  { id: "lb-core-idea",           text: "Load Balancer — The Core Idea",                          level: 1 },
  { id: "what-lb-does",           text: "What a Load Balancer Actually Does",                     level: 1 },
  { id: "traffic-journey",        text: "Basic Traffic Journey",                                  level: 1 },
  { id: "core-terminology",       text: "Core Terminology",                                       level: 1 },
  { id: "vip-virtual-service",    text: "VIP — Virtual IP / Virtual Service",                     level: 1 },
  { id: "backend-pool",           text: "Backend Pool",                                           level: 1 },
  { id: "health-check-foundation",text: "Health Check Foundation",                                level: 1 },
  { id: "algorithms-intro",       text: "Basic Load Balancing Algorithms",                        level: 1 },
  { id: "l4-vs-l7",              text: "L4 vs L7 — Foundation",                                  level: 1 },
  { id: "lb-vs-router",           text: "Load Balancer vs Router",                                level: 1 },
  { id: "lb-vs-firewall",         text: "Load Balancer vs Firewall",                              level: 1 },
  { id: "lb-vs-reverse-proxy",    text: "Load Balancer vs Reverse Proxy",                         level: 1 },
  { id: "lb-vs-dns",              text: "Load Balancer vs DNS Load Balancing",                    level: 1 },
  { id: "one-arm-two-arm",        text: "One-Arm vs Two-Arm — Introduction",                      level: 1 },
  { id: "ha-foundation",          text: "High Availability Foundation",                           level: 1 },
  { id: "dc-placement",           text: "Data Center Placement",                                  level: 1 },
  { id: "practical-example-p1",   text: "Practical Example",                                      level: 1 },
  { id: "beginner-misconceptions",text: "Common Beginner Misunderstandings",                      level: 1 },
  { id: "p1-takeaways",           text: "Phase 1 Key Takeaways",                                  level: 1 },

  // Phase 2 — Traffic Processing, Connection Flow, NAT & Return Path
  { id: "p2-orientation",         text: "Phase 2 Orientation",                                    level: 1 },
  { id: "connection-flow",        text: "Connection Flow Foundation",                             level: 1 },
  { id: "full-proxy",             text: "Full Proxy Architecture",                                level: 1 },
  { id: "forwarding-models",      text: "Forwarding / Non-Full-Proxy Models",                     level: 1 },
  { id: "packet-address-journey", text: "Packet Address Journey",                                 level: 1 },
  { id: "destination-translation",text: "Destination Translation Foundation",                     level: 1 },
  { id: "snat",                   text: "Source NAT — SNAT",                                      level: 1 },
  { id: "without-snat",           text: "Without SNAT",                                           level: 1 },
  { id: "symmetric-asymmetric",   text: "Symmetric vs Asymmetric Traffic",                        level: 1 },
  { id: "dsr",                    text: "Direct Server Return — DSR",                             level: 1 },
  { id: "one-arm-deep",           text: "One-Arm Traffic Flow — Deeper View",                     level: 1 },
  { id: "two-arm-deep",           text: "Inline / Two-Arm Traffic Flow — Deeper View",            level: 1 },
  { id: "connection-table",       text: "Connection Table / Flow State",                          level: 1 },
  { id: "tcp-handshake",          text: "TCP Connection Establishment",                           level: 1 },
  { id: "connection-reuse",       text: "Connection Reuse / Multiplexing Foundation",             level: 1 },
  { id: "http-keepalive",         text: "HTTP Keep-Alive and Load Distribution",                  level: 1 },
  { id: "timeouts",               text: "Timeouts",                                               level: 1 },
  { id: "backend-failure-active", text: "Backend Failure During Active Connection",               level: 1 },
  { id: "rst-foundation",         text: "Connection Reset — RST Foundation",                      level: 1 },
  { id: "client-ip-preservation", text: "Client IP Preservation",                                 level: 1 },
  { id: "port-translation",       text: "Port Translation",                                       level: 1 },
  { id: "return-path-ts",         text: "Return Path Troubleshooting Foundation",                 level: 1 },
  { id: "broken-return-path",     text: "Practical Scenario — Broken Return Path",                level: 1 },
  { id: "p2-mistakes",            text: "Common Engineering Mistakes",                            level: 1 },
  { id: "p2-takeaways",           text: "Phase 2 Key Takeaways",                                  level: 1 },

  // Phase 3 — Health Monitoring, Algorithms, Persistence
  { id: "p3-orientation",         text: "Phase 3 Orientation",                                    level: 1 },
  { id: "health-why",             text: "Health Monitoring — Why It Exists",                      level: 1 },
  { id: "monitor-types",          text: "Health Monitor Types",                                   level: 1 },
  { id: "tcp-monitor",            text: "TCP Health Monitor",                                     level: 1 },
  { id: "http-monitor",           text: "HTTP / HTTPS Health Monitor",                            level: 1 },
  { id: "app-aware-health",       text: "Application-Aware Health Check",                         level: 1 },
  { id: "active-passive-health",  text: "Active vs Passive Health Signals",                       level: 1 },
  { id: "health-thresholds",      text: "Health Check Interval, Timeout & Thresholds",            level: 1 },
  { id: "health-state-transitions",text: "Health State Transitions",                              level: 1 },
  { id: "health-flapping",        text: "Health Check Flapping",                                  level: 1 },
  { id: "algorithm-decision",     text: "Load Balancing Algorithm — Decision Model",              level: 1 },
  { id: "round-robin-deep",       text: "Round Robin — Deeper View",                              level: 1 },
  { id: "weighted-round-robin",   text: "Weighted Round Robin",                                   level: 1 },
  { id: "least-connections",      text: "Least Connections",                                      level: 1 },
  { id: "weighted-least-conn",    text: "Weighted Least Connections",                             level: 1 },
  { id: "hash-selection",         text: "Hash-Based Selection",                                   level: 1 },
  { id: "algorithm-comparison",   text: "Algorithm Comparison",                                   level: 1 },
  { id: "algo-limits",            text: "What Algorithms Do Not Know",                            level: 1 },
  { id: "persistence-why",        text: "Persistence / Stickiness — Why It Exists",               level: 1 },
  { id: "persistence-vs-algo",    text: "Persistence ≠ Load Balancing Algorithm",                 level: 1 },
  { id: "source-ip-persistence",  text: "Source IP Persistence",                                  level: 1 },
  { id: "cookie-persistence",     text: "Cookie-Based Persistence",                               level: 1 },
  { id: "cookie-flow",            text: "Cookie Persistence Traffic Flow",                        level: 1 },
  { id: "persisted-backend-fails",text: "What If Persisted Backend Fails?",                       level: 1 },
  { id: "persistence-timeout",    text: "Persistence Timeout",                                    level: 1 },
  { id: "persistence-app-design", text: "Persistence and Application Design",                     level: 1 },
  { id: "l7-content-switching",   text: "L7 Content Switching",                                   level: 1 },
  { id: "host-routing",           text: "Host-Based Routing",                                     level: 1 },
  { id: "path-routing",           text: "Path-Based Routing",                                     level: 1 },
  { id: "header-routing",         text: "Header-Based Routing",                                   level: 1 },
  { id: "l7-policy-eval",         text: "L7 Policy Evaluation",                                   level: 1 },
  { id: "backend-draining",       text: "Backend Draining / Graceful Maintenance",                level: 1 },
  { id: "drain-vs-down",          text: "Draining vs Marking Down",                               level: 1 },
  { id: "slow-start",             text: "Slow Start / Ramp-Up",                                   level: 1 },
  { id: "connection-limits",      text: "Connection Limits",                                      level: 1 },
  { id: "priority-pools",         text: "Priority / Failover Pools",                              level: 1 },
  { id: "practical-p3",           text: "Practical Application Example",                          level: 1 },
  { id: "ts-health-selection",    text: "Troubleshooting Health vs Selection",                    level: 1 },
  { id: "p3-mistakes",            text: "Common Engineering Mistakes",                            level: 1 },
  { id: "p3-takeaways",           text: "Phase 3 Key Takeaways",                                  level: 1 },

  // Phase 4 — TLS, HTTP/2-3, GSLB, Observability
  { id: "p4-orientation",         text: "Phase 4 Orientation",                                    level: 1 },
  { id: "tls-problem",            text: "TLS Offload — The Problem It Solves",                    level: 1 },
  { id: "tls-modes",              text: "TLS Offload vs Re-Encryption vs Passthrough",            level: 1 },
  { id: "cert-management",        text: "Certificate Management at the LB",                       level: 1 },
  { id: "mtls",                   text: "Client Certificate Authentication (mTLS)",               level: 1 },
  { id: "http2-lb",               text: "HTTP/2 — What Changes for Load Balancing",               level: 1 },
  { id: "http3-quic",             text: "HTTP/3 and QUIC — Load Balancing Implications",          level: 1 },
  { id: "gslb-foundation",        text: "GSLB — Global Server Load Balancing Foundation",        level: 1 },
  { id: "gslb-policies",          text: "GSLB Routing Policies",                                  level: 1 },
  { id: "gslb-ttl",               text: "GSLB and TTL Management",                               level: 1 },
  { id: "lb-metrics",             text: "Load Balancer Observability — Metrics",                  level: 1 },
  { id: "lb-access-logs",         text: "Load Balancer Observability — Access Logs",              level: 1 },
  { id: "lb-health-logs",         text: "Load Balancer Observability — Health Check Logs",        level: 1 },
  { id: "lb-alerting",            text: "Load Balancer Observability — Alerting",                 level: 1 },
  { id: "distributed-tracing",    text: "Distributed Tracing at the LB",                         level: 1 },
  { id: "observability-example",  text: "Practical Observability Example",                        level: 1 },
  { id: "p4-mistakes",            text: "Common Engineering Mistakes",                            level: 1 },
  { id: "p4-takeaways",           text: "Phase 4 Key Takeaways",                                  level: 1 },

  // Phase 5 — Operations, Troubleshooting & Data Center Integration
  { id: "p5-orientation",         text: "Phase 5 Orientation",                                    level: 1 },
  { id: "ops-lifecycle",          text: "Operational Lifecycle Overview",                         level: 1 },
  { id: "config-management",      text: "Configuration Management",                               level: 1 },
  { id: "backend-addition",       text: "Backend Addition",                                       level: 1 },
  { id: "backend-removal",        text: "Backend Removal — Planned Maintenance",                  level: 1 },
  { id: "emergency-removal",      text: "Emergency Backend Removal",                              level: 1 },
  { id: "cert-operations",        text: "Certificate Operations",                                 level: 1 },
  { id: "algo-persistence-ops",   text: "Algorithm and Persistence Changes",                      level: 1 },
  { id: "ts-framework",           text: "Troubleshooting Framework",                              level: 1 },
  { id: "ts-vip-unreachable",     text: "Diagnosing No-Traffic / VIP Unreachable",               level: 1 },
  { id: "ts-partial-failures",    text: "Diagnosing Partial Backend Failures",                    level: 1 },
  { id: "ts-slow-response",       text: "Diagnosing Slow Response / Timeouts",                    level: 1 },
  { id: "ts-health-failures",     text: "Diagnosing Health Check Failures",                       level: 1 },
  { id: "network-integration",    text: "Network Integration — Physical and Logical Placement",   level: 1 },
  { id: "vlan-design",            text: "VLAN Design for Load Balancing",                         level: 1 },
  { id: "routing-design",         text: "Routing Design Around the Load Balancer",                level: 1 },
  { id: "firewall-interaction",   text: "Interaction with Firewalls",                             level: 1 },
  { id: "switch-interaction",     text: "Interaction with Switches",                              level: 1 },
  { id: "virtual-cloud-lb",       text: "Load Balancer in Virtualized / Cloud Environments",     level: 1 },
  { id: "capacity-planning",      text: "Capacity Planning",                                      level: 1 },
  { id: "e2e-tracing",            text: "End-to-End Request Tracing",                             level: 1 },
  { id: "dc-integration-example", text: "Data Center Integration — Practical Example",            level: 1 },
  { id: "p5-mistakes",            text: "Common Operations Engineering Mistakes",                 level: 1 },
  { id: "p5-takeaways",           text: "Phase 5 Key Takeaways",                                  level: 1 },
];
