import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Sensors in Data Centers — Complete Engineering Guide | Behind The Tech",
  description: "Temperature, humidity, differential pressure, water leak, fuel level, current, voltage, energy, door contact, airflow, occupancy sensors — working principle, installation, BMS integration, calibration, troubleshooting. Engineer-level Hinglish guide.",
  keywords: ["data center sensors","temperature sensor","humidity sensor","water leak detection","4-20mA sensor","Modbus sensor","BMS sensor integration","differential pressure sensor","current transformer"],
  openGraph: { title: "Sensors in Data Centers — Complete Engineering Guide", description: "All data center sensor types — working principle, signals, BMS integration, calibration, troubleshooting.", url: "https://behindthetech.in/learn/non-it/bms-dcim/sensors", siteName: "Behind The Tech", type: "article", authors: ["Kumar Anil"] },
  twitter: { card: "summary_large_image", title: "Data Center Sensors — Behind The Tech", description: "Complete sensor guide for data center engineers." },
  alternates: { canonical: "https://behindthetech.in/learn/non-it/bms-dcim/sensors" },
};
export const faqs = [
  { q: "4-20 mA sensor aur 0-10V sensor mein kya difference hai?", a: "4-20 mA current loop long cable runs pe preferred hai kyunki current signal wire resistance se affect nahi hota — voltage drop problem nahi hoti. 4 mA = 0% of range (live zero — break in wire detect hota hai kyunki 0 mA wire break indicate karta hai), 20 mA = 100%. 0-10V voltage signal short runs pe simpler hai lekin cable resistance se voltage drop hoti hai long runs pe. 4-20 mA industrially more reliable hai — data centers mein remote sensors ke liye preferred signal standard hai." },
  { q: "Temperature sensor placement data center mein kyun critical hai?", a: "Server inlet temperature hot aur cold aisle mein significantly different hoti hai. Sensor galat jagah pe lagao to BMS 'all normal' show karega jabki actual server inlet hot hogi. ASHRAE guidelines recommend karte hain sensors at server inlet height (typically front face of rack at top, middle, bottom). Return air temperature, cold aisle, hot aisle aur room ambient sab different readings dete hain — purpose ke hisaab se sensor locate karo. Single sensor per zone adequate nahi hota large spaces mein." },
  { q: "Water leak sensor ne alarm generate kiya — kya karna chahiye?", a: "Immediately: leak ka physical location identify karo — sensor ka exact location check karo aur visual inspection karo. Agar active water visible hai — source identify karo (CRAC unit condensate line? Chilled water? Plumbing?). Critical equipment ke neeche ya paas mein hai to immediate protective action consider karo. Source isolate karo agar possible. Security/operations team alert karo. Sensor reset karo sirf tab jab leak source rectified aur area dry ho. False alarm possibility bhi investigate karo — condensation, humidity, or sensor fault." },
  { q: "CT (Current Transformer) kaise kaam karta hai?", a: "CT primary conductor (bus bar ya cable) se secondary winding mein proportional current induce karta hai. CT ratio (e.g., 100:5 A) primary aur secondary current ka ratio hai. Secondary current typically 5A ya 1A (standard) hota hai jo meter ya BMS input pe safe hai. CT secondary open-circuit karna hazardous hai — high voltage generate hoti hai. CT always secondary pe load ya short circuit rakho. Energy meter ya BMS mein CT ratio correctly program karo — wrong ratio means proportionally wrong current/energy readings." },
  { q: "Differential pressure sensor data center mein kahan use hota hai?", a: "Multiple applications: (1) Raised floor mein plenum pressure monitor karna — yeh ensure karta hai adequate air pressure server racks tak pahunche. (2) CRAC/CRAH filter differential pressure — filter clog hone pe pressure drop badhti hai — maintenance trigger. (3) Air containment systems mein positive/negative pressure monitoring. (4) Clean rooms ya specialized areas mein pressure differential maintain karna. Sensor placement aur range project-specific hai — OEM aur design engineer se verify karo." },
  { q: "Sensor calibration kab karni chahiye?", a: "Calibration frequency sensor type, criticality, manufacturer recommendation aur applicable standards pe depend karta hai — koi universal schedule nahi hai. General guidance: temperature sensors annually ya biannually verify karo known reference se. Humidity sensors zyada drift karte hain — more frequent calibration often needed. Pressure sensors per manufacturer recommendation. Current/energy measurement per accuracy class requirement. Critical measurements (billing, safety) higher frequency. As-found/as-left records maintain karo — calibration history important hai." },
];
export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };
