import type { Metadata } from "next";
import { SITE_OG_IMAGE } from "@/lib/schemas";
export const metadata: Metadata = {
  title: "Sensors in Data Centers — Complete Engineering Guide | Behind The Tech",
  description: "Temperature, humidity, differential pressure, water leak, fuel level, current, voltage, energy, door contact, airflow, occupancy sensors — working principle, installation, BMS integration, calibration, troubleshooting. Engineer-level English guide.",
  keywords: ["data center sensors","temperature sensor","humidity sensor","water leak detection","4-20mA sensor","Modbus sensor","BMS sensor integration","differential pressure sensor","current transformer"],
  openGraph: { title: "Sensors in Data Centers — Complete Engineering Guide", description: "All data center sensor types — working principle, signals, BMS integration, calibration, troubleshooting.", url: "https://behindthetech.in/learn/non-it/bms-dcim/sensors", locale: "en_US", siteName: "Behind The Tech", type: "article", authors: ["Kumar Anil"], images: [SITE_OG_IMAGE], },
  twitter: { card: "summary_large_image", title: "Data Center Sensors — Behind The Tech", description: "Complete sensor guide for data center engineers.", images: [SITE_OG_IMAGE.url], },
  alternates: {
    canonical: "https://behindthetech.in/learn/non-it/bms-dcim/sensors",
    languages: {
      en: "https://behindthetech.in/learn/non-it/bms-dcim/sensors",
      hi: "https://behindthetech.in/hi/learn/non-it/bms-dcim/sensors",
      "x-default": "https://behindthetech.in/learn/non-it/bms-dcim/sensors",
    },
  },
};
export const faqs = [
  { q: "What is the difference between a 4-20 mA sensor and a 0-10V sensor?", a: "The 4-20 mA current loop is preferred on long cable runs because a current signal is not affected by wire resistance — there is no voltage drop problem. 4 mA = 0% of range (live zero — a break in the wire is detected because 0 mA indicates a wire break), 20 mA = 100%. A 0-10V voltage signal is simpler on short runs, but on long runs there is voltage drop from cable resistance. 4-20 mA is industrially more reliable — it is the preferred signal standard for remote sensors in data centers." },
  { q: "Why is temperature sensor placement critical in a data center?", a: "Server inlet temperature is significantly different in the hot and cold aisle. If you install the sensor in the wrong place, the BMS will show 'all normal' while the actual server inlet will be hot. ASHRAE guidelines recommend sensors at server inlet height (typically front face of rack at top, middle, bottom). Return air temperature, cold aisle, hot aisle and room ambient all give different readings — locate the sensor according to its purpose. A single sensor per zone is not adequate in large spaces." },
  { q: "A water leak sensor generated an alarm — what should be done?", a: "Immediately: identify the physical location of the leak — check the exact location of the sensor and do a visual inspection. If active water is visible — identify the source (CRAC unit condensate line? Chilled water? Plumbing?). If it is under or near critical equipment, consider immediate protective action. Isolate the source if possible. Alert the security/operations team. Reset the sensor only when the leak source has been rectified and the area is dry. Also investigate the false alarm possibility — condensation, humidity, or sensor fault." },
  { q: "How does a CT (Current Transformer) work?", a: "A CT induces a proportional current from the primary conductor (bus bar or cable) into the secondary winding. The CT ratio (e.g., 100:5 A) is the ratio of primary and secondary current. The secondary current is typically 5A or 1A (standard), which is safe at the meter or BMS input. Open-circuiting a CT secondary is hazardous — high voltage is generated. Always keep a load or short circuit on the CT secondary. Program the CT ratio correctly in the energy meter or BMS — a wrong ratio means proportionally wrong current/energy readings." },
  { q: "Where is a differential pressure sensor used in a data center?", a: "Multiple applications: (1) Monitoring plenum pressure in the raised floor — this ensures adequate air pressure reaches the server racks. (2) CRAC/CRAH filter differential pressure — as the filter clogs the pressure drop increases — maintenance trigger. (3) Positive/negative pressure monitoring in air containment systems. (4) Maintaining pressure differential in clean rooms or specialized areas. Sensor placement and range are project-specific — verify with the OEM and design engineer." },
  { q: "When should sensor calibration be done?", a: "Calibration frequency depends on sensor type, criticality, manufacturer recommendation and applicable standards — there is no universal schedule. General guidance: verify temperature sensors annually or biannually against a known reference. Humidity sensors drift more — more frequent calibration is often needed. Pressure sensors per manufacturer recommendation. Current/energy measurement per accuracy class requirement. Critical measurements (billing, safety) at higher frequency. Maintain as-found/as-left records — calibration history is important." },
];
export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };
