import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary", text: "Quick Summary", level: 1 },
  { id: "what-is-multi-cloud", text: "What Is Multi-Cloud?", level: 1 },
  { id: "multi-cloud-vs-hybrid", text: "Multi-Cloud vs Hybrid Cloud", level: 2 },
  { id: "why-multi-cloud", text: "Why Enterprises Adopt Multi-Cloud", level: 2 },
  { id: "business-drivers", text: "Business Drivers — Real Engineering Reasons", level: 2 },
  { id: "vendor-lock-in", text: "Vendor Lock-In Avoidance", level: 2 },
  { id: "best-of-breed", text: "Best-of-Breed Strategy", level: 2 },
  { id: "cloud-sovereignty", text: "Cloud Sovereignty and Regulatory Requirements", level: 2 },
  { id: "architecture", text: "Multi-Cloud Architecture Patterns", level: 1 },
  { id: "active-active", text: "Active-Active Multi-Cloud", level: 2 },
  { id: "active-passive", text: "Active-Passive and Pilot Light", level: 2 },
  { id: "geo-distributed", text: "Geo-Distributed Global Architecture", level: 2 },
  { id: "workload-placement", text: "Workload Placement Strategy", level: 2 },
  { id: "networking", text: "Cross-Cloud Networking", level: 1 },
  { id: "connectivity-options", text: "Connectivity Options — VPN vs Private Fabric", level: 2 },
  { id: "sd-wan-multicloud", text: "SD-WAN and Exchange Fabrics", level: 2 },
  { id: "cidr-dns", text: "CIDR Planning and DNS Strategy", level: 2 },
  { id: "bgp-routing", text: "BGP Route Advertisement and Advanced Networking", level: 2 },
  { id: "identity", text: "Federated Identity and IAM", level: 1 },
  { id: "central-idp", text: "Central Identity Provider", level: 2 },
  { id: "iam-mapping", text: "IAM Mapping Across Providers", level: 2 },
  { id: "workload-identity", text: "Workload Identity and Secrets Management", level: 2 },
  { id: "identity-lifecycle", text: "SCIM Provisioning, Lifecycle Automation and JIT Access", level: 2 },
  { id: "compute", text: "Multi-Cloud Compute and Kubernetes", level: 1 },
  { id: "kubernetes-multicloud", text: "Kubernetes Multi-Cluster Management", level: 2 },
  { id: "anthos-openshift", text: "Anthos, OpenShift and Rancher", level: 2 },
  { id: "storage", text: "Storage and Data Replication", level: 1 },
  { id: "object-replication", text: "Object Storage Cross-Cloud Replication", level: 2 },
  { id: "database-replication", text: "Database Replication — No Native Tool", level: 2 },
  { id: "data-gravity", text: "Data Gravity and Migration", level: 2 },
  { id: "storage-rpo-rto", text: "RPO, RTO and Storage Consistency", level: 2 },
  { id: "security", text: "Multi-Cloud Security", level: 1 },
  { id: "zero-trust", text: "Zero Trust Across All Clouds", level: 2 },
  { id: "pam-secrets", text: "PAM, Bastion Hosts and Secrets Management", level: 2 },
  { id: "encryption-kms", text: "Encryption and KMS Differences", level: 2 },
  { id: "compliance", text: "Compliance Across Multiple Clouds", level: 2 },
  { id: "cloud-security-posture", text: "CSPM, CNAPP, CWPP and DSPM", level: 2 },
  { id: "monitoring", text: "Unified Monitoring and Observability", level: 1 },
  { id: "metrics-logging", text: "Metrics, Logging and Tracing", level: 2 },
  { id: "siem-incident", text: "SIEM and Incident Management", level: 2 },
  { id: "otel-architecture", text: "OpenTelemetry Architecture and Distributed Tracing", level: 2 },
  { id: "automation", text: "Automation — IaC, GitOps and CI/CD", level: 1 },
  { id: "terraform-multicloud", text: "Terraform Multi-Cloud", level: 2 },
  { id: "gitops", text: "GitOps with ArgoCD and Flux", level: 2 },
  { id: "finops", text: "FinOps and Cost Management", level: 1 },
  { id: "cost-visibility", text: "Cost Visibility — Unified Billing", level: 2 },
  { id: "chargeback-showback", text: "Chargeback and Showback", level: 2 },
  { id: "license-optimization", text: "License Optimization", level: 2 },
  { id: "operations", text: "Operations and Governance", level: 1 },
  { id: "cmdb-itsm", text: "CMDB, ITSM and Asset Discovery", level: 2 },
  { id: "cmp", text: "Cloud Management Platforms", level: 2 },
  { id: "migration", text: "Migration Strategy", level: 1 },
  { id: "phased-migration", text: "Phased Migration Approach", level: 2 },
  { id: "rollback", text: "Rollback Planning", level: 2 },
  { id: "failure-scenarios", text: "Failure Scenarios", level: 1 },
  { id: "decision-matrix", text: "Decision Matrix — When to Choose What", level: 1 },
  { id: "certifications", text: "Certifications and Career", level: 1 },
  { id: "best-practices", text: "Enterprise Best Practices", level: 1 },
  { id: "common-mistakes", text: "Common Engineering Mistakes", level: 1 },
  { id: "troubleshooting-playbook", text: "Troubleshooting Playbook", level: 1 },
  { id: "key-takeaways", text: "Key Takeaways", level: 1 },
];
