import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",         text: "Quick Summary",                                      level: 1 },
  { id: "who-should-read",       text: "Who Should Read This",                               level: 1 },
  { id: "what-is-anthropic",     text: "What Is Anthropic?",                                 level: 1 },
  { id: "claude-model-family",   text: "Claude Model Family",                                level: 1 },
  { id: "constitutional-ai",     text: "Constitutional AI — Safety-First Training",          level: 1 },
  { id: "aws-partnership",       text: "Anthropic and Amazon AWS",                           level: 1 },
  { id: "api-platform",          text: "Claude API Platform",                                level: 1 },
  { id: "bedrock-vs-direct",     text: "Claude Deployment Options — Cloud Platforms",                       level: 1 },
  { id: "request-flow",          text: "How a Claude API Request Flows",                     level: 1 },
  { id: "context-window",        text: "Context Window and Infrastructure Impact",           level: 1 },
  { id: "training-infra",        text: "Training Infrastructure",                            level: 1 },
  { id: "inference-infra",       text: "Inference Infrastructure",                           level: 1 },
  { id: "aws-silicon",           text: "AWS Custom Silicon — Trainium and Inferentia",       level: 1 },
  { id: "compute-strategy",      text: "Multi-Platform Compute Strategy",                     level: 1 },
  { id: "tokens-cost",           text: "Tokens, Latency and Cost",                           level: 1 },
  { id: "model-tiers",           text: "Model Tiers — Haiku, Sonnet, Opus",                 level: 1 },
  { id: "networking-storage",    text: "Networking and Storage",                             level: 1 },
  { id: "data-center",           text: "Data Center Requirements",                           level: 1 },
  { id: "reliability",           text: "Reliability and Availability",                       level: 1 },
  { id: "enterprise-deployment", text: "Enterprise AI Deployment",                           level: 1 },
  { id: "data-privacy",          text: "Data Privacy and Security",                          level: 1 },
  { id: "interpretability",      text: "Interpretability Research",                          level: 1 },
  { id: "openai-vs-anthropic",   text: "OpenAI vs Anthropic — Infrastructure Comparison",   level: 1 },
  { id: "dc-perspective",        text: "Practical Data Center Perspective",                  level: 1 },
  { id: "references",            text: "Technical References",                               level: 1 },
  { id: "key-takeaways",         text: "Key Takeaways",                                      level: 1 },
];
