import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "GPU in Data Centers — Architecture, VRAM, AI Workloads & Deployment | Behind The Tech",
  description: "GPU kya hai, CPU vs GPU design philosophy, VRAM, PCIe, AI training vs inference, multi-GPU networking, GPU server architecture, air vs liquid cooling — Zero-to-Hero Hinglish guide.",
  keywords: ["GPU data center","NVIDIA GPU","GPU AI training","VRAM","PCIe GPU","GPU server","AI infrastructure GPU","NVLink","GPU cooling"],
  openGraph: { title: "GPU in Data Centers — Architecture & AI Workloads", description: "GPU architecture, VRAM, training vs inference, multi-GPU, server deployment.", url: "https://behindthetech.in/learn/it/servers/gpu", siteName: "Behind The Tech", type: "article", authors: ["Kumar Anil"] },
  twitter: { card: "summary_large_image", title: "GPU in Data Centers — Behind The Tech", description: "GPU architecture, AI workloads, deployment guide." },
  alternates: { canonical: "https://behindthetech.in/learn/it/servers/gpu" },
};
export const faqs = [
  { q: "CPU aur GPU mein fundamental difference kya hai?", a: "CPU few powerful cores design karta hai — excellent sequential execution, complex branch prediction, large caches, general purpose. GPU thousands of simpler cores design karta hai — massive parallel throughput, matrix operations. AI training mein GPU effective hai kyunki matrix multiplication inherently massively parallel hai. CPU complex sequential tasks, OS management, application control ke liye; GPU parallel numeric workloads ke liye." },
  { q: "VRAM kya hai aur AI mein kyun critical hai?", a: "VRAM GPU ka dedicated memory hai — system RAM se physically separate. AI training mein model weights, gradients, optimizer states, activations — sab VRAM mein hote hain. VRAM capacity hard constraint hai: model + training state VRAM mein fit hona chahiye. Fit nahi hua → Out of Memory error. Large language models ke liye VRAM ek primary bottleneck hai." },
  { q: "GPU utilization 100% matlab efficient use hai?", a: "Zaruri nahi. 100% utilization dikhna lag sakta hai jabki GPU actually compute operations wait kar raha ho data ke liye (memory bandwidth bound), PCIe transfer ka wait kar raha ho, ya synchronisation overhead mein ho. True GPU efficiency profiling tools se assess karo — NVIDIA Nsight, PyTorch Profiler, etc. High utilization good signal hai lekin complete efficiency picture nahi." },
  { q: "Data center GPU aur consumer gaming GPU mein kya difference hai?", a: "Data center GPUs (NVIDIA H-series, A-series; AMD Instinct) specifically designed hain: passive cooling (data center airflow dependent), ECC memory, higher VRAM, NVLink/SXM form factor support, enterprise support lifecycle. Consumer GPUs active fans ke saath aate hain (data center airflow pe work nahi karte well), limited VRAM, typically no enterprise support. Small-scale experiments ke liye consumer GPU possible, production workloads ke liye datacenter GPUs appropriate hain." },
  { q: "Air cooling vs liquid cooling GPU infrastructure ke liye?", a: "Air cooling: front-to-back airflow, traditional CRAC/CRAH compatible. High-TDP GPU clusters mein dense deployments ke liye air cooling capacity insufficient ho sakti hai. Liquid cooling: direct liquid cooling (DLC) GPU cold plates directly cool karte hain — much higher heat density handle kar sakta hai. Rear-door heat exchangers, immersion cooling emerging options hain. Choice GPU TDP, rack density, data center cooling infrastructure aur budget pe depend karta hai." },
];
export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };
