"use client";

/**
 * components/ArticlePage.tsx
 *
 * Reusable article layout for every BTT topic page.
 *
 * SLOTS:
 *   children         — the article body (JSX, server-rendered)
 *   slug             — topic slug (used to derive meta from topics.ts)
 *   prevSlug         — previous topic in learning path
 *   nextSlug         — next topic in learning path
 *   relatedSlugs     — array of related topic slugs
 *   headings         — [{id, text, level}] for TOC (generated by page.tsx)
 */

import { useState, useEffect } from "react";
import Link from "next/link";
import { ChevronDown, Clock } from "lucide-react";
import { TOPICS, getTopicUrl, type Topic } from "@/lib/topics";
import TopicLink from "@/components/TopicLink";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ArticleHeading {
  id: string;
  text: string;
  level: 1 | 2 | 3;
}

interface ArticlePageProps {
  slug: string;
  prevSlug?: string;
  nextSlug?: string;
  relatedSlugs: string[];
  headings: ArticleHeading[];
  readingTimeMinutes: number;
  children: React.ReactNode;
}

// ─── Reading Progress Bar ─────────────────────────────────────────────────────

function ReadingProgressBar() {
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const update = () => {
      const el = document.documentElement;
      const scrollTop = el.scrollTop || document.body.scrollTop;
      const scrollHeight = el.scrollHeight - el.clientHeight;
      setProgress(scrollHeight > 0 ? (scrollTop / scrollHeight) * 100 : 0);
    };
    update();
    window.addEventListener("scroll", update, { passive: true });
    return () => window.removeEventListener("scroll", update);
  }, []);

  return (
    <div aria-hidden="true" style={{ position: "fixed", top: 64, left: 0, right: 0, height: 2, zIndex: 40, background: "rgba(0,212,255,0.08)" }}>
      <div
        style={{
          height: "100%",
          width: `${progress}%`,
          background: "var(--color-neon-blue)",
          transition: "width 0.1s linear",
        }}
      />
    </div>
  );
}

// ─── Breadcrumbs ─────────────────────────────────────────────────────────────

function Breadcrumbs({ topic }: { topic: Topic }) {
  return (
    <div style={{ marginBottom: 14 }}>
      <span
        style={{
          fontFamily: "var(--font-mono)",
          fontSize: 11,
          letterSpacing: "0.18em",
          textTransform: "uppercase",
          color: "var(--color-text-muted)",
        }}
      >
        {topic.breadcrumb[0]}
      </span>
    </div>
  );
}

// ─── Hero ─────────────────────────────────────────────────────────────────────

function ArticleHero({ topic, readingTimeMinutes }: { topic: Topic; readingTimeMinutes: number }) {
  return (
    <header style={{ marginBottom: 44 }}>
      <span
        style={{
          display: "inline-block",
          fontFamily: "var(--font-mono)",
          fontSize: 11,
          letterSpacing: "0.2em",
          textTransform: "uppercase",
          color: "var(--color-neon-blue)",
          fontWeight: 600,
          marginBottom: 18,
        }}
      >
        {topic.breadcrumb[topic.breadcrumb.length - 2] ?? topic.breadcrumb[0]}
      </span>

      <h1
        style={{
          fontFamily: "var(--font-display)",
          fontSize: "clamp(2.1rem, 4.4vw, 3.4rem)",
          letterSpacing: "0.02em",
          color: "var(--color-text-primary)",
          lineHeight: 1.15,
          margin: "0 0 24px",
        }}
      >
        {topic.title.toUpperCase()}
      </h1>

      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          alignItems: "center",
          gap: 18,
          paddingTop: 18,
          paddingBottom: 18,
          borderTop: "1px solid rgba(0,212,255,0.12)",
          borderBottom: "1px solid rgba(0,212,255,0.12)",
        }}
      >
        <span style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span
            aria-hidden="true"
            style={{
              width: 26,
              height: 26,
              borderRadius: "50%",
              background: "rgba(0,212,255,0.1)",
              border: "1px solid rgba(0,212,255,0.28)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontFamily: "var(--font-mono)",
              fontSize: 9,
              fontWeight: 700,
              color: "var(--color-neon-blue)",
            }}
          >
            AK
          </span>
          <span style={{ fontFamily: "var(--font-body)", fontSize: 13.5, color: "var(--color-text-secondary)" }}>
            Kumar Anil
          </span>
        </span>

        <span aria-hidden="true" style={{ width: 1, height: 12, background: "rgba(255,255,255,0.14)" }} />

        <span style={{ display: "flex", alignItems: "center", gap: 6, fontFamily: "var(--font-mono)", fontSize: 11.5, color: "var(--color-text-muted)", letterSpacing: "0.04em" }}>
          <Clock size={12} aria-hidden="true" />
          {readingTimeMinutes} Min Read
        </span>

        <span aria-hidden="true" style={{ width: 1, height: 12, background: "rgba(255,255,255,0.14)" }} />

        <span style={{ fontFamily: "var(--font-mono)", fontSize: 11.5, color: "var(--color-text-muted)", letterSpacing: "0.04em" }}>
          {topic.breadcrumb[0]}
        </span>
      </div>
    </header>
  );
}

// ─── Table of Contents — flat numbered list, no card chrome ──────────────────

function TableOfContents({ headings }: { headings: ArticleHeading[] }) {
  const [activeId, setActiveId] = useState<string>("");
  const [mobileOpen, setMobileOpen] = useState(false);
  const topLevel = headings.filter((h) => h.level !== 3);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) setActiveId(e.target.id);
        });
      },
      { rootMargin: "-80px 0px -70% 0px", threshold: 0 }
    );
    headings.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, [headings]);

  const handleClick = (id: string) => {
    setMobileOpen(false);
    const el = document.getElementById(id);
    if (el) {
      const top = el.getBoundingClientRect().top + window.scrollY - 90;
      window.scrollTo({ top, behavior: "smooth" });
    }
  };

  return (
    <>
      {/* Mobile TOC */}
      <div className="lg:hidden" style={{ marginBottom: 32 }}>
        <button
          onClick={() => setMobileOpen((v) => !v)}
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            width: "100%",
            padding: "10px 0",
            background: "transparent",
            border: "none",
            borderTop: "1px solid rgba(0,212,255,0.14)",
            borderBottom: "1px solid rgba(0,212,255,0.14)",
            cursor: "pointer",
          }}
          aria-expanded={mobileOpen}
        >
          <span style={{ fontFamily: "var(--font-mono)", fontSize: 10, letterSpacing: "0.18em", textTransform: "uppercase", flex: 1, textAlign: "left", color: "var(--color-text-muted)" }}>
            Contents
          </span>
          <ChevronDown
            size={14}
            style={{ color: "var(--color-text-muted)", transform: mobileOpen ? "rotate(180deg)" : "rotate(0deg)", transition: "transform 0.22s ease" }}
            aria-hidden="true"
          />
        </button>

        <div style={{ maxHeight: mobileOpen ? "600px" : "0px", overflow: "hidden", transition: "max-height 0.26s ease" }}>
          <ol style={{ listStyle: "none", margin: 0, padding: "12px 0 4px" }}>
            {topLevel.map(({ id, text }, i) => (
              <li key={id}>
                <button
                  onClick={() => handleClick(id)}
                  style={{
                    display: "flex",
                    alignItems: "baseline",
                    gap: 10,
                    width: "100%",
                    textAlign: "left",
                    padding: "8px 0",
                    background: "transparent",
                    border: "none",
                    cursor: "pointer",
                    fontFamily: "var(--font-body)",
                    fontSize: 13.5,
                    color: activeId === id ? "var(--color-neon-blue)" : "var(--color-text-secondary)",
                  }}
                >
                  <span style={{ fontFamily: "var(--font-mono)", fontSize: 10.5, color: "var(--color-text-muted)", flexShrink: 0 }}>
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  {text}
                </button>
              </li>
            ))}
          </ol>
        </div>
      </div>

      {/* Desktop sticky TOC */}
      <nav
        aria-label="Table of contents"
        className="hidden lg:block"
        style={{
          position: "sticky",
          top: 96,
          maxHeight: "calc(100vh - 128px)",
          overflowY: "auto",
        }}
      >
        <span
          style={{
            display: "block",
            fontFamily: "var(--font-mono)",
            fontSize: 10,
            letterSpacing: "0.22em",
            textTransform: "uppercase",
            color: "var(--color-text-muted)",
            fontWeight: 500,
            marginBottom: 18,
          }}
        >
          Contents
        </span>
        <ol style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 2 }}>
          {topLevel.map(({ id, text }, i) => {
            const isActive = activeId === id;
            return (
              <li key={id}>
                <button
                  onClick={() => handleClick(id)}
                  title={text}
                  style={{
                    display: "flex",
                    alignItems: "baseline",
                    gap: 9,
                    width: "100%",
                    textAlign: "left",
                    whiteSpace: "nowrap",
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                    padding: "6px 0",
                    background: "transparent",
                    border: "none",
                    borderLeft: isActive ? "2px solid var(--color-neon-blue)" : "2px solid transparent",
                    paddingLeft: isActive ? 10 : 12,
                    cursor: "pointer",
                    fontFamily: "var(--font-body)",
                    fontSize: 12.5,
                    fontWeight: isActive ? 500 : 400,
                    color: isActive ? "var(--color-text-primary)" : "var(--color-text-secondary)",
                    lineHeight: 1.4,
                    transition: "color 0.15s ease, border-color 0.15s ease, padding-left 0.15s ease",
                  }}
                  onMouseEnter={(e) => { if (!isActive) e.currentTarget.style.color = "var(--color-text-primary)"; }}
                  onMouseLeave={(e) => { if (!isActive) e.currentTarget.style.color = "var(--color-text-secondary)"; }}
                >
                  <span
                    style={{
                      fontFamily: "var(--font-mono)",
                      fontSize: 10,
                      color: isActive ? "var(--color-neon-blue)" : "var(--color-text-muted)",
                      flexShrink: 0,
                      opacity: isActive ? 1 : 0.7,
                    }}
                  >
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span style={{ overflow: "hidden", textOverflow: "ellipsis" }}>{text}</span>
                </button>
              </li>
            );
          })}
        </ol>
      </nav>
    </>
  );
}

// ─── Continue Learning (Prev / Next) ─────────────────────────────────────────

function ContinueLearning({ prevSlug, nextSlug }: { prevSlug?: string; nextSlug?: string }) {
  const prev = prevSlug ? TOPICS[prevSlug] : undefined;
  const next = nextSlug ? TOPICS[nextSlug] : undefined;

  if (!prev && !next) return null;

  return (
    <section aria-label="Continue Learning" style={{ marginTop: 56 }}>
      <div style={{ borderTop: "1px solid rgba(0,212,255,0.12)", paddingTop: 28 }}>
        <span
          style={{
            fontFamily: "var(--font-mono)",
            fontSize: 10,
            letterSpacing: "0.2em",
            textTransform: "uppercase",
            color: "var(--color-text-muted)",
          }}
        >
          Continue Reading
        </span>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 0, marginTop: 16 }}>
        {prev && (
          <Link
            href={getTopicUrl(prev)}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              gap: 12,
              padding: "16px 0",
              borderBottom: "1px solid rgba(0,212,255,0.08)",
              textDecoration: "none",
            }}
          >
            <span style={{ fontFamily: "var(--font-mono)", fontSize: 10.5, letterSpacing: "0.1em", color: "var(--color-text-muted)" }}>← PREV</span>
            <span style={{ fontFamily: "var(--font-body)", fontSize: 14.5, color: "var(--color-text-primary)", textAlign: "right" }}>{prev.title}</span>
          </Link>
        )}
        {next && (
          <Link
            href={getTopicUrl(next)}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              gap: 12,
              padding: "16px 0",
              borderBottom: "1px solid rgba(0,212,255,0.08)",
              textDecoration: "none",
            }}
          >
            <span style={{ fontFamily: "var(--font-body)", fontSize: 14.5, color: "var(--color-text-primary)" }}>{next.title}</span>
            <span style={{ fontFamily: "var(--font-mono)", fontSize: 10.5, letterSpacing: "0.1em", color: "var(--color-text-muted)" }}>NEXT →</span>
          </Link>
        )}
      </div>
    </section>
  );
}

// ─── Related Topics ───────────────────────────────────────────────────────────

function RelatedTopics({ slugs }: { slugs: string[] }) {
  const valid = slugs.filter((s) => !!TOPICS[s]);
  if (valid.length === 0) return null;

  return (
    <section aria-label="Related Topics" style={{ marginTop: 48 }}>
      <div style={{ borderTop: "1px solid rgba(0,212,255,0.12)", paddingTop: 28, marginBottom: 20 }}>
        <span
          style={{
            fontFamily: "var(--font-mono)",
            fontSize: 10,
            letterSpacing: "0.2em",
            textTransform: "uppercase",
            color: "var(--color-text-muted)",
          }}
        >
          Related Topics
        </span>
      </div>
      <div style={{ display: "flex", flexDirection: "column" }}>
        {valid.map((s) => (
          <TopicLink key={s} slug={s} variant="card" />
        ))}
      </div>
    </section>
  );
}

// ─── Main ArticlePage ─────────────────────────────────────────────────────────

export default function ArticlePage({
  slug,
  prevSlug,
  nextSlug,
  relatedSlugs,
  headings,
  readingTimeMinutes,
  children,
}: ArticlePageProps) {
  const topic = TOPICS[slug];
  if (!topic) return null;

  return (
    <>
      <ReadingProgressBar />

      <div style={{ minHeight: "100vh", background: "var(--color-void)", paddingTop: 80 }}>
        <div style={{ maxWidth: 1180, margin: "0 auto", padding: "40px 24px 96px" }}>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "180px minmax(0, 700px) 1fr",
              gap: "0 48px",
              alignItems: "start",
            }}
            className="article-layout"
          >
            {/* ── LEFT: Sticky TOC ── */}
            <aside aria-label="Article navigation" className="hidden lg:block">
              <TableOfContents headings={headings} />
            </aside>

            {/* ── CENTER: Article content ── */}
            <main id="article-content" style={{ minWidth: 0 }}>
              <Breadcrumbs topic={topic} />

              <ArticleHero topic={topic} readingTimeMinutes={readingTimeMinutes} />

              <div className="lg:hidden">
                <TableOfContents headings={headings} />
              </div>

              <article
                className="btt-article-content"
                style={{
                  fontFamily: "var(--font-body)",
                  fontSize: 17,
                  lineHeight: 1.85,
                  color: "var(--color-text-secondary)",
                  textRendering: "optimizeLegibility",
                }}
              >
                {children}
              </article>

              <ContinueLearning prevSlug={prevSlug} nextSlug={nextSlug} />
              <RelatedTopics slugs={relatedSlugs} />
            </main>

            {/* ── RIGHT: breathing gutter (empty on purpose, matches reference's wide margins) ── */}
            <div aria-hidden="true" />
          </div>
        </div>
      </div>

      <style>{`
        @media (max-width: 1023px) {
          .article-layout {
            grid-template-columns: 1fr !important;
          }
        }

        .btt-article-content h1,
        .btt-article-content h2,
        .btt-article-content h3,
        .btt-article-content h4 {
          scroll-margin-top: 104px;
        }

        .btt-article-content h2 {
          position: relative;
          font-family: var(--font-display);
          font-size: clamp(1.5rem, 2.4vw, 1.9rem);
          letter-spacing: 0.02em;
          line-height: 1.25;
          color: var(--color-text-primary);
          margin-top: 64px;
          margin-bottom: 24px;
        }
        .btt-article-content h2:first-child {
          margin-top: 0;
        }

        .btt-article-content h3 {
          position: relative;
          padding-left: 16px;
          font-family: var(--font-body);
          font-size: 1.15rem;
          font-weight: 600;
          line-height: 1.4;
          color: var(--color-text-primary);
          margin-top: 40px;
          margin-bottom: 16px;
        }
        .btt-article-content h3::before {
          content: "";
          position: absolute;
          left: 0;
          top: 0.2em;
          bottom: 0.2em;
          width: 2px;
          background: var(--color-neon-blue);
          opacity: 0.5;
          border-radius: 1px;
        }

        .btt-article-content p {
          max-width: 70ch;
          margin-bottom: 22px;
          text-wrap: pretty;
        }

        .btt-article-content strong {
          color: var(--color-text-primary);
          font-weight: 600;
        }

        .btt-article-content blockquote {
          position: relative;
          max-width: 68ch;
          margin: 36px 0;
          padding: 4px 0 4px 28px;
          border-left: 2px solid var(--color-neon-blue);
          font-family: var(--font-display);
          font-size: 1.15rem;
          font-style: normal;
          line-height: 1.5;
          color: var(--color-text-primary);
        }

        .btt-article-content ul,
        .btt-article-content ol {
          margin-bottom: 22px;
          padding-left: 22px;
        }
        .btt-article-content ul li,
        .btt-article-content ol li {
          padding-left: 4px;
          margin-bottom: 8px;
          line-height: 1.7;
        }

        .btt-article-content hr {
          position: relative;
          height: 1px;
          margin: 48px 0;
          background: linear-gradient(90deg, transparent, rgba(0,212,255,0.18) 50%, transparent);
          overflow: visible;
          border: none;
        }
        .btt-article-content hr::after {
          content: "";
          position: absolute;
          top: 50%;
          left: 50%;
          width: 5px;
          height: 5px;
          background: var(--color-neon-blue);
          opacity: 0.45;
          transform: translate(-50%, -50%) rotate(45deg);
        }

        .btt-article-content ::selection {
          background: rgba(0,212,255,0.25);
          color: var(--color-text-primary);
        }

        .btt-article-content img {
          width: 100%;
          border-radius: 10px;
          border: 1px solid rgba(0,212,255,0.12);
          margin: 28px 0 8px;
        }
      `}</style>
    </>
  );
}
