import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "what-is-lps",             text: "What is Lightning Protection System (LPS)?",  level: 1 },
  { id: "why-dc-needs-lps",        text: "Why Data Centers Need Lightning Protection",  level: 1 },
  { id: "direct-vs-induced",       text: "Direct Strike vs Induced Surge",              level: 1 },
  { id: "risk-assessment",         text: "Lightning Risk Assessment",                   level: 1 },
  { id: "protection-levels",       text: "IEC 62305 Protection Levels (LPL I–IV)",      level: 1 },
  { id: "air-termination",         text: "Air Termination",                             level: 1 },
  { id: "down-conductors",         text: "Down Conductors",                             level: 1 },
  { id: "earth-termination",       text: "Earth Termination",                           level: 1 },
  { id: "bonding",                 text: "Bonding",                                     level: 1 },
  { id: "spd",                     text: "Surge Protection Devices (SPD)",              level: 1 },
  { id: "dc-lightning-path",       text: "Typical Data Center Lightning Path",          level: 1 },
  { id: "external-lps",            text: "External LPS",                                level: 1 },
  { id: "internal-lps",            text: "Internal LPS",                                level: 1 },
  { id: "equipotential-bonding",   text: "Equipotential Bonding",                       level: 1 },
  { id: "lps-vs-earthing",         text: "Lightning Protection vs Earthing",            level: 1 },
  { id: "lps-vs-surge",            text: "Lightning Protection vs Surge Protection",    level: 1 },
  { id: "inspection-maintenance",  text: "Inspection & Maintenance",                    level: 1 },
  { id: "common-failures",         text: "Common Failures",                             level: 1 },
  { id: "testing",                 text: "Testing",                                     level: 1 },
  { id: "required-instruments",    text: "Required Instruments",                        level: 1 },
  { id: "oems",                    text: "OEMs",                                        level: 1 },
  { id: "standards",               text: "Relevant Standards",                          level: 1 },
  { id: "real-dc-example",         text: "Real Data Center Example",                    level: 1 },
  { id: "interview-questions",     text: "Common Interview Questions",                  level: 1 },
  { id: "key-takeaways",           text: "Key Takeaways",                               level: 1 },
];
