import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",          text: "Quick Summary — DR in 2 Minutes",                  level: 1 },
  { id: "dr-kya-hai",             text: "Disaster Recovery Kya Hai",                        level: 1 },
  { id: "disaster-vs-failure",    text: "Disaster vs Failure vs Outage vs Incident",        level: 1 },
  { id: "bcp-vs-dr",              text: "Business Continuity vs DR",                        level: 1 },
  { id: "backup-vs-dr",           text: "Backup vs DR",                                     level: 1 },
  { id: "ha-vs-dr",               text: "HA vs DR",                                         level: 1 },
  { id: "fault-tolerance",        text: "Fault Tolerance vs HA vs DR",                     level: 1 },
  { id: "dr-terminology",         text: "DR Terminology",                                   level: 1 },
  { id: "rpo-deep",               text: "RPO — Deep Explanation",                           level: 1 },
  { id: "rto-deep",               text: "RTO — Deep Explanation",                           level: 1 },
  { id: "rpo-vs-rto",             text: "RPO vs RTO Comparison",                            level: 1 },
  { id: "mtd-wrt",                text: "MTD / MAO aur WRT",                                level: 1 },
  { id: "bia",                    text: "Business Impact Analysis (BIA)",                   level: 1 },
  { id: "risk-vs-bia",            text: "Risk Assessment vs BIA",                           level: 1 },
  { id: "app-tiers",              text: "Application Criticality / Recovery Tiers",         level: 1 },
  { id: "site-types",             text: "Hot vs Warm vs Cold DR Sites",                     level: 1 },
  { id: "active-active",          text: "Active-Active DR",                                 level: 1 },
  { id: "active-passive",         text: "Active-Passive DR",                                level: 1 },
  { id: "pilot-light",            text: "Pilot Light",                                      level: 1 },
  { id: "warm-standby",           text: "Warm Standby",                                     level: 1 },
  { id: "backup-restore-dr",      text: "Backup-and-Restore DR Model",                      level: 1 },
  { id: "sync-replication",       text: "Synchronous Replication",                          level: 1 },
  { id: "async-replication",      text: "Asynchronous Replication",                         level: 1 },
  { id: "sync-vs-async",          text: "Sync vs Async Comparison",                         level: 1 },
  { id: "storage-replication",    text: "Storage Replication for DR",                       level: 1 },
  { id: "vmware-dr",              text: "VMware DR",                                        level: 1 },
  { id: "hyperv-dr",              text: "Hyper-V DR",                                       level: 1 },
  { id: "physical-dr",            text: "Physical Server / Bare-Metal DR",                  level: 1 },
  { id: "cloud-dr",               text: "Cloud DR",                                         level: 1 },
  { id: "hybrid-dr",              text: "Hybrid DR",                                        level: 1 },
  { id: "network-dr",             text: "Network DR Architecture",                          level: 1 },
  { id: "dns-ttl",                text: "DNS Failover aur TTL",                             level: 1 },
  { id: "load-balancer-dr",       text: "Load Balancer / Global Traffic Manager",           level: 1 },
  { id: "firewall-dr",            text: "Firewall DR",                                      level: 1 },
  { id: "identity-dr",            text: "Identity / Authentication DR",                     level: 1 },
  { id: "database-dr",            text: "Database DR",                                      level: 1 },
  { id: "storage-dr",             text: "Storage DR",                                       level: 1 },
  { id: "backup-role-in-dr",      text: "Backup Ka Role in DR",                             level: 1 },
  { id: "ransomware-dr",          text: "Ransomware aur DR",                                level: 1 },
  { id: "clean-room",             text: "Clean Room / Isolated Recovery",                   level: 1 },
  { id: "dr-architecture",        text: "Complete Primary → DR Site Architecture",          level: 1 },
  { id: "dependency-mapping",     text: "Dependency Mapping",                               level: 1 },
  { id: "recovery-sequence",      text: "Correct Recovery Sequence",                        level: 1 },
  { id: "disaster-declaration",   text: "Disaster Declaration",                             level: 1 },
  { id: "dr-runbook",             text: "DR Runbook",                                       level: 1 },
  { id: "dr-plan-vs-runbook",     text: "DR Plan vs Runbook",                               level: 1 },
  { id: "dr-testing",             text: "DR Testing",                                       level: 1 },
  { id: "dr-drill",               text: "DR Drill",                                         level: 1 },
  { id: "planned-vs-emergency",   text: "Planned Switchover vs Emergency Failover",         level: 1 },
  { id: "failback",               text: "Failback",                                         level: 1 },
  { id: "split-brain",            text: "Split-Brain",                                      level: 1 },
  { id: "recovery-validation",    text: "Recovery Validation",                              level: 1 },
  { id: "dr-orchestration",       text: "DR Orchestration",                                 level: 1 },
  { id: "dr-monitoring",          text: "DR Monitoring",                                    level: 1 },
  { id: "dr-capacity",            text: "DR Capacity Planning",                             level: 1 },
  { id: "dr-security",            text: "DR Security",                                      level: 1 },
  { id: "dr-documentation",       text: "Documentation aur Change Management",              level: 1 },
  { id: "firmware-compat",        text: "Firmware / Software Compatibility",                level: 1 },
  { id: "license-cert",           text: "License / Certificate Dependencies",               level: 1 },
  { id: "third-party-deps",       text: "Third-Party Dependencies",                         level: 1 },
  { id: "failure-scenarios",      text: "Common DR Failure Scenarios",                      level: 1 },
  { id: "troubleshoot-layers",    text: "Layer-by-Layer DR Troubleshooting",                level: 1 },
  { id: "production-incidents",   text: "Real Production Incidents",                        level: 1 },
  { id: "dangerous-mistakes",     text: "Dangerous DR Mistakes",                            level: 1 },
  { id: "om-checklist",           text: "DR O&M Checklist",                                 level: 1 },
  { id: "preventive-maintenance", text: "Preventive Maintenance",                           level: 1 },
  { id: "oem-escalation",         text: "OEM / Vendor Escalation Data",                     level: 1 },
  { id: "dr-audit",               text: "DR Audit Evidence",                                level: 1 },
  { id: "dr-metrics",             text: "DR Metrics / KPIs",                                level: 1 },
  { id: "maturity-model",         text: "DR Maturity Model",                                level: 1 },
  { id: "enterprise-example",     text: "Complete Enterprise DR Design Example",            level: 1 },
  { id: "design-checklist",       text: "DR Design Checklist",                              level: 1 },
  { id: "interview-questions",    text: "Interview / Job Knowledge",                        level: 1 },
  { id: "key-takeaways",          text: "Key Takeaways",                                    level: 1 },
];
