// ─── BTT Retrieval Engine ─────────────────────────────────────────────────────
//
// Source of truth: topics.ts (live, always available)
// Full-text layer: lib/article-index.json (generated at build time via
//   scripts/build-article-index.ts — graceful fallback if absent)
//
// Scales to 1000+ articles with zero manual maintenance.
// ─────────────────────────────────────────────────────────────────────────────

import {
  ALL_TOPICS,
  PUBLISHED_TOPICS,
  TOPICS,
  getNextTopic,
  type Topic,
  type Track,
  type TopicCategory,
} from "@/lib/topics";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ArticleContent {
  slug: string;
  headings: string[];
  bodyText: string;
  faqs: Array<{ q: string; a: string }>;
}

export interface ArticleRef {
  slug: string;
  title: string;
  track: string;
  category: string;
  description: string;
}

export interface RetrievedTopic {
  slug: string;
  title: string;
  track: string;
  category: string;
  description: string;
  breadcrumb: string[];
  related: string[];
  status: string;
  content: ArticleContent | undefined;
  score: number;
}

export interface RetrieveOptions {
  currentSlug?: string;
  currentHeading?: string;
  limit?: number;
}

interface ScoredTopic {
  topic: Topic;
  score: number;
}

// ─── Full-text index (optional build artifact) ────────────────────────────────
// Generated by: npm run build:index (scripts/build-article-index.ts)
// Falls back to metadata-only mode if the file doesn't exist yet.

function loadArticleIndex(): Record<string, ArticleContent> {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require("@/lib/article-index.json") as Record<string, ArticleContent>;
  } catch {
    return {};
  }
}

const ARTICLE_INDEX: Record<string, ArticleContent> = loadArticleIndex();

// ─── Stop-word filter ─────────────────────────────────────────────────────────

const STOPWORDS = new Set<string>([
  "the", "a", "an", "is", "are", "of", "in", "on", "to", "and", "or",
  "what", "how", "kya", "hai", "ka", "ki", "ke", "me", "mein", "kaise",
  "kaun", "ko", "se", "ek", "do", "vs", "for", "with", "this", "that",
  "it", "i", "you", "be", "was", "were", "at", "by", "from", "as",
]);

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, " ")
    .split(/\s+/)
    .filter((t) => t.length > 1 && !STOPWORDS.has(t));
}

// ─── Topic scoring ────────────────────────────────────────────────────────────

function scoreTopic(
  topic: Topic,
  queryTokens: string[],
  queryRaw: string
): number {
  let score = 0;

  const title = topic.title.toLowerCase();
  const slug = topic.slug;
  const desc = topic.description.toLowerCase();
  const crumb = topic.breadcrumb.join(" ").toLowerCase();
  const cat = String(topic.category).toLowerCase();
  const slugWords = slug.split("-");

  // Strong exact-phrase signals
  if (queryRaw.includes(slug.replace(/-/g, " "))) score += 12;
  if (queryRaw.includes(title))                   score += 10;

  for (const tok of queryTokens) {
    if (slugWords.includes(tok))                       score += 6;
    if (title.split(/\s+/).includes(tok))              score += 5;
    else if (title.includes(tok))                      score += 3;
    if (desc.includes(tok))                            score += 2;
    if (crumb.includes(tok))                           score += 1.5;
    if (cat.includes(tok))                             score += 1.5;
  }

  // Full-text bonus when build index is present
  const fc = ARTICLE_INDEX[topic.slug];
  if (fc) {
    const bodyLow = fc.bodyText.toLowerCase();
    const headLow = fc.headings.join(" ").toLowerCase();
    for (const tok of queryTokens) {
      if (headLow.includes(tok)) score += 4;
      const hits = bodyLow.split(tok).length - 1;
      score += Math.min(hits, 5) * 0.5;
    }
  }

  return score;
}

// ─── Retrieve ─────────────────────────────────────────────────────────────────

export function retrieve(
  query: string,
  opts: RetrieveOptions = {}
): RetrievedTopic[] {
  const { currentSlug, currentHeading, limit = 3 } = opts;
  const queryTokens = tokenize(query);
  const queryRaw = query.toLowerCase();

  // Score every published topic
  const scored: ScoredTopic[] = PUBLISHED_TOPICS.map(
    (topic: Topic): ScoredTopic => ({
      topic,
      score: scoreTopic(topic, queryTokens, queryRaw),
    })
  );

  // Boost the article the user is currently reading (article-awareness)
  if (currentSlug) {
    const idx = scored.findIndex((s) => s.topic.slug === currentSlug);
    if (idx >= 0) scored[idx].score += 8;
  }

  let top = scored
    .filter((s: ScoredTopic) => s.score > 0)
    .sort((a: ScoredTopic, b: ScoredTopic) => b.score - a.score)
    .slice(0, limit);

  // Guarantee the current article is always in context
  if (
    currentSlug &&
    TOPICS[currentSlug] &&
    !top.some((s) => s.topic.slug === currentSlug)
  ) {
    top = [{ topic: TOPICS[currentSlug], score: 8 }, ...top].slice(0, limit);
  }

  return top.map(({ topic, score }): RetrievedTopic => ({
    slug: topic.slug,
    title: topic.title,
    track: String(topic.track),
    category: String(topic.category),
    description: topic.description,
    breadcrumb: topic.breadcrumb,
    related: topic.related,
    status: topic.status,
    content: ARTICLE_INDEX[topic.slug],
    score,
  }));
}

// ─── Context builder ──────────────────────────────────────────────────────────

export function buildContext(
  topics: RetrievedTopic[],
  currentHeading?: string
): string {
  if (topics.length === 0) return "";

  const blocks = topics.map((t: RetrievedTopic): string => {
    const lines: string[] = [
      `ARTICLE: "${t.title}" (slug: ${t.slug})`,
      `Path: ${t.breadcrumb.join(" → ")}`,
      `Description: ${t.description}`,
    ];

    if (currentHeading && t.slug === topics[0].slug) {
      lines.push(`User is reading section: "${currentHeading}"`);
    }

    if (t.content) {
      if (t.content.headings.length > 0) {
        lines.push(`Sections: ${t.content.headings.join(" · ")}`);
      }
      if (t.content.bodyText) {
        const excerpt = t.content.bodyText.slice(0, 1600);
        const suffix = t.content.bodyText.length > 1600 ? "\n[...content continues in full article]" : "";
        lines.push(`Content:\n${excerpt}${suffix}`);
      }
      const faqs = t.content.faqs.slice(0, 4);
      if (faqs.length > 0) {
        const faqText = faqs
          .map((f: { q: string; a: string }) => `Q: ${f.q}\nA: ${f.a}`)
          .join("\n");
        lines.push(`FAQs:\n${faqText}`);
      }
    }

    if (t.related.length > 0) {
      lines.push(`Related: ${t.related.join(", ")}`);
    }

    return lines.join("\n");
  });

  return (
    "\n─── RELEVANT BTT ARTICLES (use these first) ───\n" +
    blocks.join("\n\n") +
    "\n────────────────────────────────────────────────\n"
  );
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function toRef(topic: Topic): ArticleRef {
  return {
    slug: topic.slug,
    title: topic.title,
    track: String(topic.track),
    category: String(topic.category),
    description: topic.description,
  };
}

export function getRelated(slugs: string[], limit = 4): ArticleRef[] {
  const seen = new Set<string>();
  const refs: ArticleRef[] = [];

  for (const slug of slugs) {
    const t = TOPICS[slug];
    if (t && t.status === "published" && !seen.has(slug)) {
      seen.add(slug);
      refs.push(toRef(t));
    }
    if (refs.length >= limit) break;
  }
  return refs;
}

export function getContinueLearning(slug: string): ArticleRef | null {
  const next = getNextTopic(slug);
  return next && next.status === "published" ? toRef(next) : null;
}

export function buildSources(retrieved: RetrievedTopic[]): string[] {
  return retrieved
    .filter((r) => r.status === "published")
    .map((r) => r.title);
}

export function getLearningPath(
  track: Track = "non-it",
  category: TopicCategory = "electrical"
): ArticleRef[] {
  return ALL_TOPICS.filter(
    (t: Topic) => t.track === track && t.category === category
  )
    .sort((a: Topic, b: Topic) => a.order - b.order)
    .map(toRef);
}

export function allPublishedSlugs(): string[] {
  return PUBLISHED_TOPICS.map((t: Topic) => t.slug);
}

// ─── Follow-up question generator ────────────────────────────────────────────
// Derives smart follow-ups from topics.ts relationship graph.
// No extra API call, no hardcoding — scales automatically.

export function generateFollowUps(
  retrieved: RetrievedTopic[],
  userQuery: string
): string[] {
  const q = userQuery.toLowerCase();
  const covered = new Set(retrieved.map((r) => r.slug));
  const questions: string[] = [];

  // 1. Questions from related topics (strongest signal)
  const relatedSlugs = Array.from(
    new Set(retrieved.flatMap((r: RetrievedTopic) => r.related))
  );

  for (const slug of relatedSlugs) {
    if (covered.has(slug)) continue;
    const t = TOPICS[slug];
    if (t && t.status === "published") {
      questions.push(`${t.title} ke baare mein explain karo?`);
      covered.add(slug);
      if (questions.length >= 2) break;
    }
  }

  // 2. Next topic in learning path
  const primary = retrieved[0];
  if (primary) {
    const next = getNextTopic(primary.slug);
    if (next && next.status === "published" && !covered.has(next.slug)) {
      questions.push(`${next.title} kya hota hai?`);
    }
  }

  // 3. Mode-based follow-ups if still under 3
  if (questions.length < 3 && primary) {
    const title = primary.title;
    const hasCalc  = q.includes("calculat") || q.includes("formula");
    const hasFault = q.includes("fault") || q.includes("alarm") || q.includes("troubleshoot");

    if (!hasCalc)  questions.push(`${title} ke liye calculation kaise karte hain?`);
    if (!hasFault) questions.push(`${title} mein common faults aur troubleshooting?`);
  }

  return questions.slice(0, 3);
}
