import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "what-is-sts", text: "What is a Static Transfer Switch?", level: 1 },
  { id: "why-sts-required", text: "Why STS is Required", level: 1 },
  { id: "where-sts-installed", text: "Where STS is Installed", level: 1 },
  { id: "power-flow-architecture", text: "Power Flow Architecture", level: 1 },
  { id: "internal-construction", text: "Internal Construction", level: 1 },
  { id: "scr-thyristor-technology", text: "SCR / Thyristor Technology", level: 1 },
  { id: "static-switching-principle", text: "Static Switching Principle", level: 1 },
  { id: "transfer-logic", text: "Transfer Logic", level: 1 },
  { id: "source-priority", text: "Source Priority", level: 1 },
  { id: "synchronization-requirements", text: "Synchronization Requirements", level: 1 },
  { id: "transfer-time", text: "Transfer Time — 2 to 4 ms", level: 1 },
  { id: "break-free-transfer", text: "Break-Free Transfer", level: 1 },
  { id: "single-bus-vs-dual-bus", text: "Single Bus vs Dual Bus", level: 1 },
  { id: "dual-ups-architecture", text: "Dual UPS Architecture", level: 1 },
  { id: "ab-power-distribution", text: "A & B Power Distribution", level: 1 },
  { id: "maintenance-bypass", text: "Maintenance Bypass", level: 1 },
  { id: "failure-modes", text: "Failure Modes", level: 1 },
  { id: "common-alarms", text: "Common Alarms", level: 1 },
  { id: "testing-procedure", text: "Testing Procedure", level: 1 },
  { id: "preventive-maintenance", text: "Preventive Maintenance", level: 1 },
  { id: "oem-comparison", text: "OEM Comparison", level: 1 },
  { id: "sts-vs-ats", text: "STS vs ATS", level: 1 },
  { id: "sts-vs-ups", text: "STS vs UPS", level: 1 },
  { id: "standards", text: "Standards & Codes", level: 1 },
  { id: "real-dc-example", text: "Real Data Center Example", level: 1 },
  { id: "interview-questions", text: "Interview Questions", level: 1 },
  { id: "key-takeaways", text: "Key Takeaways", level: 1 },
];
