import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary", text: "Quick Summary", level: 1 },
  { id: "what-is-azure", text: "What Is Microsoft Azure?", level: 1 },
  { id: "azure-history", text: "History and Why Azure Exists", level: 2 },
  { id: "service-models", text: "IaaS, PaaS, SaaS on Azure", level: 2 },
  { id: "shared-responsibility", text: "Shared Responsibility Model", level: 2 },
  { id: "global-infrastructure", text: "Azure Global Infrastructure", level: 1 },
  { id: "regions", text: "Regions", level: 2 },
  { id: "availability-zones", text: "Availability Zones", level: 2 },
  { id: "region-pairs", text: "Region Pairs", level: 2 },
  { id: "edge-locations", text: "Edge Locations and Specialized Infrastructure", level: 2 },
  { id: "region-selection", text: "Region Selection Strategy", level: 2 },
  { id: "resource-management", text: "Azure Resource Management", level: 1 },
  { id: "arm", text: "Azure Resource Manager (ARM)", level: 2 },
  { id: "resource-groups", text: "Resource Groups", level: 2 },
  { id: "subscriptions", text: "Subscriptions", level: 2 },
  { id: "management-groups", text: "Management Groups", level: 2 },
  { id: "azure-portal-cli", text: "Portal, CLI and PowerShell", level: 2 },
  { id: "identity", text: "Identity — Microsoft Entra ID and RBAC", level: 1 },
  { id: "entra-id", text: "Microsoft Entra ID", level: 2 },
  { id: "rbac", text: "Azure RBAC", level: 2 },
  { id: "managed-identity", text: "Managed Identity", level: 2 },
  { id: "hybrid-identity", text: "Hybrid Identity", level: 2 },
  { id: "networking", text: "Azure Networking", level: 1 },
  { id: "vnet", text: "Azure Virtual Network (VNet)", level: 2 },
  { id: "subnets-nsg", text: "Subnets and NSG", level: 2 },
  { id: "routing", text: "Route Tables and UDR", level: 2 },
  { id: "vnet-peering", text: "VNet Peering and Service Endpoints", level: 2 },
  { id: "private-link", text: "Private Link and Private Endpoints", level: 2 },
  { id: "load-balancing", text: "Load Balancing and Application Delivery", level: 1 },
  { id: "azure-lb", text: "Azure Load Balancer (L4)", level: 2 },
  { id: "application-gateway", text: "Application Gateway (L7)", level: 2 },
  { id: "front-door", text: "Azure Front Door and Traffic Manager", level: 2 },
  { id: "firewall", text: "Azure Firewall", level: 2 },
  { id: "connectivity", text: "Hybrid Connectivity", level: 1 },
  { id: "vpn-gateway", text: "Azure VPN Gateway", level: 2 },
  { id: "expressroute", text: "Azure ExpressRoute", level: 2 },
  { id: "virtual-wan", text: "Azure Virtual WAN", level: 2 },
  { id: "compute", text: "Azure Compute", level: 1 },
  { id: "azure-vms", text: "Azure Virtual Machines", level: 2 },
  { id: "vm-availability", text: "VM Availability: Sets, Zones, VMSS", level: 2 },
  { id: "app-service", text: "Azure App Service (PaaS)", level: 2 },
  { id: "aks", text: "Azure Kubernetes Service (AKS)", level: 2 },
  { id: "azure-functions", text: "Azure Functions (Serverless)", level: 2 },
  { id: "container-apps", text: "Azure Container Instances and Container Apps", level: 2 },
  { id: "storage", text: "Azure Storage", level: 1 },
  { id: "blob-storage", text: "Blob Storage", level: 2 },
  { id: "azure-files", text: "Azure Files", level: 2 },
  { id: "queue-table", text: "Queue Storage and Table Storage", level: 2 },
  { id: "managed-disks", text: "Managed Disks", level: 2 },
  { id: "storage-advanced", text: "Data Lake, NetApp Files and File Sync", level: 2 },
  { id: "databases", text: "Databases", level: 1 },
  { id: "azure-sql", text: "Azure SQL Database", level: 2 },
  { id: "cosmos-db", text: "Azure Cosmos DB", level: 2 },
  { id: "other-databases", text: "Other Managed Databases", level: 2 },
  { id: "high-availability", text: "High Availability", level: 1 },
  { id: "ha-options", text: "Availability Sets vs Availability Zones", level: 2 },
  { id: "zone-redundant", text: "Zone-Redundant Services", level: 2 },
  { id: "disaster-recovery", text: "Disaster Recovery", level: 1 },
  { id: "azure-site-recovery", text: "Azure Site Recovery (ASR)", level: 2 },
  { id: "backup", text: "Azure Backup", level: 2 },
  { id: "dr-patterns", text: "DR Patterns", level: 2 },
  { id: "monitoring", text: "Monitoring and Observability", level: 1 },
  { id: "azure-monitor", text: "Azure Monitor", level: 2 },
  { id: "log-analytics", text: "Log Analytics and KQL", level: 2 },
  { id: "defender-cloud", text: "Microsoft Defender for Cloud", level: 2 },
  { id: "security", text: "Azure Security Services", level: 1 },
  { id: "key-vault", text: "Azure Key Vault", level: 2 },
  { id: "azure-sentinel", text: "Microsoft Sentinel (SIEM/SOAR)", level: 2 },
  { id: "ddos-waf", text: "DDoS Protection and WAF", level: 2 },
  { id: "iac", text: "Infrastructure as Code on Azure", level: 1 },
  { id: "arm-templates", text: "ARM Templates and Bicep", level: 2 },
  { id: "terraform-azure", text: "Terraform on Azure", level: 2 },
  { id: "pricing", text: "Azure Pricing and Cost Management", level: 1 },
  { id: "pricing-model", text: "Pricing Model", level: 2 },
  { id: "cost-tools", text: "Cost Management Tools", level: 2 },
  { id: "azure-vs-aws", text: "Azure vs AWS", level: 1 },
  { id: "architecture-examples", text: "Architecture Examples", level: 1 },
  { id: "three-tier-azure", text: "Three-Tier Enterprise Application", level: 2 },
  { id: "hybrid-azure", text: "Hybrid DC to Azure", level: 2 },
  { id: "best-practices", text: "Best Practices", level: 1 },
  { id: "common-mistakes", text: "Common Engineering Mistakes", level: 1 },
  { id: "troubleshooting", text: "Troubleshooting", level: 1 },
  { id: "failure-scenarios", text: "Practical Failure Scenarios", level: 1 },
  { id: "certifications", text: "Azure Certifications and Career", level: 1 },
  { id: "key-takeaways", text: "Key Takeaways", level: 1 },
];
