import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",           text: "Quick Summary",                               level: 1 },
  { id: "who-should-read",         text: "Who Should Read This",                        level: 1 },
  { id: "what-you-will-learn",     text: "What You Will Learn",                         level: 1 },
  { id: "learning-path",           text: "Learning Path",                               level: 1 },
  { id: "introduction",            text: "Introduction",                                level: 1 },
  { id: "what-is-dl",              text: "What is Deep Learning?",                      level: 1 },
  { id: "why-dl-exists",           text: "Why Deep Learning Exists",                    level: 1 },
  { id: "history",                 text: "History and Evolution",                       level: 1 },
  { id: "neural-networks",         text: "Artificial Neural Networks",                  level: 1 },
  { id: "neuron",                  text: "Neuron, Weights, Bias",                       level: 2 },
  { id: "activation-functions",    text: "Activation Functions",                        level: 2 },
  { id: "hidden-layers",           text: "Hidden Layers",                               level: 2 },
  { id: "forward-propagation",     text: "Forward Propagation",                         level: 1 },
  { id: "loss-function",           text: "Loss Function",                               level: 1 },
  { id: "backpropagation",         text: "Backpropagation",                             level: 1 },
  { id: "gradient-descent",        text: "Gradient Descent and Optimizers",             level: 1 },
  { id: "training-process",        text: "Training Process — End to End",               level: 1 },
  { id: "architectures",           text: "Deep Learning Architectures",                 level: 1 },
  { id: "cnn",                     text: "CNN — Convolutional Neural Networks",         level: 2 },
  { id: "rnn",                     text: "RNN and LSTM",                                level: 2 },
  { id: "transformers",            text: "Transformers",                                level: 2 },
  { id: "attention",               text: "Attention Mechanism",                         level: 1 },
  { id: "embeddings",              text: "Embeddings",                                  level: 1 },
  { id: "transfer-learning",       text: "Transfer Learning",                           level: 1 },
  { id: "fine-tuning",             text: "Fine-Tuning and Foundation Models",           level: 1 },
  { id: "inference-process",       text: "Inference Process",                           level: 1 },
  { id: "dl-frameworks",           text: "Deep Learning Frameworks",                    level: 1 },
  { id: "cuda-stack",              text: "CUDA Software Stack",                         level: 1 },
  { id: "dl-libraries",            text: "Deep Learning Libraries",                     level: 1 },
  { id: "gpu-acceleration",        text: "GPU Acceleration",                            level: 1 },
  { id: "gpu-memory-hierarchy",    text: "GPU Memory Hierarchy",                        level: 2 },
  { id: "gpu-utilization",         text: "GPU Utilization and Occupancy",               level: 2 },
  { id: "ai-accelerators",         text: "AI Accelerator Comparison",                   level: 1 },
  { id: "nvidia-ecosystem",        text: "NVIDIA AI Software Ecosystem",                level: 2 },
  { id: "amd-stack",               text: "AMD AI Stack",                                level: 2 },
  { id: "intel-stack",             text: "Intel AI Stack and TPU",                      level: 2 },
  { id: "distributed-training",    text: "Distributed Training",                        level: 1 },
  { id: "multi-gpu-topology",      text: "Multi-GPU Topology Comparison",               level: 2 },
  { id: "memory-optimization",     text: "Memory Optimization Techniques",              level: 1 },
  { id: "training-cluster",        text: "AI Training Cluster Architecture",            level: 1 },
  { id: "dl-infrastructure",       text: "Deep Learning Infrastructure",                level: 1 },
  { id: "ai-storage",              text: "AI Storage — IOPS, Throughput, Filesystems",  level: 2 },
  { id: "networking",              text: "Networking Requirements",                      level: 2 },
  { id: "power-cooling",           text: "Power and Cooling",                           level: 2 },
  { id: "dl-benchmarks",           text: "Deep Learning Benchmarks",                    level: 1 },
  { id: "training-cost",           text: "Training Cost Analysis",                      level: 1 },
  { id: "enterprise-deployment",   text: "Enterprise Deployment",                       level: 1 },
  { id: "kubernetes-ai",           text: "Kubernetes, Kubeflow and KServe",             level: 2 },
  { id: "production-pipeline",     text: "Production Pipeline",                         level: 1 },
  { id: "inference-infra",         text: "Inference Infrastructure",                    level: 2 },
  { id: "monitoring",              text: "Monitoring — DCGM, Prometheus, Grafana",      level: 1 },
  { id: "model-drift",             text: "Model Drift and Retraining",                  level: 2 },
  { id: "security",                text: "Security Considerations",                     level: 1 },
  { id: "responsible-ai",          text: "Responsible AI and Explainability",           level: 1 },
  { id: "advantages",              text: "Advantages",                                  level: 1 },
  { id: "limitations",             text: "Limitations",                                 level: 1 },
  { id: "best-practices",          text: "Best Practices",                              level: 1 },
  { id: "common-mistakes",         text: "Common Mistakes",                             level: 1 },
  { id: "industry-use-cases",      text: "Industry Use Cases",                          level: 1 },
  { id: "comparison-tables",       text: "Comparison Tables",                           level: 1 },
  { id: "case-studies",            text: "Case Studies",                                level: 1 },
  { id: "troubleshooting",         text: "Troubleshooting",                             level: 1 },
  { id: "interview-questions",     text: "Interview Questions",                         level: 1 },
  { id: "glossary",                text: "Glossary",                                    level: 1 },
  { id: "ai-learning-path",        text: "BTT AI Learning Path",                        level: 1 },
  { id: "key-takeaways",           text: "Key Takeaways",                               level: 1 },
];
