import type { ArticleMetadata } from "@/types/engineering/content";

export const anthropicMetadata: ArticleMetadata = {
  slug: "anthropic",
  title: "Anthropic: Claude Models, API Platform, AI Safety and Infrastructure",
  seoTitle: "What Is Anthropic? Claude API, Constitutional AI, AWS Partnership",
  seoDescription:
    "A complete AI infrastructure guide to Anthropic — the Claude model family (Claude 3.5, Claude 3 Opus/Sonnet/Haiku), the API platform, Constitutional AI, the Amazon AWS partnership, training vs inference infrastructure, enterprise deployment, reliability, data privacy, and the data center perspective. For AI infrastructure engineers and DC professionals.",
  canonicalUrl: "https://behindthetech.in/learn/ai/platforms/anthropic",
  keywords: [
    "what is anthropic",
    "claude api platform infrastructure",
    "anthropic constitutional ai safety",
    "claude 3.5 sonnet haiku opus models",
    "anthropic amazon aws partnership",
    "anthropic training inference infrastructure",
    "claude api vs chatgpt api difference",
    "anthropic enterprise api",
    "ai safety alignment infrastructure",
    "claude context window tokens",
    "anthropic model serving scaling",
    "anthropic reliability availability",
    "claude data privacy security",
    "anthropic gpu compute requirements",
    "llm safety first infrastructure",
    "anthropic interpretability research",
    "claude api rate limits quotas",
    "anthropic data center cooling",
    "ai platforms comparison anthropic",
    "claude enterprise deployment",
  ],
  authorName: "Kumar Anil",
  datePublished: "2026-08-12",
  readingTimeMinutes: 50,
};
