import type { ArticleMetadata } from "@/types/engineering/content";

export const anthropicMetadata: ArticleMetadata = {
  slug: "anthropic",
  title: "Anthropic: Claude Models, API Platform, AI Safety and Infrastructure",
  seoTitle: "Anthropic Kya Hai? Claude API, Constitutional AI, AWS Partnership, Training vs Inference Infrastructure — Complete Hinglish Guide",
  seoDescription:
    "Anthropic ka complete AI infrastructure guide — Claude model family (Claude 3.5, Claude 3 Opus/Sonnet/Haiku), API platform, Constitutional AI, Amazon AWS partnership, training vs inference infrastructure, enterprise deployment, reliability, data privacy aur data center perspective. AI infrastructure engineers aur DC professionals ke liye.",
  canonicalUrl: "https://behindthetech.in/learn/ai/platforms/anthropic",
  keywords: [
    "anthropic kya hai hindi",
    "claude api platform infrastructure",
    "anthropic constitutional ai safety",
    "claude 3.5 sonnet haiku opus models",
    "anthropic amazon aws partnership",
    "anthropic training inference infrastructure",
    "claude api vs chatgpt api difference",
    "anthropic enterprise api",
    "ai safety alignment infrastructure",
    "claude context window tokens",
    "anthropic model serving scaling",
    "anthropic reliability availability",
    "claude data privacy security",
    "anthropic gpu compute requirements",
    "llm safety first infrastructure",
    "anthropic interpretability research",
    "claude api rate limits quotas",
    "anthropic data center cooling",
    "ai platforms comparison anthropic",
    "claude enterprise deployment",
  ],
  authorName: "Kumar Anil",
  datePublished: "2026-08-12",
  readingTimeMinutes: 50,
};
