import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",          text: "Quick Summary",                                          level: 1 },
  { id: "who-should-read",        text: "Who Should Read This",                                   level: 1 },
  { id: "what-is-gemini",         text: "What Is Google Gemini?",                                 level: 1 },
  { id: "model-family",           text: "Gemini Model Family",                                    level: 1 },
  { id: "ai-studio",              text: "Gemini API and Google AI Studio",                        level: 1 },
  { id: "vertex-ai",              text: "Gemini on Google Cloud Vertex AI",                       level: 1 },
  { id: "google-infra-overview",  text: "Google AI Infrastructure Overview",                      level: 1 },
  { id: "tpu-architecture",       text: "TPU Architecture",                                       level: 1 },
  { id: "tpu-generations",        text: "TPU Generations and Evolution",                          level: 1 },
  { id: "hbm",                    text: "HBM — High Bandwidth Memory",                            level: 1 },
  { id: "tpu-interconnect",       text: "TPU Interconnect and ICI",                               level: 1 },
  { id: "tpu-pods",               text: "TPU Pods and Scaling",                                   level: 1 },
  { id: "tpu-vs-gpu",             text: "TPU vs GPU — Data Center Perspective",                   level: 1 },
  { id: "training-infra",         text: "Gemini Training Infrastructure",                         level: 1 },
  { id: "inference-infra",        text: "Inference Infrastructure",                               level: 1 },
  { id: "training-vs-inference",  text: "Training vs Inference Comparison",                       level: 1 },
  { id: "networking",             text: "Networking and Distributed Training",                     level: 1 },
  { id: "storage",                text: "Storage and Checkpoints",                                level: 1 },
  { id: "power-density",          text: "AI Data Center Power and High-Density Racks",            level: 1 },
  { id: "cooling",                text: "Cooling and Thermal Management",                         level: 1 },
  { id: "liquid-cooling-chain",   text: "Liquid Cooling Chain",                                   level: 1 },
  { id: "monitoring",             text: "Monitoring",                                             level: 1 },
  { id: "failure-troubleshoot",   text: "Failure Scenarios and Troubleshooting",                  level: 1 },
  { id: "reliability",            text: "Reliability and Redundancy",                             level: 1 },
  { id: "enterprise",             text: "Enterprise Deployment",                                  level: 1 },
  { id: "privacy-security",       text: "Privacy and Security",                                   level: 1 },
  { id: "dc-perspective",         text: "Practical Data Center and O&M Perspective",              level: 1 },
  { id: "references",             text: "Technical References",                                   level: 1 },
  { id: "key-takeaways",          text: "Key Takeaways",                                          level: 1 },
];
