import type { ArticleMetadata } from "@/types/engineering/content";

export const mlMetadata: ArticleMetadata = {
  slug: "machine-learning",
  title: "Machine Learning — The Complete Engineering Guide",
  seoTitle: "What Is Machine Learning? Supervised, Unsupervised, ML Pipeline",
  seoDescription:
    "A complete engineering guide to Machine Learning — supervised learning, unsupervised learning, reinforcement learning, ML infrastructure, distributed training, MLOps, feature stores, model deployment, the enterprise ML pipeline, and industry examples. For DC engineers, IT engineers, and AI engineers.",
  canonicalUrl: "https://behindthetech.in/learn/ai/fundamentals/machine-learning",
  keywords: [
    "what is machine learning",
    "machine learning explained in hindi",
    "machine learning for beginners",
    "supervised unsupervised learning",
    "ml infrastructure",
    "mlops pipeline",
    "distributed training nccl",
    "feature store ml",
    "model deployment",
    "ml vs deep learning",
    "machine learning in data center",
    "enterprise ml pipeline",
    "gpu machine learning",
    "ml lifecycle",
    "pytorch tensorflow jax",
    "model optimization quantization",
    "ai governance responsible ai",
    "machine learning engineer jobs",
    "ml cost analysis",
    "sagemaker vertex ai azure ml",
  ],
  authorName: "Kumar Anil",
  datePublished: "2025-08-03",
  readingTimeMinutes: 65,
};
