import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",           text: "Quick Summary",                                     level: 1 },
  { id: "who-should-read",         text: "Who Should Read This",                              level: 1 },
  { id: "what-you-will-learn",     text: "What You Will Learn",                               level: 1 },
  { id: "learning-path",           text: "Learning Path",                                     level: 1 },
  { id: "introduction",            text: "Introduction",                                      level: 1 },
  { id: "why-accelerators-exist",  text: "Why AI Accelerators Exist",                         level: 1 },
  { id: "accelerator-landscape",   text: "The AI Accelerator Landscape",                      level: 1 },
  { id: "npu",                     text: "NPU — Neural Processing Unit",                      level: 1 },
  { id: "dpu",                     text: "DPU — Data Processing Unit",                        level: 1 },
  { id: "fpga-for-ai",             text: "FPGA for AI — The Reprogrammable Chip",             level: 1 },
  { id: "asic-for-ai",             text: "ASIC — Custom Silicon for AI",                      level: 1 },
  { id: "fpga-vs-asic",            text: "FPGA vs ASIC — When to Use Which",                  level: 1 },
  { id: "aws-trainium",            text: "AWS Trainium — Amazon's Training Chip",             level: 1 },
  { id: "aws-inferentia",          text: "AWS Inferentia — Amazon's Inference Chip",          level: 1 },
  { id: "intel-gaudi",             text: "Intel Gaudi — H100 Alternative",                    level: 1 },
  { id: "cerebras-wse",            text: "Cerebras WSE — The Wafer-Scale Engine",             level: 1 },
  { id: "graphcore-ipu",           text: "Graphcore IPU — A Different Architecture",          level: 1 },
  { id: "sambanova",               text: "SambaNova — Reconfigurable AI",                     level: 1 },
  { id: "edge-ai-chips",           text: "Edge AI Chips — NPUs in Your Pocket",               level: 1 },
  { id: "chip-comparison",         text: "Side-by-Side: All Major AI Chips",                  level: 1 },
  { id: "training-vs-inference",   text: "Training vs Inference — Different Hardware Needs",  level: 1 },
  { id: "custom-silicon-strategy", text: "Custom Silicon Strategy",                           level: 1 },
  { id: "dc-deployment",           text: "Data Center Deployment",                            level: 1 },
  { id: "power-cooling",           text: "Power and Cooling for AI Accelerators",             level: 1 },
  { id: "networking-storage",      text: "Networking and Storage",                            level: 1 },
  { id: "software-ecosystem",      text: "Software Ecosystems — CUDA vs the Rest",            level: 1 },
  { id: "cost-tco",                text: "Cost and TCO Analysis",                             level: 1 },
  { id: "selection-guide",         text: "Accelerator Selection Guide",                       level: 1 },
  { id: "troubleshooting",         text: "Troubleshooting AI Accelerator Issues",             level: 1 },
  { id: "future-trends",           text: "Future Trends",                                     level: 1 },
  { id: "interview-questions",     text: "Interview Questions",                               level: 1 },
  { id: "glossary",                text: "Glossary",                                          level: 1 },
  { id: "key-takeaways",           text: "Key Takeaways",                                     level: 1 },
];
