import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary", text: "Quick Summary", level: 1 },
  { id: "what-is-aws", text: "What Is AWS?", level: 1 },
  { id: "service-models", text: "IaaS, PaaS, SaaS", level: 2 },
  { id: "shared-responsibility", text: "Shared Responsibility Model", level: 2 },
  { id: "global-infrastructure", text: "AWS Global Infrastructure", level: 1 },
  { id: "regions", text: "Regions", level: 2 },
  { id: "availability-zones", text: "Availability Zones", level: 2 },
  { id: "failure-scope", text: "Failure Scope: Single vs Multi-AZ vs Multi-Region", level: 2 },
  { id: "edge-infrastructure", text: "Edge Locations, Local Zones and Outposts", level: 2 },
  { id: "region-selection", text: "Region Selection Strategy", level: 2 },
  { id: "vpc", text: "VPC — Core Network Foundation", level: 1 },
  { id: "vpc-concepts", text: "VPC, CIDR and Subnets", level: 2 },
  { id: "public-private-subnet", text: "Public vs Private Subnet", level: 2 },
  { id: "route-table", text: "Route Tables", level: 2 },
  { id: "vpc-advanced", text: "VPC Advanced: Endpoints, Peering, PrivateLink", level: 2 },
  { id: "cidr-planning", text: "CIDR Planning and Multi-VPC Design", level: 2 },
  { id: "igw-nat", text: "Internet Gateway and NAT Gateway", level: 1 },
  { id: "igw", text: "Internet Gateway", level: 2 },
  { id: "nat-gateway", text: "NAT Gateway", level: 2 },
  { id: "elastic-ip", text: "Elastic IP and ENI", level: 2 },
  { id: "security-group-nacl", text: "Security Group vs Network ACL", level: 1 },
  { id: "security-group", text: "Security Group", level: 2 },
  { id: "nacl", text: "Network ACL", level: 2 },
  { id: "sg-nacl-comparison", text: "Comparison and Common Mistakes", level: 2 },
  { id: "ec2", text: "EC2 — Compute", level: 1 },
  { id: "ec2-fundamentals", text: "Instance Fundamentals", level: 2 },
  { id: "ec2-families", text: "Instance Families and Purchasing Options", level: 2 },
  { id: "ec2-lifecycle", text: "Instance Lifecycle", level: 2 },
  { id: "ec2-advanced", text: "AMI, Launch Templates, Placement Groups", level: 2 },
  { id: "storage", text: "Storage — EBS, S3, EFS, FSx", level: 1 },
  { id: "ebs", text: "EBS — Block Storage", level: 2 },
  { id: "s3", text: "S3 — Object Storage", level: 2 },
  { id: "efs", text: "EFS — File Storage", level: 2 },
  { id: "storage-advanced", text: "FSx, Storage Gateway and Storage Classes", level: 2 },
  { id: "storage-comparison", text: "Storage Comparison", level: 2 },
  { id: "load-balancing", text: "Load Balancing", level: 1 },
  { id: "elb-types", text: "ALB, NLB and GWLB", level: 2 },
  { id: "target-groups", text: "Target Groups and Health Checks", level: 2 },
  { id: "auto-scaling", text: "Auto Scaling", level: 1 },
  { id: "asg", text: "Auto Scaling Group", level: 2 },
  { id: "dns-route53", text: "DNS — Route 53", level: 1 },
  { id: "iam", text: "IAM — Identity and Access Management", level: 1 },
  { id: "iam-concepts", text: "Users, Roles and Policies", level: 2 },
  { id: "iam-best-practices", text: "Roles vs Long-Lived Keys", level: 2 },
  { id: "iam-advanced", text: "Permission Boundaries, Organizations and SCP", level: 2 },
  { id: "high-availability", text: "High Availability Architecture", level: 1 },
  { id: "ha-vs-ft-dr", text: "HA vs Fault Tolerance vs Disaster Recovery", level: 2 },
  { id: "rds", text: "RDS — Managed Database", level: 1 },
  { id: "rds-multiaz", text: "Multi-AZ vs Read Replicas", level: 2 },
  { id: "aurora-dynamodb", text: "Aurora, DynamoDB and ElastiCache", level: 2 },
  { id: "dr-backup", text: "Backup and Disaster Recovery", level: 1 },
  { id: "observability", text: "Observability — CloudWatch and CloudTrail", level: 1 },
  { id: "observability-advanced", text: "VPC Flow Logs, EventBridge and X-Ray", level: 2 },
  { id: "hybrid-connectivity", text: "Hybrid — On-Prem to AWS", level: 1 },
  { id: "vpn-directconnect", text: "Site-to-Site VPN and Direct Connect", level: 2 },
  { id: "transit-gateway", text: "Transit Gateway and Hybrid DNS", level: 2 },
  { id: "containers", text: "Containers — ECS, EKS, Fargate", level: 1 },
  { id: "what-are-containers", text: "What Are Containers?", level: 2 },
  { id: "docker-fundamentals", text: "Docker Fundamentals", level: 2 },
  { id: "amazon-ecs", text: "Amazon ECS", level: 2 },
  { id: "amazon-eks", text: "Amazon EKS", level: 2 },
  { id: "aws-fargate", text: "AWS Fargate", level: 2 },
  { id: "container-networking", text: "Container Networking", level: 2 },
  { id: "container-use-cases", text: "Enterprise Container Use Cases", level: 2 },
  { id: "serverless", text: "Serverless — Lambda, API Gateway", level: 1 },
  { id: "lambda-execution", text: "Lambda Execution Model", level: 2 },
  { id: "cold-starts", text: "Cold Starts", level: 2 },
  { id: "api-gateway", text: "API Gateway", level: 2 },
  { id: "step-functions", text: "Step Functions", level: 2 },
  { id: "event-driven", text: "Event-Driven Architecture", level: 2 },
  { id: "serverless-use-cases", text: "Enterprise Serverless Use Cases", level: 2 },
  { id: "infrastructure-as-code", text: "Infrastructure as Code", level: 1 },
  { id: "iac-why", text: "Why Infrastructure as Code", level: 2 },
  { id: "cloudformation", text: "AWS CloudFormation", level: 2 },
  { id: "terraform", text: "Terraform", level: 2 },
  { id: "aws-cdk", text: "AWS CDK", level: 2 },
  { id: "iac-change-management", text: "IaC Change Management and Best Practices", level: 2 },
  { id: "migration", text: "Migration Strategies", level: 1 },
  { id: "migration-6r", text: "7 Rs Migration Framework", level: 2 },
  { id: "migration-hub", text: "AWS Migration Hub", level: 2 },
  { id: "application-migration-service", text: "AWS Application Migration Service", level: 2 },
  { id: "database-migration-service", text: "Database Migration Service", level: 2 },
  { id: "snowball", text: "AWS Snowball and Snowmobile", level: 2 },
  { id: "migration-workflow", text: "Enterprise Migration Workflow", level: 2 },
  { id: "security-advanced", text: "Security — Defense in Depth", level: 1 },
  { id: "kms", text: "AWS KMS", level: 2 },
  { id: "secrets-manager", text: "Secrets Manager", level: 2 },
  { id: "acm", text: "AWS Certificate Manager", level: 2 },
  { id: "guardduty", text: "Amazon GuardDuty", level: 2 },
  { id: "inspector", text: "Amazon Inspector", level: 2 },
  { id: "security-hub", text: "AWS Security Hub", level: 2 },
  { id: "waf-shield", text: "AWS WAF and Shield", level: 2 },
  { id: "cost-awareness", text: "Cost Optimization", level: 1 },
  { id: "cost-tools", text: "Cost Explorer, Budgets and Tools", level: 2 },
  { id: "well-architected", text: "AWS Well-Architected Framework", level: 1 },
  { id: "wa-operational-excellence", text: "Operational Excellence", level: 2 },
  { id: "wa-security", text: "Security", level: 2 },
  { id: "wa-reliability", text: "Reliability", level: 2 },
  { id: "wa-performance", text: "Performance Efficiency", level: 2 },
  { id: "wa-cost-optimization", text: "Cost Optimization", level: 2 },
  { id: "wa-sustainability", text: "Sustainability", level: 2 },
  { id: "architecture-examples", text: "Architecture Examples", level: 1 },
  { id: "small-web-app", text: "Small Web Application", level: 2 },
  { id: "three-tier", text: "Three-Tier Enterprise Application", level: 2 },
  { id: "highly-available-production", text: "Highly Available Production Architecture", level: 2 },
  { id: "multi-region-architecture", text: "Multi-Region Architecture", level: 2 },
  { id: "hybrid-dc-example", text: "Hybrid Data Center Integration", level: 2 },
  { id: "best-practices", text: "Operational Best Practices", level: 1 },
  { id: "common-mistakes", text: "Common Engineering Mistakes", level: 1 },
  { id: "troubleshooting", text: "Troubleshooting", level: 1 },
  { id: "ts-sequence", text: "Systematic Sequence", level: 2 },
  { id: "failure-scenarios", text: "Practical Failure Scenarios", level: 1 },
  { id: "final-architecture", text: "Final AWS Architecture", level: 1 },
  { id: "key-takeaways", text: "Key Takeaways", level: 1 },
];
