import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "backup-kya-hai",           text: "Backup Kya Hai — Definition",                          level: 1 },
  { id: "backup-vs-snapshot",       text: "Backup vs Snapshot",                                   level: 1 },
  { id: "backup-vs-replication",    text: "Backup vs Replication",                                level: 1 },
  { id: "backup-vs-archive",        text: "Backup vs Archive",                                    level: 1 },
  { id: "backup-vs-dr",             text: "Backup vs Disaster Recovery",                          level: 1 },
  { id: "rpo-rto",                  text: "RPO aur RTO — Deep Explanation",                       level: 1 },
  { id: "backup-architecture",      text: "Backup Architecture — Complete Enterprise View",       level: 1 },
  { id: "backup-types",             text: "Backup Types — Full, Incremental, Differential",       level: 1 },
  { id: "backup-window",            text: "Backup Window",                                        level: 1 },
  { id: "retention",                text: "Retention",                                            level: 1 },
  { id: "strategy-3-2-1",          text: "3-2-1 aur 3-2-1-1-0 Backup Strategy",                 level: 1 },
  { id: "air-gap",                  text: "Air Gap",                                              level: 1 },
  { id: "immutable-backup",         text: "Immutable Backup",                                     level: 1 },
  { id: "ransomware-resilient",     text: "Ransomware-Resilient Backup Architecture",             level: 1 },
  { id: "backup-encryption",        text: "Backup Encryption aur Key Management",                 level: 1 },
  { id: "compression-dedup",        text: "Backup Compression aur Deduplication",                level: 1 },
  { id: "app-consistent",          text: "Application-Consistent vs Crash-Consistent Backup",    level: 1 },
  { id: "vss",                      text: "Windows VSS — Volume Shadow Copy Service",             level: 1 },
  { id: "database-backup",          text: "Database Backup",                                      level: 1 },
  { id: "vm-backup",                text: "VM Backup",                                            level: 1 },
  { id: "vmware-backup",            text: "VMware Backup",                                        level: 1 },
  { id: "hyperv-backup",            text: "Hyper-V Backup",                                      level: 1 },
  { id: "physical-server-backup",   text: "Physical Server Backup",                              level: 1 },
  { id: "nas-backup",               text: "NAS Backup",                                          level: 1 },
  { id: "ndmp",                     text: "NDMP — Network Data Management Protocol",             level: 1 },
  { id: "san-backup",               text: "SAN Backup",                                          level: 1 },
  { id: "tape-backup",              text: "Tape Backup",                                         level: 1 },
  { id: "d2d-d2d2t",               text: "Disk-to-Disk, D2D2T aur Cloud",                       level: 1 },
  { id: "cloud-backup",             text: "Cloud Backup",                                        level: 1 },
  { id: "backup-copy",              text: "Backup Copy aur Secondary Copies",                    level: 1 },
  { id: "object-storage-backup",    text: "Object Storage Backup",                               level: 1 },
  { id: "backup-networking",        text: "Backup Networking",                                   level: 1 },
  { id: "backup-job-lifecycle",     text: "Backup Job Lifecycle",                                level: 1 },
  { id: "backup-verification",      text: "Backup Verification",                                 level: 1 },
  { id: "restore-types",            text: "Restore Types aur Workflows",                         level: 1 },
  { id: "restore-testing",          text: "Restore Testing",                                     level: 1 },
  { id: "instant-recovery",         text: "Instant Recovery",                                    level: 1 },
  { id: "backup-monitoring",        text: "Backup Monitoring",                                   level: 1 },
  { id: "capacity-planning",        text: "Backup Capacity Planning",                            level: 1 },
  { id: "performance-bottlenecks",  text: "Backup Performance Bottlenecks",                      level: 1 },
  { id: "backup-security",          text: "Backup Security",                                     level: 1 },
  { id: "failure-scenarios",        text: "Backup Failure Scenarios — Field Guide",              level: 1 },
  { id: "troubleshoot-layers",      text: "Backup Troubleshooting — Layer-by-Layer",             level: 1 },
  { id: "job-failed-flow",          text: "Backup Job Failed — Systematic Flow",                 level: 1 },
  { id: "production-incidents",     text: "Real Production Incidents",                           level: 1 },
  { id: "dangerous-mistakes",       text: "Dangerous Backup Mistakes",                           level: 1 },
  { id: "change-management",        text: "Backup Change Management",                            level: 1 },
  { id: "compatibility",            text: "Backup Software / Platform Compatibility",            level: 1 },
  { id: "enterprise-platforms",     text: "Enterprise Backup Platforms",                         level: 1 },
  { id: "oem-escalation",           text: "OEM / Vendor Escalation Data",                       level: 1 },
  { id: "om-checklist",             text: "Backup O&M Checklist",                               level: 1 },
  { id: "preventive-maintenance",   text: "Preventive Maintenance",                              level: 1 },
  { id: "backup-documentation",     text: "Backup Documentation",                               level: 1 },
  { id: "backup-migration",         text: "Backup Migration",                                   level: 1 },
  { id: "interview-questions",      text: "Interview / Job Knowledge",                           level: 1 },
  { id: "key-takeaways",            text: "Key Takeaways",                                       level: 1 },
];
