import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "SCADA — Supervisory Control and Data Acquisition Complete Guide | Behind The Tech",
  description: "SCADA kya hai, architecture, PLC/RTU/HMI, industrial protocols (Modbus/DNP3/IEC 61850/OPC UA), monitoring vs control, cybersecurity, data center applications — engineer-level Hinglish guide.",
  keywords: ["SCADA","supervisory control data acquisition","PLC RTU HMI","SCADA vs BMS","industrial protocols Modbus DNP3","SCADA cybersecurity","data center SCADA"],
  openGraph: { title: "SCADA — Supervisory Control and Data Acquisition", description: "SCADA architecture, PLC/RTU, protocols, control, historian, cybersecurity.", url: "https://behindthetech.in/learn/non-it/bms-dcim/scada", siteName: "Behind The Tech", type: "article", authors: ["Kumar Anil"] },
  twitter: { card: "summary_large_image", title: "SCADA Complete Guide — Behind The Tech", description: "SCADA for engineers — architecture, protocols, troubleshooting." },
  alternates: { canonical: "https://behindthetech.in/learn/non-it/bms-dcim/scada" },
};
export const faqs = [
  { q: "SCADA aur BMS mein kya fundamental difference hai?", a: "BMS (Building Management System) building M&E infrastructure monitor aur control karta hai — HVAC, electrical, environment — primarily building automation protocols (BACnet, Modbus) use karke. SCADA (Supervisory Control and Data Acquisition) industrial process control ke liye hai — oil refineries, power plants, water treatment, manufacturing. SCADA typically faster scan cycles, deterministic control, broader protocol range (DNP3, IEC 61850, OPC UA) aur stricter safety requirements hain. Data centers mein typically BMS use hota hai, na ki traditional SCADA — kuch hyperscale facilities SCADA-heritage platforms use karte hain custom automation ke liye." },
  { q: "PLC aur RTU mein kya difference hai?", a: "PLC (Programmable Logic Controller) primarily control logic execute karta hai — sequential aur continuous process control. Deterministic scan cycle, fast I/O response, complex program execution. Industrial manufacturing aur automation mein standard hai. RTU (Remote Terminal Unit) primarily remote site monitoring ke liye design hua tha — field data collect karo aur SCADA master ko bhejo. DNP3 ya other protocols support karta hai, often battery/solar powered remote sites pe use hota hai (utilities, pipeline monitoring). Modern RTUs PLCs ki capabilities overlap karti hain. Choice application, communication requirements aur environment pe depend karta hai." },
  { q: "SCADA mein historian kya hota hai?", a: "Historian ek specialized time-series database hai jo SCADA/control system se process variables ka historical record store karta hai — tagged data, timestamp ke saath. OSIsoft PI (now AVEVA PI) industrial historian ka de-facto standard tha — millions of tags, millions of samples per second handle karta hai. Historian se long-term trend analysis, performance reports, regulatory compliance evidence aur root cause investigation possible hoti hai. BMS aur DCIM platforms bhi internal historians use karte hain — industrial historian primarily large-scale process applications mein." },
  { q: "OPC UA kya hai aur SCADA mein kyun important hai?", a: "OPC UA (OPC Unified Architecture) ek open, vendor-neutral industrial communication standard hai — secure (TLS, certificate-based), platform-independent, semantically rich data model. SCADA, DCS, MES, ERP ke beech data exchange ke liye standard ban raha hai. Built-in security SCADA cybersecurity ke liye important hai — legacy protocols (OPC DA, DDE) security nahi karte. Data center mein SCADA-grade equipment (chillers, custom automation) BMS ya DCIM se OPC UA ke through integrate ho sakta hai where supported." },
  { q: "SCADA cybersecurity mein sabse important principle kya hai?", a: "Air gap ya network segmentation — OT (Operational Technology) network ko IT network aur internet se isolated rakhna. SCADA systems often legacy protocols aur OSes use karte hain jo cyber attacks ke against vulnerable hain. Key principles: network segmentation (OT/IT DMZ), unidirectional data diodes where applicable, regular patching (challenging for OT), role-based access, audit logging, remote access only via secure VPN/jump host, vendor access strictly controlled. IEC 62443 standard industrial cybersecurity ke liye reference framework hai." },
  { q: "Kya SCADA data center mein zaroori hai?", a: "Typical commercial ya enterprise data center mein traditional SCADA zaroori nahi hai — BMS effectively building M&E systems manage karta hai. SCADA typically use hota hai jahan: high-voltage utility interconnection ke liye (substation automation, protection relay integration — IEC 61850), large industrial cooling plants (custom PLC-based sequencing), hyperscale data centers jo custom automation develop karte hain, aur utility-scale power management applications. Most data centers BMS se operations manage karte hain bina SCADA ke." },
];
export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };
