import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "SCADA — Supervisory Control and Data Acquisition Complete Guide | Behind The Tech",
  description: "What SCADA is, architecture, PLC/RTU/HMI, industrial protocols (Modbus/DNP3/IEC 61850/OPC UA), monitoring vs control, cybersecurity, data center applications — engineer-level English guide.",
  keywords: ["SCADA","supervisory control data acquisition","PLC RTU HMI","SCADA vs BMS","industrial protocols Modbus DNP3","SCADA cybersecurity","data center SCADA"],
  openGraph: { title: "SCADA — Supervisory Control and Data Acquisition", description: "SCADA architecture, PLC/RTU, protocols, control, historian, cybersecurity.", url: "https://behindthetech.in/learn/non-it/bms-dcim/scada", locale: "en_US", siteName: "Behind The Tech", type: "article", authors: ["Kumar Anil"] },
  twitter: { card: "summary_large_image", title: "SCADA Complete Guide — Behind The Tech", description: "SCADA for engineers — architecture, protocols, troubleshooting." },
  alternates: {
    canonical: "https://behindthetech.in/learn/non-it/bms-dcim/scada",
    languages: {
      en: "https://behindthetech.in/learn/non-it/bms-dcim/scada",
      hi: "https://behindthetech.in/hi/learn/non-it/bms-dcim/scada",
      "x-default": "https://behindthetech.in/learn/non-it/bms-dcim/scada",
    },
  },
};
export const faqs = [
  { q: "What is the fundamental difference between SCADA and BMS?", a: "BMS (Building Management System) monitors and controls building M&E infrastructure — HVAC, electrical, environment — primarily using building automation protocols (BACnet, Modbus). SCADA (Supervisory Control and Data Acquisition) is for industrial process control — oil refineries, power plants, water treatment, manufacturing. SCADA typically has faster scan cycles, deterministic control, a broader protocol range (DNP3, IEC 61850, OPC UA) and stricter safety requirements. Data centers typically use BMS, not traditional SCADA — some hyperscale facilities use SCADA-heritage platforms for custom automation." },
  { q: "What is the difference between a PLC and an RTU?", a: "A PLC (Programmable Logic Controller) primarily executes control logic — sequential and continuous process control. Deterministic scan cycle, fast I/O response, complex program execution. It is standard in industrial manufacturing and automation. An RTU (Remote Terminal Unit) was primarily designed for remote site monitoring — collect field data and send it to the SCADA master. It supports DNP3 or other protocols and is often used at battery/solar powered remote sites (utilities, pipeline monitoring). Modern RTUs overlap the capabilities of PLCs. The choice depends on the application, communication requirements and environment." },
  { q: "What is a historian in SCADA?", a: "A historian is a specialized time-series database that stores the historical record of process variables from the SCADA/control system — tagged data, with timestamps. OSIsoft PI (now AVEVA PI) was the de-facto standard industrial historian — it handles millions of tags, millions of samples per second. The historian makes long-term trend analysis, performance reports, regulatory compliance evidence and root cause investigation possible. BMS and DCIM platforms also use internal historians — the industrial historian is primarily in large-scale process applications." },
  { q: "What is OPC UA and why is it important in SCADA?", a: "OPC UA (OPC Unified Architecture) is an open, vendor-neutral industrial communication standard — secure (TLS, certificate-based), platform-independent, semantically rich data model. It is becoming the standard for data exchange between SCADA, DCS, MES, ERP. Built-in security is important for SCADA cybersecurity — legacy protocols (OPC DA, DDE) do not provide security. In a data center SCADA-grade equipment (chillers, custom automation) can integrate with BMS or DCIM through OPC UA where supported." },
  { q: "What is the most important principle in SCADA cybersecurity?", a: "Air gap or network segmentation — keeping the OT (Operational Technology) network isolated from the IT network and the internet. SCADA systems often use legacy protocols and OSes that are vulnerable to cyber attacks. Key principles: network segmentation (OT/IT DMZ), unidirectional data diodes where applicable, regular patching (challenging for OT), role-based access, audit logging, remote access only via secure VPN/jump host, vendor access strictly controlled. The IEC 62443 standard is the reference framework for industrial cybersecurity." },
  { q: "Is SCADA necessary in a data center?", a: "Traditional SCADA is not necessary in a typical commercial or enterprise data center — the BMS effectively manages building M&E systems. SCADA is typically used where: for high-voltage utility interconnection (substation automation, protection relay integration — IEC 61850), large industrial cooling plants (custom PLC-based sequencing), hyperscale data centers that develop custom automation, and utility-scale power management applications. Most data centers manage operations with a BMS without SCADA." },
];
export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };
