import type { ArticleMetadata } from "@/types/engineering/content";

export const llmMetadata: ArticleMetadata = {
  slug: "llm",
  title: "Large Language Models (LLMs) — The Complete Engineering Guide",
  seoTitle: "What Are Large Language Models? LLM Architecture, Training, Inference, GPU Infrastructure — Complete English Guide",
  seoDescription:
    "A complete engineering guide to Large Language Models — Transformer architecture, parameters, tokens, KV cache, the training pipeline, RLHF, DPO, LoRA, QLoRA, MoE, quantization, vLLM, TensorRT-LLM, enterprise deployment, GPU requirements, monitoring, and production operations. For DC engineers, AI engineers, and enterprise architects.",
  canonicalUrl: "https://behindthetech.in/learn/ai/fundamentals/llm",
  keywords: [
    "what are large language models",
    "llm explained hindi",
    "transformer architecture explained",
    "llm training pipeline",
    "kv cache inference",
    "rlhf dpo alignment",
    "lora qlora fine tuning",
    "mixture of experts architecture",
    "quantization llm inference",
    "vllm tensorrt-llm serving",
    "llm gpu requirements",
    "nvidia h100 llm training",
    "enterprise llm deployment",
    "llm inference optimization",
    "speculative decoding",
    "flash attention explained",
    "open source llms comparison",
    "llm monitoring production",
    "ai factory llm infrastructure",
    "llm cost optimization",
  ],
  authorName: "Kumar Anil",
  datePublished: "2025-08-04",
  readingTimeMinutes: 85,
};
