import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",           text: "Quick Summary",                               level: 1 },
  { id: "who-should-read",         text: "Who Should Read This",                        level: 1 },
  { id: "learning-path",           text: "Learning Path",                               level: 1 },
  { id: "why-specialized",         text: "Why AI Needs Specialized Networking",         level: 1 },
  { id: "server-architecture",     text: "AI Server Networking Architecture",           level: 1 },
  { id: "intra-vs-inter",          text: "Intra-Node vs Inter-Node Communication",      level: 1 },
  { id: "gpu-to-gpu",              text: "GPU-to-GPU Communication",                    level: 1 },
  { id: "collective-comm",         text: "Collective Communication",                    level: 1 },
  { id: "allreduce",               text: "AllReduce",                                   level: 1 },
  { id: "allgather",               text: "AllGather",                                   level: 1 },
  { id: "reducescatter",           text: "ReduceScatter",                               level: 1 },
  { id: "broadcast",               text: "Broadcast",                                   level: 1 },
  { id: "all-to-all",              text: "All-to-All",                                  level: 1 },
  { id: "nccl",                    text: "NCCL",                                        level: 1 },
  { id: "rdma",                    text: "RDMA — Remote Direct Memory Access",          level: 1 },
  { id: "infiniband",              text: "InfiniBand",                                  level: 1 },
  { id: "ethernet-for-ai",         text: "Ethernet for AI",                             level: 1 },
  { id: "roce",                    text: "RoCE — RDMA over Converged Ethernet",         level: 1 },
  { id: "roce-v1-v2",              text: "RoCEv1 vs RoCEv2",                            level: 1 },
  { id: "pfc",                     text: "PFC — Priority Flow Control",                 level: 1 },
  { id: "ecn",                     text: "ECN — Explicit Congestion Notification",      level: 1 },
  { id: "cnp-congestion",          text: "CNP and RoCE Congestion Control",             level: 1 },
  { id: "tcp-vs-rdma",             text: "TCP vs RDMA",                                 level: 1 },
  { id: "leaf-spine",              text: "Leaf-Spine Architecture",                     level: 1 },
  { id: "clos-ecmp",               text: "Clos Architecture and ECMP",                 level: 1 },
  { id: "rail-architecture",       text: "GPU and NIC Rail Architecture",               level: 1 },
  { id: "bandwidth",               text: "Network Bandwidth",                           level: 1 },
  { id: "gbps-vs-gbytes",          text: "Gbps vs GB/s",                                level: 1 },
  { id: "latency",                 text: "Network Latency",                             level: 1 },
  { id: "throughput-bw-lat",       text: "Throughput vs Bandwidth vs Latency",          level: 1 },
  { id: "oversubscription",        text: "Oversubscription",                            level: 1 },
  { id: "bisection-bandwidth",     text: "Bisection Bandwidth",                         level: 1 },
  { id: "nic-rnic",                text: "NIC and RNIC",                                level: 1 },
  { id: "pcie-bottleneck",         text: "PCIe Bottlenecks",                            level: 1 },
  { id: "numa-affinity",           text: "NUMA and CPU Affinity",                       level: 1 },
  { id: "switch-architecture",     text: "Switch Architecture",                         level: 1 },
  { id: "optics-dac-aoc",          text: "DAC, AOC and Optical Transceivers",           level: 1 },
  { id: "optics-problems",         text: "Fiber and Optics Problems",                   level: 1 },
  { id: "mtu-jumbo",               text: "MTU and Jumbo Frames",                        level: 1 },
  { id: "qos",                     text: "QoS — Quality of Service",                   level: 1 },
  { id: "network-resilience",      text: "Network Resilience",                          level: 1 },
  { id: "network-security",        text: "AI Network Security",                         level: 1 },
  { id: "monitoring",              text: "AI Network Monitoring",                       level: 1 },
  { id: "troubleshooting",         text: "AI Network Troubleshooting",                  level: 1 },
  { id: "failure-scenarios",       text: "Common AI Networking Failure Scenarios",      level: 1 },
  { id: "ai-vs-traditional",       text: "AI Networking vs Traditional Data Center Networking", level: 1 },
  { id: "ib-roce-tcp-comparison",  text: "InfiniBand vs RoCE vs TCP Ethernet",          level: 1 },
  { id: "training-vs-inference",   text: "Training vs Inference Networking",            level: 1 },
  { id: "real-world-arch",         text: "Real-World AI Data Center Network Architecture", level: 1 },
  { id: "capacity-planning",       text: "AI Network Capacity Planning",                level: 1 },
  { id: "design-checklist",        text: "AI Networking Design Checklist",              level: 1 },
  { id: "key-takeaways",           text: "Key Takeaways",                               level: 1 },
];
