import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary", text: "Quick Summary", level: 1 },
  { id: "what-is-gcp", text: "What Is Google Cloud Platform?", level: 1 },
  { id: "gcp-history", text: "History and Why GCP Exists", level: 2 },
  { id: "service-models", text: "IaaS, PaaS, SaaS on GCP", level: 2 },
  { id: "shared-responsibility", text: "Shared Responsibility Model", level: 2 },
  { id: "global-infrastructure", text: "GCP Global Infrastructure", level: 1 },
  { id: "regions-zones", text: "Regions and Zones", level: 2 },
  { id: "no-region-pairs", text: "No Region Pairs — DR Is Your Choice", level: 2 },
  { id: "edge-network", text: "Edge Network and Network Tiers", level: 2 },
  { id: "region-selection", text: "Region Selection Strategy", level: 2 },
  { id: "resource-hierarchy", text: "GCP Resource Hierarchy", level: 1 },
  { id: "org-folders-projects", text: "Organization, Folders and Projects", level: 2 },
  { id: "billing-accounts", text: "Billing Accounts", level: 2 },
  { id: "labels-tags", text: "Labels, Tags and Org Policies", level: 2 },
  { id: "gcp-console-tools", text: "Console, CLI and Cloud Shell", level: 2 },
  { id: "iam", text: "Cloud IAM — Identity and Access", level: 1 },
  { id: "iam-principals", text: "Principals: Users, Groups, Service Accounts", level: 2 },
  { id: "iam-roles", text: "Roles: Basic, Predefined, Custom", level: 2 },
  { id: "service-accounts", text: "Service Accounts and Workload Identity", level: 2 },
  { id: "iam-best-practices", text: "IAM Best Practices", level: 2 },
  { id: "networking", text: "GCP Networking — Global VPC", level: 1 },
  { id: "global-vpc", text: "Global VPC Architecture", level: 2 },
  { id: "subnets", text: "Regional Subnets", level: 2 },
  { id: "firewall-rules", text: "Firewall Rules", level: 2 },
  { id: "routes", text: "Routes and Cloud Router", level: 2 },
  { id: "cloud-nat", text: "Cloud NAT", level: 2 },
  { id: "vpc-peering-shared", text: "VPC Peering and Shared VPC", level: 2 },
  { id: "private-service-access", text: "Private Service Access and Private Service Connect", level: 2 },
  { id: "load-balancing", text: "Load Balancing", level: 1 },
  { id: "cloud-lb-types", text: "Cloud Load Balancing Types", level: 2 },
  { id: "cloud-armor", text: "Cloud Armor and CDN", level: 2 },
  { id: "hybrid-connectivity", text: "Hybrid Connectivity", level: 1 },
  { id: "cloud-vpn", text: "Cloud VPN (HA VPN)", level: 2 },
  { id: "cloud-interconnect", text: "Cloud Interconnect", level: 2 },
  { id: "network-connectivity-center", text: "Network Connectivity Center", level: 2 },
  { id: "compute", text: "Compute Services", level: 1 },
  { id: "compute-engine", text: "Compute Engine (VMs)", level: 2 },
  { id: "vm-pricing", text: "VM Pricing: SUDs and CUDs", level: 2 },
  { id: "gke", text: "Google Kubernetes Engine (GKE)", level: 2 },
  { id: "cloud-run", text: "Cloud Run", level: 2 },
  { id: "cloud-functions", text: "Cloud Functions", level: 2 },
  { id: "storage-services", text: "Storage Services", level: 1 },
  { id: "cloud-storage", text: "Cloud Storage (GCS)", level: 2 },
  { id: "persistent-disk", text: "Persistent Disk and Hyperdisk", level: 2 },
  { id: "filestore", text: "Filestore", level: 2 },
  { id: "databases", text: "Database Services", level: 1 },
  { id: "cloud-sql", text: "Cloud SQL", level: 2 },
  { id: "cloud-spanner", text: "Cloud Spanner", level: 2 },
  { id: "bigtable-firestore", text: "Bigtable, Firestore and AlloyDB", level: 2 },
  { id: "high-availability", text: "High Availability", level: 1 },
  { id: "zone-regional-ha", text: "Zonal vs Regional Resources", level: 2 },
  { id: "migs", text: "Managed Instance Groups (MIGs)", level: 2 },
  { id: "disaster-recovery", text: "Disaster Recovery", level: 1 },
  { id: "dr-patterns", text: "DR Patterns and Backup", level: 2 },
  { id: "security-services", text: "Security Services", level: 1 },
  { id: "cloud-kms", text: "Cloud KMS and Secret Manager", level: 2 },
  { id: "security-command-center", text: "Security Command Center", level: 2 },
  { id: "vpc-service-controls", text: "VPC Service Controls", level: 2 },
  { id: "operations", text: "Operations Suite (Observability)", level: 1 },
  { id: "cloud-monitoring", text: "Cloud Monitoring", level: 2 },
  { id: "cloud-logging", text: "Cloud Logging and Audit Logs", level: 2 },
  { id: "trace-profiler", text: "Cloud Trace and Profiler", level: 2 },
  { id: "iac-gcp", text: "Infrastructure as Code on GCP", level: 1 },
  { id: "deployment-manager-tf", text: "Terraform and Deployment Manager", level: 2 },
  { id: "pricing-gcp", text: "GCP Pricing and Cost Management", level: 1 },
  { id: "pricing-model", text: "Pricing Model and Discounts", level: 2 },
  { id: "cost-tools", text: "Cost Management Tools", level: 2 },
  { id: "gcp-vs-clouds", text: "GCP vs AWS vs Azure", level: 1 },
  { id: "architecture-examples", text: "Architecture Examples", level: 1 },
  { id: "three-tier-gcp", text: "Three-Tier Enterprise Application", level: 2 },
  { id: "hybrid-gcp", text: "Hybrid DC to GCP", level: 2 },
  { id: "best-practices", text: "Best Practices", level: 1 },
  { id: "common-mistakes", text: "Common Engineering Mistakes", level: 1 },
  { id: "troubleshooting", text: "Troubleshooting", level: 1 },
  { id: "failure-scenarios", text: "Practical Failure Scenarios", level: 1 },
  { id: "certifications", text: "GCP Certifications and Career", level: 1 },
  { id: "key-takeaways", text: "Key Takeaways", level: 1 },
];
