import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "RAM in Servers — ECC, RDIMM, Channels, NUMA & Troubleshooting | Behind The Tech",
  description: "Server RAM kya hai, DRAM basics, ECC, RDIMM/LRDIMM, DDR generations, memory channels, NUMA relationship, DIMM population rules, RAS, scrubbing aur fault isolation — Zero-to-Hero Hinglish guide.",
  keywords: ["server RAM","ECC RAM","RDIMM LRDIMM","DDR4 DDR5","memory channels","NUMA RAM","DIMM population","memory scrubbing","server memory troubleshooting"],
  openGraph: { title: "RAM in Servers — ECC, Channels & Troubleshooting", description: "ECC, RDIMM, DDR generations, NUMA, DIMM population aur troubleshooting.", url: "https://behindthetech.in/learn/it/servers/ram", siteName: "Behind The Tech", type: "article", authors: ["Kumar Anil"] },
  twitter: { card: "summary_large_image", title: "RAM in Servers — Behind The Tech", description: "Server memory complete guide." },
  alternates: { canonical: "https://behindthetech.in/learn/it/servers/ram" },
};
export const faqs = [
  { q: "ECC RAM kya hai aur kyun server mein zaroori hai?", a: "ECC (Error-Correcting Code) RAM memory errors detect aur kuch cases mein correct kar sakta hai. Exact ECC capability — single-bit correction, multi-bit detection, chipkill — implementation pe depend karta hai. Consumer RAM mein typically yeh protection nahi hoti. Server workloads mein memory corruption catastrophic ho sakta hai — database corruption, wrong calculations, OS instability. ECC yeh protect karta hai. ECC support platform aur CPU chipset pe depend karta hai — not universally required by all servers but standard in enterprise deployments." },
  { q: "RDIMM aur UDIMM mein kya difference hai?", a: "RDIMM (Registered DIMM) mein ek register/buffer chip hota hai jo command aur address signals buffer karta hai — larger DIMM count per channel support karta hai, electrical loading reduce hota hai. Server standard. UDIMM (Unbuffered DIMM) mein yeh buffer nahi hota — simpler, lower latency, lekin limited slot count support per channel. Consumer aur some workstations mein. LRDIMM data signals bhi buffer karta hai — even higher DIMM counts, slightly higher latency. OEM compatibility matrix check karo." },
  { q: "Memory channels kya hote hain aur bandwidth pe kaise effect karta hai?", a: "CPU ka memory controller multiple parallel channels ke through RAM access karta hai. More channels = higher memory bandwidth. Maximum bandwidth ke liye sab available channels populate karo symmetric DIMMs se. OEM population guidelines exactly follow karo — platform manual mandatory reference." },
  { q: "Correctable ECC errors kitne normal hain?", a: "Isolated occasional correctable errors possible hain. Lekin consistently increasing rate on same DIMM, ya frequent correctable errors = DIMM degrading. Monitor karo per-DIMM error rate — increasing trend pe schedule replacement proactively. Uncorrectable errors = immediate investigation aur replacement." },
  { q: "Memory scrubbing kya hai?", a: "Memory scrubbing hardware process hai jo periodically RAM content scan karta hai errors ke liye — lekin error accumulate hone se pehle detect aur correct karta hai. ECC scrubbing background mein run hota hai. Kuch server platforms hardware-level scrubbing support karte hain jo silent bit errors identify karte hain jo normal operation mein surface nahi hue. Configuration options platform pe depend karte hain." },
];
export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };
