import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",           text: "Quick Summary",                                    level: 1 },
  { id: "who-should-read",         text: "Who Should Read This",                             level: 1 },
  { id: "learning-path",           text: "Learning Path",                                    level: 1 },
  { id: "why-cooling-critical",    text: "Why Cooling Is Critical for AI",                   level: 1 },
  { id: "heat-density-challenge",  text: "Heat Density Challenge",                           level: 1 },
  { id: "physics-of-heat",         text: "Physics of Heat Removal",                          level: 1 },
  { id: "temp-humidity",           text: "Temperature & Humidity Management",                 level: 1 },
  { id: "air-cooling",             text: "Air Cooling",                                      level: 1 },
  { id: "containment",             text: "Hot Aisle / Cold Aisle Containment",               level: 1 },
  { id: "air-cooling-limits",      text: "Air Cooling Limits for AI",                        level: 1 },
  { id: "liquid-cooling-intro",    text: "Liquid Cooling — Introduction",                    level: 1 },
  { id: "ashrae-liquid-classes",   text: "ASHRAE Liquid Cooling Classes (W-Classes)",         level: 1 },
  { id: "heat-removal-formula",    text: "Heat Removal Engineering Formula",                  level: 1 },
  { id: "cdu",                     text: "CDU — Cooling Distribution Unit",                  level: 1 },
  { id: "dlc-cold-plates",         text: "Direct Liquid Cooling and Cold Plates",            level: 1 },
  { id: "rear-door-hx",            text: "Rear-Door Heat Exchangers",                        level: 1 },
  { id: "immersion-cooling",       text: "Immersion Cooling",                                level: 1 },
  { id: "single-phase",            text: "Single-Phase Immersion",                           level: 1 },
  { id: "two-phase",               text: "Two-Phase Immersion",                              level: 1 },
  { id: "cooling-comparison",      text: "Cooling Technologies Comparison",                  level: 1 },
  { id: "facility-cooling-chain",  text: "Facility Cooling Chain",                           level: 1 },
  { id: "chiller-cooling-tower",   text: "Chiller and Cooling Tower",                        level: 1 },
  { id: "dry-cooler",              text: "Dry Coolers and Economizers",                      level: 1 },
  { id: "cooling-water-quality",   text: "Cooling Water Quality",                            level: 1 },
  { id: "pue-wue",                 text: "PUE and WUE Metrics",                              level: 1 },
  { id: "gpu-thermal-throttling",  text: "GPU Thermal Throttling",                          level: 1 },
  { id: "rack-power-density",      text: "Rack Power Density Planning",                      level: 1 },
  { id: "leak-detection",          text: "Leak Detection",                                   level: 1 },
  { id: "monitoring",              text: "AI Cooling Monitoring",                            level: 1 },
  { id: "failure-scenarios",       text: "Common Failure Scenarios",                         level: 1 },
  { id: "troubleshooting",         text: "Troubleshooting AI Cooling Problems",              level: 1 },
  { id: "retrofit-vs-greenfield",  text: "Retrofit vs Greenfield",                           level: 1 },
  { id: "real-world-arch",         text: "Real-World AI Data Center Cooling Architecture",   level: 1 },
  { id: "design-checklist",        text: "AI Cooling Design Checklist",                      level: 1 },
  { id: "technical-references",    text: "Technical References",                              level: 1 },
  { id: "key-takeaways",           text: "Key Takeaways",                                    level: 1 },
];
