import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  // Phase 2 — Fundamentals & Theory
  { id: "quick-summary",              text: "Quick Summary",                                            level: 1 },
  { id: "router-kya-hai",             text: "Enterprise Router Kya Hai",                               level: 1 },
  { id: "router-vs-switch",           text: "Router vs Switch vs Layer 3 Switch",                      level: 1 },
  { id: "osi-packet-forwarding",      text: "OSI Layer 3 aur Packet Forwarding",                       level: 1 },
  { id: "packet-journey",             text: "Packet Journey Through a Router",                          level: 1 },
  { id: "three-planes",               text: "Control Plane, Data Plane aur Management Plane",          level: 1 },
  { id: "rib-fib",                    text: "Routing Table — RIB aur FIB",                             level: 1 },
  { id: "lpm",                        text: "Longest Prefix Match",                                     level: 1 },
  { id: "next-hop-default",           text: "Next Hop, Default Route aur Default Gateway",             level: 1 },
  { id: "arp-ndp",                    text: "ARP, ICMPv6 aur IPv6 Neighbor Discovery",                 level: 1 },
  { id: "ttl-icmp",                   text: "TTL, Hop Limit aur ICMP",                                 level: 1 },
  // Phase 3 — Hardware & Initial Setup
  { id: "hardware-architecture",      text: "Router Hardware Architecture",                             level: 1 },
  { id: "interface-types",            text: "Interface Types aur Port Families",                        level: 1 },
  { id: "transceivers-fiber",         text: "Transceivers, Fiber aur Cabling",                         level: 1 },
  { id: "console-oob",                text: "Console Port aur OOB Management",                         level: 1 },
  { id: "psu-fan-redundancy",         text: "PSU, Fan aur Redundancy",                                 level: 1 },
  { id: "boot-process",               text: "Router Boot Process",                                      level: 1 },
  { id: "router-types",               text: "Router Types aur Use Cases",                               level: 1 },
  { id: "selection-guide",            text: "Router Selection Guide",                                   level: 1 },
  { id: "procurement-checklist",      text: "Procurement Checklist",                                    level: 1 },
  // Phase 4 — Installation & IP Addressing
  { id: "rack-installation",          text: "Rack Installation aur Physical Commissioning",             level: 1 },
  { id: "console-access",             text: "Console Access aur Initial Login",                         level: 1 },
  { id: "initial-config",             text: "Initial Configuration Workflow",                            level: 1 },
  { id: "management-ip",              text: "Management IP aur OOB Setup",                              level: 1 },
  { id: "ipv4-cidr",                  text: "IPv4 Addressing aur CIDR",                                 level: 1 },
  { id: "subnetting",                 text: "Subnetting — Practical Router Perspective",                level: 1 },
  { id: "ipv6-addressing",            text: "IPv6 Addressing",                                          level: 1 },
  { id: "interface-config",           text: "Interface Configuration",                                   level: 1 },
  { id: "static-routing",             text: "Static Routing — Production Depth",                        level: 1 },
  { id: "admin-distance",             text: "Administrative Distance aur Route Preference",             level: 1 },
  { id: "routing-metrics",            text: "Routing Metrics",                                           level: 1 },
  { id: "route-selection",            text: "Route Selection Process",                                   level: 1 },
  // Phase 5 — Dynamic Routing
  { id: "dynamic-routing",            text: "Dynamic Routing — Kyun aur Kab",                          level: 1 },
  { id: "ospf-fundamentals",          text: "OSPF Fundamentals",                                        level: 1 },
  { id: "ospf-area-design",           text: "OSPF Area Design",                                         level: 1 },
  { id: "ospf-neighbor-troubleshoot", text: "OSPF Neighbor Troubleshooting",                            level: 1 },
  { id: "isis-fundamentals",          text: "IS-IS Fundamentals",                                       level: 1 },
  { id: "bgp-fundamentals",           text: "BGP Fundamentals",                                         level: 1 },
  { id: "bgp-path-selection",         text: "BGP Path Selection",                                       level: 1 },
  { id: "bgp-enterprise",             text: "BGP in the Enterprise",                                    level: 1 },
  { id: "ecmp-load-sharing",          text: "ECMP aur Load Sharing",                                    level: 1 },
  { id: "route-summarization",        text: "Route Summarization",                                      level: 1 },
  { id: "redistribution",             text: "Route Redistribution",                                     level: 1 },
  { id: "pbr",                        text: "Policy-Based Routing (PBR)",                               level: 1 },
  // Phase 5 Advanced
  { id: "vrf",                        text: "VRF — Virtual Routing and Forwarding",                     level: 1 },
  { id: "nat-pat",                    text: "NAT aur PAT",                                              level: 1 },
  { id: "dhcp-relay",                 text: "DHCP Relay / IP Helper Concepts",                          level: 1 },
  { id: "acl-on-routers",             text: "ACL on Routers",                                           level: 1 },
  { id: "route-filtering",            text: "Route Filtering aur Prefix Lists",                         level: 1 },
  { id: "route-policy",               text: "Route Policy aur Route Maps",                              level: 1 },
  { id: "fhrp-vrrp",                  text: "First-Hop Redundancy — VRRP aur Alternatives",            level: 1 },
  { id: "bfd",                        text: "BFD — Bidirectional Forwarding Detection",                 level: 1 },
  { id: "qos-routers",               text: "QoS on Routers",                                           level: 1 },
  { id: "mpls-fundamentals",          text: "MPLS Fundamentals",                                        level: 1 },
  { id: "vpn-fundamentals",           text: "VPN Fundamentals",                                         level: 1 },
  { id: "ipsec",                      text: "IPsec",                                                    level: 1 },
  { id: "gre-tunnels",                text: "GRE Tunnels",                                              level: 1 },
  { id: "multicast-routing",          text: "Multicast Routing Fundamentals",                           level: 1 },
  // Phase 6 — WAN, DC & Security
  { id: "wan-connectivity",           text: "WAN Connectivity aur Technologies",                        level: 1 },
  { id: "dual-isp",                   text: "Dual ISP Architecture",                                    level: 1 },
  { id: "internet-edge",              text: "Internet Edge / Border Router",                             level: 1 },
  { id: "enterprise-wan",             text: "Enterprise WAN Router Design",                             level: 1 },
  { id: "dc-border-router",           text: "Router in Modern Data Center",                             level: 1 },
  { id: "north-south",                text: "North-South Traffic aur DC Border",                        level: 1 },
  { id: "router-vs-l3switch-dc",      text: "Router vs L3 Switch in DC Core",                          level: 1 },
  { id: "routing-security",           text: "Routing Security Fundamentals",                            level: 1 },
  { id: "control-plane-protection",   text: "Control Plane Protection",                                 level: 1 },
  { id: "aaa-ssh",                    text: "AAA, SSH aur Secure Management",                           level: 1 },
  { id: "routing-protocol-auth",      text: "Routing Protocol Authentication",                          level: 1 },
  // Phase 7 — Monitoring, O&M & Troubleshooting
  { id: "snmp-syslog-telemetry",      text: "SNMP, Syslog aur Streaming Telemetry",                    level: 1 },
  { id: "config-backup",              text: "Configuration Backup aur Change Management",               level: 1 },
  { id: "os-upgrade",                 text: "OS/Firmware Upgrade Strategy",                             level: 1 },
  { id: "ha-redundancy",              text: "High Availability aur Redundancy",                         level: 1 },
  { id: "troubleshooting-methodology",text: "Router Troubleshooting Methodology",                       level: 1 },
  { id: "interface-down",             text: "Interface Down Troubleshooting",                           level: 1 },
  { id: "ip-connectivity",            text: "IP Connectivity Troubleshooting",                          level: 1 },
  { id: "routing-table-troubleshoot", text: "Routing Table Troubleshooting",                            level: 1 },
  { id: "ospf-troubleshoot",          text: "OSPF Neighbor Troubleshooting",                            level: 1 },
  { id: "bgp-troubleshoot",           text: "BGP Neighbor Troubleshooting",                             level: 1 },
  { id: "nat-troubleshoot",           text: "NAT Troubleshooting",                                      level: 1 },
  { id: "asymmetric-loops",           text: "Asymmetric Routing aur Routing Loops",                     level: 1 },
  { id: "production-scenarios",       text: "Real Production Scenarios",                                level: 1 },
  // Phase 6 (Operations)
  { id: "commissioning-checklist",    text: "Router Commissioning Checklist",                           level: 1 },
  { id: "om-checklist",               text: "Preventive Maintenance aur O&M Checklist",                level: 1 },
  { id: "dc-best-practices",          text: "Data Center Best Practices",                               level: 1 },
  { id: "common-mistakes",            text: "Common Engineering Mistakes",                               level: 1 },
  { id: "interview-questions",        text: "Interview / Job Knowledge",                                level: 1 },
  { id: "key-takeaways",              text: "Key Takeaways",                                            level: 1 },
  { id: "glossary",                   text: "Glossary & Abbreviations",                                 level: 1 },
];
