import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",              text: "Quick Summary",                                        level: 1 },
  { id: "who-should-read",            text: "Who Should Read This",                                 level: 1 },
  { id: "learning-path",              text: "Learning Path",                                        level: 1 },
  { id: "what-is-ai-storage",         text: "What Is AI Storage?",                                  level: 1 },
  { id: "why-different",              text: "Why AI Workloads Need Different Storage",               level: 1 },
  { id: "ai-data-lifecycle",          text: "AI Data Lifecycle",                                    level: 1 },
  { id: "storage-hierarchy",          text: "Storage Hierarchy",                                    level: 1 },
  { id: "local-vs-shared",            text: "Local NVMe vs Shared Storage",                         level: 1 },
  { id: "parallel-file-systems",      text: "Parallel File Systems",                                level: 1 },
  { id: "object-storage",             text: "Object Storage in AI",                                 level: 1 },
  { id: "training-data-pipeline",     text: "AI Training Data Pipeline",                            level: 1 },
  { id: "gpu-to-storage",             text: "GPU-to-Storage Data Flow",                             level: 1 },
  { id: "throughput-iops-latency",    text: "Throughput vs IOPS vs Latency",                        level: 1 },
  { id: "sequential-vs-random",       text: "Sequential vs Random I/O",                             level: 1 },
  { id: "small-files-problem",        text: "Small Files Problem",                                  level: 1 },
  { id: "dataset-sharding",           text: "Dataset Sharding",                                     level: 1 },
  { id: "caching",                    text: "Caching in AI Storage",                                level: 1 },
  { id: "checkpoint-storage",         text: "Checkpoint Storage",                                   level: 1 },
  { id: "storage-networking",         text: "Storage Networking",                                   level: 1 },
  { id: "nvme-of",                    text: "NVMe-oF",                                              level: 1 },
  { id: "storage-bottlenecks",        text: "AI Storage Bottlenecks",                               level: 1 },
  { id: "resilience",                 text: "Storage Failure and Resilience",                       level: 1 },
  { id: "capacity-planning",          text: "Storage Capacity Planning",                            level: 1 },
  { id: "performance-planning",       text: "Storage Performance Planning",                         level: 1 },
  { id: "inference-storage",          text: "AI Inference Storage",                                 level: 1 },
  { id: "training-vs-inference",      text: "Training vs Inference Storage",                        level: 1 },
  { id: "monitoring",                 text: "Storage Monitoring",                                   level: 1 },
  { id: "troubleshooting",            text: "Troubleshooting AI Storage Performance",               level: 1 },
  { id: "real-world-architecture",    text: "Real-World AI Storage Architecture",                   level: 1 },
  { id: "design-checklist",           text: "AI Storage Design Checklist",                          level: 1 },
  { id: "key-takeaways",              text: "Key Takeaways",                                        level: 1 },
];
