"use client";
// D6 — OSPF Multi-Area Architecture with router roles, LSA types, LSDB vs routing table note
export default function OspfArchitecture() {
  const W = 480;
  return (
    <svg viewBox={`0 0 ${W} 480`} xmlns="http://www.w3.org/2000/svg"
      role="img" aria-label="OSPF multi-area architecture with router roles and LSA types"
      style={{ width:"100%", height:"auto", fontFamily:"Arial, sans-serif", display:"block" }}>
      <rect width={W} height="480" fill="#f8fafc" rx="10"/>
      <text x={W/2} y="20" textAnchor="middle" fontSize="13" fontWeight="700" fill="#111827">OSPF Multi-Area Architecture</text>
      <text x={W/2} y="35" textAnchor="middle" fontSize="9" fill="#6b7280">LSAs, router roles, area types, and LSDB vs routing table distinction</text>
      {/* Area 0 */}
      <rect x="120" y="46" width="240" height="90" rx="8" fill="#eff6ff" stroke="#2563eb" strokeWidth="2" strokeDasharray="4,2"/>
      <text x={W/2} y="62" textAnchor="middle" fontSize="10" fontWeight="700" fill="#2563eb">Area 0 — Backbone</text>
      <rect x="180" y="70" width="80" height="22" rx="4" fill="#2563eb"/>
      <text x="220" y="84" textAnchor="middle" fontSize="8.5" fontWeight="700" fill="#fff">Backbone Router</text>
      <text x="220" y="98" textAnchor="middle" fontSize="8" fill="#1e40af">At least one iface in Area 0</text>
      <rect x="275" y="70" width="65" height="22" rx="4" fill="#7c3aed"/>
      <text x="307" y="84" textAnchor="middle" fontSize="8" fontWeight="700" fill="#fff">ABR</text>
      <text x="307" y="98" textAnchor="middle" fontSize="7.5" fill="#5b21b6">Area Border Router</text>
      <line x1={W/2} y1="136" x2={W/2} y2="155" stroke="#6b7280" strokeWidth="1.5" markerEnd="url(#arrow)"/>
      {/* Area 1 Regular */}
      <rect x="10" y="155" width="200" height="110" rx="8" fill="#f0fdf4" stroke="#16a34a" strokeWidth="1.5"/>
      <text x="110" y="171" textAnchor="middle" fontSize="9.5" fontWeight="700" fill="#16a34a">Area 1 — Regular Area</text>
      <rect x="20" y="178" width="80" height="22" rx="4" fill="#16a34a"/>
      <text x="60" y="192" textAnchor="middle" fontSize="8" fontWeight="700" fill="#fff">Internal Router</text>
      <rect x="120" y="178" width="80" height="22" rx="4" fill="#dc2626"/>
      <text x="160" y="192" textAnchor="middle" fontSize="8" fontWeight="700" fill="#fff">ASBR</text>
      <text x="160" y="207" textAnchor="middle" fontSize="7.5" fill="#991b1b">AS Boundary Router</text>
      <text x="110" y="225" textAnchor="middle" fontSize="7.5" fill="#374151">Type 1/2 LSAs (intra-area)</text>
      <text x="110" y="238" textAnchor="middle" fontSize="7.5" fill="#374151">Type 5 External LSAs from ASBR</text>
      <text x="110" y="252" textAnchor="middle" fontSize="7.5" fill="#374151">Type 3 Summary LSAs from ABR</text>
      {/* Area 2 Stub */}
      <rect x="270" y="155" width="200" height="110" rx="8" fill="#fef9c3" stroke="#ca8a04" strokeWidth="1.5"/>
      <text x="370" y="171" textAnchor="middle" fontSize="9.5" fontWeight="700" fill="#ca8a04">Area 2 — Stub Area</text>
      <rect x="310" y="178" width="120" height="22" rx="4" fill="#ca8a04"/>
      <text x="370" y="192" textAnchor="middle" fontSize="8" fontWeight="700" fill="#fff">Internal Router(s)</text>
      <text x="370" y="215" textAnchor="middle" fontSize="7.5" fill="#92400e">Blocks Type 5 External LSAs</text>
      <text x="370" y="229" textAnchor="middle" fontSize="7.5" fill="#92400e">ABR injects default route</text>
      <text x="370" y="243" textAnchor="middle" fontSize="7.5" fill="#92400e">Receives Type 3 Summary LSAs</text>
      {/* LSA summary */}
      <rect x="10" y="278" width={W-20} height="95" rx="7" fill="#fff" stroke="#d1d5db" strokeWidth="1"/>
      <text x={W/2} y="294" textAnchor="middle" fontSize="9.5" fontWeight="700" fill="#374151">Key LSA Types</text>
      {[
        { t:"Type 1 — Router LSA", sc:"Stays within area", by:"Every router" },
        { t:"Type 2 — Network LSA", sc:"Stays within area", by:"DR on broadcast segments" },
        { t:"Type 3 — Summary LSA", sc:"Crosses area boundary", by:"ABR" },
        { t:"Type 5 — AS External LSA", sc:"Floods entire OSPF domain (except stub)", by:"ASBR" },
      ].map((l, i) => (
        <g key={i}>
          <text x="18" y={306+i*15} fontSize="8.5" fontWeight="600" fill="#1e40af">{l.t}:</text>
          <text x="180" y={306+i*15} fontSize="8.5" fill="#374151">{l.sc} · Generated by: {l.by}</text>
        </g>
      ))}
      {/* LSDB vs RIB */}
      <rect x="10" y="382" width={W-20} height="52" rx="7" fill="#faf5ff" stroke="#8b5cf6" strokeWidth="1.5"/>
      <text x={W/2} y="398" textAnchor="middle" fontSize="9.5" fontWeight="700" fill="#8b5cf6">LSDB vs Routing Table — Critical Distinction</text>
      <text x={W/2} y="413" textAnchor="middle" fontSize="8.5" fill="#4c1d95">LSDB = full topology database (all LSAs) → SPF algorithm runs on LSDB</text>
      <text x={W/2} y="427" textAnchor="middle" fontSize="8.5" fill="#4c1d95">SPF output = computed best routes → offered to system RIB → FIB programmed</text>
      <text x={W/2} y="441" textAnchor="middle" fontSize="7.5" fontStyle="italic" fill="#7c3aed">RIB ≠ LSDB. FIB ≠ LSDB. These are distinct data structures.</text>
      <defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="3" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3 z" fill="#6b7280"/></marker></defs>
    </svg>
  );
}
