import type { ArticleMetadata } from "@/types/engineering/content";

export const aiGpuMetadata: ArticleMetadata = {
  slug: "ai-gpu",
  title: "AI GPU — The Complete Engineering Guide",
  seoTitle: "What Is an AI GPU? CUDA Cores, Tensor Cores, HBM, NVLink, DGX, H100, B200 — Complete English Guide",
  seoDescription:
    "AI GPU's complete engineering guide — CPU vs GPU, CUDA Cores, Tensor Cores, HBM memory, NVLink, NVSwitch, MIG, DGX, HGX, GPU Cluster, AI Factory, cooling, power, monitoring, troubleshooting and enterprise deployment. For DC engineers, AI engineers and infrastructure architects.",
  canonicalUrl: "https://behindthetech.in/learn/ai/hardware/ai-gpu",
  keywords: [
    "what is an ai gpu",
    "gpu explained hindi",
    "cuda cores vs tensor cores",
    "hbm memory gpu",
    "nvlink explained",
    "dgx h100 server",
    "gpu cluster ai",
    "nvidia h100 b200",
    "ai factory gpu",
    "gpu cooling data center",
    "mig multi instance gpu",
    "gpu monitoring dcgm",
    "gpu power consumption",
    "rocm amd gpu",
    "gpu architecture explained",
    "streaming multiprocessor",
    "warp thread cuda",
    "fp8 tensor core",
    "nvswitch gpu",
    "enterprise gpu deployment",
  ],
  authorName: "Kumar Anil",
  datePublished: "2025-08-06",
  readingTimeMinutes: 90,
};
