import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",          text: "Quick Summary",                              level: 1 },
  { id: "who-should-read",        text: "Who Should Read This",                       level: 1 },
  { id: "what-you-will-learn",    text: "What You Will Learn",                        level: 1 },
  { id: "learning-path",          text: "Learning Path",                              level: 1 },
  { id: "introduction",           text: "Introduction",                               level: 1 },
  { id: "why-tpu-exists",         text: "Why TPU Exists — The Problem It Solved",     level: 1 },
  { id: "cpu-gpu-tpu",            text: "CPU vs GPU vs TPU — The Big Picture",        level: 1 },
  { id: "tpu-history",            text: "History of TPU — v1 to v6",                 level: 1 },
  { id: "matrix-multiplication",  text: "Matrix Multiplication — TPU Ka Core Job",   level: 1 },
  { id: "systolic-array",         text: "Systolic Array — How TPU Does Math",        level: 1 },
  { id: "tpu-chip-architecture",  text: "TPU Chip Architecture — Inside the Silicon", level: 1 },
  { id: "mxu",                    text: "MXU — Matrix Multiply Unit",                level: 1 },
  { id: "vpu",                    text: "VPU — Vector Processing Unit",               level: 1 },
  { id: "hbm-tpu",                text: "HBM Memory in TPU",                         level: 1 },
  { id: "bfloat16",               text: "BFloat16 — TPU's Special Number Format",    level: 1 },
  { id: "tpu-interconnect",       text: "TPU Interconnect — How Chips Talk",          level: 1 },
  { id: "tpu-pod",                text: "TPU Pod — Supercomputer from Chips",         level: 1 },
  { id: "tpu-versions",           text: "TPU v1 to v5e — Version Comparison",        level: 1 },
  { id: "software-stack",         text: "Software Stack — TensorFlow, JAX, XLA",     level: 1 },
  { id: "xla-compiler",           text: "XLA Compiler — The Translator",             level: 1 },
  { id: "pytorch-xla",            text: "PyTorch on TPU — torch_xla",                level: 1 },
  { id: "training-pipeline",      text: "Training Pipeline on TPU",                  level: 1 },
  { id: "inference-pipeline",     text: "Inference on TPU",                          level: 1 },
  { id: "training-vs-inference",  text: "Training vs Inference — Key Differences",   level: 1 },
  { id: "cloud-tpu",              text: "Cloud TPU — Google's AI Rental Service",    level: 1 },
  { id: "tpu-vs-gpu",             text: "TPU vs GPU — Deep Comparison",              level: 1 },
  { id: "when-to-use-tpu",        text: "When to Use TPU vs GPU",                    level: 1 },
  { id: "google-ai-stack",        text: "Google AI Infrastructure Stack",             level: 1 },
  { id: "gemini-training",        text: "Gemini Training on TPU",                    level: 1 },
  { id: "data-center-infra",      text: "Data Center Infrastructure for TPU",        level: 1 },
  { id: "power-cooling",          text: "Power and Cooling",                          level: 1 },
  { id: "cost-analysis",          text: "Cost Analysis",                              level: 1 },
  { id: "troubleshooting",        text: "Troubleshooting TPU Issues",                level: 1 },
  { id: "future-roadmap",         text: "Future Roadmap — What's Coming",            level: 1 },
  { id: "interview-questions",    text: "Interview Questions",                        level: 1 },
  { id: "glossary",               text: "Glossary",                                   level: 1 },
  { id: "key-takeaways",          text: "Key Takeaways",                              level: 1 },
];
