import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  // Phase 1 — Foundation
  { id: "quick-summary",           text: "Quick Summary",                                           level: 1 },
  { id: "fw-what",                 text: "Firewall Kya Hota Hai?",                                  level: 1 },
  { id: "fw-need",                 text: "Firewall Ki Need — Router Se Kya Different Hai?",         level: 1 },
  { id: "fw-vs-router",            text: "Firewall vs Router vs L3 Switch",                         level: 1 },
  { id: "stateless-stateful",      text: "Stateless vs Stateful Firewall",                          level: 1 },
  { id: "stateful-inspection",     text: "How Stateful Inspection Actually Works",                   level: 1 },
  { id: "five-tuple",              text: "5-Tuple and Session Table",                                level: 1 },
  { id: "tcp-udp-icmp",            text: "TCP, UDP and ICMP Session Handling",                       level: 1 },
  { id: "packet-processing",       text: "Firewall Packet Processing Journey",                       level: 1 },
  { id: "security-zones",          text: "Security Zones",                                           level: 1 },
  { id: "policy-anatomy",          text: "Security Policy / Rule Anatomy",                           level: 1 },
  { id: "rule-evaluation",         text: "Rule Evaluation and Default/Implicit Action",              level: 1 },
  { id: "return-traffic",          text: "Return Traffic Kaise Handle Hota Hai?",                    level: 1 },
  { id: "nat-relationship",        text: "NAT Ka Firewall Processing Se Basic Relationship",         level: 1 },
  { id: "ns-ew-intro",             text: "North-South vs East-West Firewalling",                     level: 1 },
  { id: "fw-placement-dc",         text: "Data Center Mein Firewall Kahan Lagta Hai?",              level: 1 },
  { id: "basic-ha",                text: "Basic Firewall HA Concept",                                level: 1 },
  { id: "practical-p1",            text: "Practical Example: User to Firewall to Web Server",        level: 1 },
  { id: "beginner-misconceptions", text: "Common Beginner Misunderstandings",                        level: 1 },
  { id: "p1-takeaways",            text: "Phase 1 Key Takeaways",                                   level: 1 },
  // Phase 2 — NAT, Objects & Advanced Policy
  { id: "network-objects",         text: "Network Objects and Address Objects",                      level: 1 },
  { id: "service-objects",         text: "Service Objects",                                          level: 1 },
  { id: "snat",                    text: "Source NAT (SNAT)",                                        level: 1 },
  { id: "pat",                     text: "PAT / Port Address Translation",                           level: 1 },
  { id: "dnat",                    text: "Destination NAT (DNAT)",                                   level: 1 },
  { id: "nat-comparison",          text: "Static NAT vs Dynamic NAT vs PAT",                        level: 1 },
  { id: "nat-table",               text: "NAT Translation Table",                                    level: 1 },
  { id: "nat-policy-interaction",  text: "NAT and Security Policy Interaction",                      level: 1 },
  { id: "hairpin-nat",             text: "Hairpin / U-Turn NAT",                                     level: 1 },
  { id: "no-nat",                  text: "No-NAT / NAT Exemption",                                   level: 1 },
  { id: "practical-nat-example",   text: "Policy Objects and NAT Practical Example",                 level: 1 },
  { id: "app-aware-policy",        text: "Application-Aware Policy",                                 level: 1 },
  { id: "identity-aware-policy",   text: "User / Identity-Aware Policy",                             level: 1 },
  { id: "schedule-policy",         text: "Time / Schedule-Based Policy",                             level: 1 },
  { id: "policy-logging",          text: "Policy Logging",                                           level: 1 },
  { id: "hit-counters",            text: "Policy Hit Counters and Rule Usage",                       level: 1 },
  { id: "policy-best-practices",   text: "Policy Design Best Practices",                             level: 1 },
  { id: "nat-policy-mistakes",     text: "Common NAT and Policy Mistakes",                           level: 1 },
  { id: "troubleshooting-flow",    text: "Phase 2 Practical Troubleshooting Flow",                   level: 1 },
  { id: "phase2-takeaways",        text: "Phase 2 Key Takeaways",                                   level: 1 },
  // Phase 3 — NGFW, Threat Inspection & Encrypted Traffic
  { id: "ngfw-adds",               text: "NGFW Kya Add Karta Hai?",                                  level: 1 },
  { id: "inspection-levels",       text: "Packet Inspection Levels",                                 level: 1 },
  { id: "app-identification",      text: "Application Identification",                               level: 1 },
  { id: "app-control",             text: "Application Control",                                      level: 1 },
  { id: "ids-ips-firewall",        text: "IDS vs IPS vs Firewall",                                   level: 1 },
  { id: "ips",                     text: "Intrusion Prevention System (IPS)",                        level: 1 },
  { id: "ips-signatures",          text: "IPS Signatures and Updates",                               level: 1 },
  { id: "protocol-decoding",       text: "Protocol Decoding and Anomaly Detection",                  level: 1 },
  { id: "url-filtering",           text: "URL Filtering",                                            level: 1 },
  { id: "dns-security",            text: "DNS Security / Domain Controls",                           level: 1 },
  { id: "file-inspection",         text: "File and Malware Inspection",                              level: 1 },
  { id: "sandboxing",              text: "Sandboxing",                                               level: 1 },
  { id: "tls-challenge",           text: "TLS/SSL Encryption Challenge",                             level: 1 },
  { id: "tls-decryption-outbound", text: "TLS/SSL Decryption / Outbound Inspection",                level: 1 },
  { id: "tls-inspection-inbound",  text: "Inbound TLS Inspection",                                  level: 1 },
  { id: "tls-limitations",         text: "TLS Inspection Limitations and Risks",                     level: 1 },
  { id: "threat-journey",          text: "Threat Prevention Packet Journey",                         level: 1 },
  { id: "ngfw-troubleshooting",    text: "Common NGFW Troubleshooting",                             level: 1 },
  { id: "phase3-takeaways",        text: "Phase 3 Key Takeaways",                                   level: 1 },
  // Phase 4 — High Availability (covered in Phase 6)
  // Phase 5 — VPN, IPsec, Remote Access
  { id: "vpn-what",                text: "VPN Kya Hota Hai?",                                        level: 1 },
  { id: "site-to-site",            text: "Site-to-Site VPN Architecture",                            level: 1 },
  { id: "remote-access",           text: "Remote-Access VPN Architecture",                           level: 1 },
  { id: "ipsec-arch",              text: "IPsec Architecture",                                       level: 1 },
  { id: "esp",                     text: "ESP — Encapsulating Security Payload",                     level: 1 },
  { id: "tunnel-transport",        text: "Tunnel Mode vs Transport Mode",                            level: 1 },
  { id: "ike",                     text: "IKE Kya Karta Hai?",                                       level: 1 },
  { id: "ikev2-flow",              text: "IKEv2 Connection Flow",                                    level: 1 },
  { id: "psk-certs",               text: "Authentication: PSK vs Certificates",                      level: 1 },
  { id: "crypto-algorithms",       text: "Cryptographic Algorithms",                                 level: 1 },
  { id: "security-associations",   text: "Security Associations (SA)",                               level: 1 },
  { id: "traffic-selectors",       text: "Interesting Traffic / Traffic Selectors",                  level: 1 },
  { id: "routing-vpn",             text: "Routing and VPN",                                          level: 1 },
  { id: "nat-ipsec",               text: "NAT and IPsec",                                            level: 1 },
  { id: "nat-t",                   text: "NAT Traversal (NAT-T)",                                    level: 1 },
  { id: "split-full-tunnel",       text: "Split Tunnel vs Full Tunnel",                              level: 1 },
  { id: "rekey-antireplay",        text: "VPN Rekey, Lifetime and Anti-Replay",                      level: 1 },
  { id: "vpn-troubleshooting",     text: "VPN Troubleshooting Workflow",                             level: 1 },
  { id: "phase5-takeaways",        text: "Phase 5 Key Takeaways",                                   level: 1 },
  // Phase 4 — HA Architecture Deep Dive
  { id: "fw-ha-why",               text: "Firewall HA Kyu Chahiye?",                                  level: 1 },
  { id: "ha-pair-arch",            text: "HA Pair Basic Architecture",                                level: 1 },
  { id: "ha-heartbeat",            text: "HA Control Link aur Heartbeat",                             level: 1 },
  { id: "failover-triggers",       text: "What Triggers Firewall Failover?",                          level: 1 },
  { id: "ha-link-failure",         text: "HA Link Failure Impact",                                    level: 1 },
  { id: "upstream-downstream-design", text: "Upstream and Downstream Network Design",                 level: 1 },
  { id: "l2-l3-ha",               text: "Layer 2 vs Layer 3 HA Connectivity",                        level: 1 },
  { id: "asymmetric-routing-ha",   text: "Asymmetric Routing in HA",                                  level: 1 },
  { id: "ha-testing",              text: "HA Testing — Not Just Configuring",                          level: 1 },
  { id: "phase4-takeaways",        text: "Phase 4 Key Takeaways",                                    level: 1 },
  // Phase 6 — High Availability, Clustering, Failover
  { id: "fw-ha-what",              text: "Firewall High Availability Kya Hai?",                      level: 1 },
  { id: "ha-why",                  text: "Why Firewall HA Is Required",                              level: 1 },
  { id: "active-passive",          text: "Active/Passive Architecture",                              level: 1 },
  { id: "active-active",           text: "Active/Active Architecture",                               level: 1 },
  { id: "ha-control",              text: "HA Control Link, Heartbeat and Peer Health",               level: 1 },
  { id: "config-sync",             text: "Configuration Synchronization",                            level: 1 },
  { id: "session-sync",            text: "Session / State Synchronization",                          level: 1 },
  { id: "stateful-stateless-failover", text: "Stateful vs Stateless Failover",                      level: 1 },
  { id: "failover-sequence",       text: "What Actually Happens During Failover?",                   level: 1 },
  { id: "address-mac-neighbor",    text: "IP Address, MAC and Neighbor Update During Failover",      level: 1 },
  { id: "routing-failover",        text: "Routing During Firewall Failover",                         level: 1 },
  { id: "nat-failover",            text: "NAT State During Failover",                                level: 1 },
  { id: "vpn-failover",            text: "VPN State During Failover",                                level: 1 },
  { id: "split-brain",             text: "Split-Brain / Dual-Active Condition",                      level: 1 },
  { id: "link-path-monitoring",    text: "Link and Path Monitoring",                                 level: 1 },
  { id: "ha-troubleshooting",      text: "Firewall HA Testing and Troubleshooting",                  level: 1 },
  { id: "phase6-takeaways",        text: "Phase 6 Key Takeaways",                                   level: 1 },
  // Phase 7 — Logging, Monitoring, Troubleshooting & Operations
  { id: "fw-ops-meaning",          text: "Firewall Operations Ka Real Meaning",                      level: 1 },
  { id: "fw-logs-what",            text: "Firewall Logs Kya Batate Hain?",                           level: 1 },
  { id: "reading-traffic-log",     text: "Traffic Log Ko Kaise Padhein?",                            level: 1 },
  { id: "allow-vs-deny-log",       text: "Allow Log vs Drop/Deny Log",                               level: 1 },
  { id: "session-table",           text: "Session Table: Most Important Troubleshooting Evidence",   level: 1 },
  { id: "packet-capture",          text: "Packet Capture on a Firewall",                             level: 1 },
  { id: "four-point-method",       text: "The Four-Point Packet Method",                             level: 1 },
  { id: "policy-troubleshooting",  text: "Troubleshooting Policy Problems",                          level: 1 },
  { id: "routing-troubleshooting", text: "Troubleshooting Routing Problems",                         level: 1 },
  { id: "nat-troubleshooting",     text: "Troubleshooting NAT Problems",                             level: 1 },
  { id: "vpn-troubleshooting-ref", text: "Troubleshooting VPN Problems",                             level: 1 },
  { id: "ha-troubleshooting-ref",  text: "Troubleshooting HA Problems",                              level: 1 },
  { id: "health-metrics",          text: "Firewall Health and Performance Metrics",                  level: 1 },
  { id: "session-capacity",        text: "Session Capacity and Connection Rate",                     level: 1 },
  { id: "monitoring-siem",         text: "Monitoring, SNMP, Syslog and SIEM",                        level: 1 },
  { id: "change-management",       text: "Change Management and Configuration Safety",               level: 1 },
  { id: "lifecycle-mgmt",          text: "Backup, Upgrade and Lifecycle Management",                 level: 1 },
  { id: "phase7-takeaways",        text: "Phase 7 Key Takeaways",                                   level: 1 },
  // Phase 8 — Architecture, Design, Sizing, Selection & Commissioning
  { id: "design-requirements",     text: "Firewall Design Requirement Se Start Hota Hai",            level: 1 },
  { id: "traffic-flows",           text: "Understand Traffic Flows Before Designing",                level: 1 },
  { id: "fw-placement",            text: "Firewall Placement in Enterprise/Data Center",             level: 1 },
  { id: "ns-ew",                   text: "North-South vs East-West Firewalling (Design)",            level: 1 },
  { id: "security-zones-design",   text: "Security Zones and Trust Boundaries",                      level: 1 },
  { id: "dmz-arch",                text: "DMZ Architecture",                                         level: 1 },
  { id: "mgmt-plane-design",       text: "Management Plane Design",                                  level: 1 },
  { id: "interface-planning",      text: "Interface and Connectivity Planning",                      level: 1 },
  { id: "routing-arch",            text: "Routing Architecture Around the Firewall",                 level: 1 },
  { id: "nat-arch",                text: "NAT Architecture Planning",                                level: 1 },
  { id: "vpn-arch",                text: "VPN Architecture Planning",                                level: 1 },
  { id: "ha-arch-planning",        text: "High Availability Architecture Planning",                  level: 1 },
  { id: "sizing",                  text: "Firewall Sizing: Throughput Is Not Enough",                level: 1 },
  { id: "capacity-headroom",       text: "Capacity Headroom and Growth",                             level: 1 },
  { id: "fw-selection",            text: "How to Select an Enterprise Firewall",                     level: 1 },
  { id: "bom",                     text: "Firewall Bill of Materials / Hidden Requirements",          level: 1 },
  { id: "pre-deployment-review",   text: "Pre-Deployment Design Review",                             level: 1 },
  { id: "commissioning",           text: "Firewall Commissioning and Acceptance Testing",            level: 1 },
  { id: "phase8-takeaways",        text: "Enterprise Firewall Final Engineering Takeaways",          level: 1 },
];
