import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  // Phase 2 — Fundamentals
  { id: "quick-summary",          text: "Quick Summary",                                          level: 1 },
  { id: "switch-kya-hai",         text: "Enterprise Network Switch Kya Hai",                      level: 1 },
  { id: "evolution",              text: "Network Switch Ka Itihaas — Evolution",                  level: 1 },
  { id: "hub-bridge-switch",      text: "Hub vs Bridge vs Switch — Fark Samjho",                 level: 1 },
  { id: "osi-layer",              text: "OSI Model mein Switch Kahaan Hai",                       level: 1 },
  { id: "ethernet-mac",           text: "Ethernet aur MAC Address — Foundation",                  level: 1 },
  { id: "switching-process",      text: "Switching Process — Andar Kya Hota Hai",                level: 1 },
  { id: "packet-journey",         text: "Packet Journey Through a Switch — Ingress to Egress",   level: 1 },
  // Phase 3 — Hardware
  { id: "hardware-anatomy",       text: "Switch Hardware — Andar Ka Anatomy",                    level: 1 },
  { id: "boot-process",           text: "Switch Boot Process",                                    level: 1 },
  { id: "front-rear-panel",       text: "Front Panel, Rear Panel aur LED Indicators",            level: 1 },
  { id: "switch-types",           text: "Switch Types — Kaunsa Kab Use Karo",                    level: 1 },
  { id: "selection-guide",        text: "Switch Selection Guide",                                 level: 1 },
  { id: "procurement-checklist",  text: "Procurement Checklist",                                  level: 1 },
  // Phase 4 — Architecture & Cabling
  { id: "network-topologies",     text: "Network Topologies",                                     level: 1 },
  { id: "three-tier-arch",        text: "Enterprise Three-Tier Architecture",                     level: 1 },
  { id: "spine-leaf",             text: "Spine-Leaf Architecture",                                level: 1 },
  { id: "clos-network",           text: "Clos Network Fundamentals",                              level: 1 },
  { id: "east-west-north-south",  text: "East-West vs North-South Traffic",                       level: 1 },
  { id: "access-dist-core",       text: "Access, Distribution aur Core Layers",                   level: 1 },
  { id: "dc-switch-arch",         text: "Data Center Switching Architecture",                     level: 1 },
  { id: "tor-mor-eor",            text: "Top-of-Rack, Middle-of-Row aur End-of-Row",             level: 1 },
  { id: "uplink-design",          text: "Uplink Design aur Oversubscription",                     level: 1 },
  { id: "enterprise-cabling",     text: "Enterprise Cabling Architecture",                        level: 1 },
  { id: "copper-cabling",         text: "Copper Ethernet Cabling",                                level: 1 },
  { id: "fiber-cabling",          text: "Fiber Optic Cabling",                                    level: 1 },
  { id: "smf-vs-mmf",             text: "Single Mode vs Multi-Mode Fiber",                        level: 1 },
  { id: "transceivers",           text: "Ethernet Transceivers",                                  level: 1 },
  { id: "dac-vs-aoc",             text: "DAC vs AOC",                                             level: 1 },
  { id: "patch-panels",           text: "Patch Panels aur Structured Cabling",                   level: 1 },
  { id: "physical-installation",  text: "Physical Installation aur Rack Deployment",             level: 1 },
  // Phase 5 — Layer 2 Technologies
  { id: "vlan-fundamentals",      text: "VLAN Fundamentals",                                      level: 1 },
  { id: "access-vs-trunk",        text: "Access Port vs Trunk Port",                              level: 1 },
  { id: "dot1q-tagging",          text: "VLAN Tagging — IEEE 802.1Q",                            level: 1 },
  { id: "native-vlan",            text: "Native VLAN",                                            level: 1 },
  { id: "broadcast-domains",      text: "Broadcast Domains",                                      level: 1 },
  { id: "ethernet-loops",         text: "Loop Problems in Ethernet",                              level: 1 },
  { id: "stp",                    text: "Spanning Tree Protocol (STP)",                           level: 1 },
  { id: "rstp",                   text: "Rapid Spanning Tree Protocol (RSTP)",                   level: 1 },
  { id: "mstp",                   text: "Multiple Spanning Tree Protocol (MSTP)",                level: 1 },
  { id: "lacp",                   text: "Link Aggregation — LACP",                               level: 1 },
  { id: "port-channel",           text: "Port Channel",                                           level: 1 },
  { id: "mlag",                   text: "MLAG — Multi-Chassis Link Aggregation",                 level: 1 },
  { id: "switch-stacking",        text: "Switch Stacking",                                        level: 1 },
  { id: "l3-switching",           text: "Layer 3 Switching Basics",                              level: 1 },
  { id: "inter-vlan-routing",     text: "Inter-VLAN Routing",                                     level: 1 },
  // Phase 6 — Advanced Features & O&M
  { id: "poe",                    text: "Power over Ethernet (PoE)",                              level: 1 },
  { id: "jumbo-frames-mtu",       text: "Jumbo Frames aur MTU",                                  level: 1 },
  { id: "qos",                    text: "Quality of Service (QoS)",                              level: 1 },
  { id: "multicast",              text: "Multicast on Switches",                                  level: 1 },
  { id: "security-features",      text: "Network Security Features",                              level: 1 },
  { id: "switch-management",      text: "Switch Management aur Monitoring",                       level: 1 },
  { id: "logging-ntp",            text: "Logging aur Time Synchronization",                       level: 1 },
  { id: "config-management",      text: "Configuration Management aur Backup",                   level: 1 },
  { id: "firmware-upgrade",       text: "Software Images, Firmware aur Upgrade Strategy",        level: 1 },
  { id: "common-mistakes",        text: "Common Engineering Mistakes",                            level: 1 },
  { id: "troubleshooting",        text: "Troubleshooting Framework",                              level: 1 },
  { id: "production-scenarios",   text: "Real Production Scenarios",                              level: 1 },
  { id: "om-checklist",           text: "Enterprise Operations aur O&M Checklist",               level: 1 },
  { id: "dc-best-practices",      text: "Data Center Best Practices",                             level: 1 },
  { id: "interview-questions",    text: "Interview / Job Knowledge",                              level: 1 },
  { id: "key-takeaways",          text: "Key Takeaways",                                          level: 1 },
];
