import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",          text: "Quick Summary",                              level: 1 },
  { id: "who-should-read",        text: "Who Should Read This",                       level: 1 },
  { id: "what-you-will-learn",    text: "What You Will Learn",                        level: 1 },
  { id: "learning-path",          text: "Learning Path",                              level: 1 },
  { id: "introduction",           text: "Introduction",                               level: 1 },
  { id: "what-is-ml",             text: "What is Machine Learning?",                  level: 1 },
  { id: "why-ml-exists",          text: "Why Machine Learning Exists",                level: 1 },
  { id: "history",                text: "History and Evolution",                      level: 1 },
  { id: "ai-evolution-timeline",  text: "AI Evolution Timeline",                      level: 2 },
  { id: "how-ml-works",           text: "How Machine Learning Works",                 level: 1 },
  { id: "ml-workflow",            text: "Machine Learning Workflow",                  level: 1 },
  { id: "ml-lifecycle",           text: "Complete ML Lifecycle",                      level: 2 },
  { id: "types-of-ml",            text: "Types of Machine Learning",                  level: 1 },
  { id: "supervised",             text: "Supervised Learning",                        level: 2 },
  { id: "unsupervised",           text: "Unsupervised Learning",                      level: 2 },
  { id: "semi-supervised",        text: "Semi-Supervised Learning",                   level: 2 },
  { id: "reinforcement",          text: "Reinforcement Learning",                     level: 2 },
  { id: "ml-vs-dl-vs-genai",      text: "ML vs Deep Learning vs Generative AI",       level: 1 },
  { id: "ml-models",              text: "ML Models",                                  level: 1 },
  { id: "training-vs-inference",  text: "Training vs Inference",                      level: 1 },
  { id: "features-labels",        text: "Features and Labels",                        level: 1 },
  { id: "dataset-preparation",    text: "Dataset Preparation",                        level: 1 },
  { id: "data-quality",           text: "Data Quality",                               level: 1 },
  { id: "feature-engineering",    text: "Feature Engineering",                        level: 1 },
  { id: "feature-store",          text: "Feature Store Architecture",                 level: 1 },
  { id: "feature-store-online",   text: "Online vs Offline Feature Store",            level: 2 },
  { id: "model-training",         text: "Model Training — Infrastructure Deep Dive",  level: 1 },
  { id: "distributed-training",   text: "Distributed Training Engineering",           level: 2 },
  { id: "model-validation",       text: "Model Validation",                           level: 1 },
  { id: "hyperparameter-tuning",  text: "Hyperparameter Tuning",                      level: 1 },
  { id: "model-deployment",       text: "Model Deployment",                           level: 1 },
  { id: "mlops",                  text: "MLOps — Production ML Engineering",          level: 1 },
  { id: "mlops-cicd",             text: "CI/CD, Shadow Deploy, Canary, Rollback",     level: 2 },
  { id: "ml-infra-architecture",  text: "ML Infrastructure Architecture",             level: 1 },
  { id: "enterprise-ai-stack",    text: "Enterprise AI Stack",                        level: 2 },
  { id: "gpus-in-ml",             text: "GPUs in Machine Learning",                   level: 1 },
  { id: "storage-requirements",   text: "Storage Requirements",                       level: 1 },
  { id: "networking-requirements",text: "Networking Requirements",                    level: 1 },
  { id: "ml-in-dc-operations",    text: "Machine Learning in Data Center Operations", level: 1 },
  { id: "enterprise-ml-pipeline", text: "Enterprise ML Pipeline",                     level: 1 },
  { id: "enterprise-tools",       text: "Enterprise ML Tools",                        level: 2 },
  { id: "production-example",     text: "Real Production Example — Bank Fraud",       level: 1 },
  { id: "real-examples",          text: "Real Production Examples",                   level: 1 },
  { id: "industry-examples",      text: "Industry-Specific ML Examples",              level: 1 },
  { id: "algorithms",             text: "Common Algorithms",                          level: 1 },
  { id: "model-optimization",     text: "Model Optimization",                         level: 1 },
  { id: "quantization",           text: "Quantization, Pruning, Distillation",        level: 2 },
  { id: "lora-qlora",             text: "LoRA, QLoRA and Fine-tuning",                level: 2 },
  { id: "infra-cost",             text: "ML Infrastructure Cost Analysis",            level: 1 },
  { id: "cloud-ml-services",      text: "AI Cloud Services Comparison",               level: 1 },
  { id: "ai-job-roles",           text: "AI/ML Job Roles",                            level: 1 },
  { id: "ai-governance",          text: "AI Governance and Responsible AI",           level: 1 },
  { id: "advantages",             text: "Advantages",                                 level: 1 },
  { id: "limitations",            text: "Limitations",                                level: 1 },
  { id: "best-practices",         text: "Best Practices",                             level: 1 },
  { id: "common-mistakes",        text: "Common Mistakes",                            level: 1 },
  { id: "security",               text: "Security Considerations",                    level: 1 },
  { id: "performance-opt",        text: "Performance Optimization",                   level: 1 },
  { id: "scalability",            text: "Scalability",                                level: 1 },
  { id: "comparison-tables",      text: "Comparison Tables",                          level: 1 },
  { id: "case-studies",           text: "Case Studies",                               level: 1 },
  { id: "interview-questions",    text: "Interview Questions",                        level: 1 },
  { id: "troubleshooting",        text: "Troubleshooting",                            level: 1 },
  { id: "glossary",               text: "Glossary",                                   level: 1 },
  { id: "key-takeaways",          text: "Key Takeaways",                              level: 1 },
];
