import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",           text: "Quick Summary",                          level: 1 },
  { id: "who-should-read",         text: "Who Should Read This",                   level: 1 },
  { id: "what-you-will-learn",     text: "What You Will Learn",                    level: 1 },
  { id: "learning-path",           text: "Learning Path",                          level: 1 },
  { id: "introduction",            text: "Introduction",                           level: 1 },
  { id: "history",                 text: "History of GPU Computing",               level: 1 },
  { id: "cpu-vs-gpu",              text: "CPU vs GPU",                             level: 1 },
  { id: "gpu-architecture",        text: "GPU Architecture — Inside the Chip",     level: 1 },
  { id: "cuda-cores",              text: "CUDA Cores",                             level: 1 },
  { id: "tensor-cores",            text: "Tensor Cores — The AI Accelerators",     level: 1 },
  { id: "rt-cores",                text: "RT Cores",                               level: 1 },
  { id: "hbm-memory",              text: "HBM — The Memory That Makes AI Possible",level: 1 },
  { id: "pcie",                    text: "PCIe — Connection to the Outside World", level: 1 },
  { id: "nvlink",                  text: "NVLink — Direct GPU-to-GPU Communication",level: 1 },
  { id: "nvswitch",                text: "NVSwitch — The GPU Interconnect Switch", level: 1 },
  { id: "cuda-software",           text: "CUDA — The Software Layer",              level: 1 },
  { id: "rocm",                    text: "ROCm — AMD's Answer to CUDA",            level: 1 },
  { id: "mig",                     text: "MIG — One GPU, Multiple Instances",      level: 1 },
  { id: "gpu-virtualization",      text: "GPU Virtualization",                     level: 1 },
  { id: "multi-gpu",               text: "Multi-GPU Systems",                      level: 1 },
  { id: "dgx",                     text: "DGX — NVIDIA's Complete AI Server",      level: 1 },
  { id: "hgx",                     text: "HGX — The GPU Baseboard",                level: 1 },
  { id: "gb200-nvl72",             text: "GB200 NVL72 — AI Supercomputer in a Rack",level: 1 },
  { id: "ai-factory",              text: "AI Factory",                             level: 1 },
  { id: "gpu-cluster",             text: "GPU Cluster",                            level: 1 },
  { id: "ai-data-centers",         text: "AI Data Centers",                        level: 1 },
  { id: "gpu-power",               text: "GPU Power",                              level: 1 },
  { id: "gpu-cooling",             text: "GPU Cooling",                            level: 1 },
  { id: "gpu-monitoring",          text: "GPU Monitoring",                         level: 1 },
  { id: "gpu-failures",            text: "GPU Failures",                           level: 1 },
  { id: "gpu-security",            text: "GPU Security",                           level: 1 },
  { id: "enterprise-deployment",   text: "Enterprise GPU Deployment",              level: 1 },
  { id: "cost-analysis",           text: "Cost Analysis",                          level: 1 },
  { id: "troubleshooting",         text: "Troubleshooting",                        level: 1 },
  { id: "future-gpus",             text: "Future GPUs",                            level: 1 },
  { id: "interview-questions",     text: "Interview Questions",                    level: 1 },
  { id: "glossary",                text: "Glossary",                               level: 1 },
  { id: "key-takeaways",           text: "Key Takeaways",                          level: 1 },
];
