import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "CPU in Servers — Architecture, NUMA, Cores, Threads & Selection | Behind The Tech",
  description: "Server CPU kya hai, cores/threads/sockets, cache hierarchy, NUMA topology, TDP, x86 vs ARM concept, hardware virtualisation extensions, workload-based selection aur troubleshooting — Zero-to-Hero Hinglish guide.",
  keywords: ["server CPU","Intel Xeon","AMD EPYC","NUMA","CPU cores threads","cache L1 L2 L3","TDP","virtualisation extensions","CPU selection data center"],
  openGraph: { title: "CPU in Servers — Architecture, NUMA & Selection", description: "CPU cores, threads, cache, NUMA, TDP, x86 vs ARM, virtualisation — complete guide.", url: "https://behindthetech.in/learn/it/servers/cpu", siteName: "Behind The Tech", type: "article", authors: ["Kumar Anil"] },
  twitter: { card: "summary_large_image", title: "CPU in Servers — Behind The Tech", description: "CPU architecture, NUMA, selection aur troubleshooting guide." },
  alternates: { canonical: "https://behindthetech.in/learn/it/servers/cpu" },
};
export const faqs = [
  { q: "Server CPU aur consumer CPU mein key differences kya hain?", a: "Multi-socket support (2S/4S configurations), more PCIe lanes, ECC memory support (platform dependent), RAS (Reliability/Availability/Serviceability) features, longer product lifecycle support, higher core counts, server-specific instruction set extensions. Intel Xeon aur AMD EPYC data center mein common hain. Specific capabilities model aur generation pe depend karti hain." },
  { q: "NUMA kya hai aur performance pe kaise impact karta hai?", a: "Non-Uniform Memory Access — multi-socket server mein har CPU (socket) ke paas directly-connected local RAM hoti hai. CPU apni local RAM access kare to fast hota hai. Doosre CPU ki RAM access karne ke liye CPU-to-CPU interconnect se jaana padta hai — higher latency, potentially lower bandwidth. NUMA-unaware workload placement performance silently degrade kar sakta hai. `numactl` Linux mein topology check karo." },
  { q: "Hyperthreading/SMT enable karna chahiye?", a: "Generally most workloads benefit karte hain, lekin benefit workload-specific hota hai — koi universal percentage claim accurate nahi hogi. Kuch latency-sensitive ya specific HPC workloads pe neutral ya slight negative impact ho sakta hai. Default on rakho, specific workload testing pe based tune karo. Security considerations (side-channel vulnerabilities) ke liye organizational policies check karo." },
  { q: "TDP kya hota hai?", a: "Thermal Design Power — watt mein — ek reference value hai jis pe cooling solution design karna chahiye. Yeh CPU ka maximum heat dissipation estimate deta hai under defined load conditions. Actual CPU power consumption workload pe depend karta hai aur kuch scenarios mein TDP se exceed ya under-run kar sakta hai depending on architecture aur configuration. TDP cooling aur power budgeting planning ke liye reference hai, universal maximum power figure nahi." },
  { q: "x86 aur ARM mein kya difference hai servers ke context mein?", a: "x86 (Intel/AMD) historically server dominant raha hai — Intel Xeon, AMD EPYC. x86 Complex Instruction Set Computing (CISC) architecture use karta hai. ARM-based server processors (AWS Graviton, Ampere Altra, etc.) Reduced Instruction Set Computing (RISC) architecture use karte hain — often better performance-per-watt in certain workloads. ARM server ecosystem growing hai. Software compatibility check karo — kuch software ARM native support require karti hai ya performance optimisation needed hai." },
];
export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };
