import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "DCIM — Data Center Infrastructure Management Complete Guide | Behind The Tech",
  description: "DCIM kya hai, architecture, asset management, power chain, capacity planning, SNMP/Modbus/API integration, Vertiv Trellis, Athenta, Sunbird, Nlyte — deep engineer-level Hinglish guide.",
  keywords: ["DCIM data center","data center infrastructure management","Vertiv Trellis","Athenta DCIM","SNMP PDU monitoring","rack capacity planning","DCIM vs BMS"],
  openGraph: { title: "DCIM — Data Center Infrastructure Management", description: "DCIM architecture, asset management, power chain, integration, troubleshooting.", url: "https://behindthetech.in/learn/non-it/bms-dcim/dcim", siteName: "Behind The Tech", type: "article", authors: ["Kumar Anil"] },
  twitter: { card: "summary_large_image", title: "DCIM Complete Guide — Behind The Tech", description: "Data Center Infrastructure Management for engineers." },
  alternates: { canonical: "https://behindthetech.in/learn/non-it/bms-dcim/dcim" },
};
export const faqs = [
  { q: "DCIM aur BMS mein kya fundamental difference hai?", a: "BMS (Building Management System) building M&E infrastructure monitor aur control karta hai — HVAC, cooling systems, electrical panels, environmental sensors. DCIM (Data Center Infrastructure Management) IT infrastructure layer pe focus karta hai — individual racks, servers, network devices, IT power distribution, IT cooling at rack level, cable connectivity, asset lifecycle. BMS floor-level environment deta hai; DCIM rack-level IT granularity deta hai. Enterprise data centers mein typically dono separate tools hote hain jo data share karte hain." },
  { q: "SNMP se DCIM mein device discover nahi ho raha — kya check karein?", a: "First: SNMP enabled hai device pe? Correct SNMP version (v1/v2c/v3)? Community string (v1/v2c) ya credentials (v3) correct? Second: Network connectivity — DCIM server se device IP ping? UDP port 161 firewall mein open? Third: DCIM driver/module — correct device type selected? MIB loaded? Fourth: SNMP agent configured to allow DCIM server IP? Fifth: Device supported in DCIM platform — some devices need specific drivers or MIBs." },
  { q: "DCIM mein rack capacity calculation kaise hoti hai?", a: "Rack capacity typically teen dimensions mein track hota hai: Space (U slots — total vs used), Power (kW/A — rated vs actual measured), aur Weight (kg — floor load). Actual power consumption DCIM intelligent PDU ya metered outlets se real-time read karta hai (where available). Power capacity comparison 'rated' (nameplate) vs 'actual' hoti hai — drained capacity estimate karta hai kab rack full hogi at current growth rate. Accurate capacity data ke liye actual metering zaroori hai — nameplate ratings conservative hote hain aur actual use typically lower hota hai." },
  { q: "Athenta DCIM kya hai?", a: "Athenta ek DCIM aur facility monitoring platform hai jo data center infrastructure monitoring, dashboards, alarms, aur reporting pe focus karta hai. Athenta facilities management aur monitoring capabilities provide karta hai — equipment monitoring, environmental data, power chain visibility, aur integration with various protocols. Actual features, editions aur capabilities Athenta ke current product documentation aur version se verify karo — platform evolves over time." },
  { q: "DCIM mein UPS data kaise integrate karte hain?", a: "Most common: SNMP (agar UPS mein network management card hai), Modbus TCP/RTU, ya manufacturer-specific protocol. Steps: UPS communication interface identify karo (SNMP card ya Modbus port); DCIM mein device add karo; protocol aur credentials configure karo; discovery run karo; relevant points map karo (load %, battery, bypass, alarms); polling configure karo. UPS data DCIM mein power chain visualization ke liye use hota hai — which racks are on which UPS, current load vs capacity." },
  { q: "DCIM reporting aur CMMS mein kya difference hai?", a: "DCIM (Data Center Infrastructure Management) real-time aur historical IT infrastructure data — assets, power, capacity, environment — manage karta hai aur reports generate karta hai. CMMS (Computerized Maintenance Management System) maintenance activities manage karta hai — work orders, preventive maintenance schedules, parts inventory, technician assignments. Kuch enterprise platforms dono integrate karte hain — DCIM se alarm aa → CMMS mein work order auto-create ho. Typically ye separate systems hote hain jo API se connected hote hain." },
];
export const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };
