import type { ArticleHeading } from "@/components/ArticlePage";

export const HEADINGS: ArticleHeading[] = [
  { id: "quick-summary",          text: "Quick Summary",                              level: 1 },
  { id: "who-should-read",        text: "Who Should Read This",                       level: 1 },
  { id: "what-you-will-learn",    text: "What You Will Learn",                        level: 1 },
  { id: "learning-path",          text: "Learning Path",                              level: 1 },
  { id: "what-is-ai-infra",       text: "What is AI Infrastructure?",                 level: 1 },
  { id: "why-it-exists",          text: "Why AI Infrastructure Exists",               level: 1 },
  { id: "evolution",              text: "History and Evolution",                      level: 1 },
  { id: "traditional-vs-ai",      text: "Traditional IT vs AI Infrastructure",        level: 1 },
  { id: "cloud-vs-ai",            text: "Cloud vs AI Infrastructure",                 level: 1 },
  { id: "hpc-vs-ai",              text: "HPC vs AI Infrastructure",                   level: 1 },
  { id: "ecosystem",              text: "AI Infrastructure Ecosystem",                level: 1 },
  { id: "gpu-deep-dive",          text: "GPU Infrastructure — Deep Dive",             level: 1 },
  { id: "blackwell-nvl72",        text: "Blackwell, GB200, and NVL72",               level: 2 },
  { id: "nvlink-nvswitch",        text: "NVLink and NVSwitch",                       level: 2 },
  { id: "pcie-cxl",               text: "PCIe, CXL, and Memory Pooling",             level: 2 },
  { id: "dpus-smartnics",         text: "DPUs and SmartNICs",                        level: 2 },
  { id: "networking",             text: "AI Networking",                              level: 1 },
  { id: "infiniband-vs-ethernet", text: "InfiniBand vs Ethernet",                    level: 2 },
  { id: "storage",                text: "AI Storage Architecture",                   level: 1 },
  { id: "power-infra",            text: "Power Infrastructure",                       level: 1 },
  { id: "cooling",                text: "Cooling Architecture",                       level: 1 },
  { id: "rack-design",            text: "AI Rack Design",                             level: 1 },
  { id: "software-stack",         text: "Software Stack",                             level: 1 },
  { id: "training-workflow",      text: "AI Training Workflow",                       level: 1 },
  { id: "inference",              text: "AI Inference Infrastructure",                level: 1 },
  { id: "ai-factory",             text: "AI Factory, AI Pod, AI Supercomputer",       level: 1 },
  { id: "dc-architecture",        text: "AI Data Center Architecture",                level: 1 },
  { id: "dc-power-cooling-ops",   text: "DC Operations — Power, Cooling, Fire, BMS", level: 2 },
  { id: "retrofit",               text: "Retrofitting Existing Data Centers",         level: 2 },
  { id: "operations",             text: "Operations and Maintenance",                 level: 1 },
  { id: "sustainability",         text: "Sustainability — PUE, WUE, CUE",            level: 1 },
  { id: "enterprise-deployment",  text: "Enterprise Deployment",                      level: 1 },
  { id: "production-example",     text: "Production Example — 256-GPU Cluster",      level: 1 },
  { id: "case-studies",           text: "Case Studies",                               level: 1 },
  { id: "advantages",             text: "Advantages",                                 level: 1 },
  { id: "limitations",            text: "Limitations",                                level: 1 },
  { id: "best-practices",         text: "Best Practices",                             level: 1 },
  { id: "common-mistakes",        text: "Common Mistakes",                            level: 1 },
  { id: "security",               text: "Security Considerations",                    level: 1 },
  { id: "performance-opt",        text: "Performance Optimization",                   level: 1 },
  { id: "scalability",            text: "Scalability and Capacity Planning",          level: 1 },
  { id: "future-trends",          text: "Future Trends",                              level: 1 },
  { id: "comparison-tables",      text: "Comparison Tables",                          level: 1 },
  { id: "vendor-landscape",       text: "Vendor Landscape",                           level: 1 },
  { id: "interview-questions",    text: "Interview Questions",                        level: 1 },
  { id: "troubleshooting",        text: "Troubleshooting Guide",                      level: 1 },
  { id: "glossary",               text: "Glossary",                                   level: 1 },
  { id: "key-takeaways",          text: "Key Takeaways",                              level: 1 },
];
